### ISSUE TITLE
Using SwaggerToCSharpWebApiControllerGenerator with $ref pointing to external files

### ISSUE THREAD

**Issue by InstanceOfAnObject** [RSuter/NSwag#1000]
I've been battling with this for a while but I can't make it work.
I have the following definitions in my JsonSchema:
```
...
  "definitions": {
    "cat": {
      "type": "object",
      "properties": { "name": { "type": "string" } }
    },
    "animals": {
      "$ref": "./animals.json"
    }
  }
```
animals.json looks like this:
```
{
  "dog": {
    "type": "object",
    "properties": { "name": { "type": "string" } }
  }
}
```
Referencing "cat" works perfectly with: "$ref": "#/definitions/cat"
But if I want to have an external file, in the same folder, with all animals definitions, the file reference doesn't work.

Searching around I found a lot of URL supported features but nothing related to relative paths on disk.

The C# code is the following:
```
var doc = SwaggerDocument.FromFileAsync(@"Contracts\pet-service.json").Result;
                
var settings = new SwaggerToCSharpWebApiControllerGeneratorSettings();
settings.CSharpGeneratorSettings.Namespace = "MyPetsApplication";

var generator = new SwaggerToCSharpWebApiControllerGenerator(doc, settings);
var code = generator.GenerateFile();
```

Is this really not supported or am I missing something?

Thanks

**Comment by RSuter** [comment]
Is an exception thrown?

**Comment by InstanceOfAnObject** [comment]
It depends.
As the object is never retrieved from the external file, the outcome vary.

If I reference only the animals definition then it will be created as an Object:
```
"responses": {
  "200": {
    "description": "",
    "schema": {
      "$ref": "#/definitions/animals"
    }
  }
},
```
results in:
```
/// <summary>Gets one dog</summary>
/// <returns>Invalid input</returns>
System.Threading.Tasks.Task<object> GetDogAsync();
```

If instead I try to point to the dog inner object, like I want, I get a "Could not resolve the path '#/definitions/animals/dog'."
```
"responses": {
  "200": {
    "description": "",
    "schema": {
      "$ref": "#/definitions/animals/dog"
    }
  }
},
```

**Digging in...**
The error is thrown from the FromJsonAsync method, called by FromFileAsync, in the JsonSchemaReferenceUtilities.UpdateSchemaReferencesAsync line but I believe the problem is on the JsonConvert.DeserializeObject.

Inspecting the resulting document, the reference to the file in the definitions is not correct.

At this point we're already passing from NSwag to NJsonSchema assemblies so I decided to ping you :)

Bellow is the full JsonSchema I'm using, just for the sake of completion.
The animals.json contents is the one I posted previously
```
{
  "$schema": "http://json-schema.org/draft-04/schema",

  "info": {
    "description": "....",
    "version": "1.0.0",
    "title": "Swagger Pet Services",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "apiteam@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "pets.swagger.io",
  "basePath": "/v1",
  "schemes": [
    "http"
  ],
  "paths": {
    "/cats/{id}": {
      "get": {
        "summary": "Gets one cat",
        "description": "",
        "operationId": "getCat",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Invalid input",
            "schema": {
              "$ref": "#/definitions/cat"
            }

          }
        },
        "security": []
      }
    },
    "/dogs/{id}": {
      "get": {
        "summary": "Gets one dog",
        "description": "",
        "operationId": "getDog",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "schema": {
                "$ref": "#/definitions/animals/dog"
              }

            }
          },
        "security": []
      }
    }
  },
  "definitions": {
    "cat": {
      "type": "object",
      "properties": { "name": { "type": "string" } }
    },
    "animals": {
      "$ref": "./animals.json"
    }
  }
}
```

**Comment by RSuter** [comment]
The main problem here is that external $refs are assumed to reference other JSON Schema documents, but your animals.json file does not contain a JSON Schema but a dictionary with JSON Schemas. Loading this document with JsonSchema4.FromFileAsync is not possible because it does not fit into a JsonSchema4 object... 

The solution would be to load external $refs as JObject (any JSON) and convert parts of it to JsonSchema4 instances (or other types, e.g. a Swagger parameter) on demand depending on the $ref pointing to it (i.e. the $ref defines the type of the JSON fragment). To be more flexible with $refs (especially external refs) we need to implement this. I'll look into this as soon as I find some time for that...

Until then, you can try to: 

1. Directly reference schemas, e.g. "dog.json": 

```
        "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "schema": {
                "$ref": "./dog.json"
              }

            }
          },
        "security": []
      }
    }
  },
  "definitions": {
    "cat": {
      "type": "object",
      "properties": { "name": { "type": "string" } }
    }
  }
```

Question: Is the type name ("Dog") correctly inferred?

2. Indirectly reference dog: 

```
        "parameters": [],
          "responses": {
            "200": {
              "description": "",
              "schema": {
                "$ref": "#/definitions/dog"
              }

            }
          },
        "security": []
      }
    }
  },
  "definitions": {
    "cat": {
      "type": "object",
      "properties": { "name": { "type": "string" } }
    },
    "dog": {
      "$ref": "./dog.json"
    }
  }
```

Question: Is "dog.json" loaded this way?

3. Manually write a tool to inline all refs (i.e. remove all external refs) and then load the resulting JSON 

I know that these are very not good solutions - for me this issue is high priority because I know we need better external ref handling... I will update this issue as soon as I dived deeper into the problem...

**Comment by InstanceOfAnObject** [comment]
Thanks for the support :)

I actually thought about that $ref replacement feature. It's not super bad but it's not pretty either.
As I saw that JSON.net as this JSchemaPreloadedResolver, I believe this should be the way to go. 
Basically we could allow the developer to pre-load the dependencies and also support automatic discovery whenever a reference is not found.

---

As a side problem, but still related to this, I managed to reference the external json document if it's referenced directly on the method (not in the definitions). The problem is that the generated c# object now is called "Json", although it's contents are perfect.
Do you see any way we could name these references?
```
{
  "title": "airplane",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "length": { "type": "integer" }
  }
}
```

```
"responses": {
  "200": {
    "description": "",
    "schema": {
      "$ref": "./airplane.json"
    }
  }
},
```
outputs:
`System.Threading.Tasks.Task<Json> GetAirplaneAsync();`

```
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.7.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class Json : System.ComponentModel.INotifyPropertyChanged
    {
        private string _name;
        private int? _length;
    
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Name
        {
            get { return _name; }
            set 
            {
                if (_name != value)
                {
                    _name = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        [Newtonsoft.Json.JsonProperty("length", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? Length
        {
            get { return _length; }
            set 
            {
                if (_length != value)
                {
                    _length = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static Json FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<Json>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
```

**Comment by InstanceOfAnObject** [comment]
Ok, I'll leave my previous comment but I did some more tests and the main "problem" is/was that each external file must contain only one object definition. We cannot nest type definitions. I think it's really the JSONSchema that doesn't support this, at least it looks like it.

Bottom line, 
- using $ref from the paths works but gives it a "Json" name
- using $ref from the definitions works well picking the name of the definition
- none of the above work if the referenced file contains more that one type

**Comment by RSuter** [comment]
Yes, this is problem with NJsonSchema, I'm just looking into it...

1. Should be easily solvable (if the ref is a document then the type name hint must be different)
2. -
3. Looking into this to be more dynamic

**Comment by RSuter** [comment]
Should fix 1. and 3.: 

https://github.com/RSuter/NJsonSchema/commit/4d8139fdfbaac5555e87765d1bc40607a50b5141
https://github.com/RSuter/NJsonSchema/commit/36292c20821a591999324b3786fed20523029013

**Comment by RSuter** [comment]
... but the $ref topic is not closed yet - lot of work to do in this area...

**Comment by RSuter** [comment]
Can you retry with the latest NSwag CI builds?

**Comment by InstanceOfAnObject** [comment]
I've updated everything to the latest builds and the document seems to be loading the external references correctly but now I get a side effect.
Creating an instance of SwaggerToCSharpWebApiControllerGeneratorSettings throws me an exception:
`System.MissingMethodException: 'Method not found: 'Void NJsonSchema.CodeGeneration.DefaultTemplateFactory..ctor()'.'`

I'm using the same code (error on line 3):
```
var doc = SwaggerDocument.FromFileAsync(@"Contracts\pet-service.json").Result;

var settings = new SwaggerToCSharpWebApiControllerGeneratorSettings();
settings.CSharpGeneratorSettings.Namespace = "MyPetsApplication";

var generator = new SwaggerToCSharpWebApiControllerGenerator(doc, settings);
var code = generator.GenerateFile();
```

Any ideas?
Thanks!

**Comment by RSuter** [comment]
Ok, you also need to update nswag to the ci build version. I’ll do some more tests today and will release a new version of nswag. You can also test at this time.. or can you test with NSwagStudio?

**Comment by InstanceOfAnObject** [comment]
On the NSwag side I'm already running the latest version, 11.9.3. I checked on AppVeyor and it the latest right? So we need a new release there I guess.
I did load the SwaggerDocument and inspecting the structure it looks good.

NSwagStudio I think it's not an option here because it does not support referencing files by local disk path.
Using ./ referenced with http(s) URLs doesn't make sense, does it?

**Comment by RSuter** [comment]
So your input is just a Swagger spec? Try to install NSwagStudio from here: 

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts (MSI installer)

Open NSwagStudio and paste an absolute path into the Swagger URL field. This should work

**Comment by RSuter** [comment]
I think this way you can test the latest version
The problem with the AppVeyor CI build is that the version number is not auto incremented

**Comment by InstanceOfAnObject** [comment]
Ok, doing it now.
I only have the local files because I want to use them in my tt to generate the web api controllers.

I tried that version of NSwagStudio and there are good and bad news :)
**Good news:**
If the reference is directly in the paths, it works perfectly. Generates both client and WebAPI controllers.
```
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "./dog.json"
            }
          }
        },
```

**Bad news:**
Doing the reference in the definitions doesn't work and throws the following:
`System.InvalidOperationException: The schema reference path './dog.json' has not been resolved.`
```
  "definitions": {
    "dog": {
      "$ref": "./dog.json"
    }
  }
```
where dog is:
```
{
  "type": "object",
  "properties": { "name": { "type": "string" } }
}
```

**Comment by RSuter** [comment]
Ah, this is a new one, will add a new unit test to NJS.

**Comment by RSuter** [comment]
Ok, in NJS it works:

**Comment by InstanceOfAnObject** [comment]
I just tested it on NSwagStudio.
I used the schema bellow so you can replicate it on your own. Moving the dog.json reference from the definitions to the response schema of the /dogs/{id} then it works.
It doesn't really matter which output I have selected.
```
{
  "$schema": "http://json-schema.org/draft-04/schema",

  "info": {
    "description": "....",
    "version": "1.0.0",
    "title": "Swagger Pet Services",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "apiteam@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "pets.swagger.io",
  "basePath": "/v1",
  "schemes": [
    "http"
  ],
  "paths": {
    "/cats/{id}": {
      "get": {
        "summary": "Gets one cat",
        "description": "",
        "operationId": "getCat",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Invalid input",
            "schema": {
              "$ref": "#/definitions/cat"
            }

          }
        },
        "security": []
      }
    },
    "/dogs/{id}": {
      "get": {
        "summary": "Gets one dog",
        "description": "",
        "operationId": "getDog",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/dog"
            }
          }
        },
        "security": []
      }
    }
  },
  "definitions": {
    "cat": {
      "type": "object",
      "properties": { "name": { "type": "string" } }
    },
    "dog": {
      "$ref": "./dog.json"
    }
  }
}
```

**Comment by RSuter** [comment]
[sample.zip](https://github.com/RSuter/NSwag/files/1391132/sample.zip)

**Comment by RSuter** [comment]
With the latest commits it works for me, please try again with CI builds: 
https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by RSuter** [comment]
v11.10.0

**Comment by InstanceOfAnObject** [comment]
Awesome!
I've updated NSwagStudio from the link you provided, Works!
I've updated my project NSwag & NJsonSchema dependencies and now everything woks perfectly.

Thanks a lot mate.
I'll be using this for a while now so probably I'll bother you again :)

Let me know if I can help you in any way.

**Comment by RSuter** [comment]
v11.10

**Comment by InstanceOfAnObject** [comment]
Just as an added piece of information, I've tested the code in a T4, which is my original requirement, and it works like a charm.
Here's the code:
```
<#@ template debug="false" hostspecific="true" language="C#" #>

<#@ assembly name="$(ProjectDir)bin\Debug\Newtonsoft.Json.dll" #>
<#@ assembly name="$(ProjectDir)bin\Debug\NJsonSchema.dll" #>
<#@ assembly name="$(ProjectDir)bin\Debug\NJsonSchema.CodeGeneration.dll" #>
<#@ assembly name="$(ProjectDir)bin\Debug\NJsonSchema.CodeGeneration.CSharp.dll" #>
<#@ assembly name="$(ProjectDir)bin\Debug\NSwag.Core.dll" #>
<#@ assembly name="$(ProjectDir)bin\Debug\NSwag.CodeGeneration.dll" #>
<#@ assembly name="$(ProjectDir)bin\Debug\NSwag.CodeGeneration.CSharp.dll" #>

<#@ import namespace="NSwag" #>
<#@ import namespace="NSwag.CodeGeneration.CSharp" #>

<#@ output extension=".cs" #>
<#
    var doc = SwaggerDocument.FromFileAsync(this.Host.ResolvePath(@"Contracts\pet-service.json")).Result;
    var settings = new SwaggerToCSharpWebApiControllerGeneratorSettings(){
        ClassName = "Pet"
    };
    settings.CSharpGeneratorSettings.Namespace = "Pets.Services";

    var generator = new SwaggerToCSharpWebApiControllerGenerator(doc, settings);
    var code = generator.GenerateFile();
#>
<#= code #>
```
Thanks mate!

**Comment by RSuter** [comment]
Nice...
If you have the time, can you update the wiki? I think it is outdated: https://github.com/RSuter/NSwag/wiki/T4
