### ISSUE TITLE
Correctly reading the filename from disposition

### ISSUE THREAD

**Issue by lucax88x** [RSuter/NSwag#1001]
Hello,

this issue is related to #834.

the problem relates in this code

```typescript
const fileNameMatch = contentDisposition ? /filename="?([^"]*)"?;/g.exec(contentDisposition) : undefined;
```

you are matching all the filenames with a ; but if the content-disposition ONLY has a normal filename, there's no ; on the http-header value, this meaning on a fail Regex

example:
```
Content-Disposition:attachment; filename=Belege.pdf
```

hope it's clear :)

**Comment by RSuter** [comment]
So the simplest solution would be to just add a ;?

    const fileNameMatch = contentDisposition ? /filename="?([^"]*)"?;/g.exec(contentDisposition + “;”) : undefined;

**Comment by RSuter** [comment]
Or better: 

    /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition)

**Comment by RSuter** [comment]
Can you test the second regex in your app?

**Comment by lucax88x** [comment]
works ;)
