### ISSUE TITLE
Problems with Authorize and AuthenticationSchemes property in ASP.NET Core 2.0

### ISSUE THREAD

**Issue by lurumad** [RSuter/NSwag#1004]
Hi,

I'm working in my ASP.NET Core 2.0 Api and today I've configured the security. When I've configured the controllers with Authorize and set AuthenticationSchemes property with "Bearer", NSwag throws an exception:

System.Reflection.CustomAttributeFormatException: 'AuthenticationSchemes' property specified was not found. ---> System.Reflection.CustomAttributeFormatException: 'AuthenticationSchemes' property specified was not found.

```csharp
    [Route("api/[controller]")]
    [ApiVersion("1.0")]
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    public class CategoriesController : ControllerBase
```

Any ideas???

Regards!!!

**Comment by lurumad** [comment]
Hi,

I've tried to encapsulate AuthorizeAttribute in my own 

```csharp
    public class JwtAuthorizeAttribute : JwtAuthorizeAttribute 
    {
        public JwtAuthorizeAttribute()
        {
            AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme;
        }
    }
```

But...

System.MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Authorization.AuthorizeAttribute.set_AuthenticationSchemes(System.String)'.

Regards!

**Comment by lurumad** [comment]
Works with ActiveAuthenticationSchemes but is obsolete and you have to use AuthenticationSchemes:

![nswag](https://user-images.githubusercontent.com/1729519/31774430-0219a1c8-b4e6-11e7-9d7d-6630124a8b49.png)

Regards!

**Comment by RSuter** [comment]
Do you have a stacktrace?

**Comment by lurumad** [comment]
Hi @RSuter 

Changing the order in referencepaths works:

Initial

```xml
 <Exec Command="$(NSwagExe_Core20) webapi2swagger /assembly:$(OutDir)$(ProjectName).dll /DefaultPropertyNameHandling:CamelCase /output:swagger.json /referencepaths:&quot;%USERPROFILE%\\.nuget\\packages,C:\\Program Files\\dotnet\\store\\x64\\netcoreapp2.0&quot;" />
```
Final

```xml
 <Exec Command="$(NSwagExe_Core20) webapi2swagger /assembly:$(OutDir)$(ProjectName).dll /DefaultPropertyNameHandling:CamelCase /output:swagger.json /referencepaths:&quot;C:\\Program Files\\dotnet\\store\\x64\\netcoreapp2.0,%USERPROFILE%\\.nuget\\packages&quot;" />
```

I don't know why if I use %programfiles% msbuild try to look for in Program Files x86 for this reason I'm using full path :(

Do you want to close the issue or do you need aditional info?

Regards!

**Comment by RSuter** [comment]
Assembly loading works best if the correct runtime is used... so i think it's fixed...

**Comment by RSuter** [comment]
I think if you first "dotnet publish" and use the correct runtime Core20 then you dont need referencepaths...
