### ISSUE TITLE
Setting baseclass on TypeScript clients 

### ISSUE THREAD

**Issue by cruising** [RSuter/NSwag#1011]
I would like to provide the generated clients with a baseclass so they can call this.getBaseUrl() as the url they need to call is only known at deployment time. I will use aurelia-configuration to provide the url at that time.
I can make the base client but the code does not compile since a 

`import { ClientBase } from './client-base';`

is missing from the head of the generated file.
I am using msbuild like this
`<Exec Command="$(NSwagExe) swagger2tsclient /input:swagger.json /output:src/server/backendservice.ts /UseGetBaseUrlMethod:true /ClientBaseClass:ClientBase" />`

Am I doing this wrong?
If this is currently not supported, would it make sense for the generator to infer the filename from the base class name?

**Comment by RSuter** [comment]
Create a new file "client.extensions.ts" add the import to the file and reference the file as ExtensionCode

https://github.com/RSuter/NSwag/wiki/SwaggerToTypeScriptClientGenerator#extended-classes-and-extension-code

**Comment by cruising** [comment]
Thank you this is great, I should have found it in the documentation.  
Only remaining problem is that in my base class I inject AureliaConfiguration and the extending class calls super() without any parameters. Is there also an extension point for providing parameters to the constructor?

**Comment by RSuter** [comment]
ConfigurationClass setting

**Comment by cruising** [comment]
Thank you for extremely fast responses, are there any examples of using the ConfigurationClass setting?

**Comment by cruising** [comment]
Found it in the source, thank you for a very nice and extensible product.

**Comment by RSuter** [comment]
Here is an aurelia sample (without ConfigurationClass setting): 
https://github.com/RSuter/NSwag/tree/master/src/NSwag.Sample.NetCoreAurelia

Here a sample for one of my clients: 
https://github.com/Picturepark/Picturepark.SDK.TypeScript/blob/master/src/picturepark-sdk-v1-fetch/nswag.json#L27

**Comment by ranouf** [comment]
@cruising , did you succeed? I m interested to do the same, but even after read the link given by @RSuter I dont understand the way to do it. Could you share your solution?

**Comment by ddlaat** [comment]
@ranouf and @cruising I'm interested as well.
@RicoSuter I'm a bit confused here. The documentation of the TypeScriptClientGenerator (https://github.com/RicoSuter/NSwag/wiki/TypeScriptClientGenerator) describes an TypeScriptGeneratorSettings object. But I think that should be the TypeScript**Client**GeneratorSettings. And the latter doesn't have a ExtensionCode property. Am I missing something?

**Comment by RicoSuter** [comment]
The TypeScriptClientGeneratorSettings contains swagger client settings, the TypeScriptGeneratorSettings contains DTO schema generator settings (e.g. extension code

**Comment by ddlaat** [comment]
Thank you for the fast response. I see it now. TypeScriptGeneratorSettings is also a property of TypeScriptClientGeneratorSettings.

**Comment by Pzixel** [comment]
Hi. Could you be more detailed here a bit? I generate my `SomeClient extends BaseClient` and now all the file is surrounded with red error strokes because I have to manually add imports to the generated file.

Is there anyway to prepend file with:
```ts
import {BaseClient} from "./baseClient";
import {ClientConfiguration} from "./clientConfiguration";
```

It's quite annoying to do it manually everey time file gets regenerated.

**Comment by ddlaat** [comment]
`
settings.TypeScriptGeneratorSettings.ExtensionCode = "import {BaseClient} from "./baseClient";";
`

**Comment by cruising** [comment]
Or if you want it in a file (for more than one line) add a file
`client.extentions.ts`

within that file add
`import {BaseClient} from "./baseClient";`
`import {ClientConfiguration} from "./clientConfiguration";`

and call the generator with this flag:
`/ExtensionCode:client.extensions.ts`

**Comment by Pzixel** [comment]
Ah, this is why I didn't find it. The property is readonly so it's not listed in the initalizer list.
