### ISSUE TITLE
C# ExcludedTypeNames is generating the wrong output (nswag file + clients)

### ISSUE THREAD

**Issue by Kyle-Muir** [RSuter/NSwag#1013]
### NJsonSchema Version: 9.7.3.0 (Newtonsoft.Json v 9.0.0.0)

When using NSwagStudio if you exclude multiple types it generates the `.nswag` file and the generated clients incorrectly. It generates the type names comma separated wrapped in a string (i.e. `"ClassA, ClassB"`) rather than strings that are comma separated (i.e. `"ClassA", "ClassB"`)

### NSwagStudio configuration:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/3029322/31968403-7c23a262-b96d-11e7-953e-cad1d8055d5a.png">

Note with the above: We also tried `Sku,HtmlString` as well to no avail.

### Expected Output:

```json
"swaggerToCSharpClient": {
      "additionalNamespaceUsages": [
        "System",
        "System.Collections.Generic",
        "System.Linq",
        "Shared"
      ],
      "excludedTypeNames": [
        "Sku", 
        "HtmlString"
      ]
    }
```

### Actual Output:

```json
"swaggerToCSharpClient": {
      "additionalNamespaceUsages": [
        "System",
        "System.Collections.Generic",
        "System.Linq",
        "Shared"
      ],
      "excludedTypeNames": [
        "Sku, HtmlString"
      ]
    }
```

The upshot of it is that when you exclude multiple types and then generate the clients it includes the excluded types:

Expected:
<img width="195" alt="image" src="https://user-images.githubusercontent.com/3029322/31968692-6f8a07de-b96e-11e7-93a6-2bc46962d574.png">

Actual:
<img width="210" alt="image" src="https://user-images.githubusercontent.com/3029322/31968629-39101680-b96e-11e7-941b-32fd768e999b.png">

If there's any further information I can provide let me know and I'll provide it.

**Comment by RSuter** [comment]
Please test with CI installer: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by Kyle-Muir** [comment]
@RSuter can't launch NSwag studio after downloading from CI:

<img width="657" alt="image" src="https://user-images.githubusercontent.com/3029322/31969419-063808dc-b971-11e7-9189-bddbbf99fbbd.png">

**Comment by RSuter** [comment]
Please try again soon

**Comment by Kyle-Muir** [comment]
Loads but this error, also cannot generate outputs/files:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/3029322/31970822-ea49ef32-b975-11e7-9db3-2be5ede6c562.png">

**Comment by RSuter** [comment]
Can't see a problem now, have you checked your config file? Are the paths correct? Will check this tomorrow...

**Comment by Kyle-Muir** [comment]
@RSuter user error. Disregard.

I've successfully run it using the latest build and the issue is still present as described above.

<img width="265" alt="image" src="https://user-images.githubusercontent.com/3029322/31971401-341d70e6-b978-11e7-9515-7848faa06971.png">

**Comment by RSuter** [comment]
My bad, stringarrayconverter is the wrong converter: 

https://github.com/RSuter/NSwag/blob/master/src/NSwagStudio/Converters/StringArrayConverter.cs

Will fix tomorrow

**Comment by Kyle-Muir** [comment]
I've raised a PR #1014 which fixes this

**Comment by RSuter** [comment]
v11.11.1
