### ISSUE TITLE
NSwagerStudio: Runtime: NetCore20 not work. (Question).

### ISSUE THREAD

**Issue by aap4ixx** [RSuter/NSwag#1015]
Hi,

Please help my in the problem.

Via NSwagStudio i try generate outputs code for SCharp client use Runtime: NetCore20
When i press a button "Generate Outputs", studio show me error message "The system cannot find the file specified".
How i can generate CShart code use NetCore20?

Runtime: WinX64 and WInX86 working
Runtime: NetCore10, NetCore11 and NetCore20 not work.

![ssss](https://user-images.githubusercontent.com/27344435/32001894-c1c7f968-b9a3-11e7-85a0-d178d418da27.png)

**Comment by RSuter** [comment]
How did you install NSwagStudio? Via MSI installer?

**Comment by aap4ixx** [comment]
Hi RSuter.

Yes i install via MSI.

![sssa](https://user-images.githubusercontent.com/27344435/32002734-d6148ccc-b9a5-11e7-8100-d7a6804e9cf6.png)

**Comment by RSuter** [comment]
Are the required directories in the install directory?

![image](https://user-images.githubusercontent.com/2603405/32002824-af6c6ee4-b99d-11e7-8fd9-50bc83bd5f57.png)

**Comment by aap4ixx** [comment]
Hi,

I download from this link: http://rsuter.com/Projects/NSwagStudio/installer.php

![ssddcfsdf](https://user-images.githubusercontent.com/27344435/32002966-6aba6f2c-b9a6-11e7-90d4-871e8e843ef6.png)

**Comment by RSuter** [comment]
Ah, is dotnet core installed?

**Comment by RSuter** [comment]
The binaries are called with "dotnet path/to/nswag-dll run temp.json"

**Comment by RSuter** [comment]
the binary "dotnet" must be globally available

**Comment by aap4ixx** [comment]
Ураааа.
After installation "dotnet-runtime-2.0.0-win-x64.exe", everything worked.
RSuter big thanks for you assist and sorry for my stupid question :)
