### ISSUE TITLE
TypeLoadException for NSwag.CodeGeneration.DefaultTemplateFactory (v11.11.0)

### ISSUE THREAD

**Issue by sandord** [RSuter/NSwag#1016]
When doing this:

    var clientGeneratorSettings = new SwaggerToTypeScriptClientGeneratorSettings();

I get this exception:

> System.TypeLoadException: 'Declaration referenced in a method implementation cannot be a final method.  Type: 'NSwag.CodeGeneration.DefaultTemplateFactory'.  Assembly: 'NSwag.CodeGeneration, Version=11.11.0.0, Culture=neutral, PublicKeyToken=c2d88086e098d109'.'

These are my package references:

    <PackageReference Include="NJsonSchema" Version="9.9.10" />
    <PackageReference Include="NJsonSchema.CodeGeneration" Version="9.9.10" />
    <PackageReference Include="NJsonSchema.CodeGeneration.CSharp" Version="9.9.10" />
    <PackageReference Include="NJsonSchema.CodeGeneration.TypeScript" Version="9.9.10" />
    <PackageReference Include="NSwag.CodeGeneration" Version="11.11.0" />
    <PackageReference Include="NSwag.CodeGeneration.CSharp" Version="11.11.0" />
    <PackageReference Include="NSwag.CodeGeneration.TypeScript" Version="11.11.0" />
    <PackageReference Include="NSwag.Core" Version="11.11.0" />
    <PackageReference Include="NSwag.SwaggerGeneration" Version="11.11.0" />
    <PackageReference Include="NSwag.SwaggerGeneration.WebApi" Version="11.11.0" />

Any idea what's causing this? I haven't been able to figure it out yet...

**Comment by RSuter** [comment]
The latest version of NJsonSchema has a breaking change, please use NJS v9.9.0 with the latest NSwag version

**Comment by sandord** [comment]
Excellent, that solved it. Isn't it possible to put a dependency version constraint in the NuGet package? Or is that impossible to do once it has been released?

**Comment by RSuter** [comment]
I think its not possible to change the dependencies after a package has been published... It is my fault that this happened... (a minor/patch version should not have breaking changes). I'm currently doing big refactorings... I'll release NSwag soon so that this is no longer an issue...

**Comment by sandord** [comment]
Sounds good. Thanks for responding so quickly.

**Comment by RSuter** [comment]
Ok, should be fixed with v11.11.1

**Comment by RSuter** [comment]
With this version you can also use a newer version of NJS than NSwag specifies...
