### ISSUE TITLE
NSwagStudio generate wrong enum structure.

### ISSUE THREAD

**Issue by aap4ixx** [RSuter/NSwag#1017]
Hi,

I have simple JSON string.
```
swagger: '2.0'
info:
  description: List of available API's
  version: 0
  title: API Sorce
  contact: {}
  license: {}
host: DBG.tu
basePath: /Swg
tags: []
paths: {}
definitions: {
  "FirstMetdod<MetValue>": {
      "type": "object",
      "properties": {
        "GroupChar": {
          "type": "string",
          "enum": [
            "A",
            "B",
            "C",
            "D"
          ]
        }
      }
    }
}
```

NSwag Studio provide me code for CSharp Client and i put this code to visual studio C# project.
Visual studio provide my error on code (Enum construction not valid).

![not valid enum](https://user-images.githubusercontent.com/27344435/32013428-c76ed222-b9c3-11e7-9dfd-d647cbef0ff1.png)

I try parse JSON to another parse and parse didn't found any critical error with enum.
[https://editor.swagger.io//?_ga=2.137349680.1622466978.1508932166-60382640.1506511334#/](url)

**Comment by RSuter** [comment]
It seems that the names are not correctly transformed... bug.
