### ISSUE TITLE
Does NSwag provide Inline Code samples in Swagger UI?

### ISSUE THREAD

**Issue by codestellar** [RSuter/NSwag#1019]
I am looking to create inline code samples for my swagger api documentation.
Something like [this](https://developer.incontact.com/API/AgentAPI#!/PhoneCalls/dialPhone)
Is this available in NSwag or can be added as an enhancement?
![example_swagger](https://user-images.githubusercontent.com/17561784/32041613-52416f66-ba52-11e7-8eda-436e38127b55.png)

**Comment by RSuter** [comment]
I think you need something like this: https://github.com/RSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration.WebApi.Tests/OperationProcessors/SwaggerOperationProcessorAttributeTests.cs

**Comment by RSuter** [comment]
Can we close this?

**Comment by RSuter** [comment]
https://blog.rsuter.com/nswag-tutorial-implement-a-custom-operation-processor-to-define-redoc-code-samples/

**Comment by codestellar** [comment]
@RSuter ReDoc UI is missing 'try it out' feature in Swagger UI. So, I am looking to play with Swagger UI only.

**Comment by RSuter** [comment]
It's just a sample how to add additional properties to Swagger operations...
