### ISSUE TITLE
Client generation for Action with optional bool parameter

### ISSUE THREAD

**Issue by zuckerthoben** [RSuter/NSwag#1021]
Imagine this sample action:

`public async Task<IActionResult> Get([FromQuery]string order = null, [FromQuery]bool IsOrder = true)`

The NSwag generated client method looks like this (with generateOptionalParameters): 

```
public async Task<Object> GetAsync(string order = null, bool? IsOrder)
{
    if (isOrder == null)
        throw new ArgumentNullException("IsOrder");

        ...
}
```

This looks weird to me. Why is the generated parameter not like the one from the action? Is this a limitation of reflection? 
This way I have to specify a value for an otherwise optional parameter. And as a consumer I dont even know what the default value for the bool is here, if I dont bother.

**Comment by RSuter** [comment]
Actually `bool IsOrder = true` is an optional parameter (if it is not provided/set then it is true). This is why the swagger spec specifies it as optional and thus the parameter is nullable in the generated client...

**Comment by zuckerthoben** [comment]
Yes thats exactly the point. Its an optional parameter and I would expect it to be nullable and not throw exceptions. But it actually is not nullable, because the generator also adds the null check at the beginning of the method which throws ArgumentNull. 

The expected behavior is that GetAsync() without params just works.
The actual behavior is that GetAsync() throws ArgumentNullException for an optional parameter and you have to do GetAsync(isOrder = false/true). And then you have the problem that you dont know which one is the expected default.  

The reason for the null check is the following that is generated below in the client: 
      `urlBuilder_.Append("isOrder=").Append(System.Uri.EscapeDataString(System.Convert.ToString(isOrder.Value, System.Globalization.CultureInfo.InvariantCulture)));`

isOrder.Value will throw NullReference if you actually null the bool?. The generator would have to null check isOrder and set true or false if it is null. It can only do that reliably if the generator actually know the default. 

My solution would be to only append isOrder=%Value% if isOrder != null. Or even better the generated client should mirror the action and have bool isOrder = true as a parameter instead of bool? isOrder.

**Comment by RSuter** [comment]
Yes, this seems wrong...

**Comment by RSuter** [comment]
What do you think?

https://github.com/RSuter/NSwag/commit/202c1b8dd1acc63ca945508fb7d27868838f9c17

**Comment by zuckerthoben** [comment]
Looks good to me. Tested it with the ci build (https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/2795/artifacts).
