### ISSUE TITLE
CSharp client is not compilling with nullable DateTime parameter when using liquid template

### ISSUE THREAD

**Issue by mgierlasinski** [RSuter/NSwag#1023]
When there is nullable DateTime parameter, code generated from Liqud template can't be compiled - .Value for parameter is not added. It seems that parameter.Type.EndsWith is never true, replacing it with parameter.IsNullable seems to fix the problem.

**Line 120 of Client.Class.liquid:**
`urlBuilder_.Append("{{ parameter.Name }}=").Append(System.Uri.EscapeDataString({{ parameter.VariableName }}{% if parameter.Type.EndsWith("?") %}.Value{% endif %}.ToString("{{ ParameterDateTimeFormat }}", System.Globalization.CultureInfo.InvariantCulture))).Append("&");`

**Possible fix:**
`urlBuilder_.Append("{{ parameter.Name }}=").Append(System.Uri.EscapeDataString({{ parameter.VariableName }}{% if parameter.IsNullable %}.Value{% endif %}.ToString("{{ ParameterDateTimeFormat }}", System.Globalization.CultureInfo.InvariantCulture))).Append("&");`

**Comment by RSuter** [comment]
A yes, this has not been correctly migrated... i'm not sure whether just using `parameter.IsNullable` is correct, because .Value must only be used for Nullable<> and not for other types which are nullable (eg DTOs etc).

**Comment by mgierlasinski** [comment]
Yes but before this line there is a check:

`if parameter.IsDate`

So I assumed that it will be valid only for Nullable<DateTime>.

**Comment by RSuter** [comment]
Correct...

**Comment by RSuter** [comment]
The problem is here: https://github.com/RSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Templates/Liquid/Client.Class.liquid#L124

**Comment by RSuter** [comment]
But ok, I'll move the check into the model class

**Comment by RSuter** [comment]
v11.11.3
