### ISSUE TITLE
Question: How to exclude a method from being generated on the client?

### ISSUE THREAD

**Issue by bhaidar** [RSuter/NSwag#1026]
Hello,
Is there a way to exclude a method from being generated on the client? (Angular and Typescript).

Thank

**Comment by RSuter** [comment]
Methods can only be proteced but not excluded... you have to remove it from the spec first

**Comment by bhaidar** [comment]
Hi @RSuter,
Remove it from the spec first, means removing it from controller?

**Comment by RSuter** [comment]
you can also apply the SwaggerIgnoreAttribute to the ctrl

**Comment by bhaidar** [comment]
@RSuter 

> SwaggerIgnoreAttribute
 
Works only for controllers! Not for actions.

Also, noticing something weird, an action input is being generated as a set of parameters and not the object itself is being generated :(

**Comment by RSuter** [comment]
When using nswag to generate a spec, SwaggerIgnoreAttribute also works for operations (im pretty sure)

**Comment by RSuter** [comment]
2. this is because swagger cannot describe this

**Comment by bhaidar** [comment]
> When using nswag to generate a spec, SwaggerIgnoreAttribute also works for operations (im pretty sure)

You mean NSwag.AspNetCore middleware?

**Comment by RSuter** [comment]
yes or the command line tool

**Comment by bhaidar** [comment]
I believe the problem is the swagger json generator should look at this attribute and remove the action etc. I will give it a try now.

**Comment by bhaidar** [comment]
@RSuter 
Excellent this attributes works for both actions and controllers.

Still one issue.

On one of the actions, it receives an input of Type: GetUsersInputDto

This class contains a single property of Type: QueryInputDto. Something like this:

````
 public class GetUsersInputDto
{
  public QueryInputDto QueryInput { get; set; }
}
````
The class QueryInputDto is also a complex class.

When rendered, the method accepting the input of type GetUsersInputDto is now accepting an input of type QueryInputDto (angular client).

Why is the parent class being ignored?

Thanks

**Comment by RSuter** [comment]
Complex query objects are flattened because swagger cannot express this... You should only use primitive query parameters and/or a complex body parameter

**Comment by bhaidar** [comment]
You mean one level complex object? And not two levels?

**Comment by bhaidar** [comment]
The weird thing some objects are working fine and they are complex and
contains complex objects. The problem is only when having a complex object
with a single complex object property.

**Comment by RSuter** [comment]
Please create a new issue for this issue with a repro...
