### ISSUE TITLE
Generated code breaks after update to TypeScript 2.6.1

### ISSUE THREAD

**Issue by huubhermsen** [RSuter/NSwag#1031]
Hi,

Since we've updated to TypeScript 2.6.1 the generated output breaks our build. This is due to the headers in the output which don't conform to the new `RequestInit` interface in lib.dom.ts. In the old version it accepted a `<any>` type for the headers property but now it only accepts `<Headers | string[][]>`.

For now we can simply solve this by reverting to TypeScript version 2.5.3.

Is there a way to influence the way the headers get generated?

**Comment by RSuter** [comment]
Can you show me an example what is generated and what is expected? Is there a way to generate it so that it works with both versions?

**Comment by RSuter** [comment]
And we are talking only about the fetch/aurelia template?

**Comment by huubhermsen** [comment]
Yep, sorry I didn't mention that, we're using the fetch template

**Comment by RSuter** [comment]
I'm wondering why it even currently works without `new Headers`?

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Headers

**Comment by huubhermsen** [comment]
I'm not sure, maybe it's a legacy thing?

**Comment by RSuter** [comment]
Please test with CI artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by huubhermsen** [comment]
Works like a charm!

Thank you for the speedy solution.

Van: Rico Suter [mailto:notifications@github.com]
Verzonden: donderdag 2 november 2017 12:18
Aan: RSuter/NSwag <NSwag@noreply.github.com>
CC: Huub Hermsen | Wazzurb <Huub@wazzurb.com>; Author <author@noreply.github.com>
Onderwerp: Re: [RSuter/NSwag] Generated code breaks after update to TypeScript 2.6.1 (#1031)


Please test with CI artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by RSuter** [comment]
Ok, thanks for testing. I hope you can live with the CI artifacts for now, the current version of NSwag has a lot of changes so I have to heavily test it before I can publicly release it...

**Comment by MariuszKogut** [comment]
I guess this fix is not compatible to TypeScript 2.4 and earlier. We are still using TypeScript 2.4.2 and ran into an issue. Since NSwag 11.12.2.0 all generated header like Content-Type and Accept are lost. So our RestApi is throwing 401.

Issue with TypeScript 2.4.2
```
        let options_ = <RequestInit>{
            method: "GET",
            headers: new Headers({
                "Content-type": "application/json",
                "Accept": "application/json"
            })
        };

```

No Issue with TypeScript 2.4.2
```
        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Content-type": "application/json",
                "Accept": "application/json"
            }
        };

```

**Comment by RSuter** [comment]
How is this possible? Is this a compiler feature?

**Comment by RSuter** [comment]
Why would this not work in older TS versions? It's a browser/language feature and not a TS feature: 

![image](https://user-images.githubusercontent.com/2603405/32480361-b02d6c20-c38e-11e7-84a9-93b6c636f35f.png)

**Comment by RSuter** [comment]
Accoring to MDN this is allowed: 

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Headers
