### ISSUE TITLE
NSwag does not take into account SwaggerResponseRemoveDefaults when csharp client is generated from .net assemblies.

### ISSUE THREAD

**Issue by PeterTim** [RSuter/NSwag#1032]
I've an API controller with a method that returns the only 201 (Created). In this case nswag will generate the code that will throw SwaggerException for 201 status code. I was trying to set SwaggerResponseRemoveDefaults but it did not help. So, I have a method that returns some content but this content could not be obtained because of the exception.

If I use the swagger specification then the generated code is good, i.e. the SwaggerException will not be thrown.

**Comment by RSuter** [comment]
Please provide a sample controller operation

**Comment by PeterTim** [comment]
[Route("storages")]
[ResponseType(typeof(Storage))]
[SwaggerResponseRemoveDefaults]
[SwaggerResponse(HttpStatusCode.Created)]
public IHttpActionResult PostStorage([FromBody] Storage storage)
{
   var newStorage = new Storage();
    return Content(HttpStatusCode.Created, newStorage);
}

**Comment by PeterTim** [comment]
I found a fix. The ResponseTypeAttribute should be removed and the response type should be specified in the SwaggerResponse attribute for 201 code.
