### ISSUE TITLE
NSwag generate error code when еhe class name is the same.

### ISSUE THREAD

**Issue by aap4ixx** [RSuter/NSwag#1033]
Hi,

A have simple "definitions" JSON schema.
in schema i have two same name "BaseReport" with different parameter "<History>" and "<Session> ".

` \"definitions\": {
	        BaseReport<History>
		{
		...
		},
 		BaseReport<Session> 
		{
		...
		}
	}
`
Nswag generate code with error:
![img_1](https://user-images.githubusercontent.com/27344435/32332943-621f177e-bfef-11e7-96dc-ea0000432155.png)

![img_2](https://user-images.githubusercontent.com/27344435/32332946-656e8efa-bfef-11e7-9ea8-e8fd5da67c68.png)

**Comment by RSuter** [comment]
I think this is fixed with this commit: 

https://github.com/RSuter/NJsonSchema/commit/a89df69edc4fca67dbac5ded306343daaa501796

**Comment by RSuter** [comment]
Please test with the latest CI artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

Available in 5 mins.

**Comment by aap4ixx** [comment]
Hi,

Today i check in new version and didn't found issue.
Thanks.

**Comment by RSuter** [comment]
Ok so you're running nswag v11.12.2?
