### ISSUE TITLE
Could not load 'AngularClient' template for 'TypeScript' generator.

### ISSUE THREAD

**Issue by sandord** [RSuter/NSwag#1035]
v11.11.3 throws `Could not load 'AngularClient' template for 'TypeScript' generator.`

Code:

```
var clientGeneratorSettings = new SwaggerToTypeScriptClientGeneratorSettings
{
    Template = TypeScriptTemplate.Angular,
};

var clientGenerator = new SwaggerToTypeScriptClientGenerator(document, clientGeneratorSettings);
var code = clientGenerator.GenerateFile();
```

This works fine with v9.9.3 and NJsonSchema v9.9.11.

**Comment by RSuter** [comment]
Dont use a newer version than njs v9.9.17

**Comment by RSuter** [comment]
https://www.nuget.org/packages/NSwag.Core/
Dependencies

Sorry, usually the latest version of nswag works with the latest version of njs... i did a breaking change because i made a major refactoring. I’d like to fix this by releasing nswag, but i have to heavily test it first...

**Comment by RSuter** [comment]
Please also test with the latest version: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/2825/artifacts

**Comment by RSuter** [comment]
Poll: Are you using nswag config files (nswag.json)?

**Comment by sandord** [comment]
I understand. So I guess that for the foreseeable future, when upgrading packages it would be best to upgrade NSwag to the latest version but keep NJsonSchema at the minimum version as required by NSwag.

**Comment by sandord** [comment]
I'm not using nswag.json.

**Comment by RSuter** [comment]
No, usually its the best to keep both latest... this is just temporary, will fix it tomorrow...

**Comment by sandord** [comment]
Please keep in mind that it already is tomorrow :p. I'm off to bed. Thanks for helping me out, looking forward to the new stuff.

**Comment by RSuter** [comment]
Please upgrade to the latest version of NSwag (v11.12.0) and NJsonSchema (v9.10.3) - everything should now work as expected. Please report if you have any problems (there were some major refactorings, but 99% of APIs should be the same).
