### ISSUE TITLE
NSwagStudio "waiting for maintainer" in Chocolatey 

### ISSUE THREAD

**Issue by hmoratopcs** [RSuter/NSwag#1036]
NSwagStudio packages uploaded to Chocolatey after August are in "waiting for maintainer" status. https://chocolatey.org/packages/nswagstudio

**Comment by RSuter** [comment]
I saw this and hopefully it is fixed with this commit: 

https://github.com/RSuter/NSwag/commit/7fb46eb853fdd54e9332bd975e22c39bea04798e

**Comment by RSuter** [comment]
v11.12.0 seems to be approved - I think this fixed the problem...
