### ISSUE TITLE
Updating packages in NSwag breaking changes.

### ISSUE THREAD

**Issue by alexdrl** [RSuter/NSwag#1037]
I have update NSwag.AspNetCore and NSwag.CodeGeneration.CSharp from 11.7.2 to 11.11.3.

Two thing I have noticed... Why the class WebApiAssemblyToSwaggerGeneratorSettings moved to NSwag.Commands, i fitted better in NSwag.SwaggerGeneration.WebApi.

Also, NSwag.Commands does not have an strong name as the other libraries.

**Comment by RSuter** [comment]
WebApiAssemblyToSwaggerGenerator and WebApiAssemblyToSwaggerGeneratorSettings have a dependency to NSwag.AssemblyLoader and I dont want to have this dependency in NSwag.SwaggerGeneration.WebApi... I can sign NSwag.Commands... I'm also not very happy that WebApiAssemblyToSwaggerGenerator and WebApiAssemblyToSwaggerGeneratorSettings are in NSwag.Commands but its better to have them there than in NSwag.SwaggerGeneration.WebApi - maybe we need a new library for that... 

Do you use WebApiAssemblyToSwaggerGenerator and WebApiAssemblyToSwaggerGeneratorSettings directly in your app?

**Comment by alexdrl** [comment]
The use case is a .NET Core console app that uses NSwag for generating Swagger and C# code files for ASP.NET Core APIs. This app is called as an msbuild task before the build in a .NET Standard library.

Sorry if I was a little harsh, but without your good explanation, the change was a bit confusing.

**Comment by RSuter** [comment]
Why dont you directly use NSwag.MSBuild? Do you need customizations?

**Comment by alexdrl** [comment]
We have a custom class GenericsTypeNameGenerator that inherits from DefaultTypeNameGenerator, with replaces the keyword "Of" and "And" of generic return types of Controllers, also, we select controllers based on name...

**Comment by RSuter** [comment]
I was thinking about removing these assembly* generators. Because i dont see a scenario where you really need them. Cant you directly reference the needed project and call the generators with controller types?

**Comment by RSuter** [comment]
I removed these generators because they make the code too complicated.
Now you can specify a custom generator:

**Comment by RSuter** [comment]
Please upgrade to the latest version of NSwag (v11.12.0) and NJsonSchema (v9.10.3). 

The WebApiAssemblyToSwaggerGenerator and WebApiAssemblyToSwaggerGeneratorSettings have been removed, but new TypeNameGeneratorType and SchemaNameGeneratorType settings have been added so you dont need to write an own command line tool... otherwise you can use the WebApiToSwaggerCommand to do the same as before...

Please report any problems.

**Comment by RSuter** [comment]
I have to remove the strong name for NSwag.Commands because it depends from YamlDotNet which does not have a strong name. Is this a problem?

**Comment by alexdrl** [comment]
We tried updating to those package versions and it worked with minor modifications. Thank you for the effort and sorry for the late reply.
