### ISSUE TITLE
XML langword elements ignored when generating Swagger descriptions

### ISSUE THREAD

**Issue by paulomorgado** [RSuter/NSwag#1042]
For this controller action:

```C#
[HttpPost]
[Route("{?index}"]
[SwaggerOperation("Action")]
/// <param name="index">The index of the record to store. <see langword="null"/> for the default record.</param>
public async Task<IHttpActionResult> ActionAsync(
    [FromUri, Range(0, int.MaxValue)] int? index = null,
    CancellationToken cancellationToken = default(CancellationToken))
{
    // ...
}
```

The Swagger description for the `index` parameter will be `The index of the record to store.  for the default record.` instead of `The index of the record to store. null for the default record.`.

**Comment by RSuter** [comment]
Must be fixed in: 

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Infrastructure/XmlDocumentationExtensions.cs

**Comment by paulomorgado** [comment]
Do you have a test for it?

**Comment by paulomorgado** [comment]
Try throwing a `<see langword="null"/>` in there. You'll see that it will yield a space.

It would be nice if it yielded `null`.

**Comment by RSuter** [comment]
I think we should replace all `<see ... />` tags with the "langword" attribute value... should be easy to implement.
