### ISSUE TITLE
Multi-line summaries result in invalid generated C# client code

### ISSUE THREAD

**Issue by sandord** [RSuter/NSwag#1043]
```
    /// <summary>
    /// line1
    /// line2
    /// </summary>
    public string MyProperty { get; set; }
```

Results in:

```
    /// <summary>line1
line2</summary>
    [Newtonsoft.Json.JsonProperty("MyProperty", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string MyProperty
    {
        get { return _myProperty; }
        set 
        {
            if (_myProperty != value)
            {
                _myProperty = value; 
                RaisePropertyChanged();
            }
        }
    }
```
Which obviously won't compile.

**Comment by RSuter** [comment]
are you using the latest version of nswag/njs?

**Comment by sandord** [comment]
I'm sorry for not mentioning the version numbers. They are NSwag 11.12.0 and NJS 9.10.3. I pinned the latter because of recent problems and I'm going to try what happens when I remove the version pin.

**Comment by sandord** [comment]
Hm, apparently I didn't pin the version anymore. Anyway, I saw another update and now I'm on 11.12.1 / 9.10.3 and now the aforementioned bug is gone.

Thanks!

**Comment by RSuter** [comment]
This bug is not gone... just looking into this...

**Comment by sandord** [comment]
Indeed, now it seems the summaries are gone altogether.

**Comment by RSuter** [comment]
They are gone?

**Comment by sandord** [comment]
Yeah, I was trying to look them up to check whether the second line was correct again and saw that there were no summaries at all anymore.

**Comment by sandord** [comment]
At least that explains why I didn't get a compilation error and was a bit too quick to conclude that the bug had been solved.

**Comment by RSuter** [comment]
Very strange, in v11.12.1 I only sign the DLLs no other changes...

**Comment by sandord** [comment]
I think it happened because of some work I was doing in the meantime. Yep, I merged by models and controllers into a single project which hadn't XML doc enabled yet. Sorry about that.

**Comment by RSuter** [comment]
Ok, this was a problem at your end. But the multiline xml docs bug is fixed in the NJS commit (above). I'll upgrade NJS in NSwag do some tests and will release then...

**Comment by sandord** [comment]
Ok, thanks!

**Comment by RSuter** [comment]
v11.12.2 => released in approx. 15 minutes

**Comment by RSuter** [comment]
https://ci.appveyor.com/project/rsuter/nswag

Please upgrade, verify and report if it doesnt look good now...

**Comment by sandord** [comment]
Are you aware that the build failed?

**Comment by RSuter** [comment]
Just saw it... Seems that chocolatey is down AGAIN... retrying...

**Comment by RSuter** [comment]
Ok, looks good... new versions published to nuget

**Comment by sandord** [comment]
Tried it and it looks good!

**Comment by RSuter** [comment]
Ok, nice. Thanks for reporting and testing..
