### ISSUE TITLE
C# Compile Error When Using Negative Enum Values

### ISSUE THREAD

**Issue by myalexbennett** [RSuter/NSwag#1054]
When I input the following JSON with a negative enum value into NSwagStudio.

```
        "dayoffRule": {
          "format": "int32",
          "description": "Day off rule for the shift. ScheduleData.Enums.ShiftDayOffRule",
          "enum": [
            0,
            1,
            3,
            -1
          ],
          "type": "integer"
        },
```

I get the following invalid C#. Notice _1 is defined twice.

```
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.6.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum ShiftDayoffRule
    {
        _0 = 0,

        _1 = 1,   <<<

        _3 = 3,

        _1 = -1,   <<<

    }
```

Is there a workaround for this?

**Comment by RSuter** [comment]
You can provide a custom EnumNameGenerator

**Comment by myalexbennett** [comment]
So it doesn't work out of the box?

**Comment by RSuter** [comment]
We have to fix this here: https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration/DefaultEnumNameGenerator.cs#L12

**Comment by johnxjcheng** [comment]
@RSuter, I fixed the issue in the suggested location and created a pull request.

**Comment by RSuter** [comment]
Merged and nswag updated, release soon
