### ISSUE TITLE
DefaultTemplateFactory.GetEmbeddedLiquidTemplate AssemblyResolve issue

### ISSUE THREAD

**Issue by BlackGad** [RSuter/NSwag#1063]
Issue here that Assembly.Load do not trigger AssemblyResolve event. So .NET expected to see this assembly in AppDomain codebase folder.

Could you scan current AppDomain prior to Assembly.Load call? 

Example:
```csharp
var assemblyName = "NSwag.CodeGeneration." + language;
var assembly = AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(a => a.GetName().Name == assemblyName) ??
               Assembly.Load(new AssemblyName(assemblyName));
```

**Comment by RSuter** [comment]
What does this solve/what is your problem?

**Comment by BlackGad** [comment]
Trying to create some toolchain to control MSBuild build process from C# code using attributes. Attributes has their own assembly references. So I create dependency sandbox in temporary folder. Mechanism implemented using AssemblyResolve app domain event. Everything works except NSwag.CodeGeneration.CSharp assembly on client code generation. CodeBase in my case means nothing. And because DefaultTemplateFactory called from code where NSwag.CodeGeneration.CSharp assembly has been already resolved example above will work.

**Comment by RSuter** [comment]
I know inject assemblies into the factory: 

https://github.com/RSuter/NJsonSchema/commit/bfdbc58c51722155f1124460e0c35d6cb444ba91

This should solve your problem, because the assemblies are already loaded or trigger AssemblyResolve. Ok?

**Comment by BlackGad** [comment]
Yep looks promising :)

**Comment by BlackGad** [comment]
Thank you!

**Comment by RSuter** [comment]
Retest with v11.12.8

**Comment by BlackGad** [comment]
Defect still exist... You manage to pass assembly reference directly to DefaultTemplateFactory but forget to actually [use](https://github.com/RSuter/NSwag/blob/876d1236ff4faad74e23221d16a84b9fbd280a48/src/NSwag.CodeGeneration/DefaultTemplateFactory.cs) this reference :)

**Comment by RSuter** [comment]
Shit, sorry.

**Comment by RSuter** [comment]
v11.12.9

**Comment by BlackGad** [comment]
Works like a charm! Thank you again.
