### ISSUE TITLE
Type Script Generator: Angular 5 and OpaqueToken was removed

### ISSUE THREAD

**Issue by andrewinkler1** [RSuter/NSwag#1068]
The OpaqueToken is no longer available in Angular 5, we can no longer compile the generated type script client.

**Comment by RSuter** [comment]
There is a new option (i think TokenType) where you can switch to InjectionToken

**Comment by ite-klass** [comment]
The option is called `InjectionTokenType` ([ref](https://github.com/RSuter/NSwag/blob/6d253eb85a9820f4c3e562a5c586f366bd38dbfe/src/NSwag.Commands/Commands/CodeGeneration/SwaggerToTypeScriptClientCommand.cs#L77))

**Comment by RSuter** [comment]
@ite-klass thanks for correcting me here...
