### ISSUE TITLE
Web API Controller generation: Missing [FromBody] attribute on .NET Core

### ISSUE THREAD

**Issue by nmcc** [RSuter/NSwag#1075]
ASP.NET WebApi Core requires Controller parameters that are built from parsing the HTTP request body to have the corresponding parameter to be decorated with the attribute `[FromMember]`
e.g.
```csharp
public void Post([FromBody]string value)
```

I'm using the `swaggerToCSharpController` generator to generate Controllers targeting .NET Core 2.0.

I've followed [these instructions](https://github.com/RSuter/NSwag/wiki/SwaggerToCSharpControllerGenerator) to configure the generator, and I could get the generated code to compile properly.

But because the `[FromMember]` attribute is not generated, those parameters are not deserialized from the Request Body.

**Comment by RSuter** [comment]
The controller generator is not yet complete and features like that may be missing. Are you interested to contribute this feature?

**Comment by nmcc** [comment]
I'll give it a try within my free time 😄

**Comment by nikobiker12** [comment]
I think [FromBody] attribute is not specific to ASPNET CORE. Am I wwrong ?

**Comment by RSuter** [comment]
It exists in ASP.NET Core and ASP.NET... and you should render it when parameter.Kind == Body (not if it is an object)

**Comment by RSuter** [comment]
And please use fully qualified types (with namespace) so that no usings are required
