### ISSUE TITLE
Handle custom exceptions with Angular HttpClient

### ISSUE THREAD

**Issue by remcok** [RSuter/NSwag#1086]
Possibly also fixes #1070 #1071 #1072 #1059 

Unfortunately [Release v11.12.10](7151026db6d6b14bdfb2801d7abf216820a3579e) didn't fix the handling of the status codes and returning of custom exceptions for my Angular client. So I manually edited the generated code and found the following below.

It would take me too long to understand the in's and out's of the NSwag project itself and set it up locally to create a PR myself so hopefully you can review my code below and adopt this into your code for the next release so this can be automated. 

First I think there is some regression in commit  a3bdb16f702d5654af9ac7d73700ead2c92337a3.

The `catch` is checking for the instance of `HttpResponseBase` https://github.com/RSuter/NSwag/blob/a3bdb16f702d5654af9ac7d73700ead2c92337a3/src/NSwag.CodeGeneration.TypeScript/Templates/AngularClient.liquid#L82

After that, the response is casted to`any`
https://github.com/RSuter/NSwag/blob/a3bdb16f702d5654af9ac7d73700ead2c92337a3/src/NSwag.CodeGeneration.TypeScript/Templates/AngularClient.liquid#L87

But the `protected process{{...` method accepts a `HttpResponse<Blob>` and I think this should actually be of type `HttpResponseBase` so the cast as mentioned above could be avoided.
https://github.com/RSuter/NSwag/blob/a3bdb16f702d5654af9ac7d73700ead2c92337a3/src/NSwag.CodeGeneration.TypeScript/Templates/AngularClient.liquid#L97

The actual type checking should occur inside the body of the `protected process{{...` method because the parameter passed-in could be of type `HttpResponse<Blob>` __or__ `HttpErrorResponse`.

The class `HttpErrorResponse` doesn't have a property `body` but has an `error` property instead. So we need a way to determine the right content for the parameter to pass to the `blobToText` function. If we would use `blobToText(response.body)` on a response of type `HttpErrorResponse` an empty string will be returned resulting in not passing the actual error message/object back to the caller.

I tested the code below for `status === 409` and it seems to work.

Example:

    // Global function at same level as function blobToText 
    function responseToBlob(response: HttpResponseBase): any {
        if (response instanceof HttpResponse) {
            return response.body;
        }
        else if (response instanceof HttpErrorResponse) {
            return response.error;
        }
    }

    // Changes are:
    // response: HttpResponseBase
    // let blob: any = responseToBlob(response);
    // Replace `response.body` with `blob`
    protected processTest(response: HttpResponseBase): Observable<SwaggerResponse<void>> {
        const status = response.status;
         
        let blob: any = responseToBlob(response);

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 202) {
            return blobToText(blob).flatMap(_responseText => {
            return Observable.of<SwaggerResponse<void>>(new SwaggerResponse(status, _headers, <any>null));
            });
        } else if (status === 404) {
            return blobToText(blob).flatMap(_responseText => {
            return throwException("A server error occurred.", status, _responseText, _headers);
            });
        } else if (status === 400) {
            return blobToText(blob).flatMap(_responseText => {
            return throwException("A server error occurred.", status, _responseText, _headers);
            });
        } else if (status === 409) {            
            return blobToText(blob).flatMap(_responseText => {
            let result409: any = null;
            let resultData409 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result409 = resultData409 ? ErrorResponseModelOfSignUpError.fromJS(resultData409) : <any>null;
            return throwException("A server error occurred.", status, _responseText, _headers, result409);
            });
        } else if (status !== 200 && status !== 204) {
            return blobToText(blob).flatMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Observable.of<SwaggerResponse<void>>(new SwaggerResponse(status, _headers, <any>null));
    }

**Comment by RSuter** [comment]
I've updated the templates, please retest with the latest CI artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by remcok** [comment]
I didn't know how to make use of the nuget packages from above link in VS2017 so I've regenerated my code with the artifact of NSwagStudio. The propagation of the exceptions now works out of the box. Perfect, and thanks for the quick (re)action.

**Comment by RSuter** [comment]
Using the ci nuget packages is a little bit tricky because they have the same version as the latest released packages, this why you should use the studio - as you did... thanks for testing
