### ISSUE TITLE
Is it possible to share DTO classes?

### ISSUE THREAD

**Issue by ishepherd** [RSuter/NSwag#1088]
I'm generating a client for 2 swagger specs. I have used external `$ref` in one of the swagger specs to refer to some definitions in the other one.

I did this to avoid DRY violation, however when I generate the C# clients for each (separately), they each have independent DTO classes.

_Edit to add_ Also, the versions created through the external-$ref often have unhelpful names eg `Anonymous`, `Anonymous2`, ..

How can I make them share DTOs?

**Comment by RSuter** [comment]
Currently there are only two options to achieve this: 

- Preprocess the two swagger specs and merge them into a single one
- Generate both independently and exclude DTO classes from one spec with the excludedTypeNames setting

**Comment by ishepherd** [comment]
Ok, thanks
