### ISSUE TITLE
(NSwag/TypeScript web api client) generated code expects HttpResponse and can't handle HttpErrorResponse 

### ISSUE THREAD

**Issue by ctokareff** [RSuter/NSwag#1090]
Issue related to .Net Core 2.0 Web API

Generated code snipped looks like:
```
        if (status === 200) {
            return blobToText(response.body).flatMap(_responseText => {
...
            });
        } else if (status === 400) {
            return blobToText(response.body).flatMap(_responseText => {
...
```
But if result was returned via NotFoud() or StatusCode() then 'response' has type HttpErrorResponse and has no 'body', but 'error' instead.
Please put appropriate error handling code there

**Comment by remcok** [comment]
Hi @ctokareff, please check issue #1086

**Comment by RSuter** [comment]
I've updated the templates, please retest with the latest CI artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by RSuter** [comment]
Fixed with latest version. Reopen if its not the case..
