### ISSUE TITLE
 Abstract class results in wrong generated TS code.

### ISSUE THREAD

**Issue by rado0x54** [RSuter/NSwag#1093]
Hey,

with 11.12.10, apparently 'abstract' was added to some generated TS classes. This results in invalid code:

```
/** Base class for payloads that may be validated. */
export abstract class AbstractPayload implements IAbstractPayload {

    constructor(data?: IAbstractPayload) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
        }
    }

    static fromJS(data: any): AbstractPayload {
        let result = new AbstractPayload();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}
```

which results in
`error TS2511: Cannot create an instance of the abstract class 'AbstractPayload'.`
on line 
`let result = new AbstractPayload();`

11.12.9. works fine.

**Comment by RSuter** [comment]
Can you try this template which should fix the issue?

https://raw.githubusercontent.com/RSuter/NJsonSchema/master/src/NJsonSchema.CodeGeneration.TypeScript/Templates/Class.liquid

(use the TemplateDirectory setting and replace Class.liquid)

**Comment by faramos** [comment]
Hi,

I having this error using nswagstudio v11.13.3.0

There is some way to correct it using this template?

TIA

**Comment by RSuter** [comment]
So, you just want to disable the generation of abstract classes?

**Comment by faramos** [comment]
It´s required for me to generate the code for abstract classed.

I'll illustrate it better with two examples:

Examples:

**1.** 

   ```
 export class EntitiesDifference extends EntitiesOperation implements IEntitiesDifference {
    source: QueryNode = null;
    except: QueryNode = null;

    constructor(data?: IEntitiesDifference) {
        super(data);
        this._discriminator = "EntitiesDifference";
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.source = data["Source"] ? QueryNode.fromJS(data["Source"]) : new QueryNode();
```

NOTE: QueryNode is abstract. I replaced the code with null to continue working.

**2.**

```
static fromJS(data: any): PathPredicate {
        data = typeof data === 'object' ? data : {};
        if (data["discriminator"] === "InRelativePeriod") {
            let result = new InRelativePeriod();
            result.init(data);
            return result;
        }
```

NOTE: InRelativePeriod is abstract too. And is not possible to receive a discriminator with this value.

**Comment by RSuter** [comment]
Ok, I see - two more "special cases".

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/issues/1093#issuecomment-363476113
