### ISSUE TITLE
Automatically run 'dotnet publish' before NSwag.MSBuild target for ASP.NET Core

### ISSUE THREAD

**Issue by comdw** [RSuter/NSwag#1095]
My aim is to have swagger.json automatically generated at build time, which I understand is what NSwag.MSBuild is for.  As per [this](https://github.com/RSuter/NSwag/wiki/Assembly-loading), I need to (manually) run `dotnet publish` before my NSwag target would work.  However this doesn't give me a project that will build from clean.

I've tried adding a dotnet publish step to run before NSwag:

```
<Target Name="PublishForNSwag" AfterTargets="PostBuildEvent">
  <Exec Command="dotnet publish" />
</Target>

<Target Name="NSwag" AfterTargets="PublishForNSwag" DependsOnTargets="PublishForNSwag" >
  <Exec Command="$(NSwagExe_Core20) run nswag.json" />
</Target>
```

However this causes a loop in the build, since dotnet publish will attempt to build the project first (which will also trigger these targets).  There is a `--no-build` switch for dotnet publish but [that's been removed](https://github.com/dotnet/cli/issues/5331).  The workaround mentioned there is to instead use `dotnet msbuild /t:publish /p:NoBuild=True /p:BuildProjectReferences=False` but it doesn't solve the issue for me - I still get the build loop.

The only other workaround I know of is to reference the NuGet cache path (%userprofile%\.nuget\packages) in my nswag.json but this doesn't feel quite right as a solution and I'm not sure it will always load the right versions of nuget package DLLs in the case where several versions reside in that cache (and currently doesn't work due to [this](https://github.com/RSuter/NSwag/pull/1094)).

Does anyone have a better way to make this work, as I'm sure this must be a common requirement?  Maybe I'm going about it the wrong way...?

**Comment by RSuter** [comment]
It seems that dotnet publish is not needed, see this discussion: https://github.com/RSuter/NSwag/issues/1159#issuecomment-363886104
