### ISSUE TITLE
How can I create a new client ?

### ISSUE THREAD

**Issue by ZhaoRd** [RSuter/NSwag#1103]
Now the client only suppert  C# and angular ?
I will use Vue.js , and Vue use axios lib to request http .
How can I crate a new client to  create axios proxy  client code ?

**Comment by RSuter** [comment]
You have to add a new entry to the TypeScriptTemplate enum (e.g. Axios), add the "Axios.template" template, and implement all cases for this library... (maybe you need to extend the view models)

**Comment by RSuter** [comment]
Ref: https://github.com/axios/axios

**Comment by ZhaoRd** [comment]
@RSuter   now, axios support  Typescript ,  how can I do  with   nswag  to   build   axios  client ?

**Comment by dyesdyes** [comment]
Any update on this ?

@ZhaoRd have you found a workaround ?

**Comment by RSuter** [comment]
I currently dont have the time to add this. But shouldnt be that hard to implement...

**Comment by thijscrombeen** [comment]
#1945

**Comment by RSuter** [comment]
PR merged and will be available soon in v12.0.14, thanks @thijscrombeen for the PR! Please open new specific issues when there are problems with the axios template...

Release PR: https://github.com/RSuter/NSwag/pull/1945
