### ISSUE TITLE
Problem with C# generated api client and JSON TypeNameHandling.Auto.

### ISSUE THREAD

**Issue by alexdrl** [RSuter/NSwag#1110]
Hello, we are getting an issue using the generated API client from NSwag... The problem is the problem described in this issue. https://github.com/JamesNK/Newtonsoft.Json/issues/1128

The workaround is simple as adding the parameter `typeof(T)` in the `SerializeObject` call which corresponds to the type that accepts the API Controller. As I understand, this should be harmless, right?

EDIT: Would setting https://github.com/RSuter/NSwag/blob/f3f215f350a9ee787c22460cd90da3d7b5330d83/src/NSwag.Commands/Commands/CodeGeneration/SwaggerToCSharpClientCommand.cs#L193 to true solve this?

EDIT2: Setting the parameter to true worked, this would be a nice addition to the Wiki :)

Thank you.

**Comment by RSuter** [comment]
Thanks for reporting, can you update the wiki?

**Comment by alexdrl** [comment]
Done 😄 Can you review?

**Comment by RSuter** [comment]
Looks good, thank you...
