### ISSUE TITLE
Empty Value In Http Request Headers If Value is Empty

### ISSUE THREAD

**Issue by mvu02** [RSuter/NSwag#1125]
Using the NSwag generated code, we are adding a header with an empty value to the HTTP request, which occurs because we are setting the value of the optional header parameter to be null. The behavior that we want is when the optional header parameter is null, we should not be adding the header to the HTTP request at all.

An example of such a request is shown here:

POST https://google.com HTTP/1.1
Connection: Keep-Alive
Content-Type: text/plain
Accept: application/json
EmptyHeader:
Host: https://google.com

Our EmptyHeader parameter is null so NSwag is trying to run this:

request_.Headers.TryAddWithoutValidation("EmptyHeader", EmptyHeader!= null ? System.Convert.ToString(EmptyHeader, System.Globalization.CultureInfo.InvariantCulture) : null);

Which as a result ends up adding a header with an empty value. 

Is this the expected behavior for NSwag or should we be adding an if check to the template to make sure that if the value is null we should not try to add it to the header at all.

**Comment by RSuter** [comment]
We should add this if check to the templates... can you create a pr?

**Comment by mvu02** [comment]
@RSuter I created the PR, could you take a look? Thanks.

**Comment by RSuter** [comment]
Closing as PR is merged.
