### ISSUE TITLE
Exclude operation from authorization

### ISSUE THREAD

**Issue by burodevelopment** [RSuter/NSwag#1134]
I have implemented a API-Key authorization according to the middleware wiki. But now all operations need a API-Key. Is there a simple way to exclude 1 or more operations?

**Comment by burodevelopment** [comment]
Solved!

Changed authentication method from DelegatedHandler to AttributeFilter and can use AllowAnonymous attribute now. Check for AllowAnonymous on within a DocumentProcessor and clear the Security.

**Comment by skorunka** [comment]
@burodevelopment Hi, I'm facing the same issue with `Basic Authentication`. How did you exactly deal with that? Where did you change the authentication method?

I do generate C# clients using NSwag cli and then implement the interfaces. But I'm not able to mark one specific action with `[AllowAnonymous]`.

Thank you.

**Comment by RicoSuter** [comment]
Maybe with this processor?

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Generation.AspNetCore/Processors/AspNetCoreOperationSecurityScopeProcessor.cs

See also
https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware#add-oauth2-authorization-openapi-3

**Comment by skorunka** [comment]
@RicoSuter Hi Rico, thank you for a quick reply. I think I'm looking for something else. Let me reformulate my question.

I have C# clients generated from API json spec. All the controllers derive from `ApiControllerBase` which has `[Authorize]` attribute. So, all the requests must be authenticated. Now, I need to set action `/authorize` on a `UsersController` as `AllowAnonymous`. To allow endpoint `users/authorize` to be executed without authentication and I don't know how to do that.

I partially achieved that, by adding  `AllowAnonymous` to a `UsersController`(which is partial class), but now all the requests to `users` endpoint can be executed without authentication.

Is the `AspNetCoreOperationSecurityScopeProcessor ` whan I;m really looking for?

Thank you.

**Comment by RicoSuter** [comment]
I think this is not really an nswag issue but an asp.net core security question, right?

**Comment by skorunka** [comment]
Yes, it can be handled outside the generated clients code. But I think having the generator to handle the "security" attributes from the JSON/YAML spec would be nice feature to have:

You can set the authentication on the document level:
```
security:
  - basicAuth: []
```

In that case every controller should have `[Authorization]` attribute.

When you turn off authentication on the endpoint level:
```
      security: []
```
such an action should  have `[AllowAnonymous]`.

What do you think?

**Comment by RicoSuter** [comment]
So this is only for the controller generatpr?

**Comment by burodevelopment** [comment]
I agree with @skorunka. I would be a great feature for the generator to act on these kind of attributes. And I like to see this even on method level. So I can exclude 1 method within the controller as I wanted in the first place by starting this issue ;-)

**Comment by skorunka** [comment]
Yes, just for the controller generator.

**Comment by RicoSuter** [comment]
So this is actually just about generating the [Authorization] and [AllowAnonymous] based on the security info in the spec for C# controllers?

**Comment by skorunka** [comment]
Exactly.

**Comment by ismdiego** [comment]
> Yes, it can be handled outside the generated clients code. But I think having the generator to handle the "security" attributes from the JSON/YAML spec would be nice feature to have:
> 
> You can set the authentication on the document level:
> 
> ```
> security:
>   - basicAuth: []
> ```
> 
> In that case every controller should have `[Authorization]` attribute.
> 
> When you turn off authentication on the endpoint level:
> 
> ```
>       security: []
> ```
> 
> such an action should have `[AllowAnonymous]`.
> 
> What do you think?

Any news about this? I know this issue is closed, but I think I'm facing the same problem. I want to add "AllowAnonymous" to just one method of the generated controller. Security settings in OpenApi doc seems to not be considered yet (?).

Anyway, I would like to know if @burodevelopment  and/or @skorunka have some new hints about this.

**Comment by burodevelopment** [comment]
@ismdiego I cannot recall my specific case anymore :)

**Comment by ismdiego** [comment]
> @ismdiego I cannot recall my specific case anymore :)

Thanks anyway 👍 :)
