### ISSUE TITLE
Load all Controllers in assemblies specified by wildcard

### ISSUE THREAD

**Issue by galloglach** [RSuter/NSwag#1135]
When using _webapi2swagger_ is there a way to load all Controllers from assemblies specified by wildcard?

**Comment by galloglach** [comment]
If I update `IsolatedCommandBase.RunIsolatedAsync(string)` so that it calls 
`PathUtilities.ExpandFileWildcards(IEnumerable<string>).First()` before calling
`Path.GetFullPath(string)`,
as in:
```diff
protected async Task<TResult> RunIsolatedAsync(string configurationFile)
{
-    var assemblyDirectory = AssemblyPaths.Any() ? Path.GetDirectoryName(Path.GetFullPath(AssemblyPaths.First())) : configurationFile;
+    var assemblyDirectory = AssemblyPaths.Any() ? Path.GetDirectoryName(Path.GetFullPath(PathUtilities.ExpandFileWildcards(AssemblyPaths).First())) : configurationFile;
    var bindingRedirects = GetBindingRedirects();
    var assemblies = GetAssemblies(assemblyDirectory);

    using (var isolated = new AppDomainIsolation<IsolatedCommandAssemblyLoader<TResult>>(assemblyDirectory, AssemblyConfig, bindingRedirects, assemblies))
    {
        return await Task.Run(() => isolated.Object.Run(GetType().FullName, JsonConvert.SerializeObject(this), AssemblyPaths, ReferencePaths)).ConfigureAwait(false);
    }
}
```

then this works
`webapi2swagger /assembly:MyWebApiAssemblyNamespaceRoot*.dll /output:MyWebService.json`

**Comment by RSuter** [comment]
Good find. Can you create a PR?

**Comment by galloglach** [comment]
Hi Rico,

My first stab at doing a PR on Github and I’m unable to push my branch from “GitHub Desktop”, this is the error message I get,
“Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.“

Do you need to give me permission?

Also, the branch name is “issue-1135”, is that ok, or do you have a particular naming convention?

Regards,

Joe Friel
Lead Developer, Software Development, PSE
SITA

E-Mail:      joe.friel@sita.aero
Direct:      +353 (0) 74 9194 737
CVS:         293 4737
Mobile:     +353 (0) 860 219 256
Address:  SITA INC Ireland Ltd | Office Building 1 | IDA Business & Technology Park | Carnamuggagh Lower | Letterkenny | Co. Donegal | F92 XEP3 | Ireland

Join the conversation:
[cid:image003.jpg@01D38B03.F8EB9DB0]<http://www.sita.aero/resources/sita-social>
www.sita.aero
Please consider your environmental responsibility before printing

**Comment by RSuter** [comment]
You have to create a fork of nswag (a copy of the repo in your account) and push changes there, then create a pr from your repo and master into nswag/master
