### ISSUE TITLE
How to add custom Swagger UI

### ISSUE THREAD

**Issue by satishviswanathan** [RSuter/NSwag#1137]
As compared to SwashBuckle does Nswag provide a way to inject custom assets like the index.html and the styles.

Sample Swashbuckle Code
------------------------------
c.CustomAsset("index", thisAssembly, "Synapse.RF.Api.SwaggerExtension.index.html");
c.InjectStylesheet(thisAssembly, "Synapse.RF.Api.SwaggerExtension.swaggerExt.css");

Looking for a similar implementation in NSwag. Any help on this issue is really appreciated.

**Comment by Wesselfick** [comment]
Has there been any update on this ?

**Comment by RSuter** [comment]
I think it would be best/most flexible to just use UseSwagger() or UseSwaggerWithApiExplorer() and host the ui yourself...

**Comment by aaronhudon** [comment]
@RSuter can you advise if css/javascript injection is possible?

**Comment by RSuter** [comment]
Nope not out of the box but you could add a middleware which serves your css on the same path and register it before nswag... or create a PR with this feature
