### ISSUE TITLE
WebApi To Swagger doesn't support inheritance

### ISSUE THREAD

**Issue by FizzBuzz791** [RSuter/NSwag#1138]
I have the following (simplified) setup;

    [RoutePrefix("api/common/standard")]
    public class StandardController : ApiController
    {
        [HttpPost, Route("export")]
        public IHttpActionResult ExportStandard(StandardExportCriteria criteria) { ... }
    }

    [RouterPrefix("api/whatever/specific")]
    public class SpecificController : StandardController
    {
        [HttpPost, Route("export")]
        public IHttpActionResult ExportSpecific(SpecificExportCriteria criteria) { ... }
    }

All the configuration options are default and these two classes/controllers are in *separate* files, so I would expect two endpoints out of this setup;

- Standard_ExportStandard
- Specific_ExportSpecific

Unfortunately though, I get the following error when I try to run `nswag webapi2swagger ...`;  

> System.InvalidOperationException: The method 'Post' on path '/api/whatever/specific/export' is registered multiple times (check the DefaultUrlTemplate setting [default for Web API: 'api/{controller}/{id}'; for MVC projects: '{controller}/{action}/{id?}']).

I'm at a loss as to why this is occurring. I happens both via Nswag.MSBuild and via NSwagStudio.
I've tried using the "flatten inheritance heirarchy" setting as both true and false (explicitly) with no luck.
I've tried specifying *just* the SpecificController in the Controller option. 
I'm using NSwag Build 956 (a.k.a. latest release).
If I change the second route to export2 it all works fine.
Swashbuckle seems to happily generate the correct/expected json as per above expectations.

Perhaps it's my understanding of the DefaultUrlTemplate that is flawed?

**Comment by RSuter** [comment]
If you have RouterPrefix or Route attributes, the DefaultUrlTemplate is not used... It seems that NSwag uses the attribute 

[RoutePrefix("api/common/standard")]

also for the SpecificController and thus you have a duplicated route... I'll look into this...

**Comment by RSuter** [comment]
Is this really working? 

What operation is called when accessing "api/whatever/specific/export"? ExportStandard or ExportSpecific of which controller type? Can this be handled by Web API?

**Comment by FizzBuzz791** [comment]
Yeah, they are distinct routes. WebAPI has no problem with the above setup. We're using it in production right now; we have some global variables defined in js that point at the specific endpoints, we'd just like to migrate to swagger to avoid the overhead of managing all these endpoints manually.

Calling `api/whatever/specific/export` accesses `SpecificController.ExportSpecific`.
Calling `api/common/standard/export` accesses `StandardController.ExportStandard`.

**Comment by RSuter** [comment]
Ok, do you think this unit test is correct?

        [RoutePrefix("api/common/standard")]
        public class StandardController : ApiController
        {
            [HttpPost, Route("export")]
            public void ExportStandard(string criteria) {  }
        }

        [RoutePrefix("api/whatever/specific")]
        public class SpecificController : StandardController
        {
            [HttpPost, Route("export")]
            public void ExportSpecific(string criteria) {  }
        }

        [TestMethod]
        public async Task When_there_are_duplicate_paths_through_inheritance_then_the_base_method_is_ignored()
        {
            //// Arrange
            var generator = new WebApiToSwaggerGenerator(new WebApiToSwaggerGeneratorSettings());

            //// Act
            var document = await generator.GenerateForControllersAsync(new Type[] { typeof(StandardController), typeof(SpecificController) });
            var swaggerSpecification = document.ToJson();

            //// Assert
            Assert.AreEqual(2, document.Operations.Count());
            Assert.IsTrue(document.Operations.Any(o => o.Path == "/api/common/standard/export"));
            Assert.IsTrue(document.Operations.Any(o => o.Path == "/api/whatever/specific/export"));
        }

**Comment by RSuter** [comment]
Please check the unit test in the commit, does it look good?

**Comment by FizzBuzz791** [comment]
Left a comment on the commit for you.
