### ISSUE TITLE
When GenerateSwaggerAsync() catches exception it caches it forever

### ISSUE THREAD

**Issue by prochnowc** [RSuter/NSwag#1144]
We have some custom `IOperationProcessor` which needs to retrieve OIDC configuration. However when this request fails (which might temporarly fail because OIDC config is fetched over http) the failure is cached forever.

In middlewares the method
`protected virtual async Task<string> GenerateSwaggerAsync(HttpContext context)`
(AspNet and AspNetCore)

contains:

```catch (Exception ex)
        {
          swaggerMiddleware._swaggerJson = ex.ToString();
        }
```

The Exception should be cached - but not forever.

**Comment by RSuter** [comment]
Duplicate: https://github.com/RSuter/NSwag/issues/1151
Please discuss there...
