### ISSUE TITLE
`useHttpClientCreationMethod` in NSwagStudio?

### ISSUE THREAD

**Issue by ishepherd** [RSuter/NSwag#1148]
FYI. I can't see it there or am I missing it?

I don't care as long as I can change it in the `.nswag` without NSwagStudio wiping it out (Confirmed)

**Comment by RSuter** [comment]
Yes, it is there: 

![image](https://user-images.githubusercontent.com/2603405/35140926-4db8c8e2-fcf9-11e7-96ec-bd6b3c59d637.png)

but it is only available if a base class is set (ClientBaseClass) and InjectHttpClient is set to false

**Comment by ishepherd** [comment]
Oh, got it. Thanks.
(I hadn't tried that option. I had been declaring the base class via my client's `partial` companion class).
