### ISSUE TITLE
Crash after upgrading from 11.12.16 to 11.13.1

### ISSUE THREAD

**Issue by odinnou** [RSuter/NSwag#1158]
Hello, after upgrading "NSwag.AspNetCore" package to the version "11.13.1" and publish my API with "Release" configuration.

I try to call an action from my Swagger, then i got an 500 error.

After downgrade the package to 11.12.16 and republish the API, the error has dissapeared.

I attach the error (it's an html file, but I need to rename the extension
[Internal Server Error.txt](https://github.com/RSuter/NSwag/files/1671484/Internal.Server.Error.txt)
)

Thx in advance! (sorry for my english)

**Comment by RSuter** [comment]
Can you provide a complete reproduction sample?

**Comment by odinnou** [comment]
MY BAD -.-
I publish on my server without overwrite this file : InternalAPI.deps.json
so it's fail.

Sorry again
