### ISSUE TITLE
Get the HttpContent out of a generated client method

### ISSUE THREAD

**Issue by ishepherd** [RSuter/NSwag#1163]
I have a paging API where the client calls the server in a loop to fetch all pages.

I'm looking for:

1. My Loop calls _Generated GET_
a. The method returns *HttpContent*
2. My Loop looks at the `HttpContent.Headers`, to find out whether another page is available
a. If so, it calls _Generated GET_ again, *async*.
3. While it waits for that second page, My Loop can stay busy by reading and unpacking the HttpContent of first page. (Lots of JSON to deserialize)

Any ideas how to do such a thing or am I completely in the realm of handcoding?
Can I supply a custom template for just one Swagger Operation?

**Comment by RSuter** [comment]
I recommend to make the operation in question protected (ProtectedMethods setting) and implement it yourself in the partial class...

**Comment by ishepherd** [comment]
OK, thanks... I had assumed that just makes it `protected`, but now I see that it renames it too. So I can declare my own version.
