### ISSUE TITLE
Generated C# client code uses HttpClient wrong, leading to connection starvation issues

### ISSUE THREAD

**Issue by jtheisen** [RSuter/NSwag#1164]
`HttpClient` has a peculiar caveat, see this article:

https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

Since the generated client creates `HttpClient` instances per request, you're going to have a connection starvation issue very quickly if you're doing a lot of requests or if you're on Azure Web Apps where connections are severely limited.

I think the generated client should make `HttpClient` an instance member and reuse that.

I'm aware of the workaround of passing a custom instance in, but this will hit anyone who uses the default.

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/issues/1097

Ok, maybe we should change the default settings so that HttpClient injection is the default...

**Comment by jtheisen** [comment]
I see.

I'd be in favor of holding a single instance per nswag client even for the not-injected case.

The current not-injected behavior is never what you want: Even in that load-balancer case that is mentioned in the other ticket you still need to watch out not to create too many clients by using a pool or something.

One `HttpClient` per nswag-client strikes me as the most reasonable default.
