### ISSUE TITLE
Antipaterns in c# code generation

### ISSUE THREAD

**Issue by cordasfilip** [RSuter/NSwag#1172]
When generating c# client code the created code uses a few not recommend solutions for writing c# apps.
First https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/
There should be a way of controlling the HttpClient creation like a virtual method GetHttpClient.
Also serialization of json is somewhat unoptimized https://www.newtonsoft.com/json/help/html/Performance.htm
You should also add a method for serialization and deserialization.

**Comment by heldersepu** [comment]
Good stuff thanks for sharing!

**Comment by RSuter** [comment]
There are already many ways to control how HttpClient is used (e.g. InjectHttpClient, DisposeHttpClient, UseHttpClientCreationMethod, HttpClientType). Improving JSON serialization would be great...

Also see https://github.com/RSuter/NSwag/issues/1097

**Comment by cordasfilip** [comment]
@RSuter Thanks I don't know how I missed the setting sorry about that.

**Comment by shaynevanasperen** [comment]
See also https://github.com/aspnet/HttpClientFactory

**Comment by RSuter** [comment]
Closing as there are already enough settings to completely control that and also use HttpClientFactory
