### ISSUE TITLE
WebApiToSwaggerGenerator - external reference

### ISSUE THREAD

**Issue by MaxDeg** [RSuter/NSwag#1179]
Hello,

I'm trying to generate a swagger from WebApi controllers, I case of BadRequest the object returned is a ProblemDetail which is part of a shared library. For this shared type a swagger definition exists and I would like to reuse it. 
For this I use a type mapper to map the ProblemDetail to the url of the definition. But neither of those two mapper work.

With the primivetypemapper, I get the following error: "Could not find the JSON path of a referenced schema: Manually referenced schemas must be added to the 'Definitions' of a parent schema."
Which is correct because it's what I want.

With the ObjectTypeMapper, I get no error but it generate a wrong swagger:
```
 "400": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/ProblemDetail"
            },
            "x-nullable": true
          }
```

```csharp
var settings = new WebApiToSwaggerGeneratorSettings
            {
                IsAspNetCore = options.IsAspNetCore,
                DefaultEnumHandling = options.DefaultEnumHandling,
                DefaultPropertyNameHandling = options.DefaultPropertyNameHandling,
                FlattenInheritanceHierarchy = options.FlattenInheritanceHierarchy,
                Title = options.Title ?? serviceManifest.Service.Name,
                Version = options.Version,
                TypeMappers =
                {
                    new ObjectTypeMapper(typeof(ProblemDetail), new JsonSchema4
                    {
                        DocumentPath = "http://my-domain/problem.json#/definitions/problem-detail"
                    }),
                    new PrimitiveTypeMapper(typeof(ProblemDetail), s =>
                    {
                        s.Reference = new JsonSchema4
                        {
                            DocumentPath = "http://my-domain/problem.json#/definitions/problem-detail"
                        };
                    })
                }
            };
```

Any idea on how to get it working? Is it possible?

**Comment by RSuter** [comment]
try

    DocumentPath = "http://my-domain/problem.json"
    ReferencePath = "http://my-domain/problem.json#/definitions/problem-detail"

**Comment by MaxDeg** [comment]
It worked indeed :)
Thanks a lot for the very fast answer.

For the record:
```csharp
new PrimitiveTypeMapper(typeof(ProblemDetail), s =>
{
    var jsonRef = (IJsonReferenceBase)s;
    jsonRef.DocumentPath = "http://my-domain/problem.json";
    jsonRef.ReferencePath = "http://my-domain/problem.json#/definitions/problem-detail";
})
```

**Comment by RSuter** [comment]
You're welcome...
Indeed, I think you dont even have to set DocumentPath if you only serialize the spec to JSON after generating it...
