### ISSUE TITLE
3621

### ISSUE THREAD

**Issue by ranouf** [RSuter/NSwag#1196]
Hi,

I have a weird problem on fromJS function. 
I received correctly the data from the API:
![image](https://user-images.githubusercontent.com/1764519/36283858-d8e4145a-1273-11e8-860e-6e1704e33471.png)

But after using the fromJS function, the serialization doesnt work:
![image](https://user-images.githubusercontent.com/1764519/36283911-fba1aee4-1273-11e8-9fc1-4d5ab356ca83.png)

This the JS SensorData class
![image](https://user-images.githubusercontent.com/1764519/36283944-12b26c40-1274-11e8-98aa-db6c7b39ffdd.png)

This is the C# SensorData class
![image](https://user-images.githubusercontent.com/1764519/36284003-34c83b7a-1274-11e8-86ad-a85750051a37.png)

My guess is the DateTime conversion maybe ...

I will do some tests, but problably other people could have this problem, they will interested bu the solution :).

Let me know it you have a solution?

**Comment by ranouf** [comment]
I only keep the Frequency:
![image](https://user-images.githubusercontent.com/1764519/36284779-01e9f8b2-1277-11e8-998c-2302b71ba547.png)
![image](https://user-images.githubusercontent.com/1764519/36284791-1279a236-1277-11e8-9961-757c067fcf43.png)

And I have the same problem ...

**Comment by ranouf** [comment]
I fixed the issue by changing Class to Interface in NsSwagStudio in TypeStyle:
![image](https://user-images.githubusercontent.com/1764519/36285207-a2679cee-1278-11e8-8804-c780cbcf3e3d.png)

**Comment by RSuter** [comment]
Actually, we should still look into this...

**Comment by RSuter** [comment]
And keep in mind that lots of features are not available with interfaces because the data is not transformed (i.e. date properties are string properties in interfaces because JSON does not support dates).

**Comment by RSuter** [comment]
I think you need to correctly set the DefaultPropertyNameHandling to CamelCase?

**Comment by ranouf** [comment]
You were right! It works perfectly.
![image](https://user-images.githubusercontent.com/1764519/36318106-e3e1f1a8-130c-11e8-9422-f3fe8b95c4e8.png)
![image](https://user-images.githubusercontent.com/1764519/36318120-ecbb8168-130c-11e8-9e40-f604ae198939.png)

**Comment by RSuter** [comment]
We can close it...
