### ISSUE TITLE
Override equals in Model

### ISSUE THREAD

**Issue by josefarinna** [RSuter/NSwag#1199]
We are using Mock library for creating our unit test, and some of the nswag functions has a parameter that is a nswag model, I would like to override the equals of that model so I can successfully mock the function.

Is it possible to do it?

**Comment by RSuter** [comment]
You can override a template (for example Class.liquid): https://github.com/RSuter/NJsonSchema/wiki/Templates

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/Templates/Class.liquid

**Comment by RSuter** [comment]
I've added Class.Body.liquid so you can add additional class body code without replacing the whole class template (and miss future fixes in it).

**Comment by RSuter** [comment]
(will be available in the next release)
