### ISSUE TITLE
WebAPI - Returns "object" instead of Type

### ISSUE THREAD

**Issue by Jascen** [RSuter/NSwag#1201]
I updated my NSwag and found that my newly generated C# Client started returning "object" rather than the concrete types I had defined in my **ProducesResponseType** attributes.  After debugging, I have deduced that the reason for this is because of commit c3c3a896.  The addition of **|| a.GetType().Name == "ProducesAttribute"** to _WebApi.OperationResponseProcessor.ProcessAsync()_ started pulling in my attributes for **[Produces("application/json")]**.

As a quick fix, I cloned the source and simply removed the new code.  However, I'd like to know if I'm doing something wrong or if this is just a bug.

**Comment by RSuter** [comment]
So you have a ProducesResponseTypeAttribute and a ProducesAttribute on the operation?

**Comment by Jascen** [comment]
Yes.  As an example:

[HttpGet("Id")]
            [Produces("application/json")]
            [ProducesResponseType(200, Type = typeof(TimeRunTimeImageResultViewModel))]
            public virtual async Task<IActionResult> GetAsync([FromQuery] int timeRunId, [FromQuery] int timeImageResultId, CancellationToken cancellationToken)

**Comment by RSuter** [comment]
The response type is not even checked.. this is why I removed it, if you want to support it, can you create a PR?

**Comment by Jascen** [comment]
Sorry, I didn't realize that it was closed in a checkin.  Now I see the point of confusion was that I am using an overload that you are now properly ignoring in 64a8ab1.
