### ISSUE TITLE
NSwag Non Nullable Dates not .net Standard Compatible

### ISSUE THREAD

**Issue by blueboxes** [RSuter/NSwag#1205]
Using Nswag studio and the ` [Required] ` attribute on an int property, it correctly generates a non-nullable int property with single attribute.

```
[Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
public int Id { get; set; }
```
    
If I do the same for a date it also includes System.ComponentModel.DataAnnotations which is not .net Standard Compatible

```
        [Newtonsoft.Json.JsonProperty("StartDateTime", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTime StartDateTime { get; set; }
```

I think this is a bug?

**Comment by RSuter** [comment]
Install System.ComponentModel.Annotations or disable annotation generation

See https://github.com/RSuter/NSwag/wiki/SwaggerToCSharpClientGenerator#required-dependencies-for-the-client

**Comment by blueboxes** [comment]
Thanks I did not realise System.ComponentModel.DataAnnotation was now a nuget package.
