### ISSUE TITLE
C# client generation questios

### ISSUE THREAD

**Issue by ili** [RSuter/NSwag#1207]
Hello! I do have few questions:
* I'm looking forward to make API responses read only POCOs, I do mean smth like that:
```cs
puclic class MyResponce
{
    [Newtonsoft.Json.JsonConstructor]
    public MyResponce(int intValue, string stringValue)
    {
         IntValue = intValue;
         StringValue = stringValue;
    } 

    public int IntValue { get; }
    public string StringValue { get; }
}
```

Are there any possibility to do that?

* Is it possible to generate synchronous controller API?
* Is it possible to force using [ConfigureAwait(false) for async calls in client](https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f)

**Comment by RSuter** [comment]
1. You can generate POCOs instead of INPCs (setting)
2. There is a setting to also generate sync methods (not recommended)
3. We should definitely generate ConfigureAwait(false), good point

**Comment by RSuter** [comment]
New issue created: https://github.com/RSuter/NSwag/issues/1209

**Comment by ili** [comment]
> You can generate POCOs instead of INPCs (setting)

I do, but I want to make them read only. You see, for example I do have complex request to insert business operation, there are huge data amount:
* contractors
* stuff
* payments 

etc. so I do want to guarantee that all data would be filled on client side, if contract would be changed and new field would be added I would like to check it at compiler time. So the thing I do want is to fill all data as constructor parameters. So I do need to generate POCOs like `MyResponce` in the firs post sample

> There is a setting to also generate sync methods (not recommended)
I see, but I would prefer using sync methods, please, how does this setting is called?

**Comment by RSuter** [comment]
1. This scenario is currently not supported, but you can completely replace the templates: https://github.com/RSuter/NJsonSchema/wiki/Templates
2. GenerateSyncMethods
3.

**Comment by ili** [comment]
Thanks a lot!
