### ISSUE TITLE
SwaggerUiSettings is now a generic but the documentation doesn't how show to use it as such.

### ISSUE THREAD

**Issue by Maleki** [RSuter/NSwag#1230]
Version 11.16.0

Trying out NSwag in Asp.NET Core and the example in the wiki contains the following line.

`app.UseSwaggerUi(typeof(Startup).GetTypeInfo().Assembly, new SwaggerUiSettings()`

In visual studio SwaggerUiSettings is underlined with the error description `Using the generic type 'SwaggerUiSettings<T>' requires 1 type arguments`

Reverted to 11.15.4 and the error disappears.

**Comment by RSuter** [comment]
I've updated the wiki: https://github.com/RSuter/NSwag/wiki/Middlewares

**Comment by Maleki** [comment]
Looks good.  Thanks.

**Comment by seblucas** [comment]
@RSuter 
Thanks for updating the docs
I fixed a typo in https://github.com/RSuter/NSwag/wiki/Middlewares/fdf28e872c02c4f913550139bb5b7a23ea72873c

**Comment by RSuter** [comment]
Thanks for fixing the typos!
