### ISSUE TITLE
Virtual methods for MultipleClientsFromOperationIdOperationNameGenerator  ?

### ISSUE THREAD

**Issue by GreenMooseWork** [RSuter/NSwag#1231]
Hi.

I was planning of deriving from the default `MultipleClientsFromOperationIdOperationNameGenerator` so I could tweak it a tad and  "V1" prefix in the operation methods, but I noticed that the public methods are not virtual. Is this by design?

Thanks for a great library :)

**Comment by RSuter** [comment]
No it's not by design, I just thought that most people just implement an own version of IOperationNameGenerator :-)

**Comment by RSuter** [comment]
v11.16.1
