### ISSUE TITLE
web api net core 2.0 generate client

### ISSUE THREAD

**Issue by angelru** [RSuter/NSwag#1240]
Hello, 

I'm receiving this error with web api assembly:

tem.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. El sistema no puede encontrar el archivo especificado.
File name: 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'Microsoft.AspNetCore.Mvc.ViewFeatures'

**Comment by RSuter** [comment]
https://github.com/RSuter/NSwag/wiki/Assembly-loading#net-core

**Comment by angelru** [comment]
thanks a lot!

**Comment by cwaldron** [comment]
After following all the step (also please inform where to place the publish instruction in the build file.  I had to guess at it via trial & error), I get the following failure ...

![image](https://user-images.githubusercontent.com/2838270/41689408-93dbc6c6-7544-11e8-955c-33ff4f35f30e.png)

**Comment by RSuter** [comment]
Use the correct runtime:

![image](https://user-images.githubusercontent.com/2603405/41703327-2fd1234e-7533-11e8-8c27-6cfaaf9165db.png)
