### ISSUE TITLE
I'd like to use yaml instead of json on swaggerUI

### ISSUE THREAD

**Issue by risogolo** [RSuter/NSwag#1243]
I'd like to load static yaml file (not generated)  via SwaggerUI, is it possible?

**Comment by RSuter** [comment]
I think this could work: 

```
app.UseSwaggerUi(settings => 
{
     settings.SwaggerRoute = "/my/path/to/swagger.yaml";
     settings.SwaggerUiRoute = "/swagger";
});
```

**Comment by risogolo** [comment]
This was the 1st thing I actually tried, but it does not work, it says - file not found, file is located in the same folder as json which works

**Comment by risogolo** [comment]
This works only when the swagger file is generated from the assembly but I need to just load a static file instead

**Comment by RSuter** [comment]
Seems to work for me?

![image](https://user-images.githubusercontent.com/2603405/38020997-06f9aca6-327c-11e8-870e-c0a7b2d6362b.png)

It probably only works if the file is hosted on the same server...

**Comment by RSuter** [comment]
Just don't add the assembly as first parameter then only the UI is served and no spec is generated...

**Comment by risogolo** [comment]
Yes that works, I was trying with UseSwaggerUi3, and that does not work, it says:
Failed to load API definition. Fetch errorNot Found /swagger/v1/swagger.yaml

**Comment by RSuter** [comment]
Can you try to directly load the yaml file which is shown in the UI? Is this working? (also check what URL is loaded by the UI with F12 and check if this is accessible)

**Comment by risogolo** [comment]
not sure whether this helps:
![image](https://user-images.githubusercontent.com/13233569/38021841-3b87cef6-327e-11e8-8599-d862a18c04d7.png)

**Comment by RSuter** [comment]
Yes, so now you just have to ensure that the yaml file is served from http://localhost:3001/swagger/v1/swagger.yaml - you need to do this manually...

**Comment by risogolo** [comment]
Not sure what you mean, the file is located in that folder, if I use UseSwaggerUi it works, if I use UseSwaggerUi3 it does not.

**Comment by risogolo** [comment]
sorry for confusion, so it does not work in both cases when you want to display static yaml file, I was cached version from browser when I used generated yaml from assembly before

**Comment by RSuter** [comment]
I think you cannot just put a file in a directory and access it with ASP.NET Core, you need to register a middleware for that: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?tabs=aspnetcore2x

**Comment by risogolo** [comment]
I have it there, see my previous comment

**Comment by RSuter** [comment]
The problem may be that the UI and static file are both served from /swagger and only one of the middlewares are being process and the other is ignored... maybe try to register the static file middleware before nswag m.?

**Comment by risogolo** [comment]
the StaticFiles middleware was registered before, but I got back to the static json, not yaml an it says something different: 
Can't read from server. It may not have the appropriate access-control-origin settings.

**Comment by RSuter** [comment]
Ok, then you're probably almost there
https://docs.microsoft.com/en-us/aspnet/core/security/cors

**Comment by risogolo** [comment]
So, my findings:
json issues:
the message about cors is wrong, I had all the stuff allowed, but the problem is that I had non valid json, then it is evaluated in js file as `else if (response.status === 0) {
          return self.fail('Can\'t read from server.  It may not have the appropriate access-control-origin settings.');`
if I want to expose yaml file via staticfiles lib I have to register the extensions like `var provider = new FileExtensionContentTypeProvider();
            // Add new mappings
            provider.Mappings[".yaml"] = "application/x-yaml";` then use it in staticfiles settings

**Comment by RSuter** [comment]
Good findings. It would be great if you could update the wiki with that: https://github.com/RSuter/NSwag/wiki/Middlewares#customization
