### ISSUE TITLE
Errors with typescript 2.8.1

### ISSUE THREAD

**Issue by Guymestef** [RSuter/NSwag#1244]
Hello,

The generated api is throwing transpilation errors for:

```typescript
let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v, k) => _headers[k] = v); };
```
Parameter 'v' implicitly has an 'any' type.
Parameter 'k' implicitly has an 'any' type.

**Comment by RSuter** [comment]
Thanks for reporting. Is this the only issue with TS 2.8?

**Comment by Guymestef** [comment]
At first view yes. But I'm only using the template Fetch, so for other templates, I don't know.

**Comment by RSuter** [comment]
Ok, that's fine...
