### ISSUE TITLE
Wrong $ref generated for responses when using alongside custom operation process

### ISSUE THREAD

**Issue by crafty615** [RSuter/NSwag#1247]
I am using the the `SwaggerResponseAttribute` alongside my own attribute that adds a parameter for the request body. They work individually but when used at the same time, my custom attribute works fine but the `SwaggerResponseAttribute` has the wrong $ref paths generated.

Here is what I have:
Attributes on controller endpoints:
`[SwaggerResponse(typeof(Animal))]
[SwaggerBodyParam(typeof(Animal))]`

OperationProcessor:
`public class SwaggerBodyParamOperationProcessor : IOperationProcessor
{
    private readonly SwaggerBodyParam _bodyParam;

    /// <summary>
    /// Creates a new instance of SwaggerBodyParamOperationProcessor
    /// </summary>
    /// <param name="bodyParam"></param>
        public SwaggerBodyParamOperationProcessor(SwaggerBodyParam bodyParam)
        {
            _bodyParam = bodyParam;
        }

        /// <summary>
        /// Adds the body param schema to swagger endpoints with the SwaggerBodyParam Attribute
        /// </summary>
        /// <param name="context">Operation Processor Context</param>
        /// <returns>True</returns>
        public Task<bool> ProcessAsync(OperationProcessorContext context)
        {
            if (_bodyParam != null)
            {
                if (context.OperationDescription.Operation.Consumes == null)
                    context.OperationDescription.Operation.Consumes = new List<string>();

                context.OperationDescription.Operation.Consumes.Clear();
                context.OperationDescription.Operation.Consumes.Add(_bodyParam.MediaType);

                if (context.OperationDescription.Operation.Parameters != null)
                {
                    context.OperationDescription.Operation.Parameters.Add(new SwaggerParameter()
                    {
                        Name = _bodyParam.ParameterName,
                        Kind = SwaggerParameterKind.Body,
                        IsRequired = _bodyParam.IsRequired,
                        Schema = context.SchemaResolver.GetSchema(_bodyParam.ParameterType, false)
                    });
                }
            }

            return Task.FromResult(true);
        }
    }`

Swagger UI response:
`Response Class (Status 200)
Animal
<span class="strong">#/paths//animals/Post/parameters/0/schema is not defined!</span>`

Swagger Json:
`"put": {
                "tags": [
                    "Animal"
                ],
                "summary": "Updates an Animal",
                "operationId": "Animal_UpdateAnimal",
                "consumes": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Animal's ID",
                        "format": "int32",
                        "x-nullable": false
                    },
                    {
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "discriminator": "AnimalType",
                            "additionalProperties": false,
                            "required": [
                                "Diet",
                                "AnimalType"
                            ],
                            "properties": {
                                "Id": {
                                    "type": "integer",
                                    "format": "int32"
                                },
                                "Species": {
                                    "type": "string"
                                },
                                "NumberOfLegs": {
                                    "type": "integer",
                                    "format": "int32"
                                },
                                "IsDomesticated": {
                                    "type": "boolean"
                                },
                                "Diet": {
                                    "$ref": "#/definitions/Diet"
                                },
                                "IsExtinct": {
                                    "type": "boolean"
                                },
                                "AnimalType": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "x-nullable": true,
                        "description": "Animal",
                        "schema": {
                            "$ref": "#/paths//animals/Post/parameters/0/schema"
                        }
                    }
                }
            }`

As you can see the $ref is generating "#/paths//animals/Post/parameters/0/schema" instead of "#/definitions/Animal"

**Comment by RSuter** [comment]
Try adding a reference:

```
Schema = new JsonSchema4 
{ 
    Reference = context.SchemaResolver.GetSchema(_bodyParam.ParameterType, false)
}
```

**Comment by crafty615** [comment]
That worked perfect. I didn't realize that you should set the reference on the schema when you get an existing schema and set the whole schema object when you generate a new schema.
