### ISSUE TITLE
Combining MSBuild and nswag.json variables might create invalid json

### ISSUE THREAD

**Issue by glatzert** [RSuter/NSwag#1251]
I was trying to use Variables and NSwag.json from MSBuild like this:

```
<Exec Command="$(NSwagExe_Core20) webapi2swagger run nswag.json /variables:"assembly=$(TargetPath)" />
```

This will end in Invalid JSON, since $(TargetPath) naturally contains "\" which is needed to be escaped in JSON.

My proposals to solve this are:
- Either provide a way to pass overrides for nswag.json (e.g: `/overrides:"path:in:json=newValue"`) (which is still problematic, because multiple overrides have to be separated by something, which might also be part of newValue)
 - Or allow automatic string escaping in nswag.json (e.g: `nswag.exe run nswag.json /escapeVars:true /variable:"foo=b\ar"`)

I assume the last one would be easier to implement in the variable Substitution, and with some advice where to look, i'd also provide a PR for that.

**Comment by RSuter** [comment]
I'd say that variables are only allowed in string properties, so they should be always escaped?

The code is in: 
https://github.com/RSuter/NSwag/blob/master/src/NSwag.Commands/NSwagDocumentBase.cs#L183
https://github.com/RSuter/NSwag/blob/master/src/NSwag.Commands/NSwagDocumentBase.cs#L271

**Comment by glatzert** [comment]
Hm.. there's a solution for the Environment variables, which might also work for user provided variables here:

https://github.com/RSuter/NSwag/blob/3a780d1e55844eccd7162d5b0d77271e2ecb68d6/src/NSwag.Commands/NSwagDocumentBase.cs#L181

Can you think of any valid use case for "\" in the nswag.json currently?

**Comment by RSuter** [comment]
Hmm, backslashes are allowed in paths on Windows... Maybe we should instead of replacing this particular case just JSON escape the env vars and other vars?

**Comment by glatzert** [comment]
Windows uses `/` and `\` interchangeably as far as I know (that's why the replacement in line 181 also solves the problem). So problaby it'd be sufficient to use `p.Value.Replace("\\", "/")` instead of p.Value during the Substitution.

But since i'm more or less new to nswag, I cannot forsee use cases for `\` in variables ..

**Comment by RSuter** [comment]
`.Replace("\\", "/")` avoids the problem of escaping \ in the vars - but it seems that we have to escape anyway, so we can just remove the replace and instead of proper escaping...

```JSON
"path": "sample/$(myPath)/foo"
```

Here my path can be "foo\bar" or "foo/bar" but \ must be escaped in order to have valid JSON...

**Comment by glatzert** [comment]
Changed two lines of Code, all Tests (not using something remote) were green:
https://github.com/RSuter/NSwag/pull/1252
