### ISSUE TITLE
The generator Inferface for angular are PascalCase and not camelCase

### ISSUE THREAD

**Issue by Anderman** [RSuter/NSwag#1258]
The generator interface is PascalCase
```
export interface ConflictInfo {
    ReadyToUpdate?: IntusPlanning[] | null;
    ReadyToDelete?: IntusPlanning[] | null;
    NewForUpdate?: IntusPlanning[] | null;
    Updates: number;
    Deletes: number;
}
```
But net core use camelCase for json output.
I tried some settings in mine .nswag file. But this doesnot seems to work. 
```
{
  "runtime": "NetCore20",
  "swaggerGenerator": {
    "webApiToSwagger": {
      "controllerNames": [],
      "isAspNetCore": true,
      "defaultUrlTemplate": "api/{controller}/{id?}",
      "defaultPropertyNameHandling": "CamelCase",
      "defaultReferenceTypeNullHandling": "Null",
      "defaultEnumHandling": "Integer",
      "flattenInheritanceHierarchy": false,
      "generateKnownTypes": true,
      "generateXmlObjects": false,
      "generateAbstractProperties": false,
      "addMissingPathParameters": false,
      "ignoreObsoleteProperties": false,
      "allowReferencesWithProperties": false,
      "excludedTypeNames": [],
      "output": null,
      "assemblyPaths": [
        "bin/Debug/netcoreapp2.0/Itzos.Vvt.Web.dll"
      ],
      "referencePaths": [
        "%USERPROFILE%/.nuget/packages"
      ]
    }
  },
  "codeGenerators": {
    "swaggerToTypeScriptClient": {
	  "PropertyNameHandling" : "CamelCase",
	  "DefaultPropertyNameHandling" : "CamelCase",
      "className": "{controller}Client",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 2.7,
      "template": "Angular",
      "promiseType": "Promise",
      "httpClass": "HttpClient",
      "injectionTokenType": "InjectionToken",
      "dateTimeType": "Date",
      "nullValue": "Null",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateOptionalParameters": false,
      "wrapDtoExceptions": false,
      "wrapResponses": false,
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "useTransformOptionsMethod": false,
      "useTransformResultMethod": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "markOptionalProperties": true,
      "generateCloneMethod": false,
      "typeStyle": "Interface",
      "generateDefaultValues": false,
      "excludedTypeNames": [],
      "handleReferences": false,
      "generateConstructorInterface": true,
      "convertConstructorInterfaceData": false,
      "importRequiredTypes": true,
      "useGetBaseUrlMethod": false,
      "baseUrlTokenName": "API_BASE_URL",
      "queryNullValue": "",
      "output": "../../my-app/src/app/services/backend.service.ts"
    }
  }
}
```
I also tried to change the startup.cs
```
            app.UseSwaggerUi(typeof(Startup).GetTypeInfo().Assembly, new SwaggerUiSettings
            {
                DefaultPropertyNameHandling = PropertyNameHandling.CamelCase
            });

```

Is there a way to use camel case in my generated output??

**Comment by RSuter** [comment]
The casing in the interfaces is exactly as the properties in the Swagger spec, because in an interface, we cannot rename them (they must exactly match the received JSON structure). 

    DefaultPropertyNameHandling = PropertyNameHandling.CamelCase

should change the casing of the properties in the Swagger spec and thus generate lower camel cased interfaces... (but maybe you also need to change the ASP.NET serializer to serialize correctly). Check the swagger spec if the properties are lower camel case...

**Comment by RSuter** [comment]
Or did you add [JsonProperty("MyProperty")] with upper cased names? If so, the serializer serializes to these properties and then the TS interfaces cannot be lower cased...

**Comment by Anderman** [comment]
The net Core api response with lower camelCase. 
`{"readyToUpdate":[{"intusPlanningId":5970,"datum":"0001-01-01T00:00:00","resGroepId"`

My C# class is with upper camelCase
```
    public class ConflictInfo
    {
        public IEnumerable<IntusPlanning> ReadyToUpdate { get; set; }
        public IEnumerable<IntusPlanning> ReadyToDelete { get; set; }
        public IEnumerable<IntusPlanning> NewForUpdate { get; set; }
        public int Updates => ReadyToUpdate?.Count()??0;
        public int Deletes => ReadyToDelete?.Count()??0;
    }

```

The generatored interface in my backendserivce.ts
```
export interface ConflictInfo {
    ReadyToUpdate?: IntusPlanning[] | null;
    ReadyToDelete?: IntusPlanning[] | null;
    NewForUpdate?: IntusPlanning[] | null;
    Updates: number;
    Deletes: number;
}

```
But I expected this

```
export interface conflictInfo {
    readyToUpdate?: intusPlanning[] | null;
    readyToDelete?: intusPlanning[] | null;
    newForUpdate?: intusPlanning[] | null;
    updates: number;
    deletes: number;
}

```

**Comment by RSuter** [comment]
Can you post the generated Swagger spec? How do you generate the spec? Via middleware (then `DefaultPropertyNameHandling = PropertyNameHandling.CamelCase` should be enough)? If you generate via NSwagStudio/command line then you need to set it also in the nswag.json...

**Comment by Anderman** [comment]
I used the WebApi Assembly option and NSwagstudio. If I used the first tab (Swagger specification) and 'create local copy' I get the correct casing
`"ConflictInfo":{"type":"object","properties":{"readyToUpdate":{"type":"array","items":{"$ref":"#/definitions/IntusPlanning"}},"readyToDelete":{"type":"array","items":{"$ref":"#/definitions/IntusPlanning"}},"newForUpdate":{"type":"array","items":{"$ref":"#/definitions/IntusPlanning"}},"updates":{"format":"int32","type":"integer","readOnly":true},"deletes":{"format":"int32","type":"integer","readOnly":true}}}`

![image](https://user-images.githubusercontent.com/1858745/38385579-8721f8ba-3912-11e8-8f63-5fc1b6c3ad6c.png)

**Comment by RSuter** [comment]
![image](https://user-images.githubusercontent.com/2603405/38385776-197e6554-3913-11e8-8d6d-e747212610ea.png)

**Comment by Anderman** [comment]
Thx

**Comment by RSuter** [comment]
Please update the wiki if this information is missing.
