### ISSUE TITLE
Multiple RoutePrefix ignored

### ISSUE THREAD

**Issue by Nensec** [RSuter/NSwag#1261]
In our API I've used a custom route provider that stitches RoutePrefix attributes together from base classes, however this approach renders me unable to use NSwag as the URLs produced are incorrect.

The structure I have is as follows

    [RoutePrefix("api/v1")]
    public class BaseController : ApiController
    { ... }

    [RoutePrefix("locations")]   
    public class LocationBaseController : BaseController
    { ... }

    [RoutePrefix("stores")]   
    public class StoreController : LocationBaseController
    { ... }

    [RoutePrefix("warehouses")]   
    public class WarehouseController : LocationBaseController
    { ... }

This will produce a route URL like `~/api/v1/locations/stores/` for the API, but NSwag doesn't see any of the RoutePrefix attributes resulting in a URL such as  `~/stores/`.

**Comment by Nensec** [comment]
Thanks for the quick answer, I didn't get the chance to mess with it too much on friday anymore but this seems to be a way to solve the problem : )

**Comment by RSuter** [comment]
This is probably a “bug” as route prefix inheritance is not implemented. This is why we shouldnt close the issue yet....

**Comment by Nensec** [comment]
It is not part of the default web api framework though, the default framework only supports 1 RoutePrefix. Any new ones will override the base class

**Comment by RSuter** [comment]
Ah ok, then you should implement this rule in an operation processor.
