### ISSUE TITLE
SwaggerDocument.ToJson() is calling unexisting JsonSchemaSerializationContext

### ISSUE THREAD

**Issue by chapas** [RSuter/NSwag#1262]
"Could not load type 'NJsonSchema.Infrastructure.JsonSchemaSerializationContext' from assembly 'NJsonSchema, Version=9.10.42.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'."

JsonSchemaSerializationContext exists on version 9.10.41.0
Only JsonSchemaSerialization exists 9.10.42.0

**Comment by RSuter** [comment]
For now you need to downgrade to v9.10.41 until the next version of nswag is released. Sorry for the breaking change.

**Comment by chapas** [comment]
Ok. Thanks for your work.
