### ISSUE TITLE
Application will not start with NSwag in .net Core 2 - works fine with swashbuckle

### ISSUE THREAD

**Issue by statler** [RSuter/NSwag#1266]
After getting all of my client models working with NSwag (amazing tool BTW), I am trying to move my generation across to get the whole chain working with one system.

I have followed the wiki and [this](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?tabs=visual-studio%2Cvisual-studio-xml), essentially adding the NUGET packages and the Configure code;
`    
    app.UseStaticFiles();

    // Enable the Swagger UI middleware and the Swagger generator
    app.UseSwaggerUi(typeof(Startup).GetTypeInfo().Assembly, settings =>
    {
        settings.GeneratorSettings.DefaultPropertyNameHandling = PropertyNameHandling.CamelCase;
    });`

Unfortunately my application starts, but then hangs trying to get the swagger.json. Any ideas on what I can try to figure out what is going on? It isn't my .net core model because that works perfectly with my swashbuckle implementation - and yes, I did take the sb code out when implementing nswag.

Any help appreciated.

**Comment by RSuter** [comment]
The ui renders correctly? If so, what error do you get if you directly access the swagger.json URL?

**Comment by statler** [comment]
That's the weird thing... The json renders perfectly.

A couple of screenshots attached.

[swag.zip](https://github.com/RSuter/NSwag/files/1888557/swag.zip)

**Comment by RSuter** [comment]
Try manually installing Microsoft.AspNetCore.StaticFiles v2.0.2 manually in the host application.

https://www.nuget.org/packages/Microsoft.AspNetCore.StaticFiles/2.1.0-preview1-final

**Comment by statler** [comment]
Already have v2.02 installed.

For some reason it works with swagger3.0...

I need jwt support anyway, but would be curious to know what the problem was.

`            
    app.UseSwaggerUi3(typeof(Startup).GetTypeInfo().Assembly, settings =>
            {
                settings.GeneratorSettings.DefaultPropertyNameHandling = PropertyNameHandling.CamelCase;
            });`

**Comment by RSuter** [comment]
This is really strange, maybe you can F12 (developer tools) in Chrome to see an actual error message?
I think, you should use Swagger UI 3 anyways as this is the way forward...

**Comment by statler** [comment]
Even stranger - the whole browser hangs - can't f12 or anything. Really weird. I cant even get the json, unless I shut down the browser and open it again. Not to worry. v3 works

**Comment by RSuter** [comment]
Can we close this or should we investigate?

**Comment by statler** [comment]
It works with swagger 3 - so close away.
