### ISSUE TITLE
Ignoring properties in generated json without using attributes

### ISSUE THREAD

**Issue by statler** [RSuter/NSwag#1267]
With swashbuckle, I did the following to remove the specified properties on every generated model. Is this possible using NSwag? It is the only thing I havent figured out how to do in my translation;

I am thinking it could maybe be done with ContractResolver and modifying the serialization, but is there and easier way?

`

    services.AddSwaggerGen(c =>
     {
         c.SchemaFilter<SwaggerFieldFilter>();
     }

    public class SwaggerFieldFilter : ISchemaFilter
    {
        public void Apply(Schema model, SchemaFilterContext context)
        {
            if (model.Properties != null)
            {
                model.Properties.Remove("UniqueId");
                model.Properties.Remove("Hrid");
                model.Properties.Remove("CreatedBy");
                model.Properties.Remove("CreatedOn");
                model.Properties.Remove("ModifiedBy");
                model.Properties.Remove("ModifiedOn");
                model.Properties.Remove("OptimisticLockField");
            }
        }
    }
`

**Comment by RSuter** [comment]
You can implement that with a schema processor: https://github.com/RSuter/NJsonSchema/wiki/Schema-Processors

Or with a custom contract resolver (you have to register the resolver in the settings): https://blog.rsuter.com/advanced-newtonsoft-json-dynamically-rename-or-ignore-properties-without-changing-the-serialized-class/

**Comment by statler** [comment]
Cool - I went with the contractresolver, it was easier than I expected. One gotcha though, the error message preventing use of a contractresolver and DefaultPropertyNameHandling together. The error message is probably a bit inaccurate - I tried just removing the setting, but that didn't work - neither did setting to null (non nullable type). In the end, I figured out it needs to be explicitly set to PropertyNameHandling.Default

My code based on your example is;
`

            app.UseSwaggerUi3(typeof(Startup).GetTypeInfo().Assembly, settings =>
            {
                settings.SwaggerRoute = "/swagger/v2/swagger.json";
                settings.GeneratorSettings.SchemaNameGenerator = new MySchemaNameGenerator();
                settings.GeneratorSettings.DefaultPropertyNameHandling = PropertyNameHandling.Default;
                settings.GeneratorSettings.IsAspNetCore = true;

                var jsonResolver = new PropertyModContractResolver();
                jsonResolver.IgnoreGlobalProperty("UniqueId", "Hrid", "CreatedBy");

                settings.GeneratorSettings.ContractResolver = jsonResolver;
                settings.GeneratorSettings.OperationProcessors.Add(new OperationSecurityScopeProcessor("JWT token"));
                settings.GeneratorSettings.DocumentProcessors.Add(
                    new SecurityDefinitionAppender("JWT token", new SwaggerSecurityScheme
                    {
                        Type = SwaggerSecuritySchemeType.ApiKey,
                        Name = "Authorization",
                        Description = "Copy 'Bearer ' + valid JWT token into field",
                        In = SwaggerSecurityApiKeyLocation.Header
                    }));
                
            });

    public class PropertyModContractResolver : DefaultContractResolver
    {
        private readonly HashSet<string> _globalIgnores = new HashSet<string>();
        private readonly Dictionary<Type, HashSet<string>> _ignores = new Dictionary<Type, HashSet<string>>();
        private readonly Dictionary<Type, HashSet<string>> _includes = new Dictionary<Type, HashSet<string>>();
        private readonly Dictionary<Type, Dictionary<string, string>> _renames = new Dictionary<Type, Dictionary<string, string>>();

        public PropertyModContractResolver()
        {
        }

        public void IgnoreGlobalProperty(params string[] jsonPropertyNames)
        {
            foreach (var prop in jsonPropertyNames)
                _globalIgnores.Add(prop);
        }

        public void IncludeProperty(Type type, params string[] jsonPropertyNames)
        {
            if (!_ignores.ContainsKey(type))
                _ignores[type] = new HashSet<string>();

            foreach (var prop in jsonPropertyNames)
                _ignores[type].Add(prop);
        }

        public void IgnoreProperty(Type type, params string[] jsonPropertyNames)
        {
            if (!_ignores.ContainsKey(type))
                _ignores[type] = new HashSet<string>();

            foreach (var prop in jsonPropertyNames)
                _ignores[type].Add(prop);
        }

        public void RenameProperty(Type type, string propertyName, string newJsonPropertyName)
        {
            if (!_renames.ContainsKey(type))
                _renames[type] = new Dictionary<string, string>();

            _renames[type][propertyName] = newJsonPropertyName;
        }

        protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
        {
            var property = base.CreateProperty(member, memberSerialization);

            if (IsIncluded(property.DeclaringType, property.PropertyName)) property.ShouldSerialize = i => true;
            else if (_globalIgnores.Contains(property.PropertyName) || IsIgnored(property.DeclaringType, property.PropertyName))
                property.ShouldSerialize = i => false;

            if (IsRenamed(property.DeclaringType, property.PropertyName, out var newJsonPropertyName))
                property.PropertyName = newJsonPropertyName;

            return property;
        }

        private bool IsIgnored(Type type, string jsonPropertyName)
        {
            if (!_ignores.ContainsKey(type))
                return false;

            return _ignores[type].Contains(jsonPropertyName);
        }

        private bool IsIncluded(Type type, string jsonPropertyName)
        {
            if (!_includes.ContainsKey(type))
                return false;

            return _includes[type].Contains(jsonPropertyName);
        }

        private bool IsRenamed(Type type, string jsonPropertyName, out string newJsonPropertyName)
        {
            Dictionary<string, string> renames;

            if (!_renames.TryGetValue(type, out renames) || !renames.TryGetValue(jsonPropertyName, out newJsonPropertyName))
            {
                newJsonPropertyName = null;
                return false;
            }

            return true;
        }
    }
`

**Comment by RSuter** [comment]
You mean the "The settings DefaultPropertyNameHandling and ContractResolver cannot be used at the same time" exception?

**Comment by statler** [comment]
Yes. That one.

It has to be explicitly set to default to avoid the exception.

Just a quick question while I have your attention - does the splitting types to individual files work for any of the typescript client code generating methods yet? I thought I saw there was a way to do it, but havent been able to find it.

**Comment by RSuter** [comment]
Ok, I've updated the exception message to contain more information. Also I've added ContractResolverType setting to the CLI so that you can also define it when running the generator via CLI (see commits above).

At the moment, multiple file output is implemented in NJsonSchema (base of NSwag) but not completely implemented in NSwag (the generators must generate multiple artifacts instead of a single artifact with multiple files in it...) and also we have to expose it in the tooling (CLI, UI, etc.)

**Comment by statler** [comment]
Cool. Is there a similar method for excluding an entire type from the model?

**Comment by RSuter** [comment]
I think you can implement a primitive type mapper and map your type to an any schema: 

https://github.com/RSuter/NJsonSchema/wiki/Type-Mappers#primitive-type-mapper
