### ISSUE TITLE
Setting TypeScript version inside the .csproj file

### ISSUE THREAD

**Issue by lucassp** [RSuter/NSwag#1268]
Hi guys,

I'm trying to set the TypeScript version inside the `.csproj` file but it seems that it's getting ignored. It might be that I'm not using the correct parameter for it. Here's the command:

```XML
<Exec Command="$(NSwagExe_Core20) swagger2tsclient /input:$(OutDir)api.json /output:..\api.ts /generateClientClasses:false /typeScriptVersion:2.4 /dateTimeType:Date /nullValue:Undefined /generateDtoTypes:true /markOptionalProperties:true /generateCloneMethod:true /typeStyle:Class /generateDefaultValues:true /generateConstructorInterface:true" />
```

Is there anything I'm not doing correctly here? Thanks!

SO: https://stackoverflow.com/questions/49750258/nswag-msbuild-typescript-version-issues

**Comment by RSuter** [comment]
Why do you know that it is actually not working?

Seems to be correct: 
https://github.com/RSuter/NSwag/blob/master/src/NSwag.Commands/Commands/CodeGeneration/SwaggerToTypeScriptClientCommand.cs#L48

**Comment by RSuter** [comment]
BTW: I recommend creating an nswag.json file with all configs and use this with `nswag run nswag.json` - this way you can change everything in a file editor or NSwagStudio and can also provide placeholders: 

https://github.com/RSuter/NSwag/wiki/CommandLine#execute-nswag-configuration-document

**Comment by lucassp** [comment]
Thanks! I moved my config to a separate json file. It seems the problem isn't related to the TypeScript version.

I jumped from version 11.12.9 to 11.17 and some classes have been converted to abstract classes:

```TypeScript
export abstract class Entity implements IEntity {
    /** Gets or sets the id of the entity
             */
    id?: string | undefined;

    constructor(data?: IEntity) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
        }
    }

    static fromJS(data: any): Entity {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'Entity' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        return data; 
    }

    clone() {
        const json = this.toJSON();
        let result = new Entity();
        result.init(json);
        return result;
    }
}
```

And even though the class is abstract, the `clone()` method exists and it tries to create an instance for it.

**Comment by RSuter** [comment]
Ou that's bad...
