### ISSUE TITLE
How to include all dtos - even unused ones

### ISSUE THREAD

**Issue by statler** [RSuter/NSwag#1269]
My generator is working well - only problem is that I want all my DTOs to be generated in the swagger document, not just the ones used by the controllers. I have a stack of additional DTOs to add - how do I do this neatly?

**Comment by RSuter** [comment]
You can implement a custom document processor and add all not-yet-added DTOs with the context.SchemaResolver or SchemaGenerator

https://github.com/RSuter/NSwag/wiki/Document-Processors-and-Operation-Processors

**Comment by RSuter** [comment]
Didn't test this, but try something like: 

```csharp
    public class MyDocumentProcessor : IDocumentProcessor
    {
        public async Task ProcessAsync(DocumentProcessorContext context)
        {
            var assembly = GetType().GetTypeInfo().Assembly;
            foreach (var type in assembly.ExportedTypes
                .Where(t => t.FullName.StartsWith("MyNamespace.") && t.GetTypeInfo().IsClass))
            {
                if (!context.SchemaResolver.HasSchema(type, false))
                {
                    await context.SchemaGenerator.GenerateAsync(type, null, context.SchemaResolver);
                }
            }
        }
    }
```

**Comment by RSuter** [comment]
Can you tell me if this works?

**Comment by statler** [comment]
You sir, are a scholar and a gent. I spent ages on this before your reply and got REALLY close, but it is this simple in the end.

Thank you so much. BTW - yes it works.

**Comment by RSuter** [comment]
Updated wiki with sample.
