### ISSUE TITLE
NSwag doesn't fetch path parameters from class attribute

### ISSUE THREAD

**Issue by sh2ezo** [RSuter/NSwag#1277]
Hello!
I have the following code:
![image](https://user-images.githubusercontent.com/1949160/38824362-a7bab448-41b1-11e8-8c22-9a3af1666bf1.png)

And NSwag fetches following route:
![image](https://user-images.githubusercontent.com/1949160/38824515-26ecad84-41b2-11e8-9b32-a9de136bca3c.png)

while I expect something like this:
`/api/accounts/{accountId}/foo`

version 11.17.0 from NuGet

Is it anything wrong with my code or with NSwag?
Thanks!

**Comment by RSuter** [comment]
The default generator does not scan properties yet, you can try the new generator `UseSwagger*WithApiExplorer()` (experimental). But it should be simple to add to the default generator.

**Comment by sh2ezo** [comment]
I have written the following code:
![image](https://user-images.githubusercontent.com/1949160/38833240-a29d3fb4-41cd-11e8-8113-387e7ed9eb0f.png)

Tried to look for something that consumes Type or WebApiAssembly but found nothing.

Code above gives me the empty result:
![image](https://user-images.githubusercontent.com/1949160/38833413-2001ea36-41ce-11e8-9c58-99fa9fca1136.png)

Generated schema:
`{
  "x-generator": "NSwag v11.17.0.0 (NJsonSchema v9.10.42.0 (Newtonsoft.Json v11.0.0.0))",
  "swagger": "2.0",
  "info": {
    "title": "My Title",
    "version": "1.0.0"
  },
  "host": "localhost:65501",
  "schemes": [
    "http"
  ]
}`

I think I have this because I have not specified an assembly. How can I specify it?

**Comment by sh2ezo** [comment]
It works! Thanks. As I understand it ignores all action which returns View. Am I right?

**Comment by RSuter** [comment]
Hmm, good question. It just uses the ASP.NET Api Explorer - don't know all rules of it... Otherwise just add 

     [ApiExplorerSettings(IgnoreApi=true)]

or

    [SwaggerIgnore]

to the class/operation.

Important: Keep in mind that the ApiExplorer generator is still experimental and will see some improvements/maybe breaking changes in the future... Please report any problems (e.g. wrong specs, etc.) with it.
