### ISSUE TITLE
UseSwaggerUi3WithApiExplorer doesn't load any page

### ISSUE THREAD

**Issue by LucaGanio** [RSuter/NSwag#1282]
I tried using UseSwaggerUi3WithApiExplorer but whne I try to navigate to the index page nothing is rendered, and in the browser console I can see an error stating that "RedirectUrl" is undefined.
I tracked this down in sources and it seems the problem is that in the UseSwaggerUi3WithApiExplorer extension a SwaggerUiSettings is used while it should be a SwaggerUi3Settings

**Comment by RSuter** [comment]
v11.17.2

**Comment by giggio** [comment]
Thanks, I can confirm it works now without the extra call.

**Comment by mainmen** [comment]
Thanks giggio. You just made my day

**Comment by wjulianpineda** [comment]
is stil an issue, we need to call
 `app.UseSwaggerUi3WithApiExplorer();`
twice to make it work:

` app.UseSwaggerUi3WithApiExplorer(settings => {

                settings.GeneratorSettings.DefaultPropertyNameHandling = PropertyNameHandling.CamelCase;
                settings.PostProcess = options =>
                {
                    options.Info.Version = "v1";
                    options.Info.Title = "Reseller API";
                    options.Info.Description = "services to Reseller clients";
                    options.Info.TermsOfService = "None";
                    options.Info.Contact = new NSwag.SwaggerContact
                    {
                        Name = "Gerencia Senpai",
                        Email = "gerencia@senpai.com.co",
                        Url = "http://senpai.com.co"
                    };
                    //settings.Info.License = new NSwag.SwaggerLicense
                    //{
                    //    Name = "Use under LICX",
                    //    Url = "https://example.com/license"
                    //};
                };
            });
            app.UseSwaggerUi3WithApiExplorer();`
