### ISSUE TITLE
C# client generation NullReferenceException when using response_.Content

### ISSUE THREAD

**Issue by damianh** [RSuter/NSwag#1291]
Given this generated code:

    if (status_ == "401") 
    {
        var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
        throw new SwaggerException("Bad Request", (int)response_.StatusCode, responseData_, headers_, null);
    }

the `await response_.Content.ReadAsStringAsync()` will throw if `.Content` is null, which it can be if there is no body returned.

Let me know if you agree and I can PR a change to the template.

Cheers!

**Comment by RSuter** [comment]
I agree, we should fix that... but please don't use ? as it may not be available for all users (they may use an older C# version), just use a regular null check...

**Comment by damianh** [comment]
Understood.
