### ISSUE TITLE
Custom TypeNameGenerator causes an error

### ISSUE THREAD

**Issue by MaximBalaganskiy** [RSuter/NSwag#1299]
I've got a simple name generator
```csharp
public class NSwagTypeNameGenerator : ITypeNameGenerator {
    public string Generate(JsonSchema4 schema, string typeNameHint, IEnumerable<string> reservedTypeNames) {
        return typeNameHint;
    }
}
```

Running `nswag run nswag.json /runtime:winx86` results in an errror
```log
System.InvalidOperationException: Could not find the JSON path of a referenced schema: Manually referenced schemas must be added to the 'Definitions' of a parent schema.
Server stack trace: 
   at NJsonSchema.JsonPathUtilities.GetJsonPaths(Object rootObject, IEnumerable`1 searchedObjects, IContractResolver contractResolver)
   at NJsonSchema.JsonSchemaReferenceUtilities.UpdateSchemaReferencePaths(Object rootObject, Boolean removeExternalReferences, IContractResolver contractResolver)
   at NSwag.SwaggerDocument.ToJson(SchemaType schemaType)
   at NSwag.Commands.SwaggerGeneration.WebApiToSwaggerCommand.<RunIsolatedAsync>d__91.MoveNext()
```

Same command produces the outputs without the generator. Excluding certain controllers from the list also solves the issue but I could not figure out what exactly is causing this, because it also works with those controllers alone.

**Comment by RSuter** [comment]
I think you have to ensure that you don't use one of the reservedTypeNames...

**Comment by MaximBalaganskiy** [comment]
Thanks, inheriting the default implementation solves the problem.

**Comment by dmitry-pavlov** [comment]
> Thanks, inheriting the default implementation solves the problem.

That did the trick. You can inherit your custom type name generator from `DefaultTypeNameGenerator` like this: 

`        public class CustomTypeNameGenerator : DefaultTypeNameGenerator, ISchemaNameGenerator { ... } ` 

The base class will handle `reservedTypeNames` in the base `Generate` method.
