### ISSUE TITLE
RxJS Observable import needs updating for RxJS 6

### ISSUE THREAD

**Issue by simeyla** [RSuter/NSwag#1311]
Angular 6 now uses RxJS 6. The RxJS import for Angular template needs updating from :

    import { Observable } from 'rxjs/Observable';

to 

    import { Observable } from 'rxjs';

This is just due to organizational changes in the new version RxJs 6.

[](https://auth0.com/blog/whats-new-in-rxjs-6/)

**Comment by simeyla** [comment]
Looks like RxJS changed a lot more than just this (eg having to use Pipe instead of chaining operators). I'm sure you're already aware of this

**Comment by RSuter** [comment]
Duplicate of: https://github.com/RSuter/NSwag/issues/1255
