### ISSUE TITLE
NSwag not detecting controllers loaded with AddApplicationPart

### ISSUE THREAD

**Issue by nstohler** [RSuter/NSwag#1322]
I load all my controllers into my ASP.NET Core 2 project using AddApplicationPart() like this:
```
services.AddMvc().
    AddApplicationPart(typeof(AdminController).GetTypeInfo().Assembly)
    AddApplicationPart(typeof(UserAccountsController).GetTypeInfo().Assembly);            
```

This results in an empty swagger.json. 

If I add a very simple controller with some actions into my startup project, I get those actions generated in swagger.json. 

I set up NSwag using this guide: https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml

Anything I'm missing?

**Comment by RSuter** [comment]
The "old" generator (UseSwaggerUi()) does not use application parts but looks for controller in the provided assembly/assemblies (first parameter). Either you pass the controller assemblies to UseSwaggerUi or you use the new API Explorer-based generator which will be the preferred way eventually (UseSwaggerUiWithApiExplorer())...

**Comment by nstohler** [comment]
I've tried using `app.UseSwaggerWithApiExplorer` / `app.UseSwaggerUi3WithApiExplorer`, but that gave me then an empty swagger.json (not even the local controller with its actions in the asp.net core project was present).

When I use `app.UseSwagger(assembliesList, ...)` /  `app.UseSwaggerUi3WithApiExplorer` I get the all my actions...

**Comment by RSuter** [comment]
Did you also call AddMvc() and AddSwagger() in ConfigureServices()?

**Comment by nstohler** [comment]
AddSwagger() in ConfigureServices() was the missing piece! Now the ApiExplorer-Methods are working, thanks!

Just a note: the Microsoft article is also missing the AddSwagger() method.

**Comment by RSuter** [comment]
Actually it's not missing, because it is only needed with the `UseSwagger*WithApiExplorer()` methods which are currently "experimental" and will eventually replace the other methods. And the article uses the old `UseSwagger*()` methods for now...

**Comment by nstohler** [comment]
Ok, sorry then.
Thanks again!
