### ISSUE TITLE
JsonExceptionFilterAttribute - MissingMethodException: Method not found: 'Newtonsoft.Json.SerializationBinder Newtonsoft.Json.JsonSerializerSettings.get_Binder()'.

### ISSUE THREAD

**Issue by DamienLaw** [RSuter/NSwag#1336]
I have an ASP.NET Core website to which I added the `JsonExceptionFilterAttribute` according to the instructions [here](https://github.com/RSuter/NSwag/wiki/JsonExceptionFilterAttribute).
```
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc(options =>
        {
            options.Filters.Add(new JsonExceptionFilterAttribute());
        });
    }
}
```

I then threw an exception from one of the controllers and got this instead.
![image](https://user-images.githubusercontent.com/14930009/40318773-503e9b86-5d58-11e8-883e-b4d5e1bf644a.png)

It looks like some missing dependencies.

**Comment by RSuter** [comment]
Strange. Are you on the latest NSwag versions everywhere?

**Comment by DamienLaw** [comment]
I have several projects in my solution. All but one are libraries. I installed the latest stable NSwag.AspNetCore 11.17.9 using NuGet only to my ASP.NET Core 2.1 RC web project.

**Comment by RSuter** [comment]
This? https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/issues/23

**Comment by RSuter** [comment]
> @isaacabraham I was able to repro the error you're seeing, but only if I explicitly reference Newtonsoft.Json 11.0.1-beta3 from my test project. It appears that in version 11, JSON.NET is deprecating the Binder property in favor of the SerializationBinder property. I'm not sure why your project is picking up a beta version of JSON.NET, but if you're able to use 10.0.3, it should work.

**Comment by DamienLaw** [comment]
I installed the latest stable version (not a beta) of Json.NET v11.0.2 NOT directly to my ASP.NET Core 2.1 RC web project but to a library which my web project references.

I tried re-installing Json.NET 10.0.3 to my library but the issue still persists.

**Comment by RSuter** [comment]
Its a bug in CopySettibgs triggered by a breaking change in Newtonsoft.Json

**Comment by RSuter** [comment]
v11.17.13 is now running with latest .net core 2.1.300, will probably not fix this but worth a try...

**Comment by kachalkov** [comment]
Hi, updated to 11.17.13, still the same issue for us...

**Comment by RSuter** [comment]
We need to fix the settings clone methods: 

https://github.com/RSuter/NSwag/blob/master/src/NSwag.AspNet.WebApi/JsonExceptionFilterAttribute.cs#L108

https://github.com/RSuter/NSwag/blob/master/src/NSwag.AspNetCore/JsonExceptionFilterAttribute.cs#L122

e.g. by using reflection so that the breaking change (some properties have gone/changed) does not trigger a problem...

**Comment by simeyla** [comment]
Still seeing this now (well for the first time actually) with 2.2.2 and NSwag 12.0.14.
Took me a while to realize that the error I was seeing in Fiddler was actually this error - and not the controller exception I was trying to catch!

So is this filter just out of commission for now and I should do something like a [simple middleware for exception handling](https://code-maze.com/global-error-handling-aspnetcore/) instead?

Also you might want to put a note at the top of the [JsonExceptionFilterAttribute](https://github.com/RSuter/NSwag/wiki/JsonExceptionFilterAttribute) wiki if it won't be working for a while. This seems like the most relevant documentation page you have for global exception handling and it's very confusing when it doesn't give you JSON back after adding it.

Thanks

**Comment by RSuter** [comment]
We need to fix this in in JsonExceptionFilterAttribute.CopySettings() which was introduced by a breaking change in Newtonsoft.Json: For compatibility reasons, NSwag uses an older version of Newtonsoft.Json where there were different properties and thus with the latest version this CopySettings method fails... We need to implement it in a more generic (e.g. reflection) way so that it works with old and new versions of Newtonsoft.Json... do you have time to look into this and create a PR?

**Comment by RSuter** [comment]
Closed but would be great if you could add a unit test for it @simeyla 

Please test this change in v12.0.18 (not yet released)

**Comment by RicoSuter** [comment]
Can you confirm that it's now working as expected with v12.0.18? /cc @simeyla
