### ISSUE TITLE
NSwag.AspNetCore - <param> XML comments are not parsed

### ISSUE THREAD

**Issue by piaste** [RSuter/NSwag#1337]
Minimal repro: https://github.com/piaste/nswagscratch

Given the following method:

```
        /// <summary> gets foo 
        /// <param name="id">not actually used</param>
        /// </summary>        
        [HttpGet("{id}")]
        public ActionResult<string> Get(int id)
        {
            return "value";
        }
```

which creates the following XML doc file:

```
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>nswagscratch</name>
    </assembly>
    <members>
        <member name="M:nswagscratch.Controllers.ValuesController.Get(System.Int32)">
            <summary> gets foo 
            <param name="id">not actually used</param>
            </summary>        
        </member>
    </members>
</doc>
```

the XML comment for the `id` parameter shows up in IntelliSense, but the NSwag generator dumps it in the general endpoint description:

![image](https://user-images.githubusercontent.com/12280683/40381960-6448eeba-5dfd-11e8-97a8-5c588c2f0c12.png)

**Comment by RSuter** [comment]
Did you add the required packages?

https://github.com/RSuter/NJsonSchema/wiki/XML-Documentation#net-core

**Comment by piaste** [comment]
Yes, my original project had them both in the output, and I've confirmed they appear in the repro as well. No difference.


<details>
<summary>Full content of the `/publish/` folder for win-x64 (click to expand)</summary>
api-ms-win-core-console-l1-1-0.dll<br>
api-ms-win-core-datetime-l1-1-0.dll<br>
api-ms-win-core-debug-l1-1-0.dll<br>
api-ms-win-core-errorhandling-l1-1-0.dll<br>
api-ms-win-core-file-l1-1-0.dll<br>
api-ms-win-core-file-l1-2-0.dll<br>
api-ms-win-core-file-l2-1-0.dll<br>
api-ms-win-core-handle-l1-1-0.dll<br>
api-ms-win-core-heap-l1-1-0.dll<br>
api-ms-win-core-interlocked-l1-1-0.dll<br>
api-ms-win-core-libraryloader-l1-1-0.dll<br>
api-ms-win-core-localization-l1-2-0.dll<br>
api-ms-win-core-memory-l1-1-0.dll<br>
api-ms-win-core-namedpipe-l1-1-0.dll<br>
api-ms-win-core-processenvironment-l1-1-0.dll<br>
api-ms-win-core-processthreads-l1-1-0.dll<br>
api-ms-win-core-processthreads-l1-1-1.dll<br>
api-ms-win-core-profile-l1-1-0.dll<br>
api-ms-win-core-rtlsupport-l1-1-0.dll<br>
api-ms-win-core-string-l1-1-0.dll<br>
api-ms-win-core-synch-l1-1-0.dll<br>
api-ms-win-core-synch-l1-2-0.dll<br>
api-ms-win-core-sysinfo-l1-1-0.dll<br>
api-ms-win-core-timezone-l1-1-0.dll<br>
api-ms-win-core-util-l1-1-0.dll<br>
api-ms-win-crt-conio-l1-1-0.dll<br>
api-ms-win-crt-convert-l1-1-0.dll<br>
api-ms-win-crt-environment-l1-1-0.dll<br>
api-ms-win-crt-filesystem-l1-1-0.dll<br>
api-ms-win-crt-heap-l1-1-0.dll<br>
api-ms-win-crt-locale-l1-1-0.dll<br>
api-ms-win-crt-math-l1-1-0.dll<br>
api-ms-win-crt-multibyte-l1-1-0.dll<br>
api-ms-win-crt-private-l1-1-0.dll<br>
api-ms-win-crt-process-l1-1-0.dll<br>
api-ms-win-crt-runtime-l1-1-0.dll<br>
api-ms-win-crt-stdio-l1-1-0.dll<br>
api-ms-win-crt-string-l1-1-0.dll<br>
api-ms-win-crt-time-l1-1-0.dll<br>
api-ms-win-crt-utility-l1-1-0.dll<br>
appsettings.Development.json<br>
appsettings.json<br>
clrcompression.dll<br>
clretwrc.dll<br>
clrjit.dll<br>
coreclr.dll<br>
dbgshim.dll<br>
hostfxr.dll<br>
hostpolicy.dll<br>
Microsoft.AspNetCore.Antiforgery.dll<br>
Microsoft.AspNetCore.Authentication.Abstractions.dll<br>
Microsoft.AspNetCore.Authentication.Cookies.dll<br>
Microsoft.AspNetCore.Authentication.Core.dll<br>
Microsoft.AspNetCore.Authentication.dll<br>
Microsoft.AspNetCore.Authentication.Facebook.dll<br>
Microsoft.AspNetCore.Authentication.Google.dll<br>
Microsoft.AspNetCore.Authentication.JwtBearer.dll<br>
Microsoft.AspNetCore.Authentication.MicrosoftAccount.dll<br>
Microsoft.AspNetCore.Authentication.OAuth.dll<br>
Microsoft.AspNetCore.Authentication.OpenIdConnect.dll<br>
Microsoft.AspNetCore.Authentication.Twitter.dll<br>
Microsoft.AspNetCore.Authentication.WsFederation.dll<br>
Microsoft.AspNetCore.Authorization.dll<br>
Microsoft.AspNetCore.Authorization.Policy.dll<br>
Microsoft.AspNetCore.Connections.Abstractions.dll<br>
Microsoft.AspNetCore.CookiePolicy.dll<br>
Microsoft.AspNetCore.Cors.dll<br>
Microsoft.AspNetCore.Cryptography.Internal.dll<br>
Microsoft.AspNetCore.Cryptography.KeyDerivation.dll<br>
Microsoft.AspNetCore.DataProtection.Abstractions.dll<br>
Microsoft.AspNetCore.DataProtection.dll<br>
Microsoft.AspNetCore.DataProtection.Extensions.dll<br>
Microsoft.AspNetCore.Diagnostics.Abstractions.dll<br>
Microsoft.AspNetCore.Diagnostics.dll<br>
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.dll<br>
Microsoft.AspNetCore.dll<br>
Microsoft.AspNetCore.HostFiltering.dll<br>
Microsoft.AspNetCore.Hosting.Abstractions.dll<br>
Microsoft.AspNetCore.Hosting.dll<br>
Microsoft.AspNetCore.Hosting.Server.Abstractions.dll<br>
Microsoft.AspNetCore.Html.Abstractions.dll<br>
Microsoft.AspNetCore.Http.Abstractions.dll<br>
Microsoft.AspNetCore.Http.Connections.Common.dll<br>
Microsoft.AspNetCore.Http.Connections.dll<br>
Microsoft.AspNetCore.Http.dll<br>
Microsoft.AspNetCore.Http.Extensions.dll<br>
Microsoft.AspNetCore.Http.Features.dll<br>
Microsoft.AspNetCore.HttpOverrides.dll<br>
Microsoft.AspNetCore.HttpsPolicy.dll<br>
Microsoft.AspNetCore.Identity.dll<br>
Microsoft.AspNetCore.Identity.EntityFrameworkCore.dll<br>
Microsoft.AspNetCore.Identity.UI.dll<br>
Microsoft.AspNetCore.Identity.UI.Views.dll<br>
Microsoft.AspNetCore.JsonPatch.dll<br>
Microsoft.AspNetCore.Localization.dll<br>
Microsoft.AspNetCore.Localization.Routing.dll<br>
Microsoft.AspNetCore.MiddlewareAnalysis.dll<br>
Microsoft.AspNetCore.Mvc.Abstractions.dll<br>
Microsoft.AspNetCore.Mvc.ApiExplorer.dll<br>
Microsoft.AspNetCore.Mvc.Core.dll<br>
Microsoft.AspNetCore.Mvc.Cors.dll<br>
Microsoft.AspNetCore.Mvc.DataAnnotations.dll<br>
Microsoft.AspNetCore.Mvc.dll<br>
Microsoft.AspNetCore.Mvc.Formatters.Json.dll<br>
Microsoft.AspNetCore.Mvc.Formatters.Xml.dll<br>
Microsoft.AspNetCore.Mvc.Localization.dll<br>
Microsoft.AspNetCore.Mvc.Razor.dll<br>
Microsoft.AspNetCore.Mvc.Razor.Extensions.dll<br>
Microsoft.AspNetCore.Mvc.RazorPages.dll<br>
Microsoft.AspNetCore.Mvc.TagHelpers.dll<br>
Microsoft.AspNetCore.Mvc.ViewFeatures.dll<br>
Microsoft.AspNetCore.NodeServices.dll<br>
Microsoft.AspNetCore.Owin.dll<br>
Microsoft.AspNetCore.Razor.dll<br>
Microsoft.AspNetCore.Razor.Language.dll<br>
Microsoft.AspNetCore.Razor.Runtime.dll<br>
Microsoft.AspNetCore.ResponseCaching.Abstractions.dll<br>
Microsoft.AspNetCore.ResponseCaching.dll<br>
Microsoft.AspNetCore.ResponseCompression.dll<br>
Microsoft.AspNetCore.Rewrite.dll<br>
Microsoft.AspNetCore.Routing.Abstractions.dll<br>
Microsoft.AspNetCore.Routing.dll<br>
Microsoft.AspNetCore.Server.HttpSys.dll<br>
Microsoft.AspNetCore.Server.IISIntegration.dll<br>
Microsoft.AspNetCore.Server.Kestrel.Core.dll<br>
Microsoft.AspNetCore.Server.Kestrel.dll<br>
Microsoft.AspNetCore.Server.Kestrel.Https.dll<br>
Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll<br>
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll<br>
Microsoft.AspNetCore.Session.dll<br>
Microsoft.AspNetCore.SignalR.Common.dll<br>
Microsoft.AspNetCore.SignalR.Core.dll<br>
Microsoft.AspNetCore.SignalR.dll<br>
Microsoft.AspNetCore.SignalR.Protocols.Json.dll<br>
Microsoft.AspNetCore.SpaServices.dll<br>
Microsoft.AspNetCore.SpaServices.Extensions.dll<br>
Microsoft.AspNetCore.StaticFiles.dll<br>
Microsoft.AspNetCore.WebSockets.dll<br>
Microsoft.AspNetCore.WebUtilities.dll<br>
Microsoft.CodeAnalysis.CSharp.dll<br>
Microsoft.CodeAnalysis.dll<br>
Microsoft.CodeAnalysis.Razor.dll<br>
Microsoft.CSharp.dll<br>
Microsoft.DiaSymReader.Native.amd64.dll<br>
Microsoft.DotNet.PlatformAbstractions.dll<br>
Microsoft.EntityFrameworkCore.Abstractions.dll<br>
Microsoft.EntityFrameworkCore.Design.dll<br>
Microsoft.EntityFrameworkCore.dll<br>
Microsoft.EntityFrameworkCore.InMemory.dll<br>
Microsoft.EntityFrameworkCore.Relational.dll<br>
Microsoft.EntityFrameworkCore.SqlServer.dll<br>
Microsoft.Extensions.Caching.Abstractions.dll<br>
Microsoft.Extensions.Caching.Memory.dll<br>
Microsoft.Extensions.Caching.SqlServer.dll<br>
Microsoft.Extensions.Configuration.Abstractions.dll<br>
Microsoft.Extensions.Configuration.Binder.dll<br>
Microsoft.Extensions.Configuration.CommandLine.dll<br>
Microsoft.Extensions.Configuration.dll<br>
Microsoft.Extensions.Configuration.EnvironmentVariables.dll<br>
Microsoft.Extensions.Configuration.FileExtensions.dll<br>
Microsoft.Extensions.Configuration.Ini.dll<br>
Microsoft.Extensions.Configuration.Json.dll<br>
Microsoft.Extensions.Configuration.KeyPerFile.dll<br>
Microsoft.Extensions.Configuration.UserSecrets.dll<br>
Microsoft.Extensions.Configuration.Xml.dll<br>
Microsoft.Extensions.DependencyInjection.Abstractions.dll<br>
Microsoft.Extensions.DependencyInjection.dll<br>
Microsoft.Extensions.DependencyModel.dll<br>
Microsoft.Extensions.DiagnosticAdapter.dll<br>
Microsoft.Extensions.FileProviders.Abstractions.dll<br>
Microsoft.Extensions.FileProviders.Composite.dll<br>
Microsoft.Extensions.FileProviders.Embedded.dll<br>
Microsoft.Extensions.FileProviders.Physical.dll<br>
Microsoft.Extensions.FileSystemGlobbing.dll<br>
Microsoft.Extensions.Hosting.Abstractions.dll<br>
Microsoft.Extensions.Hosting.dll<br>
Microsoft.Extensions.Http.dll<br>
Microsoft.Extensions.Identity.Core.dll<br>
Microsoft.Extensions.Identity.Stores.dll<br>
Microsoft.Extensions.Localization.Abstractions.dll<br>
Microsoft.Extensions.Localization.dll<br>
Microsoft.Extensions.Logging.Abstractions.dll<br>
Microsoft.Extensions.Logging.Configuration.dll<br>
Microsoft.Extensions.Logging.Console.dll<br>
Microsoft.Extensions.Logging.Debug.dll<br>
Microsoft.Extensions.Logging.dll<br>
Microsoft.Extensions.Logging.EventSource.dll<br>
Microsoft.Extensions.Logging.TraceSource.dll<br>
Microsoft.Extensions.ObjectPool.dll<br>
Microsoft.Extensions.Options.ConfigurationExtensions.dll<br>
Microsoft.Extensions.Options.dll<br>
Microsoft.Extensions.Primitives.dll<br>
Microsoft.Extensions.WebEncoders.dll<br>
Microsoft.IdentityModel.Logging.dll<br>
Microsoft.IdentityModel.Protocols.dll<br>
Microsoft.IdentityModel.Protocols.OpenIdConnect.dll<br>
Microsoft.IdentityModel.Protocols.WsFederation.dll<br>
Microsoft.IdentityModel.Tokens.dll<br>
Microsoft.IdentityModel.Tokens.Saml.dll<br>
Microsoft.IdentityModel.Xml.dll<br>
Microsoft.Net.Http.Headers.dll<br>
Microsoft.VisualBasic.dll<br>
Microsoft.Win32.Primitives.dll<br>
Microsoft.Win32.Registry.dll<br>
mscordaccore.dll<br>
mscordaccore_amd64_amd64_4.6.26426.02.dll<br>
mscordbi.dll<br>
mscorlib.dll<br>
mscorrc.debug.dll<br>
mscorrc.dll<br>
netstandard.dll<br>
Newtonsoft.Json.Bson.dll<br>
Newtonsoft.Json.dll<br>
NJsonSchema.dll<br>
NSwag.Annotations.dll<br>
NSwag.AspNetCore.dll<br>
NSwag.Core.dll<br>
NSwag.SwaggerGeneration.AspNetCore.dll<br>
NSwag.SwaggerGeneration.dll<br>
NSwag.SwaggerGeneration.WebApi.dll<br>
nswagscratch.deps.json<br>
nswagscratch.dll<br>
nswagscratch.exe<br>
nswagscratch.pdb<br>
nswagscratch.runtimeconfig.json<br>
nswagscratch.xml<br>
Remotion.Linq.dll<br>
sni.dll<br>
sos.dll<br>
SOS.NETCore.dll<br>
sos_amd64_amd64_4.6.26426.02.dll<br>
System.AppContext.dll<br>
System.Buffers.dll<br>
System.Collections.Concurrent.dll<br>
System.Collections.dll<br>
System.Collections.Immutable.dll<br>
System.Collections.NonGeneric.dll<br>
System.Collections.Specialized.dll<br>
System.ComponentModel.Annotations.dll<br>
System.ComponentModel.DataAnnotations.dll<br>
System.ComponentModel.dll<br>
System.ComponentModel.EventBasedAsync.dll<br>
System.ComponentModel.Primitives.dll<br>
System.ComponentModel.TypeConverter.dll<br>
System.Configuration.dll<br>
System.Console.dll<br>
System.Core.dll<br>
System.Data.Common.dll<br>
System.Data.dll<br>
System.Data.SqlClient.dll<br>
System.Diagnostics.Contracts.dll<br>
System.Diagnostics.Debug.dll<br>
System.Diagnostics.DiagnosticSource.dll<br>
System.Diagnostics.FileVersionInfo.dll<br>
System.Diagnostics.Process.dll<br>
System.Diagnostics.StackTrace.dll<br>
System.Diagnostics.TextWriterTraceListener.dll<br>
System.Diagnostics.Tools.dll<br>
System.Diagnostics.TraceSource.dll<br>
System.Diagnostics.Tracing.dll<br>
System.dll<br>
System.Drawing.dll<br>
System.Drawing.Primitives.dll<br>
System.Dynamic.Runtime.dll<br>
System.Globalization.Calendars.dll<br>
System.Globalization.dll<br>
System.Globalization.Extensions.dll<br>
System.IdentityModel.Tokens.Jwt.dll<br>
System.Interactive.Async.dll<br>
System.IO.Compression.Brotli.dll<br>
System.IO.Compression.dll<br>
System.IO.Compression.FileSystem.dll<br>
System.IO.Compression.ZipFile.dll<br>
System.IO.dll<br>
System.IO.FileSystem.AccessControl.dll<br>
System.IO.FileSystem.dll<br>
System.IO.FileSystem.DriveInfo.dll<br>
System.IO.FileSystem.Primitives.dll<br>
System.IO.FileSystem.Watcher.dll<br>
System.IO.IsolatedStorage.dll<br>
System.IO.MemoryMappedFiles.dll<br>
System.IO.Pipelines.dll<br>
System.IO.Pipes.AccessControl.dll<br>
System.IO.Pipes.dll<br>
System.IO.UnmanagedMemoryStream.dll<br>
System.Linq.dll<br>
System.Linq.Expressions.dll<br>
System.Linq.Parallel.dll<br>
System.Linq.Queryable.dll<br>
System.Memory.dll<br>
System.Net.dll<br>
System.Net.Http.dll<br>
System.Net.Http.Formatting.dll<br>
System.Net.HttpListener.dll<br>
System.Net.Mail.dll<br>
System.Net.NameResolution.dll<br>
System.Net.NetworkInformation.dll<br>
System.Net.Ping.dll<br>
System.Net.Primitives.dll<br>
System.Net.Requests.dll<br>
System.Net.Security.dll<br>
System.Net.ServicePoint.dll<br>
System.Net.Sockets.dll<br>
System.Net.WebClient.dll<br>
System.Net.WebHeaderCollection.dll<br>
System.Net.WebProxy.dll<br>
System.Net.WebSockets.Client.dll<br>
System.Net.WebSockets.dll<br>
System.Net.WebSockets.WebSocketProtocol.dll<br>
System.Numerics.dll<br>
System.Numerics.Vectors.dll<br>
System.ObjectModel.dll<br>
System.Private.CoreLib.dll<br>
System.Private.DataContractSerialization.dll<br>
System.Private.Uri.dll<br>
System.Private.Xml.dll<br>
System.Private.Xml.Linq.dll<br>
System.Reflection.DispatchProxy.dll<br>
System.Reflection.dll<br>
System.Reflection.Emit.dll<br>
System.Reflection.Emit.ILGeneration.dll<br>
System.Reflection.Emit.Lightweight.dll<br>
System.Reflection.Extensions.dll<br>
System.Reflection.Metadata.dll<br>
System.Reflection.Primitives.dll<br>
System.Reflection.TypeExtensions.dll<br>
System.Resources.Reader.dll<br>
System.Resources.ResourceManager.dll<br>
System.Resources.Writer.dll<br>
System.Runtime.CompilerServices.Unsafe.dll<br>
System.Runtime.CompilerServices.VisualC.dll<br>
System.Runtime.dll<br>
System.Runtime.Extensions.dll<br>
System.Runtime.Handles.dll<br>
System.Runtime.InteropServices.dll<br>
System.Runtime.InteropServices.RuntimeInformation.dll<br>
System.Runtime.InteropServices.WindowsRuntime.dll<br>
System.Runtime.Loader.dll<br>
System.Runtime.Numerics.dll<br>
System.Runtime.Serialization.dll<br>
System.Runtime.Serialization.Formatters.dll<br>
System.Runtime.Serialization.Json.dll<br>
System.Runtime.Serialization.Primitives.dll<br>
System.Runtime.Serialization.Xml.dll<br>
System.Security.AccessControl.dll<br>
System.Security.Claims.dll<br>
System.Security.Cryptography.Algorithms.dll<br>
System.Security.Cryptography.Cng.dll<br>
System.Security.Cryptography.Csp.dll<br>
System.Security.Cryptography.Encoding.dll<br>
System.Security.Cryptography.OpenSsl.dll<br>
System.Security.Cryptography.Pkcs.dll<br>
System.Security.Cryptography.Primitives.dll<br>
System.Security.Cryptography.X509Certificates.dll<br>
System.Security.Cryptography.Xml.dll<br>
System.Security.dll<br>
System.Security.Permissions.dll<br>
System.Security.Principal.dll<br>
System.Security.Principal.Windows.dll<br>
System.Security.SecureString.dll<br>
System.ServiceModel.Web.dll<br>
System.ServiceProcess.dll<br>
System.Text.Encoding.CodePages.dll<br>
System.Text.Encoding.dll<br>
System.Text.Encoding.Extensions.dll<br>
System.Text.Encodings.Web.dll<br>
System.Text.RegularExpressions.dll<br>
System.Threading.Channels.dll<br>
System.Threading.dll<br>
System.Threading.Overlapped.dll<br>
System.Threading.Tasks.Dataflow.dll<br>
System.Threading.Tasks.dll<br>
System.Threading.Tasks.Extensions.dll<br>
System.Threading.Tasks.Parallel.dll<br>
System.Threading.Thread.dll<br>
System.Threading.ThreadPool.dll<br>
System.Threading.Timer.dll<br>
System.Transactions.dll<br>
System.Transactions.Local.dll<br>
System.ValueTuple.dll<br>
System.Web.dll<br>
System.Web.HttpUtility.dll<br>
System.Windows.dll<br>
System.Xml.dll<br>
System.Xml.Linq.dll<br>
System.Xml.ReaderWriter.dll<br>
System.Xml.Serialization.dll<br>
System.Xml.XDocument.dll<br>
System.Xml.XmlDocument.dll<br>
System.Xml.XmlSerializer.dll<br>
System.Xml.XPath.dll<br>
System.Xml.XPath.XDocument.dll<br>
ucrtbase.dll<br>
web.config<br>
WindowsBase.dll<br>
</details>

**Comment by RSuter** [comment]
Yes, but i cannot see the .xml doc files in this listing?

**Comment by piaste** [comment]
It's in there:

> nswagscratch.xml

The content of that file is what I posted in the first post.

(Besides, if it couldn't find the file, NSwag wouldn't show *any* comment text.)

**Comment by RSuter** [comment]
ATM nswag searches for xml docs with the same name as the assembly but with .xml extension

**Comment by RSuter** [comment]
Just saw that your cml summary shows up in the screenshot!? Where’s the problem?

**Comment by RSuter** [comment]
Ah i see: The xml param tag must not be placed into the summary tag but i think below...
