### ISSUE TITLE
using NSwag for multi swagger urls

### ISSUE THREAD

**Issue by hitaspdotnet** [RSuter/NSwag#1348]
I have a application in DotNetCore with multi micro-services.
Each micro-service have own swagger.json on separate port

```
  "swaggerGenerator": {
    "fromSwagger": {
      "url": "http://MyContinerIP:MyServicePort/swagger/v1/swagger.json",
      "output": null
    }
  }
```
My front-end is AngularSPA so is there anyway to put Urls as array for generating joint output with containing all micro-services API's?

**Comment by RSuter** [comment]
Not at the moment. You can manually merge them with the NSwag.Core package and the SwaggerDocument class. Would be great as contribution...

**Comment by RSuter** [comment]
Deplicate of https://github.com/RSuter/NSwag/issues/1273
