### ISSUE TITLE
Date offsets with Angular6/AspNetCore2 WebApi combo

### ISSUE THREAD

**Issue by nstohler** [RSuter/NSwag#1351]
I have an Angular 6 app that talks to a Asp.Net Core 2 WebApi backend. I produce the ng clients using nswag (msbuild version) from the Asp.Net Core 2 server project. 

POST:
I created a simple form, where one of the inputs is a simple text input where users can specify a date in the format YYYY-MM-DD (just for simplicity) in a reactive form component. The date gets parsed by momentjs and then sent (along with other data) to the backend. In the case of post / [FromBody], I had the problem that the moment date got converted and had an offset of 2 hours (My locale is de-CH) when it reached the server. I'm only interested in the date, not the time part, so I constructed my date like this:

```
var d = '2018-5-28'; // from form
var today = moment(d).startOf('day');
console.log(now.toISOString()); // what gets sent to webapi: 2018-05-27T22:00:00.000Z
```

This results in the WebApi action getting the wrong date.  When I do this before posting, I get the correct date on the server:

```
var d = '2018-5-28'; // from form
var now = moment(d).utc().startOf('day');
console.log(now.toISOString()); // what gets sent to webapi: 2018-05-28T00:00:00.000Z
```

GET:
Now I remembered I had some GET actions that take a date as a route parameter, so I tried to send the second date (utc'd) there:

```
GET
http://localhost:7733/api/test-date-get/2018-05-28T00:00:00.000Z
```

In the action, I just bounced back the received date object:
```
{
    "date": "2018-05-28T02:00:00+02:00",
    "year": 2018,
    "month": 5,
    "day": 28
}
```
What I want is to not care about any time offsets at all. I store (mostly) dates without any time in the database. Is there a clean way to achieve this? Should I use some other NSwag options to create the typescript code (I thought it's nice to have moment objects instead of javascript dates)? Or is there something I should configure in Asp.Net Core 2 / Angular / MomentJS to have them agree better on the date formats?

**Comment by RSuter** [comment]
Try adding the JsonSchemaDateAttribute attribute: https://github.com/RSuter/NJsonSchema/wiki/JsonSchemaGenerator#provided-njsonschema-attributes

**Comment by RSuter** [comment]
Do you use NSwag to generate the Swagger spec (or Swashbuckle)? Can you post the produced Swagger spec? Is the "format" property of the parameter/property set to "date" (instead of "date-time")?

**Comment by nstohler** [comment]
My generated swagger.json viewmodel:
```
"ReservationCreateEditViewModel": {
  "type": "object",
  "additionalProperties": false,
  "required": [
	"datum"
  ],
  "properties": {
	"datum": {
	  "type": "string",
	  "format": "date-time"
	}
  }
}
```
c#:
```
public class ReservationCreateEditViewModel
{
  [Required]        
  [JsonSchemaDate]
  DateTime Datum              { get; set;   }
```

**Comment by RSuter** [comment]
There are two components to this problem: 

1. We need to generate the correct Swagger spec, i.e. `"format": "date"`
2. We need to generate the correct client code for date properties: In C# I think it's DateTime with a special converter (or a Noda time type). 

For 1. NJS (NJsonSchema) supports Noda time out of the box, so if you use the time type of Noda it should correctly generate `"format": "date-time"` and for 2. you can define the Node time type as DateType: 

![image](https://user-images.githubusercontent.com/2603405/40654520-d4b73e4a-633e-11e8-9a66-f4afd137851d.png)

I'm wondering why `[JsonSchemaDate]` does not generate `"format": "date"`... This looks like a bug. Maybe it works when using `[JsonSchema(JsonObjectType.String, Format = "date")]`?

**Comment by nstohler** [comment]
> I'm wondering why [JsonSchemaDate] does not generate "format": "date"... This looks like a bug. Maybe it works when using [JsonSchema(JsonObjectType.String, Format = "date")]?
I tried that now, it still created `"format": "date-time"` in the swagger spec. 

I used NSwag studio to change the spec to `"format": "date"` and generated the Typescript client there. This resulted in 
`data["datum"] = this.datum ? this.datum.format('YYYY-MM-DD') : <any>undefined;` being generated, which works perfect (without any special momentJs conversion). 

Also, I'm not generating the CSharp client from the swagger spec. I used NSwag Studio to create the swagger spec from "Web API or ASP.NET Core Assembly", then use that to generate the Typescript client. 

So my main problem/goal is to configure my C# properties corretly so that NSwag.MSBuild will generate `"format": "date"` instead of `"format": "date-time"`. 
Secondary goal would be to get the same working for server side route/query parameters.

**Comment by RSuter** [comment]
I think `"format": "date"` also works the same way with MomentJS... 

Have you tried `[JsonSchema(JsonObjectType.String, Format = "date")]` (probably also not working as in the end it is the same)?

**Comment by RSuter** [comment]
I'm not sure if this is correctly implemented for parameters or only working correctly for properties...

**Comment by nstohler** [comment]
> Have you tried [JsonSchema(JsonObjectType.String, Format = "date")] (probably also not working as in the end it is the same)?

I tried that now, it still created "format": "date-time" in the swagger spec.

**Comment by RSuter** [comment]
Ok, i found the bug / it's a bug - stop trying to solve it :-)

**Comment by RSuter** [comment]
Ok, I think this commit should fix it... now I have to release everything :)

**Comment by RSuter** [comment]
Please reopen if something is still not working.

**Comment by nstohler** [comment]
Thanks!

It seems to be working now, I'm still testing it all. Will let you know if something comes up
