### ISSUE TITLE
Route {version:apiVersion} in ASP.Net Core 2.1 MVC throws parameter has no type exception during generation

### ISSUE THREAD

**Issue by cupdegraft** [RSuter/NSwag#1364]
Using ApiVersion in an ASP.Net Core 2.1 MVC api project, the Route attribute tag "{version:apiVersion}" is throwing an exception during generation: InvalidOperationException "The parameter … on path … has no type" from NSwag.SwaggerGeneration.AspNetCore.OperationParameterProcessor.ProcessASync() line 53. 

It looks like the parameters returned from context.MethodInfo.GetParameters() at line 48 includes the "version" found in the route (not specified as a method argument) and has no type assigned which is causing the exception. 

I don't see any test cases in the NSwag.SwaggerGeneration.AspNetCore.Tests project related to testing the ApiVersion functionality.

**Comment by RSuter** [comment]
ApiVersioning is not yet really well tested and supported I think... can you post some sample C# code to reproduce this?

**Comment by cupdegraft** [comment]
Here is a .zip of a simple asp.net core v2,1 api project (created from vs2017 template) that has Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer 2.2.0 and NSwag.AspNetCore 11.17.13 added as nuget packages. If you point a browser at "http://localhost:[port]/swagger/swagger.json" you will see the exception: The parameter 'version' on path '/api/v{version}/Values' has no type throwing in NSwag.AspNetCore.Middlewares.AspNetCoreToSwaggerMiddleware.GenerateSwaggerAsync(HttpContext context). 

[ApiVersionBug.zip](https://github.com/RSuter/NSwag/files/2086016/ApiVersionBug.zip)

**Comment by RSuter** [comment]
Please retry with latest version. Api versioning support has bern improved...

**Comment by cupdegraft** [comment]
That got it - thanks!
