### ISSUE TITLE
TypeScript: Serialization of property of type any causing problems

### ISSUE THREAD

**Issue by mutzl** [RSuter/NSwag#1366]
My swagger.json contains a type with a property of type object.
```
...
      "properties": {
        "value": { "type": "object" },
...
      } }
```
NSwag generates Typescript like
`    value?: any | undefined;`

and a toJSON method like
```
    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (this.value) {
            data["value"] = {};
            for (let key in this.value) {
                if (this.value.hasOwnProperty(key))
                    data["value"][key] = this.value[key];
            }
        }
...
        return data;
    }
```
But this is causing troubles when serializing the object.
In case, the property contains a string, it is serialized to an array of characters.
And a boolean for example is serialized to an empty property!

Objects:
```
{value: "Test"}
{value: true}
```
Serialized to
```
value = {{ "0": "T",  "1": "e",  "2": "s",  "3": "t" }}
value = {{}}
```

Not sure why the complex serialization logic is generated here.
A simple
`data["value"] = this.value;`
would solve everything in my case.

**Comment by RSuter** [comment]
I think this issue has recently been reported and we need to look into this. Fixing is simple but there must be a good reason it is this way ATM..

**Comment by RSuter** [comment]
Fixed: https://github.com/RSuter/NSwag/commit/9e3828c67cb98c2ad28e52d531e5af9d76b2cb79

**Comment by RSuter** [comment]
Can you test with ci artifacts? https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/3190/artifacts

**Comment by mutzl** [comment]
Looks good! Thank you!

**Comment by RSuter** [comment]
Ok, thanks for testing. Will release soon (today or tomorrow).
