### ISSUE TITLE
Only overwrite file if there are changes

### ISSUE THREAD

**Issue by teyc** [RSuter/NSwag#1370]
Request for comment:

My MSBuild file generates `.cs` clients from Swagger, and often this results in the clients being rebuilt when there werer no change in the API definitions. It would be useful if `NSwag` does not overwrite the output file unless there were changes.

**Comment by RSuter** [comment]
Should be simple to implement...

**Comment by RSuter** [comment]
Thanks for reporting

**Comment by RSuter** [comment]
Simply first read content and check for changes? Perf problem?

Ref: https://github.com/RSuter/NSwag/blob/master/src/NSwag.Commands/Commands/OutputCommandExtensions.cs#L40

**Comment by teyc** [comment]
I'll create a PR?

**Comment by RSuter** [comment]
Thanks for implementing this

**Comment by egorshulga** [comment]
Hey @teyc @RicoSuter! It's been a year, sorry :)
Could we make it an opt-out feature? 
I'm integrating nswag with msbuild and interferes with incremental builds.

**Comment by RicoSuter** [comment]
Why is this a problem?
