### ISSUE TITLE
NSwagStudio: System.InvalidOperationException: Unsupported target framework '.NETCoreApp'.

### ISSUE THREAD

**Issue by andrewliang** [RSuter/NSwag#1375]
Hi folks!

I launched NSwagStudio, set my ASP.NET Core 2.1 app's project path and clicked on **Generate Outputs**.  I then got the following error:

![image](https://user-images.githubusercontent.com/1163664/41193596-3a8e5e7e-6bdc-11e8-894c-4bfc0017df94.png)

Any ideas? Thanks!

I'm currently using NSwagStudio V11.17.13.0

**Comment by RSuter** [comment]
Choose the correct runtime (2.1) at the top left of the ui...

**Comment by andrewliang** [comment]
Thanks 😅

**Comment by RSuter** [comment]
Does it work now? Next version will fix some assembly loading problems...
