### ISSUE TITLE
Deserialization broken with Wrapper object

### ISSUE THREAD

**Issue by larcai** [RSuter/NSwag#1376]
For some reason the all my responses are now wrapped and cause deserialization to fail.
I cannot find where to disable this, and cannot find a way a workaround via Serialization Settings

The version is NSwag v11.17.13.0
This following wrapper class is generated

```
public partial class ActionResultOfUserViewModel 
    {
        [Newtonsoft.Json.JsonProperty("Result", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public byte[] Result { get; set; }    
        [Newtonsoft.Json.JsonProperty("Value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public UserViewModel Value { get; set; }    
    }
```

Then the following code fail to deserialize because the API return UserViewModel as json…

`result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<ActionResultOfUserViewModel>(responseData_, _settings.Value);`

Any suggestions?

**Comment by RSuter** [comment]
I think this is fixed here: https://github.com/RSuter/NSwag/issues/1377

**Comment by RSuter** [comment]
Is this solved with v11.17.14+?

**Comment by larcai** [comment]
I had a look a few moments ago, It is fixed - Thanks very much

**Comment by RSuter** [comment]
BTW: For new asp.net core 2.1 projects you should prefer the new api explorer based generator: https://github.com/RSuter/NSwag/wiki/AspNetCoreToSwaggerGenerator
