### ISSUE TITLE
Support correcty type with ActionResult<T>

### ISSUE THREAD

**Issue by giggio** [RSuter/NSwag#1377]
Currently in ASPNET Core 2.1 we return `Task<ActionResult<SomeResponse>>`, so it is easier to return other results, such as `NotFoundResult`. [More info](https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-web-apis/).

If we do that, the response type will be incorrectly set to `"file"`, as per `SwaggerJsonSchemaGenerator`:

https://github.com/RSuter/NSwag/blob/e30b6c082fd40f424b2a08544faed6c9e2536143/src/NSwag.SwaggerGeneration/SwaggerJsonSchemaGenerator.cs#L81-L89

To resolve that we could use `[SwaggerResponse(typeof(SomeResponse))]`, but that is cumbersome. Ideally the `IsFileResponse` would understand this pattern.

Maybe the change should be to `GenerateWithReferenceAndNullability`:
https://github.com/RSuter/NSwag/blob/e30b6c082fd40f424b2a08544faed6c9e2536143/src/NSwag.SwaggerGeneration/SwaggerJsonSchemaGenerator.cs#L65-L79

So that it understands `ActionResult<T>` as it already does with `JsonResult<T>`.

**Comment by RSuter** [comment]
You can also switch to the new generator UseSwagger*WithApiExplorer() etc which should already support this...

**Comment by RSuter** [comment]
Ref: #999

**Comment by RSuter** [comment]
Is this solved with v11.17.14+

**Comment by springy76** [comment]
With 11.17.15 I neither have return types using legacy nor experimental-API-Explorer genereator. Swashbuckle does it since weeks, the "More info" link in the OP to the blog entry from February already mentions that ActionResult<T> has been introduced exactly for tools like Swashbuckle and NSwag.

**Comment by RSuter** [comment]
@springy76 I think this should be working. What's the output?

**Comment by springy76** [comment]
The 200 response is just missing, saying "undocumented" when trying out.

**Comment by RSuter** [comment]
Oh shit...

**Comment by RSuter** [comment]
Just checked, looks good to me (but there's another problem). Can you post the signature of your controller action method?

**Comment by RSuter** [comment]
Sample which works for me: 

```
        [HttpGet("findByStatus")]
        [Produces("application/json")]
        public async Task<ActionResult<IEnumerable<Pet>>> FindByStatus(string[] status)
        {
            await Task.Delay(0);
            return new ObjectResult(Array.Empty<Pet>());
        }

        [HttpGet("findByCategory")]
        [Produces("application/json")]
        [ProducesResponseType(typeof(IEnumerable<Pet>), (int)HttpStatusCode.OK)]
        [ProducesResponseType(typeof(SerializableError), (int)HttpStatusCode.BadRequest)]
        public async Task<ActionResult<IEnumerable<Pet>>> FindByCategory([BindRequired] string category)
        {
            await Task.Delay(0);
            return new ObjectResult(Array.Empty<Pet>());
        }
```

output: 

```
    "/pet/findByStatus": {
      "get": {
        "tags": [
          "Pet"
        ],
        "operationId": "Pet_FindByStatus",
        "consumes": [
          ...
        ],
        "parameters": [
          {
            "name": "status",
            "in": "body",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "x-nullable": true
          }
        ],
        "responses": {
          "200": {
            "x-nullable": true,
            "description": "",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Pet"
              }
            }
          }
        }
      }
    },
    "/pet/findByCategory": {
      "get": {
        "tags": [
          "Pet"
        ],
        "operationId": "Pet_FindByCategory",
        "parameters": [
          {
            "type": "string",
            "name": "category",
            "in": "query",
            "required": true,
            "x-nullable": true
          }
        ],
        "responses": {
          "200": {
            "x-nullable": true,
            "description": "",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Pet"
              }
            }
          },
          "400": {
            "x-nullable": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/SerializableError"
            }
          }
        }
      }
    },
```

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/pull/1385

**Comment by springy76** [comment]
My bad, I defined 400/404/500 `[SwaggerResponse]`s on the abstract base controller class and was not aware of the existence of `[SwaggerDefaultResponse]`.

But instead of adding `[SwaggerDefaultResponse]` to all 120+ actions, can I declare `[SwaggerDefaultResponse]` on the base (of course I can), and then revoke it for the 2-3 actions for which it is not true?

**Comment by RSuter** [comment]
@springy76 I think this should work... If i remember correctly, SwaggerDefaultResponse is only applied if no 2xx response is manually defined... but you have to try this.

**Comment by RSuter** [comment]
I also recommend to use the new Api Explorer based generator as the other one will be deprecated eventually... Is SwaggerDefaultResponse also working with the new Api explorer based generator?

**Comment by springy76** [comment]
Maybe you could introduce a new counterpart `[RemoveSwaggerDefaultResponse]` to `[SwaggerDefaultResponse]` the same way as `[Authorize]` has the counterpart `[AllowAnonymous]`?

**Comment by RSuter** [comment]
If you have [ProducesResponseType] or [SwaggerResponse] attributes, the default response is always ignored except when [SwaggerDefaultResponse] is defined... so why do you need this [RemoveSwaggerDefaultResponse] attribute?

**Comment by springy76** [comment]
When I add [SwaggerDefaultResponse] to the base controller I might have the (very rare) need to opt-out of that.

It now works for both the old and the new ApiExplorer based generator. I'm just analyzing the differences since the new JSON is 22kb smaller (480 instead of 502) than the older one.

**Comment by RSuter** [comment]
Ok, that might make sense :-)

It is smaller? I was expecting it to be bigger as it has more "produces" information... please report any problematic diffs as the end goal is that both generators produce more or less the same spec...

**Comment by RSuter** [comment]
But can't you just add a [SwaggerResponse(typeof(void), Status.OK)]

**Comment by giggio** [comment]
I can't move to ApiExplorer until #1294 is fixed.

**Comment by simeyla** [comment]
@RSuter where is `[SwaggerDefaultResponse]` coming from? I only see [one usage but no definition](https://github.com/RSuter/NSwag/search?q=SwaggerDefaultResponse).

Wanted to use it in conjunction with `ActionResult<T>` when I'm also declaring a response type for 400 response.

        [HttpPost("RequestToken")]
        //[ProducesResponseType(typeof(JWTToken), 200)]
        [SwaggerDefaultResponse]
        [ProducesResponseType(typeof(RequestTokenError), 400)]
        public async Task<ActionResult<JWTToken>>

**Comment by RSuter** [comment]
Implemented here: https://github.com/RSuter/NSwag/blob/master/src/NSwag.Annotations/SwaggerDefaultResponseAttribute.cs

**Comment by simeyla** [comment]
Just to clarify usage for a method. 

        [SwaggerResponse(HttpStatusCode.OK, typeof(LoginResponse), IsNullable = false)]
        public ActionResult<LoginResponse> Login(string accessToken) { ...

If you add `IsNullable=false` to the attribute it will generate typescript code without `| null`.

    // typescript client - not nullable
    login(accessToken: string): Observable<LoginResponse> { ...

It's important to do this if you're using `strict` mode in typescript because otherwise you'll get 'this object may be null' errors everywhere. Unless of course you want to allow a null for specific methods, in which case don't add the attribute.

> Type 'UserMappingInfo | null' is not assignable to type 'UserMappingInfo'.
>  Type 'null' is not assignable to type 'UserMappingInfo'.
