### ISSUE TITLE
Unused TypeScript imports cause problems with --noUnusedLocals flag

### ISSUE THREAD

**Issue by MattDillard** [RSuter/NSwag#1378]
When generating code targeted at TypeScript 2.7, targeting Angular, the following import appears near the top of the generated file:

    import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpResponseBase, HttpErrorResponse } from '@angular/common/http';

I compile my application with the `--noUnusedLocals` flag, though, and neither `HttpParams` nor `HttpErrorResponse` is ever used in the generated code. As a result, this file shows two compilation errors.

Here is the TypeScript portion of the NSwag config file:

```
  "codeGenerators": {
    "swaggerToTypeScriptClient": {
      "className": "{controller}Client",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 2.7,
      "template": "Angular",
      "promiseType": "Promise",
      "httpClass": "HttpClient",
      "injectionTokenType": "InjectionToken",
      "dateTimeType": "MomentJS",
      "nullValue": "Null",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateOptionalParameters": false,
      "wrapDtoExceptions": false,
      "wrapResponses": false,
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "useTransformOptionsMethod": false,
      "useTransformResultMethod": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "markOptionalProperties": true,
      "generateCloneMethod": false,
      "typeStyle": "Class",
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "handleReferences": false,
      "generateConstructorInterface": true,
      "convertConstructorInterfaceData": false,
      "importRequiredTypes": true,
      "useGetBaseUrlMethod": false,
      "baseUrlTokenName": "API_BASE_URL",
      "queryNullValue": "",
      "output": "../../../Angular/libs/generated/WebAPIv1.ts"
    }
  }
```

I did a grep through the NSwag source code and couldn't find either of those two types referenced in the code base - are they never emitted into the generated code? If not, can we change NSwag not to emit them in the import statement?

**Comment by MattDillard** [comment]
For a bit more information, it appears that HttpErrorResponse was used for a short period of time in December 2017.

`AngularClient.liquid` referenced it on Dec 6 in commit [ffaba3](https://github.com/RSuter/NSwag/commit/ffaba3e880b210e2dc16405c700e5e5beb90c24c#diff-3a1779297660769005d6184a40a856a8), and it was removed on Dec 20 in commit [f00a37](https://github.com/RSuter/NSwag/commit/f00a37866d2078b6f42088180543b8e740fc49b8#diff-3a1779297660769005d6184a40a856a8).

**Comment by RSuter** [comment]
It really looks that it's never used...

**Comment by RSuter** [comment]
Thanks for reporting.
