### ISSUE TITLE
Unable to include JsonExtensionData in swagger.json file

### ISSUE THREAD

**Issue by MarijnCatthoor** [RSuter/NSwag#1382]
I have a model that has a property that is decorated with the JsonExtensionData attribute:
![image](https://user-images.githubusercontent.com/34912984/41404309-2a4aa664-6fc7-11e8-9ffe-96ab34b57dff.png)
However, when generating the swagger.json file, this isn't added as additionalproperties:
![image](https://user-images.githubusercontent.com/34912984/41404375-5323cdae-6fc7-11e8-85d9-d2957a899bb9.png)

I use following code to enable NSwag in my web API:
![image](https://user-images.githubusercontent.com/34912984/41404443-86d161ac-6fc7-11e8-8498-33949dc75500.png)

The Web API is an .Net core 2.0 web API.

Any idea on how I can force the creation of the AdditionalProperties property and why this is isn't generated out of the box?

Thanks in advance!

**Comment by RSuter** [comment]
This needs to be added here: https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L320

=> Check whether a property with JsonExtensionDataAttribute exists and if so, generate the correct schema...

Also the code generators need to correctly process objects with an `additionalProperties` schema (i.e. generate the same property with the attribute, not sure whether this is already implemented).

**Comment by RSuter** [comment]
Now handled by schema generator and was already handled by C# generator (idk how it looks in the TS gen).
