### ISSUE TITLE
[TypeScript] StringEnumConverter with CamelCaseText generate PascalCase enums

### ISSUE THREAD

**Issue by YZahringer** [RSuter/NSwag#1387]
When ASP.NET Core is configured with `CamelCaseText` `StringEnumConverter`, enums in TypeScript should be generated in CamelCase?
````cs
services.AddMvc().AddJsonOptions(options =>
{
    options.SerializerSettings.Converters.Add(new StringEnumConverter {CamelCaseText = true});
});
````

**Comment by RSuter** [comment]
Can you also show a sample enum, the actual and expected output?

**Comment by YZahringer** [comment]
Actual API enum:
````cs
public enum MyEnum
{
    Value1,
    Value2
}
````
Actual TypeScript output:
````ts
export enum MyEnum {
  Value1 = "Value1", 
  Value2 = "Value2"
}
````
Expected TypeScript output (camelCase string):
````ts
export enum MyEnum {
  Value1 = "value1", 
  Value2 = "value2"
}
````

**Comment by RSuter** [comment]
TODO: Use SerializerSettings instead of ContractResolver in NSwag
