### ISSUE TITLE
Guidance on contract first approach.

### ISSUE THREAD

**Issue by DannyRyman** [RSuter/NSwag#1388]
I was very glad to see that consideration is given to supporting a contract first approach by providing the SwaggerToCSharpControllerGenerator tool (as this is our preferred workflow), but the documentation is a bit light, so I would be grateful if someone can answer a few questions?

Once the initial controller has been generated, is it expected that the developers then switch to having the swagger scheme inferred from the code? or is it possible to continue schema first and regenerate the controller whenever an updated schema is provided? We would strongly prefer the later approach, as it suits our workflow, but I am lost at how you can setup the solution to expose both the swagger schema and the Swagger UI documentation though the API based on a schema (rather than inferred from the assembly).

Any help would be gratefully appreciated ;)

**Comment by RSuter** [comment]
I think both approaches are possible, but I personally think the second approach (stay schema-first) makes more sense. To do that, you can host the source swagger.json in your wwwroot and add: 

            app.UseSwaggerUi3(s =>
            {
                s.SwaggerRoute = "/my/path/in/wwwroot/swagger.json";
                s.SwaggerUiRoute = "/swagger";
            });
            
and e.g. use the same spec to generate the controllers... e.g. automatically as a prebuild target with the NSwag.MSBuild package.

**Comment by DannyRyman** [comment]
Brilliant! Thanks for the info.
