### ISSUE TITLE
TypeScript 2.5.3 --strict won't compile default NSwag output

### ISSUE THREAD

**Issue by nerfpops** [RSuter/NSwag#1403]
With `--strict` it's important to explicitly tell the compiler when something can be undefined.

The problematic code is on line 12:
```
protected jsonParseReviver: (key: string, value: any) => any = undefined;
```
With strict enabled, the following compiler error is given:
```
(TS) Type 'undefined' is not assignable to type '(key: string, value: any) => any'
```
The solution:
```
protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;
```

**Comment by RSuter** [comment]
This is already implemented, just change the `TypeScriptVersion` setting: https://github.com/RSuter/NSwag/blob/master/src/NSwag.CodeGeneration.TypeScript/Templates/AngularClient.liquid#L20

**Comment by RSuter** [comment]
... and: https://github.com/RSuter/NSwag/blob/master/src/NSwag.CodeGeneration.TypeScript/Models/TypeScriptClientTemplateModel.cs

**Comment by nerfpops** [comment]
Of course. Sorry for just assuming this wasn't implemented. As always, your library is awesome.
