### ISSUE TITLE
How to provide additional information for the expected data in a controller action

### ISSUE THREAD

**Issue by statler** [RSuter/NSwag#1406]
As per so question
https://stackoverflow.com/questions/50867026/nswag-provide-additional-information-for-the-expected-data-in-a-controller-act

I have a controller action that accepts data in the form of an array of objects (Complex object called ControlLinePointDto). For reasons described in my question and answer [here](https://stackoverflow.com/questions/50852571/net-core-controller-to-update-array-but-only-with-included-properties), I read this into a JArray rather than a ControlLinePointDto[]. I do this in multiple places with different objects.

How can I change the documentation (NSwag) so that it is documented (including example) as a ControlLinePointDto[], rather than []?

    [HttpPost("AddPoints")]
    [ProducesResponseType(typeof(List<ControlLinePointDto>), 200)]
        
        public async Task<IActionResult> AddPoints(int ControlLineId, [FromBody] JArray pointSetJson){
    }

**Comment by RSuter** [comment]
ATM you can do that with a custom operation processor, but it may be not that simple... https://github.com/RSuter/NSwag/wiki/Document-Processors-and-Operation-Processors

I'd like to have a special attribute, e.g. `[SwaggerType(typeof(ControlLinePointDto[]))]` which can be applied to a parameter to change it's swagger type...

**Comment by RSuter** [comment]
Would this attribute solve your problem?

**Comment by statler** [comment]
Absolutely it would!

**Comment by RSuter** [comment]
I created a PR in NJS, should also work on parameters when used in NSwag: https://github.com/RSuter/NJsonSchema/pull/721

This enables even more scenarios (e.g. change DTO schema types). 
What do you think?

**Comment by statler** [comment]
That looks like it will do the trick. Thanks heaps for looking into that so quickly.

Cheers
D

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/commit/500c4be3e7516b832c9951780965e50e53e12bb2#diff-206fdab6f08fded58b6deef0d4ca34a8R236

**Comment by RSuter** [comment]
New NSwag version will be released soon (today)
