### ISSUE TITLE
.nswag file being edited by invoking `run`

### ISSUE THREAD

**Issue by gregorylyons** [RSuter/NSwag#1407]
When executing `dotnet nswag run service.nswag`, the underlying nswag file is being edited (and settings replaced with presumed defaults). I suspect this happens when the file is loaded, as the generated output reflects the changed settings, rather than the initial nswag values.

- dateType
- dateTimeType
- timeType
- timeSpanType
- dictionaryType

appear to be problematic (other properties may also be broken, I haven't done exhaustive testing).

Diff of the settings file before/after:
https://gist.github.com/gregorylyons/8d9cc03a9a219b01cac5a689b6579d48/revisions?diff=unified#diff-277cbbc112726fb71238040b7a5706c9

**Comment by RSuter** [comment]
This is actually a feature: NSwag migrates the document so that it works correctly with the latest version... here we are adding namespaces because all usings have been removed.

**Comment by gregorylyons** [comment]
Thanks for the reply! I raised the issue because it seems inconsistent, the following three properties escape this behaviour. If that's expected, we can just close off this issue.

- arrayType
- arrayBaseType
- dictionaryBaseType

**Comment by RSuter** [comment]
I think this is expected, next major versions will change the defaults...
