### ISSUE TITLE
Generic Types

### ISSUE THREAD

**Issue by statler** [RSuter/NSwag#1408]
I have read some of the issues on Generic support, but can't quite get to the bottom of the current state of play.

Essentially, nearly all of my controllers have an action like this;

        [HttpGet]
        [ProducesResponseType(typeof(LoadResultMap<VariationListDto>), 200)]
        public Object GetVariation(DataSourceLoadOptions loadOptions)
        {
            return DataSourceLoader.Load(_context.Variation.Where(x => x.ProjectId == _userService.Project_ID)
                .ProjectTo<VariationListDto>(), loadOptions);
        }

    public class LoadResultMap<T>
    {
        public List<T> data;
        public int totalCount;
        public int groupCount;
        public object[] summary;
    }

This makes an absolute mess in the swagger of course. How can I go about getting this to come through cleanly in client generation. Is there an easy way?

**Comment by RSuter** [comment]
See https://github.com/RSuter/NJsonSchema/issues/23

Generics are not supported by swagger/openapi/json schema so this would be completely custom and will only work in the njs/nswag toolchain...

**Comment by statler** [comment]
Thanks - I saw that but didn't really understand it - is the response in that post an indication of how this might be achieved? If so, is there anywhere I can read more about how to implement it? I don't really understand what is going on there.

**Comment by RSuter** [comment]
Swagger/openapi uses a slightly modified version of json schema to describe dto schemas... however json schema does not know the notion of generics. However, it is allowed to extend json schema with custom properties staring with x-. This njs issue explains how we could implement that. The problem is that this extension will only be understood by the njs/nswag toolchain and it is a bigger untertaking to implement that...

**Comment by statler** [comment]
OK - so not really an option for the moment?

**Comment by RSuter** [comment]
It's not on my prio list to do in my spare time...

**Comment by RSuter** [comment]
Closed, see duplicate in NJS
