### ISSUE TITLE
Is it possible to get SwaggerOperation => Parameter when parameters are defined in Definition schema

### ISSUE THREAD

**Issue by Nadun1** [RSuter/NSwag#1411]
I use an asp.net core plugin "NSwag.CodeGeneration.CSharp" to convert swagger files into Objects.
Everything works great apart from When i tried to Get parameter definitions from Parameters defined as schema  in SwaggerOperation object.When Parameters defined as schema definition it returns null for for Parameter object.
Is there any way to identify does parameters are defined as schema definition.currently i'm using 

`SwaggerOperation.Parameters[i].IsAnyType`

Is it correct ?

**Comment by RSuter** [comment]
ActualParameters?

**Comment by RSuter** [comment]
Or use  SwaggerOperation.ActualParameters[i].ActualParameter.ActualSchema.IsAnyType for more $ref resolution
