### ISSUE TITLE
How to send a patch request with nswag?

### ISSUE THREAD

**Issue by JamesVG1** [RSuter/NSwag#1418]
const patch: OperationOfLocation[] = [
        OperationOfLocation.fromJS({'op': 'replace', 'path': '/locationType', 'value': LocationType.Company}),
        OperationOfLocation.arguments({'op': 'replace', 'path': '/street', 'value': this.companyAddressForm.value.street})
      ];  

      this.locationService.patch(this.co.locationId, patch);

I am unable to use patch. The JsonPatchDocument comes in to c# with a count of 0

**Comment by RSuter** [comment]
Ref: https://github.com/RSuter/NSwag/issues/1410
