### ISSUE TITLE
Cant use any OAUTH2 flow besides 'implicit'

### ISSUE THREAD

**Issue by steve-tapley** [RSuter/NSwag#1419]
Hi,

In this commit: https://github.com/RSuter/NSwag/commit/f92e130fffba8cdb11ad6a4854e33b5de1fc4149#diff-5807da60806d730573427582cb0bf027

... the UpdateFlows function looks like it has some debug code in there that always just sets the flow to implicit (line 163).  
I think Line 163 should be removed...

Cheers,
Steve

**Comment by RSuter** [comment]
Is this now working with v11.17.18?
