### ISSUE TITLE
[Code Gen] ConvertToString() cannot handle null value

### ISSUE THREAD

**Issue by bhutten14** [RSuter/NSwag#1424]
We run in an issue where we have a rest API `GetByIDsAsync(IEnumerable<string> ids)` and a NSwag generated client. When providing a list of string elements and an element is a null value, the generated code fails on the `ConvertToString()`.
It fails on the `if (value.GetType().IsArray)`, which is a pitty because `System.Convert.ToString()` can handle null values, but `GetType()` doesn't.

**Comment by RSuter** [comment]
Is this fix ok?

**Comment by bhutten14** [comment]
I'm sorry, which fix?
