### ISSUE TITLE
Question: Hide endpoints from documentation, but generate client code

### ISSUE THREAD

**Issue by aaronhudon** [RSuter/NSwag#1427]
I am looking for a technique where the swagger user interface documentation can hide one or more endpoints, but the JSON document still retains all of the information so client code can be generated.

I am generating user interface documentation through:
`UseSwaggerUi3(....)`

**Comment by RSuter** [comment]
I recommend generating two Swagger specs, one for the UI and one for further processing: 

UseSwagger(with route a)
UseSwaggerUi3(with route b)

Use an operation processor in UI to exclude some operations: https://github.com/RSuter/NSwag/wiki/Document-Processors-and-Operation-Processors

**Comment by aaronhudon** [comment]
Perfect, exactly what I needed.

This worked for me, hiding "Controller1" and "Controller2" - could generalize through an attribute on the controller in the future.

```
app.UseSwaggerUi3(typeof(Startup).GetTypeInfo().Assembly, settings =>
{
    settings.GeneratorSettings.OperationProcessors.Add(new HideInternalController());
});

class HideInternalController : IOperationProcessor
{
    public Task<bool> ProcessAsync(OperationProcessorContext context)
    {
	if(context.ControllerType == typeof(Controllers.Controller1) ||
		context.ControllerType == typeof(Controllers.Controller2))
	{
		return Task.FromResult(false);
	}
	return Task.FromResult(true);
    }
}
```
