### ISSUE TITLE
Question: SwaggerToTypeScript - custom resposeTypes?

### ISSUE THREAD

**Issue by Bilaltariq98** [RSuter/NSwag#1429]
Hi, 

I'm wondering if its possible to change the responseType from blob to text on generation. I was previously using the SwaggerToTypeScript tool with the HttpClass set to Http which I've now changed to HttpClient so that I'm able to intercept request/responses, but had issues with the responseType being blob whenever an error triggered.

Thanks!

**Comment by RSuter** [comment]
Can you show a small sample code of what is generated and what you want to be generated?

**Comment by Bilaltariq98** [comment]
Before (with HttpClass:Http) : 

`


        post(accountId: string, body: CreateAccount | null): Observable<CommonResponse> {
        let url_ = this.baseUrl + "/v1/user/{accountId}/userAccounts";
        if (policyId === undefined || policyId === null)
            throw new Error("The parameter accountId must be defined.");
        url_ = url_.replace("{accountId}", encodeURIComponent("" + accountId )); 
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);
        
        let options_ : any = {
            body: content_,
            method: "post",
            headers: new Headers({
                "Content-Type": "application/json", 
                "Accept": "application/json"
            })
        };

        return this.http.request(url_, options_).flatMap((response_ : any) => {
            return this.processPost(response_);
        }).catch((response_: any) => {
            if (response_ instanceof Response) {
                try {
                    return this.processPost(response_);
                } catch (e) {
                    return <Observable<CommonResponse>><any>Observable.throw(e);
                }
            } else
                return <Observable<CommonResponse>><any>Observable.throw(response_);
        });
    }
`


After (with HttpClass:HttpClient): 

`


        post(accountId: string, body: CreateAccount | null): Observable<CommonResponse> {
        let url_ = this.baseUrl + "/v1/user/{accountId}/userAccounts";
        if (policyId === undefined || policyId === null)
            throw new Error("The parameter policyId must be defined.");
        url_ = url_.replace("{accountId}", encodeURIComponent("" + accountId)); 
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);
        
        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json", 
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).flatMap((response_ : any) => {
            return this.processPost(response_);
        }).catch((response_: any) => {
            if (response_ instanceof HttpResponse) {
                try {
                    return this.processPost(response_);
                } catch (e) {
                    return <Observable<CommonResponse>><any>Observable.throw(e);
                }
            } else
                return <Observable<CommonResponse>><any>Observable.throw(response_);
        });
    }
`

So, whenever I'm calling any of the API's now generated by nswag with the /HttpClass:HttpClient flag set, success requests get converted to text by a blobToText method that's generated, however exceptions are still in blob format? 

Additionally, while debugging the '(response_ instanceof HttpResponse)' always seems to return false and goes to the else case.

**Comment by Bilaltariq98** [comment]
So turns out the project had a dependencies on a previous version of nswag, updating resolved the issues. 

Thanks & Apologies!
