### ISSUE TITLE
Make ExtensionData available in client generator templates

### ISSUE THREAD

**Issue by mrexwinkel** [RSuter/NSwag#1436]
I added an IOperationProcessor to extent the swagger file generation adding additional data using the ExtensionData dictionary. I want to use that information during the client generation but the model that is provided to the templates does not contain the ExtensionData. It would be great if that could be added.

**Comment by RSuter** [comment]
Ok, I've added the ExtensionData properties to the models, not sure however how to use this in the liquid templates...

**Comment by mrexwinkel** [comment]
I tried to use it in the liquid template and can't get it to work. So I started with a simple test of the DotLiquid library and I got it to work in such a way that I can access the dictionary by key:
```liquid
{% assign x = Items["x-doc-example"] -%}
{% for example in x -%}
/// {{ example.text }}
/// <example>{{example.text}}</example>
{% endfor -%}
```
Then I start tracing this back to the NSwag/NJsonSchema and found that NJsonSchema does some custom wrapping using the LiquidProxyHash class in NJsonSchema. A property of type IDictionary is mapped to a list of hashes and that makes is impossible to access an item based on they key.
Because it is a list I can only access the items from the dictionary by position.

**Comment by RSuter** [comment]
Thanks for investigating... will fix this in njs soon

**Comment by RSuter** [comment]
Ok this commit should fix it

**Comment by mrexwinkel** [comment]
I tried your new implementation an ran in some issues. When property values itself are dictionaries or lists containing dictionaries then it will not work because they are wrapped inside a LiquidProxyHash.
I used the following model:
```c#
var model = new Model
{
     Items = new Dictionary<string, object>
    {
         {"x-doc-example", new[] { new Dictionary<string, object> {
             { "text", "some text" },
             { "code", "some code" }
         } } }
    }
};
```
I changed the implentation of the LiquidProxyHash into the following:

```c#
internal class LiquidProxyHash : Hash
    {
        private readonly IDictionary<string, PropertyInfo> _properties;

        public LiquidProxyHash(object obj)
        {
            Object = obj;
            _properties = obj?.GetType().GetRuntimeProperties()
                .ToDictionary(p => p.Name, p => p) ??
                    new Dictionary<string, PropertyInfo>();
        }

        public object Object { get; }

        public override bool Contains(object key)
        {
            return _properties.ContainsKey(key.ToString()) || base.Contains(key);
        }

        protected override object GetValue(string key)
        {
            if (_properties.ContainsKey(key))
            {
                var value = _properties[key].GetValue(Object);
                if (IsObject(value))
                {
                    return GetObjectValue(value);
                }
                return value;
            }
            else
                return base.GetValue(key);
        }

        private object GetObjectValue(object value)
        {
            if (value is IDictionary dictionary)
            {
                var hash = new Hash();
                foreach (var k in dictionary.Keys)
                {
                    var v = dictionary[k];
                    hash[k.ToString()] = IsObject(v) ? GetObjectValue(v) : v;
                }
                return hash;
            }
            else if (value is IEnumerable enumerable)
            {
                
                var list = new List<object>();
                foreach (var item in enumerable)
                {
                    list.Add(IsObject(item) ? GetObjectValue(item) : item);
                }
                return list;
            }
            else
                return new LiquidProxyHash(value);
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if (obj is LiquidProxyHash hash && hash.Object != Object)
                return false;

            return base.Equals(obj);
        }

        private static bool IsObject(object value)
        {
            return value != null && value.GetType().GetTypeInfo().IsClass && !(value is string);
        }
    }
```
This seems to do the trick. I don't know if it has other implications, did not changed this in the NJsonSchema code base. Just copied your implementation to test it in a small console app.

**Comment by mrexwinkel** [comment]
The implementation of LiquidProxyHash in your commit differs slightly from my implementation and it does not work for my use case. Was my change breaking stuff ? If so I may have to look at formatting my extension values differently so it will work with the current implementation.

**Comment by RSuter** [comment]
Yes, some tests failed... thats why i changed it... can you provide a test here? https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.Tests/LiquidTests.cs

**Comment by mrexwinkel** [comment]
Yes, do you want me to create a branch or paste the test here ?

**Comment by RSuter** [comment]
Up to you, but you can just paste it here.

**Comment by mrexwinkel** [comment]
Ok, will paste it for now.
```c#
[Fact]
public void LiquidModelHasNestedDictionaryAndLists_KeyAccessAndListIterationShouldWork()
{
    /// Arrange
    var model = new TestModel();
    model.Bar["Baz"] = new[] { new Dictionary<string, object> {
                { "key1", "value1" },
                { "key2", "value2" }
            } };

    var liquid = "{% assign x = Bar[\"Baz\"] -%}{% for i in x -%}key1={{ i[\"key1\"] }}key2={{ i[\"key2\"] }}{% endfor -%}";
            
    /// Act
    var hash = new LiquidProxyHash(model);
    var template = Template.Parse(liquid);
    var text = template.Render(new RenderParameters(CultureInfo.InvariantCulture)
    {
        LocalVariables = hash,
    });

    /// Assert
    Assert.Equal("key1=value1,key2=value2", text);
}
```

**Comment by mrexwinkel** [comment]
I was testing on the master branch of NSwag, I switched to the latest nuget packages (11.17.19) of NSwag and I noticed that the ExtensionData property on the OperationModelBase<,> was not there. Could you provide a package containing the ExtensionData property ? 
Then I can implement a workaround using only dictionaries and no arrays. That would be very helpful.

**Comment by RSuter** [comment]
I hope it's finally working for you :-)

**Comment by RSuter** [comment]
… at least your test is passing now. What do you think?

**Comment by mrexwinkel** [comment]
Hi Rico,

Great job! It is working perfectly.

Thx.

**Comment by john-larson** [comment]
I am adding ExtensionData as follows:
`context.Schema.ExtensionData.Add("abc", "def");`

But I cannot access this data from the Enum.liquid template. What is the proper way to access this data? Any help would be appreciated. @RicoSuter @mrexwinkel

**Comment by jeremyVignelles** [comment]
How would you expect to write an extension of an enum in JSON?
I'm pretty sure that extension data are only available for objects

**Comment by john-larson** [comment]
@jeremyVignelles It appears to be present here:
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.TypeScript/Models/EnumTemplateModel.cs

**Comment by jeremyVignelles** [comment]
I mean, this shouldn't probably be here.
Have a look at the OpenApi documentation:
https://swagger.io/docs/specification/data-models/enums/

an enum is just declared as a list of values.
When you say `value: MyEnumValue`, what do you expect to pass as an extension data and how do you expect to pass it?

**Comment by john-larson** [comment]
As far as I understand, extension data is about adding extra information to the generated openapi document so that code generators etc. can make use of this data during generation. Kind of like metadata for the schema. It is not something that is added to classes or enums automatically.

**Comment by jeremyVignelles** [comment]
I'm sorry, you're right, I was thinking about AdditionalData, not about schema extensions
