### ISSUE TITLE
Assembly size (NSwag.AspNetCore.dll)

### ISSUE THREAD

**Issue by SebastianStehle** [RSuter/NSwag#1446]
Hi,

I use NSwag.AspNetCore and it is great. Usually I do not care about the assembly size, but 32MB!?

It would be great to have separate packages for the UIs, e.g. I use ReDoc from CDN and don't need it.

**Comment by RSuter** [comment]
It is already 32mb? Thats a lot... good idea to split it into separate packages. Will look into this soon

**Comment by SebastianStehle** [comment]
![image](https://user-images.githubusercontent.com/1236435/42441850-6bfb72e0-8369-11e8-89e2-dee49877320a.png)

I think the .map files can be omitted. It would also make sense to add the assets as gzipped files and serve them as gzip-encoded-content. (Is there a browser who does not support gzip?)

**Comment by RSuter** [comment]
By removing the .map files i got it down to 10 mb

**Comment by SebastianStehle** [comment]
Great, are you going to deploy this?

**Comment by RSuter** [comment]
Created new issue: https://github.com/RSuter/NSwag/issues/1491
