### ISSUE TITLE
Getting an Error when referencing YAML Documents

### ISSUE THREAD

**Issue by Em1ss1oN** [RSuter/NSwag#1458]
When generating C# Controller from a swagger with references to YAML Files NSwag encounters an error when deserializing contract. The root cause was fixed in NJsonSchema (https://github.com/RSuter/NJsonSchema/issues/736), it need to be propagated to NSwag.

**Comment by RSuter** [comment]
Done, just some minutes ago, please retest.

**Comment by Em1ss1oN** [comment]
Looks like the problem was fixed in NJsonSchema.Yaml package, but NSwag, for some reasons, does not use it but implements the same yaml-to-json conversion itself. So, fix needs to be reimplemented in NSwag too. Unfortunately, SwaggerDocument does not expose public api with ability to inject JsonSchemaResolverFactory. May be, it could be implemented through exposing protected CreateReferenceResolver method from SwaggerDocument and inheriting from it, it seems to be a less-breaking change. I'll create a PR later this weekend.

**Comment by RSuter** [comment]
Can we close this one? Release in soon...

**Comment by RSuter** [comment]
v11.18.0

**Comment by Em1ss1oN** [comment]
Updated to 11.18.0, the problem is gone, thanks again!
