### ISSUE TITLE
TypeScript / Angular: TimeSpan & Moment Duration

### ISSUE THREAD

**Issue by jochenjonc** [RSuter/NSwag#1460]
Hi,

I have an API that has parameter with TimeSpan as type. After generating the Angular 6 code, the TimeSpan is mapped to a moment type in TypeScript.
Because of that I was unable to get it working, the conversion between moment and TimeSpan throw an error when calling the API.

So I was wondering if it couldn't be solved by using [moment.Duration](https://momentjs.com/docs/#/durations/) as type in the client-side code instead of moment?

Regards,

Jochen Jonckheere

**Comment by RSuter** [comment]
This has to be fixed here: https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.TypeScript/TypeScriptTypeResolver.cs#L127

Can you propose the correct mappings?

**Comment by jochenjonc** [comment]
In the file you are referring to the type of Time and TimeSpan should change from moment.Moment to moment.Duration.

```typescript
...
else if (Settings.DateTimeType == TypeScriptDateTimeType.MomentJS ||
                     Settings.DateTimeType == TypeScriptDateTimeType.OffsetMomentJS)
            {
                if (schema.Format == JsonFormatStrings.Date)
                    return "moment.Moment";

                if (schema.Format == JsonFormatStrings.DateTime)
                    return "moment.Moment";

                if (schema.Format == JsonFormatStrings.Time)
                    return "moment.Duration";

                if (schema.Format == JsonFormatStrings.TimeSpan)
                    return "moment.Duration";
            }
...
```

But the init function in a class also has to change. Instead of `moment(data["birthdate"].toString())` it should be `moment.duration(data["birthtime"].toString())`. See https://momentjs.com/docs/#/durations/creating/.
At first sight I couldn't find the code that is reponisble for that.

I have tested this by manually changing the generated code on an API that returns a TimeStamp in it's model.

**Comment by RSuter** [comment]
Implemented by https://github.com/RSuter/NJsonSchema/commit/efc2d8b992bb88310c1a9d84f1bb89bc494d083a

**Comment by RSuter** [comment]
Ref: https://github.com/RSuter/NJsonSchema/issues/747

**Comment by RSuter** [comment]
Implemented in NJS, NSwag updated...
