### ISSUE TITLE
format - datetime from open API json is generated to string instead of DateTime

### ISSUE THREAD

**Issue by robertbaker** [RSuter/NSwag#1466]
probably more of these, it's like it's ignoring the format value.

**Comment by RSuter** [comment]
Can you provide more context? In the C# client code generator?

**Comment by robertbaker** [comment]
Yes in the C# client code generator, poco classes, using an swagger/openapi json file (provided from azure api-m).

**Comment by RSuter** [comment]
Can you post a sample swagger spec?

**Comment by robertbaker** [comment]
I will need to share it with you privately.

**Comment by JanBN** [comment]
Any news ?

**Comment by robertbaker** [comment]
I moved on. The spec came from swagger or API management. I'm closing because I can't provide the spec
