### ISSUE TITLE
Unreachable code in operations

### ISSUE THREAD

**Issue by molnarm** [RSuter/NSwag#1477]
Using version 11.17.21 from NuGet.

Example yaml and generated code in a gist [here](https://gist.github.com/molnarm/a28be1ecd653ee524fb6d485d8007f41).

When generating a client for operations with typed default responses, after all the different cases for status codes, an extra `else` branch is added to handle the default response, but after this, an extra line ([line 135](https://gist.github.com/molnarm/a28be1ecd653ee524fb6d485d8007f41#file-generatedcode-cs-L135) in my example) is added with a return, which causes build errors because it's dead code (all branches of the status `if` either throw or return).

I didn't try to understand all possible cases in [the corresponding template](https://github.com/RSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid), but I see that if I remove the default response from the YAML, then there's no conditionless branch in the if-else, so this last return statement makes sense, but in other cases, it's problematic.

**Comment by RSuter** [comment]
Just avoiding 

                        return default(ExampleClass);

in this case would solve the problem?

**Comment by molnarm** [comment]
Yes, that would fix this particular case.
