### ISSUE TITLE
JsonInheritanceConverter Can't Handle Circular References ($ref)

### ISSUE THREAD

**Issue by ikaros88** [RSuter/NSwag#1479]
When generating a client using NSwagStudio, the resulting C# client contains a copy of the JsonInheritanceConverter class to handle discriminator values for polymorphic DTOs. The problem is when the DTOs have circular references, using the $id and $ref system, as JsonInheritanceConverter  seems to parse the JObjects before the $ref tokens have been resolved, resulting in errors as the $ref tokens clearly do not contain the discriminator value.

The following lines from ReadJson fail when the jObject only contains a $ref:

`            var discriminator = Newtonsoft.Json.Linq.Extensions.Value<string>(jObject.GetValue)_discriminator));
            var subtype = GetObjectSubtype(objectType, discriminator);`

I fixed this in the generated client by inserting
`            if (jObject.ContainsKey("$ref"))
            {
                var reference = jObject["$ref"].ToString();
                return serializer.ReferenceResolver.ResolveReference(serializer, reference);
            }`
just prior to the above lines.

This fix works for my use case, i do not know if it is a general fix though. Is there any chance of fixing this so i do not have to re-insert the code after every Client generator run?

Is there maybe a more sophisticated way of dealing with this problem, e.g. forcing JSON.NET to resolve references before the converter runs?

Greetings

**Comment by RSuter** [comment]
I created an issue in NJsonSchema as this has to be fixed there...
Can you provide some sample code, or better: A unit test to reproduce this?

**Comment by ikaros88** [comment]
Sample code available in the new issue.
