### ISSUE TITLE
Setting to specify startup directory in NSwagStudio

### ISSUE THREAD

**Issue by syska** [RSuter/NSwag#1484]
startup directory setting (default: nswag.json directory)

At the moment is uses the NSwagStudio directory. This can cause issues for ASPNETCORE apps that is dependent on files when starting up.

**Original issue:**

So, just looking at the exception ... it seems it tried to start the whole project since it's trying to locate the appsettings.json ... ofcause it's not in the "C:\Program Files (x86)\Rico Suter\NSwagStudio\appsettings.json" path ... 

Am I doing something wrong or missing something here? 

It's clearly an issue in this part of the code ... 

```
.SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
            .AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production"}.json", optional: true)
            .Build();
```

**Comment by pranavkm** [comment]
cc @javiercn for suggestions.

> Change the current directory before running the generator

I guess that could be one way to go. xunit seems to do this - https://github.com/xunit/xunit/blob/81c103b41278b5746f5921133ba340af2df619f7/src/xunit.runner.msbuild/xunit.cs#L195. `dotnet ef` on the other hand doesn't mangle with the path.

> And how to determine the default working directory?

In the most common case, it would be the project directory. If you're working with an assembly on disk, I guess some heuristic to locate the csproj would be a possible solution. Another might to have a working directory setting that could be specified

**Comment by javiercn** [comment]
Id recommend having the working directory as a setting if possible. I imagine this is to set the ContentRoot

**Comment by RSuter** [comment]
Closed by https://github.com/RSuter/NSwag/commit/f697097beaa41702342de6fee03b6005185be374
