### ISSUE TITLE
[NSwagStudio] The output is empty

### ISSUE THREAD

**Issue by ifle** [RSuter/NSwag#1486]
I try to create the .NET client for the some payment service that has the swagger specification as [yaml](https://developers.paymentsos.com/docs/api/zoozswagger.yaml). I converted it to json, but swag studio generate the empty output
https://gist.github.com/ifle/bc321899362cca303ef956d6c3523b70#file-paymentsapi-json

**Comment by syska** [comment]
Just a guess ... its OpenAPI not Swagger ... 

From the input in the NSwagStudio, it says it should be Swagger Specification ... so could that be the issue?

**Comment by RSuter** [comment]
OpenAPI should also be supported... hopefully i find the time to look into this soon. Spec seems to look good.

**Comment by RSuter** [comment]
Please retry with v11.18.1

**Comment by ifle** [comment]
It works. Thanks a lot!!!
