### ISSUE TITLE
SwaggerToCSharpClientGenerator: Custom naming for interfaces/client?

### ISSUE THREAD

**Issue by greenmooseSE** [RSuter/NSwag#1487]
I use ```CSharpGeneratorSettings.TypeNameGenerator``` setting to suffix my generated DTOs with the version number (e.g. ```PingGetVmV1``` instead of ```PingGetVm``` in example below), but I cannot find a way to do the same with the generated clients or interfaces (using ```GenerateClientInterfaces = true```).

Is there a way to do this? i.e. instead of below
```csharp
namespace ApiClient.Generated.v1
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "11.17.6.0 (NJsonSchema v9.10.46.0 (Newtonsoft.Json v10.0.0.0))")]
    public partial interface IPingClient
    {
        /// <summary>Returns "Pong!".</summary>
        /// <exception cref="SwaggerException">A server side error occurred.</exception>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        System.Threading.Tasks.Task<PingGetVmV1> GetPingAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "11.17.6.0 (NJsonSchema v9.10.46.0 (Newtonsoft.Json v10.0.0.0))")]
    public partial class PingClient : ApiClient.ApiClientBase, IPingClient
    {

```
I would like the types to be named ```IPingClientV1``` and ```PingClientV1```.

Thanks.

**Comment by RSuter** [comment]
I think you cando that with a custom operation name generator: 

https://github.com/RSuter/NSwag/blob/master/src/NSwag.CodeGeneration/OperationNameGenerators/MultipleClientsFromOperationIdOperationNameGenerator.cs

**Comment by greenmooseSE** [comment]
Worked out great, thanks!
