### ISSUE TITLE
Optional route parameters detected as required

### ISSUE THREAD

**Issue by fubar-coder** [RSuter/NSwag#1490]
Example:

```cs
[HttpPost("change-password/{userId?}")]
public async Task<ActionResult> ChangePassword(
	[Required, FromForm] string oldPassword,
	[Required, FromForm] string newPassword,
	Guid? userId = null)
{
	/* some code */
	return Ok();
}
```

It doesn't matter if I use `userId?` or `*userId` as query parameter, the `userId` parameter is always shown as required in the Swagger UI and the `swagger.json`.

**Comment by RSuter** [comment]
In Swagger all route parameter MUST be required and cannot be optional

**Comment by RSuter** [comment]
See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameter-object

**Comment by fubar-coder** [comment]
OK, thank you for the clarification.
