### ISSUE TITLE
NSwag Studio installer does not exist

### ISSUE THREAD

**Issue by RamiSh** [RSuter/NSwag#1495]
The following url for the NSwagStudio points to msi that does not exist.

http://rsuter.com/Projects/NSwagStudio/installer.php

This uri is from NSwagStudio webpage.
https://github.com/RSuter/NSwag/wiki/NSwagStudio

**Comment by RSuter** [comment]
Sorry, build artifacts just broke because of an NPM error - just fixing. 
You can download v11.18.0 here: https://ci.appveyor.com/api/buildjobs/nxipvuc6t25c8nbr/artifacts/src%2FNSwagStudio.Installer%2Fbin%2FRelease%2FNSwagStudio.msi

**Comment by RSuter** [comment]
Ok link is fixed now
