### ISSUE TITLE
moment.Duration & format

### ISSUE THREAD

**Issue by jochenjonc** [RSuter/NSwag#1496]
Hi,

I've just tested the changes made to NSwag to handle TimeSpan as moment.Duration in TypeScript (#1460) and there is still a problem in the toJSON function that get's generated.
The following `this.myTimeSpan.format('HH:mm:ss')` doesn't work, it seems that moment.Duration has no format function. It has been a long and ongoing discussion on the moment GitHub see [463](https://github.com/moment/moment/issues/463) & [1048](https://github.com/moment/moment/issues/1048).

The solution seems to be to create a moment.Moment and use format on that, it should be the following code: `moment.utc(this.myTimeSpan).format('HH:mm:ss')` or to use the [Moment Duration Format](https://momentjs.com/docs/#/plugins/duration-format/) plugin.

Anyway, an other problem is the loss of days & fractional seconds when doing the format back to Json. This can't be solved with the trick via `moment.utc`, and there the Moment Duration Format is needed.

```this.myTimeSpan.format('d.hh:mm:ss.SS')```

This should be conform the ASP.NET style time spans.

So I would suggest to change the format in code and to require the usage of the Moment Duration Format plugin. To install the plugin the following npm packages are needed:

```
npm install moment-duration-format
npm install --save-dev @types/moment-duration-format
```

And I needed to add the following import in the generated file, just after `import * as moment from 'moment';`:
```
import 'moment-duration-format';
```

I hoped there was an easier way, but after a lot of research it was the best I could come up with.

Regards,

Jochen

**Comment by RSuter** [comment]
So with `moment-duration-format` we only need to change format to `.format('d.hh:mm:ss.SS')`?

**Comment by jochenjonc** [comment]
Yes that's right.

**Comment by RSuter** [comment]
Can you update the MomentJS wiki with your finding and moment-duration-format requirements? That would be great...

https://github.com/RSuter/NSwag/wiki/SwaggerToTypeScriptClientGenerator#datetime-handling

**Comment by RSuter** [comment]
Ok, i think it's fine now..

**Comment by RSuter** [comment]
Wondering if we should add this import or you have to manually import it in extension code...

**Comment by jochenjonc** [comment]
In the NSwag code after the following line the extra import for moment-duration-format also needs to be added.
https://github.com/RSuter/NSwag/blob/2f5d7d35bdc07e76de09220d3f517d83eecbc9fc/src/NSwag.CodeGeneration.TypeScript/Templates/File.liquid#L55

But I'm not sure if there is a possibility to include the line only if TimeSpans are being generated? Because otherwise a lot of existing projects that don't use TimeSpan will have to install the moment-duration-format package.

**Comment by RSuter** [comment]
> But I'm not sure if there is a possibility to include the line only if TimeSpans are being generated? Because otherwise a lot of existing projects that don't use TimeSpan will have to install the moment-duration-format package.

Yep, that was also my concern...

**Comment by jochenjonc** [comment]
I think it isn't possible to import something globally in typescript and thus it has to be part of the file.

**Comment by RSuter** [comment]
Reopened until fixed in NSwag

**Comment by RSuter** [comment]
v11.18.1
