### ISSUE TITLE
responseType: 'Blob' ... trying to understand why

### ISSUE THREAD

**Issue by syska** [RSuter/NSwag#1497]
This is driving me crazy ... 

```
addNode(customer: string, parentNodeId: number, inputModel: AddNodeModel | null): Observable<ClientResponseOfListNodeModel | null> {
        let url_ = this.baseUrl + "/api/CadInformation/{customer}/{parentNodeId}";
        if (customer === undefined || customer === null)
            throw new Error("The parameter 'customer' must be defined.");
        url_ = url_.replace("{customer}", encodeURIComponent("" + customer)); 
        if (parentNodeId === undefined || parentNodeId === null)
            throw new Error("The parameter 'parentNodeId' must be defined.");
        url_ = url_.replace("{parentNodeId}", encodeURIComponent("" + parentNodeId)); 
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(inputModel);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json", 
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processAddNode(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processAddNode(<any>response_);
                } catch (e) {
                    return <Observable<ClientResponseOfListNodeModel | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<ClientResponseOfListNodeModel | null>><any>_observableThrow(response_);
        }));
    }
```

What are the reason for responseType being 'blob'? Size?

Trying to create an interceptor and it seems rather hacky to use the `blobToText` on the same object again ... 

Tried searching, but could not really find any useful information ... maybe I'm doing something wrong ... 

```
[HttpPost("{customer:guid}/{parentNodeId:int}")]
        public async Task<ClientResponse<ListNodeModel>> AddNode(Guid customer, int parentNodeId, [FromBody]AddNodeModel inputModel)
        {
           // snip ... 
            return new ClientResponse<ListNodeModel>(model, new ValidationMessage(true, $"Node added with name: '{model.Name}'.", string.Empty));
        }
```

It's working ... but this is driving me nuts ...

**Comment by RSuter** [comment]
The whole idea is to make code generation easier as blobs can be used for any response type... there are scenarios where a response returns a blob (file) and an unsuccessful response returns json (a dto)... is this an issue?

**Comment by syska** [comment]
@RSuter 

All my responses is json except one ... 

Just trying to understand why this was done ... :-) and since I could not find an answer searching the web. Going to the source seemed like the last option.

The only reason is that handeling the interceptors requires me to parse the response again ... since if it's a ClientResponse it might have information which needs to be shown in a toaster message, so I can handle it all in the same place ... 

BTW. NSwagStudio works now with the WorkingDirectory ... AWESOME.

But I see the reason why ... good to know, now my mind can relax again ...

**Comment by simeyla** [comment]
Just putting this here in case anyone else comes across this.

I had an issue today with `<link rel="preload" as="fetch" href="https://____" />` to load a very important dynamic JSON file as early as possible. When subsequently loading the data with nswag I get the error:

> A preload for 'https://_______' is found, but is not used because the new request loads the content as a blob.

Now, obviously to be able to construct the URL for my `<link rel="preload">` in the first place I must know the URL that I would otherwise be calling with my nswag Angular client. And of course it must be absolutely identical. So I think I'll probably have to bypass nswag entirely and just load that JSON file directly with Angular's HTTP client.

Probably nothing you could do. And probably safer this way so I can guarantee the URL matches.
