### ISSUE TITLE
Issue generating Clients where the controller have a route parameter, but not used in the method

### ISSUE THREAD

**Issue by syska** [RSuter/NSwag#1500]
Not sure if this is an issue ... using the API Explorer in nswag.

The route looks like this:
`/api/{language}/baskets/{basketId}`

`language` is used by aspnetcore to set the Culture

The controller looks like this:
```
    [Route("api/{language}/baskets")]
    public class BasketController : ApiControllerBase
    {
        private readonly IMediator _mediator;

        public BasketController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet("{basketId:guid}")]
        [ProducesResponseType(typeof(Basket), 200)]
        [ProducesResponseType(typeof(ValidationMessage[]), 400)]
        [ProducesResponseType(typeof(ForbiddenMessage), 403)]
        public async Task<IActionResult> GetBasket([FromRoute] Guid basketId)
        {
            var basket = await _mediator.Send(new GetBasket.Query(basketId));

            var newBasket = await _mediator.Send(new SaveBasket.Command(basket));

            return Json(newBasket);
        }
    }
```

The swagger file from swashbuckle looks like this:
![image](https://user-images.githubusercontent.com/317770/43550816-1cc79490-95e5-11e8-922e-386fb9ca97e9.png)

The client generated from with the API Explorer just removed the `{language}` parameter ... so the url ends up looking like `/api/baskets/{basketId}` ... and ofcause it can't hit the URL cause its missing the `{language}` part ... 

This works if we put the {language} parameter in the method signature ... is this by design? If it is ... and I can kind a understand why ... is there any way to overcome this somehow? We need this to set the Culture ... but with a MiddlewareFilter injected on all method before route action is performed ...

**Comment by RSuter** [comment]
@pranavkm is this something which is missing in api explorer?

**Comment by pranavkm** [comment]
This issue was moved to aspnet/Mvc#8192

**Comment by RSuter** [comment]
It seems that Swashbuckle has special logic to handle this case... 

until this is fixed directly in api explorer, we could implement a custom operation processor (running as one of the first processors) which adds this parameter to the params list...

**Comment by RSuter** [comment]
Maybe it's a problem in this line: 

https://github.com/RSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration.AspNetCore/Processors/OperationParameterProcessor.cs#L50

Maybe the parameter is exposed but has no type?

**Comment by RSuter** [comment]
It seems that the parameter is provided by api explorer but the type is null: 

![image](https://user-images.githubusercontent.com/2603405/43574605-f3680a66-9644-11e8-8e2f-624fc6db5879.png)

@pranavkm I think we can close the issue in aspnet and have to fix it here...

**Comment by RSuter** [comment]
Created a pr: https://github.com/RSuter/NSwag/pull/1501

**Comment by RSuter** [comment]
@syska does this look good to you? Logic: Treat implicit parameters without type as typeof(string) and not-nullable when they are path params...

**Comment by syska** [comment]
@RSuter This would be "awesome" ... satisfies our needs.

**Comment by RSuter** [comment]
v11.18.1
