### ISSUE TITLE
OpenAPI 3.0.0 - Support schema object

### ISSUE THREAD

**Issue by themultiplexer** [RSuter/NSwag#1503]
Types, formats and defaults of parameters should be stored in the new [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject).
Although SchemaType is set to OpenAPI3 it still uses the Swagger2 syntax for parameters.
I guess it is simply not implemented yet, but it is pretty important to me, because otherwise the UI displays **any** as the type of the parameter and the defaults are missing.

In Swagger 2.0 you could store types and defaults in the parameter directly:

```
"parameters": [{
            "type": "integer",
            "format": "int32",
            "default": 42,
            "name": "test",
            "in": "query",
            "description": "simple int"
          }]
```
but in OpenAPI 3.0.0 and up you have to use the schema object:
```
"parameters": [{
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 42
            },
            "name": "test",
            "in": "query",
            "description": "simple int"
          }]
```

**Comment by RSuter** [comment]
I think this has to be changed here: 

https://github.com/RSuter/NSwag/blob/fac99a7dbf5e610a8e772eee107f76bf93b9f169/src/NSwag.SwaggerGeneration/SwaggerGenerator.cs#L91

Do we **always** have to use "schema" in OAI3?

**Comment by themultiplexer** [comment]
Awesome! Thank you for your instant response!
I think so :/ ReDoc and Swagger Editor refuse to accept the old syntax...

**Comment by RSuter** [comment]
Hmm, it seems that the parameter object no longer “inherits” from the schema object in openapi 3. 

@darrelmiller can you confirm that?

**Comment by darrelmiller** [comment]
@RSuter Parameter now contains a complete schema object rather than inheriting a few properties.  Or if it contains a content object in theory it could have multiple schema objects.

**Comment by RSuter** [comment]
Another related commit: https://github.com/RSuter/NSwag/commit/89bb712d9b374633ad3de39ff694842db235e91f

@darrelmiller Ok, thanks for your response. Then we will always generate "schema" and no longer use schema properties on the parameter itself...

**Comment by RSuter** [comment]
BTW: This is very good decision as it makes spec handling much easier in OO languages :-)

**Comment by RSuter** [comment]
Created a follow up issue to clean this up: https://github.com/RSuter/NSwag/issues/1504

**Comment by RSuter** [comment]
Please test with v11.18.1

**Comment by darrelmiller** [comment]
@RSuter We did the same thing with Response Headers.  There's no way I wanted to have to define all those properties multiple times :-)
