### ISSUE TITLE
Post, Put and Delete Actions not using Controller Route in ASP.Net Core 2.1

### ISSUE THREAD

**Issue by gollumsluvslave** [RSuter/NSwag#1506]
I have some controllers each with a route attribute
E.g.

    [Route("api/contexts/{contextId}/[controller]")]
    [ApiController]
    public class VariablesController : CalcSvcControllerBase

All the get actions are getting the correct route url in the documentation, but Post, Put and Delete do not seem to pickup from the controller route:-
![image](https://user-images.githubusercontent.com/7115121/43648809-5c431708-9733-11e8-937e-c8f48d826179.png)

This obviously gives a 404 when using the try functionality.

Wondering if there is anything I have missed - it seems odd that Get is working fine.

ASP.Net Core 2.1 Web API, Nswag.AspNetCore Nuget Package 11.18.1

**Comment by RSuter** [comment]
UseSwagger*() or UseSwagger*WithApiExplorer()?

**Comment by gollumsluvslave** [comment]
Just figured this out - the Delete, Post and Put actions didn't have the contexId from the route as a parameter to the actions - the body already has that in a type.

D'oh.

All good now!
