### ISSUE TITLE
[C#] Question - Generate dictionary key as TS Enum type: { [key in keyof typeof EnumType] : SomeClass; }

### ISSUE THREAD

**Issue by popovsergii** [RSuter/NSwag#1507]
Generate dictionary key as Enum type like:

[TypeScript]
{[key in keyof typeof EnumType] : ClassType; }

I have on server a dictionary type (IDictionary<EnumType, ClassType>) as response result

Is there any way I can do that?

Thanks!

**Comment by RSuter** [comment]
I think that json schema does not support specifying a type/schema for the dictionary key... for that we’d need a custom extension.

**Comment by popovsergii** [comment]
Yea it's NJsonSchema,

Please take a look for a PR I'm suggesting
[patch.diff.txt](https://github.com/RSuter/NSwag/files/2261063/patch.diff.txt)

**Comment by RSuter** [comment]
How this does solve this problem? Can you create a PR in NJS?

**Comment by RSuter** [comment]
PR: https://github.com/RSuter/NJsonSchema/pull/755
