### ISSUE TITLE
Generated TypeScript files doesn’t compile with compiler setting “strict:” true

### ISSUE THREAD

**Issue by pekspro** [RSuter/NSwag#1509]
I tried to generate TypeScript files from the petstore swagger file (http://petstore.swagger.io/v2/swagger.json) with NSwagStudio 11.18.1.0. The generated files don’t compile with “strict”: true defined in the TypeScript configuration file:

	...
	  "compilerOptions": {
	    "strict": true,
	    "sourceMap": true,
	    "target": "es2015"
	  },
	...

It complains on functions that returns null where null can’t be returned and some other stuff.

Would be nice if that was supported :-) I’m using TypeScript 2.8.

**Comment by RSuter** [comment]
Did you change the typescript version to the latest available version?

**Comment by pekspro** [comment]
Yes, I selected version 2.7 (nswagstudio).

(Thanks for a super fast reply by the way :-)

**Comment by RSuter** [comment]
Can you post examples where the output is not strict compliant? (it seems TypeScript got stricter :-))

**Comment by pekspro** [comment]
I think a have solved the problem with functions returning null in JQueryCallbacks in #1542.

I haven’t been able to replicate the other problems. All others where related to Promises so I guess it was something in my system that caused these problems. Sorry about that :-)

**Comment by RSuter** [comment]
Can we close this one?

**Comment by RSuter** [comment]
BTW: You can test your custom templates by overriding them: https://github.com/RSuter/NSwag/wiki/Templates

**Comment by pekspro** [comment]
I’m guilty of this, I’m closing it myself :-)
