### ISSUE TITLE
Omitting ”export” in generated TypeScript-files

### ISSUE THREAD

**Issue by pekspro** [RSuter/NSwag#1515]
If I generate a TypeScript file in NSwagStudio with the following settings:

Swagger specification URL: http://petstore.swagger.io/v2/swagger.json
Module name: (empty)
TypeScript version: 2.7
Template: JQueryCallbacks

Then the generated output begins with this:

	import * as jQuery from 'jquery';
	
	export class Client {
	    baseUrl: string;
	    beforeSend: any = undefined;
	    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;
	
	    constructor(baseUrl?: string) {
	        this.baseUrl = baseUrl ? baseUrl : "https://petstore.swagger.io/v2";
	    }
	...
	
Since I’m not using modules (it just makes me confused… :-), is it somehow possible to omit the **export** keyword on all classes and interfaces? It would be nice to remove the first line that begins with **import** as well.

If **import** or **export** is used in a file TypeScript adds some stuff in the generated JavaScript files that browser complains about. Fairly easy to work around but would be nicer if it wasn’t necessary.

**Comment by RSuter** [comment]
The export keyword cannot be omitted with a setting, you can see that here: 
https://github.com/RSuter/NSwag/blob/master/src/NSwag.CodeGeneration.TypeScript/Templates/JQueryCallbacksClient.liquid#L10

But you can override the templates: 
https://github.com/RSuter/NSwag/wiki/Templates

**Comment by pekspro** [comment]
Thanks for another quick answer :-) I will have a look on that.

**Comment by pekspro** [comment]
If I wrote an PR that make the “export” keyword optional, would you accept that? I have looked on the source code and it seems to be feasible. As I understand it’s necessary to do some tweaks on the NJsonSchema too.

Not a big deal for me, but certainly an improvement :-). Would be easier to use than changing the templates locally.

**Comment by RSuter** [comment]
Yes, why not... I think we need to add a new setting (e.g. ExportTypes, default false) here: https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.TypeScript/TypeScriptGeneratorSettings.cs#L85

Add and handle it to the model in NJS and NSwag + add new config to command line + UI...

**Comment by pekspro** [comment]
I agree, it should be a setting for this. I will try to dig into this the following weekend. I hope I find all places where changed should be made :-)

**Comment by RSuter** [comment]
Expose the setting in this model and use it in all class templates: 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.TypeScript/Models/ClassTemplateModel.cs

After that we need to do the same in NSwag and update CLI and UI..

**Comment by RSuter** [comment]
Ref: https://github.com/RSuter/NJsonSchema/pull/762
