### ISSUE TITLE
"version" input parameter appeared in all operations with NSwag 11.18

### ISSUE THREAD

**Issue by srollinet** [RSuter/NSwag#1516]
Hi!

I updated NSwag.MSBuild from 11.17.21 to 11.18.2 and now in swagger.json the following parameter appeared in all the operations.

```
          {
            "type": "string",
            "name": "version",
            "in": "path",
            "required": true,
            "x-nullable": false
          }
```

Here is also the code of the generated typescript client

```
    getCameras(version: string): Observable<CameraDto[]> {
        let url_ = this.baseUrl + "/api/v1/Cameras";
        if (version === undefined || version === null)
            throw new Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version)); 
        .....
```
As you can sere, there is no {version} path parameter to replace.

If I rollback to version 11.17.21, the parameter disappears.

I will try to provide you a simplified sample project tomorrow if needed.

Thanks for your help!

**Comment by RSuter** [comment]
This is a regression of this commit: 
https://github.com/RSuter/NSwag/commit/d6690d7050b5a2229caa7c47e90ebcba47e20e77

And this issue:
https://github.com/RSuter/NSwag/issues/1500

I think we need to check whether the implicit path param is actually used in the route...

**Comment by RSuter** [comment]
How can we reproduce this in a test?

Like this:
https://github.com/RSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration.AspNetCore.Tests/LanguageParameterTests.cs

**Comment by srollinet** [comment]
The simplest for me is to provide you this sample project 
[nswag_version_issue.zip](https://github.com/RSuter/NSwag/files/2268943/nswag_version_issue.zip)

It has the same configuration:
- It uses ApiVersionning
- It has an abstract controller that defines the route and the default version "1"
- It has a controller, where I have to repeat the version otherwise the url contains {version}, but I don't want it. (I think this is related to another opened issue: #1288 )

**Comment by srollinet** [comment]
This problem appeared again in the last version (12.0.4) Is this on purpose?

here is an updated repro: [nswag_version_issue_2.zip](https://github.com/RSuter/NSwag/files/2648313/nswag_version_issue_2.zip)

if you execute `dotnet build` a 'version' input parameter is added on each method in swagger.json
