### ISSUE TITLE
Removing hostname doesn’t remove service scheme in TypeScript client generation

### ISSUE THREAD

**Issue by pekspro** [RSuter/NSwag#1517]
I’m using NSwagStudio 11.18.2.0. If I generate a TypeScript client for http://petstore.swagger.io/v2/swagger.json with the default settings the generated client starts like this:
	
	export class Client {
	    baseUrl: string;
	    beforeSend: any = undefined;
	    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;
	
	    constructor(baseUrl?: string) {
	        this.baseUrl = baseUrl ? baseUrl : "https://petstore.swagger.io/v2";
	    }

If I change the service host name in the setting to ‘.’ the generated code will then instead be:

	export class Client {
	    baseUrl: string;
	    beforeSend: any = undefined;
	    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;
	
	    constructor(baseUrl?: string) {
	        this.baseUrl = baseUrl ? baseUrl : "https:///v2";
	    }

**https:///v2** is not a valid URL :-/ Shouldn’t **https://** be removed as well so the default URL will only be **/v2**?

(Btw, this is my third issue in a really short time. I’m sorry about that, I just really like this tool :-)

**Comment by RSuter** [comment]
Please retest with v11.18.5

**Comment by pekspro** [comment]
Thanks! But it didn’t work :-( Same result as before.

I have an idea what is wrong. The change you did affects the swagger generation. But the setting **Service host** is specific for the TypeScript generation. Maybe… Not sure how things are put together :-)

**Comment by pekspro** [comment]
It does work if I use the petstore specification URL:
http://petstore.swagger.io/v2/swagger.json

But not the URL generated in my application:
https://localhost:44330/swagger/v1/swagger.json

That specification starts with:

	  "x-generator": "NSwag v11.18.5.0 (NJsonSchema v9.10.67.0 (Newtonsoft.Json v11.0.0.0))",
	  "swagger": "2.0",
	  "info": {
	    "title": "My Title",
	    "version": "1.0.0"
	  },
	  "host": "localhost:44330",
	  "schemes": [
	    "https"
	  ],
	  "consumes": [
	    "application/json"
	  ],
