### ISSUE TITLE
Nullable properties are required in swagger.json

### ISSUE THREAD

**Issue by Kahbazi** [RSuter/NSwag#1519]
I'm using `UseSwaggerUi3WithApiExplorer` and `Page` and `PageSize` inputs are set as required in swagge.json.

Shouldn't they be optional since they are nullable?
How Can I make them optional? 

I don't want to bring them out of GetListCommand

    [HttpGet]
    public ActionResult GetList([FromQuery]GetListCommand getListCommand)
    {
        return Ok(await _mediator.Send(getListCommand));
    }

    public class GetListCommand
    {
        public int? Page { get; set; }
        public int? PageSize { get; set; }
    }

**Comment by RSuter** [comment]
I have created a PR with the tests and of course it fails: 

![image](https://user-images.githubusercontent.com/2603405/43850772-24a7200a-9b39-11e8-8bf5-21e50c41cc32.png)

PR: https://github.com/RSuter/NSwag/pull/1521

@pranavkm Is there a way to mark query parameters of complex types as optional like you can do that in simple parameters (`int? page = null`)? Of course `public int? Page { get; set; } = 0;` does not work because this cannot be inspected with reflection...

**Comment by Kahbazi** [comment]
Can you decide based on the Nullable type? if it's Nullable, it's optional

**Comment by RSuter** [comment]
The "problem" (or good thing) is that this is not implemented in NSwag but in API Explorer (ASP.NET Core)...

**Comment by Kahbazi** [comment]
Can we solve it by checking if the Type is nullable in here
https://github.com/RSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration.AspNetCore/Processors/OperationParameterProcessor.cs#L303

**Comment by RSuter** [comment]
Just a remark: `[DefaultValue(null)]` on the property is also ignored...

**Comment by pranavkm** [comment]
We added a `IsRequired` property to `ApiParameterDescriptor` in 2.2 that essentially checks if there's an annotation that marks that the parameter is required (https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Abstractions/ApiExplorer/ApiParameterDescription.cs#L45-L56). Perhaps that's what the processor should use and fallback to the same heuristics for 2.1 or earlier.

**Comment by RSuter** [comment]
Where can i find the heuristics for <=2.1?

**Comment by pranavkm** [comment]
@RSuter - essentially duplicating this bit: https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.ApiExplorer/DefaultApiDescriptionProvider.cs#L319-L332.

**Comment by RSuter** [comment]
@pranavkm Thanks for your replies. Can you quickly review the PR? Does it look good like that?

https://github.com/RSuter/NSwag/pull/1521
