### ISSUE TITLE
Swagger should use JsonSerializerSettings configured in MVC

### ISSUE THREAD

**Issue by AccessViolator** [RSuter/NSwag#1520]
I add Swagger conditionally based on environment (keep it disabled in prod), and found that adding Swagger screws up JsonSerializerSettings configured by AddJsonOptions()

**Comment by RSuter** [comment]
Screws up the settings? How? I think it should only read it, assignment here: 

https://github.com/RSuter/NSwag/blob/master/src/NSwag.AspNetCore/Middlewares/AspNetCoreToSwaggerMiddleware.cs#L90

**Comment by AccessViolator** [comment]
Specifically I noticed effect that adding StringEnumConverter would give.

**Comment by AccessViolator** [comment]
I add swagger via ApiExplorer, if it matters...

**Comment by RSuter** [comment]
Please explain this a little bit more, what are the effects? Sample?

**Comment by AccessViolator** [comment]
This is embarrassing, but now after reenabling the swagger I can't reproduce it myself :) 
The problem was that enum values were serialized as strings instead of numbers.

**Comment by AccessViolator** [comment]
Gonna reopen if this reappears.
