### ISSUE TITLE
Swagger 2 - Enum: Type Parameter Missing

### ISSUE THREAD

**Issue by themultiplexer** [RSuter/NSwag#1527]
In Swagger 2 Schema the type property is missing (https://editor.swagger.io even shows it as an error):

```
"parameters": [
          {
            "name": "logLevelType",
            "in": "path",
            "required": true,
            "description": "Debug, Information, Warning, Error, HealthIssue",
            "x-schema": {
              "$ref": "#/definitions/LogLevelType"
            },
            "x-nullable": false,
            "enum": [
              0,
              1,
              2,
              3,
              4
            ]
          }, ...
              ]
```

`"type": "integer"` should be in there. I tried explictly typing the enum but it didn't work.

`public enum LogLevelType : int`

As it works as expected in OpenAPI 3 Specification Version I guess it is not my fault.

**Comment by RSuter** [comment]
In v11.18.4 soon (next hour)
