### ISSUE TITLE
RxJs6 - Unused TypeScript imports cause problems with --noUnusedLocals flag

### ISSUE THREAD

**Issue by bwoodle** [RSuter/NSwag#1533]
We're in the process of updating to Angular 6 and RxJs 6 and we've pulled the latest NSwag build and set "rxJsVersion": 6.0 in our swaggerToTypescriptClient.

The following import line in the generated client is failing the --noUnusedLocals flag.

    //     Generated using the NSwag toolchain v11.18.3.0 (NJsonSchema v9.10.67.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)

    [...]

    import { Observable, from as _observableFrom, throwError as _observableThrow, of as _observableOf } from 'rxjs';

With the error:

    TS6133: '_observableFrom' is declared but its value is never read.

Here is the TypeScript portion of the NSwag config file:

    "swaggerToTypeScriptClient": {
      "className": "{controller}Client",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 2.7,
      "template": "Angular",
      "promiseType": "Promise",
      "httpClass": "HttpClient",
      "useSingletonProvider": false,
      "injectionTokenType": "InjectionToken",
      "rxJsVersion": 6.0,
      "dateTimeType": "MomentJS",
      "nullValue": "Null",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateOptionalParameters": false,
      "wrapDtoExceptions": false,
      "wrapResponses": false,
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "useTransformOptionsMethod": false,
      "useTransformResultMethod": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "markOptionalProperties": true,
      "generateCloneMethod": false,
      "typeStyle": "Class",
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "handleReferences": false,
      "generateConstructorInterface": true,
      "convertConstructorInterfaceData": false,
      "importRequiredTypes": true,
      "useGetBaseUrlMethod": false,
      "baseUrlTokenName": "API_BASE_URL",
      "queryNullValue": "",
      "output": "../../../Angular/libs/generated/WebAPIv1.ts"
    }

I'm assuming there are scenarios where observableFrom is exercised but our particular case isn't generating code that exercises it.  If the import cannot be removed is there any solution for altering it or potentially adding `// @ts-ignore` above that line?

**Comment by RSuter** [comment]
You can alter/enhance templates here: https://github.com/RSuter/NJsonSchema/wiki/Templates

Is just adding `// @ts-ignore` an option to avoid all such problems? :-)

**Comment by bwoodle** [comment]
Thank you for the quick reply!

For posterity, the template which controls imports is here: https://github.com/RSuter/NSwag/blob/master/src/NSwag.CodeGeneration.TypeScript/Templates/File.liquid

I was able to add `"templateDirectory": "./templates",` to the swaggerToTypeScriptClient section and modify the template in that directory to remove the import.

As to `// @ts-ignore` my expectations of generated code are a little lower than code written by developers :)

**Comment by RSuter** [comment]
Didnt know you can now disable these compiler errors... i see it the same, for generated code it should be fine and keeps the generator simpler :-)
