### ISSUE TITLE
How to set https?

### ISSUE THREAD

**Issue by doghappy** [RSuter/NSwag#1545]
I used NSwag to generate Api documents. my website protocol is `https`, but NSwag still uses `http`

![image](https://user-images.githubusercontent.com/20038914/44448321-82970d80-a61d-11e8-862b-08ea46727064.png)

**Comment by RSuter** [comment]
The scheme is set to the one from the request: 
https://github.com/RSuter/NSwag/blob/master/src/NSwag.AspNetCore/Middlewares/AspNetCoreToSwaggerMiddleware.cs#L96

You can change this in a PostProcess action or document processor (settings).

**Comment by skorunka** [comment]
NSwag v12 `app.UseSwagger(configure => configure.PostProcess = (document, _) => document.Schemes = new[] { SwaggerSchema.Https });`

**Comment by rockstardev** [comment]
@RicoSuter I've tired with `PostProcess` in `AddSwaggerDocument` and it did nothing. Only when I switched to:

```
app.UseOpenApi(a => {
	a.PostProcess = (document, _) => {
		document.Schemes = new[] { OpenApiSchema.Https, OpenApiSchema.Http };
	};
});
```

Did I get this to work. What's the difference?

**Comment by RicoSuter** [comment]
Change this in UseSwagger() or UseOpenApi..

**Comment by rockstardev** [comment]
@RicoSuter I'm asking because in previous comment (https://github.com/RicoSuter/NSwag/issues/1545#issuecomment-444098812) you are saying:

`Please post process in AddSwaggerDocument and not in UseSwagger`

So I was just wondering on rational/why behind it back then. Thanks!

**Comment by RicoSuter** [comment]
When running via cli then only AddSwaggerDocument is called, when starting in as regular asp app the both are called and the url/https stuff is overwritten in the use() call with the actual endpoint info and thus this has to be changed there. The document itself (except endpoint info) should be changed in add()

**Comment by Saibamen** [comment]
Why Swagger can't call HTTP when you are entering http://bla.example.com/swagger/ and HTTPS when entering from https://bla.example.com/

If I set `document.Schemes = new[] { OpenApiSchema.Https, OpenApiSchema.Http };`, I can't use Swagger on localhost...
