### ISSUE TITLE
How I can specify the fetch options?

### ISSUE THREAD

**Issue by jiehu567** [RSuter/NSwag#1560]
Hi, I'm using Typescript, and nswag to generate API client, however, to support CORS I have to specify manually in each of the API call with credentials: "include".

```
let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            **mode: 'cors',
            credentials: "include",**
            headers: {
                "CorrelationId": correlationId !== undefined && correlationId !== null ? "" + correlationId : "", 
                "Content-Type": "application/json", 
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processConversation(_response);
        });
```

Might I know if there's options to set with commandline?

My command line is like:

`nswag swagger2tsclient /input:swagger.json /output:./gen/index.ts /ExtensionCode:./base/extension.ts /ClientBaseClass:BaseClient /UseGetBaseUrlMethod:true /GenerateOptionalParameters:true`

**Comment by RSuter** [comment]
You can set the UseTransformOptionsMethod (or similar)

**Comment by jiehu567** [comment]
Thanks @RSuter , It works! I add transformOptions method in my BaseClient, and reset the options as return. 
We were using window.fetch override to handle this but setting as yours is much more scalable way!
Thanks
