### ISSUE TITLE
Generated code from nswagstudio for Angular6 throws The requested resource does not support http method 'OPTIONS' on httpGet

### ISSUE THREAD

**Issue by roscoedeemarutam** [RSuter/NSwag#1563]
Hi, 

I Generated my angular 6 service from the nswagstudio but when I do a get request I get 
"The requested resource does not support http method 'OPTIONS'"

Is there something missing in the generated code? Can anyone point me in the right direction of this error? 

/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.18.7.0 (NJsonSchema v9.10.70.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, from as _observableFrom, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

import * as moment from 'moment';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable({
    providedIn: 'root'
})
export class DossierWebConsultatieService {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    getDossier(dossierId: string | null, isExcludedBroker?: boolean | undefined): Observable<DossierWCModel | null> {
        let url_ = this.baseUrl + "/web/api/DossierWebConsultatie/GetDossier?";
        if (dossierId === undefined)
            throw new Error("The parameter 'dossierId' must be defined.");
        else
            url_ += "dossierId=" + encodeURIComponent("" + dossierId) + "&"; 
        if (isExcludedBroker === null)
            throw new Error("The parameter 'isExcludedBroker' cannot be null.");
        else if (isExcludedBroker !== undefined)
            url_ += "isExcludedBroker=" + encodeURIComponent("" + isExcludedBroker) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json", 
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetDossier(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetDossier(<any>response_);
                } catch (e) {
                    return <Observable<DossierWCModel | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<DossierWCModel | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetDossier(response: HttpResponseBase): Observable<DossierWCModel | null> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <DossierWCModel>JSON.parse(_responseText, this.jsonParseReviver);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<DossierWCModel | null>(<any>null);
    }
}

export interface DossierWCModel {
    olderThen3Years: boolean;
    hasDelayedSteps: boolean;
    fullDossierNr?: string | undefined;
    fullPolisNr?: string | undefined;
    keyExternalDossier?: string | undefined;
    licensePlate?: string | undefined;
    incidentLocation?: string | undefined;
    beheerder?: string | undefined;
    klantNaam?: string | undefined;
    telMakelaar?: string | undefined;
    emailMakelaar?: string | undefined;
    faxMakelaar?: string | undefined;
    notabladi?: string | undefined;
    notablad?: string | undefined;
    datumOngeval?: string | undefined;
    datumAangifteEuromex?: string | undefined;
    oldDossierNr?: string | undefined;
    dossierNr?: string | undefined;
    polisNr?: string | undefined;
    datumGeregeld?: string | undefined;
    parties?: DossierPartyWCModel[] | undefined;
    scheme?: DossierSchemeWCModel | undefined;
}

export interface DossierPartyWCModel {
    name?: string | undefined;
    address?: AddressDTO | undefined;
    relations?: DossierPartyWCModel[] | undefined;
    email?: string | undefined;
    fax?: string | undefined;
    mobile?: string | undefined;
    phone?: string | undefined;
    referte?: string | undefined;
    klantNummer?: string | undefined;
    typePartij?: string | undefined;
    typePartijRow?: string | undefined;
    scheme?: DossierSchemeWCModel | undefined;
}

export interface AddressDTO {
    busNr?: string | undefined;
    city?: string | undefined;
    country?: string | undefined;
    houseNr?: string | undefined;
    postalCode?: string | undefined;
    street?: string | undefined;
}

export interface DossierSchemeWCModel {
    datumAanvang: moment.Moment;
    datumEinde?: moment.Moment | undefined;
    steps?: DossierStepWCModel[] | undefined;
    dossierParties?: DossierPartyBaseWCModel[] | undefined;
}

export interface DossierStepWCModel {
    vrijstap?: string | undefined;
    name?: string | undefined;
    nameRow?: string | undefined;
    datumGepland?: string | undefined;
    datumUitgevoerd?: string | undefined;
    notablad?: string | undefined;
}

export interface DossierPartyBaseWCModel {
    name?: string | undefined;
    klantNummer?: string | undefined;
}

export class SwaggerException extends Error {
    message: string;
    status: number; 
    response: string; 
    headers: { [key: string]: any; };
    result: any; 

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if(result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader(); 
            reader.onload = function() { 
                observer.next(this.result);
                observer.complete();
            }
            reader.readAsText(blob); 
        }
    });
}

Nswag config:

{
  "runtime": "Default",
  "defaultVariables": null,
  "swaggerGenerator": {
    "webApiToSwagger": {
      "controllerNames": [
        "Euromex.Web.Controller.Webconsultatie.DossierWebConsultatieController"
      ],
      "isAspNetCore": false,
      "defaultUrlTemplate": "api/{controller}/{id?}",
      "addMissingPathParameters": false,
      "defaultPropertyNameHandling": "CamelCase",
      "defaultReferenceTypeNullHandling": "Null",
      "defaultEnumHandling": "Integer",
      "flattenInheritanceHierarchy": false,
      "generateKnownTypes": false,
      "generateXmlObjects": false,
      "generateAbstractProperties": false,
      "ignoreObsoleteProperties": false,
      "allowReferencesWithProperties": true,
      "excludedTypeNames": [],
      "serviceHost": null,
      "serviceBasePath": null,
      "serviceSchemes": [],
      "infoTitle": "DossierWebConsultatieController",
      "infoDescription": "The Dossier controller for the Web consultation app",
      "infoVersion": "1.0.0",
      "includedVersions": null,
      "documentTemplate": null,
      "documentProcessorTypes": [],
      "operationProcessorTypes": [],
      "typeNameGeneratorType": null,
      "schemaNameGeneratorType": null,
      "contractResolverType": null,
      "serializerSettingsType": null,
      "output": "../Content/Swagger specs/DossierWebConsultatieControllerSpec.json",
      "outputType": "Swagger2",
      "assemblyPaths": [
        "../bin/Euromex.Web.dll"
      ],
      "assemblyConfig": "../Web.config",
      "referencePaths": []
    }
  },
  "codeGenerators": {
    "swaggerToTypeScriptClient": {
      "className": "{controller}Service",
      "moduleName": "DossierWebConsultatie",
      "namespace": "DossierServices",
      "typeScriptVersion": 2.7,
      "template": "Angular",
      "promiseType": "Promise",
      "httpClass": "HttpClient",
      "useSingletonProvider": true,
      "injectionTokenType": "OpaqueToken",
      "rxJsVersion": 6.0,
      "dateTimeType": "MomentJS",
      "nullValue": "Undefined",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateOptionalParameters": true,
      "wrapDtoExceptions": false,
      "clientBaseClass": null,
      "wrapResponses": false,
      "wrapResponseMethods": [],
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "protectedMethods": [],
      "configurationClass": null,
      "useTransformOptionsMethod": false,
      "useTransformResultMethod": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "markOptionalProperties": true,
      "generateCloneMethod": false,
      "typeStyle": "Interface",
      "classTypes": [],
      "extendedClasses": [],
      "extensionCode": null,
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "handleReferences": false,
      "generateConstructorInterface": true,
      "convertConstructorInterfaceData": true,
      "importRequiredTypes": true,
      "useGetBaseUrlMethod": false,
      "baseUrlTokenName": "API_BASE_URL",
      "queryNullValue": "",
      "templateDirectory": null,
      "typeNameGeneratorType": null,
      "propertyNameGeneratorType": null,
      "enumNameGeneratorType": null,
      "serviceHost": null,
      "serviceSchemes": null,
      "output": "../../Euromex.WebConsultatie/src/app/services/Generated/DossierWebConsultatie.WebApi.Generated.Service.ts"
    }
  }
}

thx in advance,
R

**Comment by roscoedeemarutam** [comment]
I had a mistake in my baseurl mapping. Fixed now!

**Comment by RSuter** [comment]
Can we close this issue then?

**Comment by roscoedeemarutam** [comment]
absolutely!
