### ISSUE TITLE
Possible API version mismatch in swagger generated HTML

### ISSUE THREAD

**Issue by OculiViridi** [RSuter/NSwag#1565]
Using the following configuration, I get those results in the swagger HTML.

NSwag configuration

```
public static void UseSwagger(this IApplicationBuilder app)
{
	string title = "My Control API";
	string description = "My API for Core functionalities.";

	app.UseSwaggerWithApiExplorer(config =>
	{
		config.GeneratorSettings.OperationProcessors.TryGet<ApiVersionProcessor>().IncludedVersions = new[] { "1.0" };
		config.SwaggerRoute = "v1.0.json";

		config.GeneratorSettings.Title = title;
		config.GeneratorSettings.Description = description;
	});

	app.UseSwaggerWithApiExplorer(config =>
	{
		config.GeneratorSettings.OperationProcessors.TryGet<ApiVersionProcessor>().IncludedVersions = new[] { "2.0" };
		config.SwaggerRoute = "v2.0.json";

		config.GeneratorSettings.Title = title;
		config.GeneratorSettings.Description = description;
	});

	app.UseSwaggerUi3(config =>
	{
		config.SwaggerRoutes.Add(new SwaggerUi3Route("v1.0", "/v1.0.json"));
		config.SwaggerRoutes.Add(new SwaggerUi3Route("v2.0", "/v2.0.json"));
	});
}
```

HTML Pages

When selecting version v1, the tag on the top-right of the API title shows 1.0.0.

![nswag version problem 1](https://user-images.githubusercontent.com/42179710/44836076-458ed480-ac36-11e8-826e-5d56a0ef8826.png)

When selecting version v2, the tag **keeps showing 1.0.0**.

![nswag version problem 2](https://user-images.githubusercontent.com/42179710/44836087-4aec1f00-ac36-11e8-8d51-acf1c5cf6287.png)

Should that version tag be related to API version or what?

**Comment by RSuter** [comment]
Left: `config.SwaggerRoute = "v1.0.json";`
Middle: `config.GeneratorSettings.Version = "1.0.0";`
Right: `config.SwaggerRoutes.Add(new SwaggerUi3Route("v1.0"...`

**Comment by OculiViridi** [comment]
Updated my code! Thank you!
