### ISSUE TITLE
axios

### ISSUE THREAD

**Issue by ZhaoRd** [RSuter/NSwag#1572]
now ,  axios  support  typescript  ,  how  can I  create  a  axios  client ?

**Comment by RSuter** [comment]
Ref: https://github.com/RSuter/NSwag/issues/1103

**Comment by thijscrombeen** [comment]
Please take a look at my pull request

#1945

**Comment by RSuter** [comment]
PR merged and will be available soon in v12.0.14, thanks @thijscrombeen for the PR! Please open new specific issues when there are problems with the axios template...

Release PR: https://github.com/RSuter/NSwag/pull/1945
