### ISSUE TITLE
Assembly parameter value for nswag aspnetcore2swagger command 

### ISSUE THREAD

**Issue by older** [RSuter/NSwag#1573]
I'm trying to use latest version of nswag (11.18.7 at the moment) from msbuild in asp.net core project (netcoreapp2.1) and aspnetcore2swagger command just doesn't work. Error is always **System.IO.FileNotFoundException** no matter if I use full assembly path, relative path from project folder or just assembly name. I'm using it the way it is recommended in the documentation for .NET Core projects:

```
  <Target Name="NSwag" AfterTargets="Build">
    <Copy SourceFiles="@(ReferencePath)" DestinationFolder="$(OutDir)References" />
    <Message Importance="high" Text="Run '$(NSwagExe_Core21) aspnetcore2swagger /assembly:$(OutDir)$(AssemblyName).dll'" />
    <Exec Command="$(NSwagExe_Core21) aspnetcore2swagger /assembly:$(OutDir)$(AssemblyName).dll" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>
```

If I just replace **aspnetcore2swagger** command with **webapi2swagger** without making any other changes - it works perfectly.

**Comment by RSuter** [comment]
Im currently fighting (again) with the assembly loader, hope to find a fix for that soon...

**Comment by RSuter** [comment]
Can you retry with v11.19.0?

**Comment by RSuter** [comment]
+ you shouldnt use webapi2swagger as this generator will not be supported eventually... we need to get aspnetcore2swagger running in all scenarios... please try aspnetcore2swagger with a project (and not assembly) + nobuild true when running from csproj

**Comment by older** [comment]
1. Tried with  v11.19.0 by replacing **webapi2swagger** with **aspnetcore2swagger** in my `csproj` file but got the same error as with the previous version:
```Could not load file or assembly 'C:\Path\To\My\Project\bin\Debug\netcoreapp2.1\bin\Debug\netcoreapp2.1\MyProjectOutputAssembly.dll'.```
So it looks like it repeats `bin\Debug\netcoreapp2.1` twice unlike **webapi2swagger** does.

1. Also tried with a project instead of assembly as you suggested. Here's what I put in my `csproj` file:
```
  <Target Name="NSwag" AfterTargets="Build">
    <Copy SourceFiles="@(ReferencePath)" DestinationFolder="$(OutDir)References" />
    <Exec Command="$(NSwagExe_Core21) aspnetcore2swagger /nobuild:true /project:$(MSBuildProjectFile) /output:$(OutDir)swagger.json" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>
```
but then I get this:
```System.InvalidOperationException: aspnet2swaggercommand requires the entry point type MyApp.Program to have either an BuildWebHost or CreateWebHostBuilder method. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x for suggestions on ways to refactor your startup type.```
and MyApp.Program does have CreateWebHostBuider method:
```
        public static IWebHostBuilder CreateWebHostBuider(string[] args) =>
                WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
```

**Comment by RSuter** [comment]
Can you provide a sample project to repro this?

**Comment by older** [comment]
I tried to reproduce an error with **aspnetcore2swagger** and _/project_ parameter and found that I had typo in CreateWebHostBuilder method name (it was manually updated from ASP.NET Core pre 2.1), when I fixed this - everything works.

But I could reproduce error with _/assembly_ parameter. Do you need sample project for this?

**Comment by RSuter** [comment]
There are some problems with .NET Core 2.0 + assembly loading - but with 2.1 it works for my sample project. It would be great to have this failing sample project....

**Comment by older** [comment]
1. Here's sample project: [aspnetcore2swagger.zip](https://github.com/RSuter/NSwag/files/2360744/aspnetcore2swagger.zip) demonstrating error with _/assembly_ parameter.

1. Strangely enough, while _/project_ parameter worked when I built it in Visual Studio, it didn't work in VSTS build and I've got this:
```
System.InvalidOperationException: Project outputs could not be located in 'D:\a\1\s\src\MyProject\bin\Debug\netcoreapp2.1\'. Ensure that the project has been built.
```
Here's relevant part of VSTS log: [vsts.log](https://github.com/RSuter/NSwag/files/2360767/vsts.log)

**Comment by RSuter** [comment]
You need to set /nobuild=false

**Comment by older** [comment]
But then I get infinite building loop when I build locally in Visual Studio.

**Comment by RSuter** [comment]
Ok, yes when executed within csproj you need to set nobuild=true, but maybe you need to also change the configuration to release: /configuration=Release because you probably build in Release mode on VSTS?

**Comment by RSuter** [comment]
Assembly load should be fixed with this commit: https://github.com/RSuter/NSwag/commit/c1f8fa998391fe40153d965a34b80d8d1f8164fb

**Comment by RSuter** [comment]
Just releasing v11.19.1 with this fix, please retry with that

**Comment by older** [comment]
Seem to be working fine now. Thanks!

**Comment by matthewz0584** [comment]
Same here with the "bin\Debug\netcoreapp2.1" doubled. And even when I made it find the assembly somehow it halted with "Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfiguration'" exception.

Then I literally copied the recommended snippet from [here](https://github.com/RicoSuter/NSwag/wiki/MSBuild) which uses nswag.json instead of command line parameters and all the trouble magically went away.

**Comment by EspressoBeans** [comment]
> Workaround for now. Putting `$(ProjectDir)\bin\debug\netcoreapp2.2`

@simeyla, can you help me with where and how you defined ProjectDir variable?  - Or is it already a canned variable?  When I use it I get an error System.UnauthorizedAccessException: Access to the path 'C:\Users\espressobeans\Application Data' is denied.
