### ISSUE TITLE
minLength for references

### ISSUE THREAD

**Issue by SebastianStehle** [RSuter/NSwag#1574]
Hi,

I posted a bug to the redoc repository, that my swagger definition does not work with the newest alpha.

https://github.com/Rebilly/ReDoc/issues/631

And I got the following answer:
----
I checked it out and it is caused by the following pattern which is used in multiple places in your spec:

```
{
  "description": "The field properties.",
  "minLength": 1,
  "allOf": [
    {
      "$ref": "#/definitions/FieldPropertiesDto"
    }
  ]
}
```

Can you explain, why there is a minLength property?

My json: https://www.dropbox.com/s/g0szlu37n9qlyy1/swagger.json?dl=0

**Comment by RSuter** [comment]
Indeed, doesnt make much sense. Can you post the property code and the dto code?

**Comment by RSuter** [comment]
Ah its probably a property with [Required] and not of thype string, right?

**Comment by SebastianStehle** [comment]
Yes, exactly:

        /// <summary>
        /// The schema properties.
        /// </summary>
        [Required]
        public SchemaPropertiesDto Properties { get; set; }

**Comment by RSuter** [comment]
Ok yes, this is a bug... - the MinLength should only be generated for required string properties. Is it correct that you'd expect that this property is not set on this property? Is redoc failing completely because of this?

**Comment by SebastianStehle** [comment]
Yes and yes, but others validators don't care, it is only redoc.

**Comment by SebastianStehle** [comment]
Thanks, will this be published to nuget automatically?

**Comment by RSuter** [comment]
Not really, I need to release a new NJS version und update the packages in NSwag and release that too... is this urgent?

**Comment by SebastianStehle** [comment]
No, it is fine, just a question.
