### ISSUE TITLE
Diffrent generation in app.UseSwaggerUiWithApiExplorer(..); vs app.UseSwaggerUi(..)

### ISSUE THREAD

**Issue by Chrille79** [RSuter/NSwag#1580]
If you have an action like

```c#
[HttpGet("[action]")]
public async Task<string> Test([FromHeader] string apa)
{
           ...
}
```

"apa" parameters get required in UseSwaggerUiWithApiExplorer
and optional in UseSwaggerUi (correct)

I belive the error is in `OperationParameterProcessor.IsNullable` because `Nullable.GetUnderlyingType(typeof(string)) == null`

**Comment by RSuter** [comment]
The behavior has changed slightly (reverted) in v.18.19.0, are you using that?

Related https://github.com/RSuter/NSwag/issues/1556

/cc @pranavkm

**Comment by Chrille79** [comment]
We are using NSwag.AspNetCore v11.19.0

**Comment by RSuter** [comment]
I think if you set it to null `Test([FromHeader] string apa = null)` it is optional...

**Comment by Chrille79** [comment]
Nope still required

**Comment by RSuter** [comment]
This line probably has to be removed: 
https://github.com/RSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration.AspNetCore/Processors/OperationParameterProcessor.cs#L118

Then this will take effect: 
https://github.com/RSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration.AspNetCore/Processors/OperationParameterProcessor.cs#L344

**Comment by pranavkm** [comment]
> This line probably has to be removed:
> https://github.com/RSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration.AspNetCore/Processors/OperationParameterProcessor.cs#L118

That looks correct.

**Comment by RSuter** [comment]
@Chrille79  Is this ok?

        public ActionResult MyAction([FromHeader] string required, [FromHeader] string optional = null)

**Comment by Chrille79** [comment]
` public ActionResult MyAction([FromHeader] string required, [FromHeader] string optional = null)`
Results in diffrent rendering between UseSwaggerUiWithApiExplorer and UseSwaggerUi.
Maybe a better way is 
` public ActionResult MyAction([Required][FromHeader] string required, [FromHeader] string optional)`
Then you get the same rendering for both UseSwaggerUiWithApiExplorer and UseSwaggerUi.

**Comment by RSuter** [comment]
The main problem here is that this information should be (correctly) provided by API Explored and not be implemented in NSwag at all. 

I think there is no way that UseSwaggerUiWithApiExplorer (AspNetCoreToSwaggerGenerator) and UseSwaggerUi (WebApiToSwaggerGenerator) will yield the same results (mainly because UseSwaggerUi may be implemented in a wrong way). 

UseSwaggerUi will be deprecated eventually and for ASP.NET Core you should only use UseSwaggerUiWithApiExplorer() + we need to provide the best experience there... 

/cc @pranavkm @rynowak

**Comment by Chrille79** [comment]
I see, but both
`public ActionResult MyAction([FromHeader] string required, [FromHeader] string optional = null)` are optional in asp.net core MVC viewpoint. But the RequiredAttribute does make it required!?

**Comment by RSuter** [comment]
I think API Explorer does not process the RequiredAttribute for params...
