### ISSUE TITLE
Change default value in example json output 

### ISSUE THREAD

**Issue by wesley-pattison** [RSuter/NSwag#1589]
Hi,

Is there a way to override the value that is displayed in the json output for ‘Example value’?

I have a constant that I want to be displayed, but instead it generates the value ‘string’. 

I have also tried to use an enum but I can only get the first value to ever appear. 

Using the DefaultValue attribute does nothing either.

**Comment by wesley-pattison** [comment]
I was able to achieve this by using a SchemaProcessor that looks for a DefaultValueAttribute on the type coming in. If present, it will set the Example object property for the property that has the DefaultValueAttribute over it.

**Comment by nallejacobsson** [comment]
@wesley-pattison @kyurthich Any SchemaProcessor-samples available? Thanks!
