### ISSUE TITLE
NSwag.MSBuild 11.12.11 broke the ArrayType setting

### ISSUE THREAD

**Issue by stijnherreman** [RSuter/NSwag#1595]
I'm using the sample petstore specification from https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore.json

I'm using the following build target:

```xml
<Target Name="GenerateClientWithNSwag" AfterTargets="Build">
  <Exec Command="$(NSwagExe) swagger2csclient /input:swagger.json /classname:Client /arraytype:System.Collections.Generic.List /output:Client.cs" />
</Target>
```

When using NSwag.MSBuild 11.12.10, code like this is generated:

```cs
public System.Threading.Tasks.Task<System.Collections.Generic.List<Pet>> ListPetsAsync(int? limit)
{
    return ListPetsAsync(limit, System.Threading.CancellationToken.None);
}
```

When using NSwag.MSBuild 11.12.11, code like this is generated:

```cs
public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Pet>> ListPetsAsync(int? limit)
{
    return ListPetsAsync(limit, System.Threading.CancellationToken.None);
}
```

This regression is still present in the current 11.19.1 version.

**Comment by RSuter** [comment]
I think for that you need to change the ReponseArrayType setting: 

![image](https://user-images.githubusercontent.com/2603405/45352129-196d3f00-b5b8-11e8-853f-1f3efab5131f.png)

**Comment by stijnherreman** [comment]
That works, thanks!
