### ISSUE TITLE
Default value of enum is displayed as integer even though EnumHandling.String i set

### ISSUE THREAD

**Issue by hoidenG** [RSuter/NSwag#1597]
I have setup my swagger generator with string enum handling which works as expected except from when setting a default value on an enum in the API (see 2 red squares in image snippet of generated swagger document below) then the default value is still displayed as an integer

![image](https://user-images.githubusercontent.com/9443357/45361382-52b2a880-b5d2-11e8-8b09-ca0354849ea3.png)

Setup of DefaultEnumHandling to string:
```
var settings = new WebApiToSwaggerGeneratorSettings
{
    DefaultPropertyNameHandling = PropertyNameHandling.CamelCase,
    DefaultEnumHandling = EnumHandling.String
};
var generator = new WebApiToSwaggerGenerator(settings);
```

Object with default enum value:
```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace Experiment.Swagger.Api
{
    public class ContentWithEnumeration
    {
        [Required]
        [DefaultValue(MyEnumeration.C)]
        public MyEnumeration MyEnumeration { get; set; }
    }
    public enum MyEnumeration
    {
        A,
        B,
        C
    }
}
```

.Net Framework 4.7 
NSwag.SwaggerGeneration.WebApi 11.17.0

Thanks

**Comment by RSuter** [comment]
We need to handle this here (i.e. convert to string when enum is a string enum): 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L928

As a workaround you could just use a string in [DefaultValue], like: 

    [DefaultValue("C")]

or maybe even: 

    [DefaultValue(MyEnumeration.C.ToString())]

**Comment by hoidenG** [comment]
Thanks for the quick answer!

**Comment by RSuter** [comment]
Please check the unit test in the previous commit. Is this fix ok?

**Comment by hoidenG** [comment]
Yes it is. 
Your quick response is much appreciated!
