### ISSUE TITLE
[NSwag.MSBuild] Include script bundle as embedded resources to the same assembly as the api

### ISSUE THREAD

**Issue by Wezea** [RSuter/NSwag#1598]
Hi,

I'm currently working on a project which needs to include the final bundled javascript artifacts as embedded resources.

For creating the api, I'm using the NSWag.MSBuild to create my typescript client.

With this approach I'm obviously facing the probleme, that I have to build the assemblies first, so NSWag.MSBuild can create the typescript client for the api. Then I'm bundling my javascript, together with the created typescript client. Now I acutally need to trigger the build again to include the latest built artifacts as embedded resources.

Is there any elegant approach to do this using MSBuild?

Looking forward to some suggestions.
Thank you.

**Comment by RSuter** [comment]
NSwag.MSBuild with AspNetCoreToSwagger generator can be used with assemblies or a csproj as input but either way it will/needs to compile the project first and a second build is needed to actually embed the new JS bundle. 

A way to "fix" this would be to have some more projects, eg a Web project (actual ASP.NET API project) an API project (with the controllers) and a Generator project (also an ASP.NET project which references the API project). Now the spec/typescript is generated in the Generator project first (the Web project has a dependency on the Generator), updates the JS in the Web project and next the Web project is built with latest JS and embeds it... does this sound reasonable?

**Comment by RSuter** [comment]
And the Generator project could just use the same Startup.cs and stuff as Web (linked files). Not sure if this is a good solution though...

**Comment by Wezea** [comment]
Thank you again for the clarification. We now figured out a solution which can be hooked into the build chain by triggering another build and avoiding further builds by passing through a build property:

```xml
<Target>
  <Exec Command="$(NSwagExe_Core21) run nswag.json" Condition="$(SkipCustomization)!='true'" />
  <Exec Command="npm run build" Condition="$(SkipCustomization)!='true'" />
  <Exec Command="dotnet msbuild /p:SkipCustomization=true /v:m" Condition="$(SkipCustomization)!='true'"/>
</Target>
```

**Comment by RSuter** [comment]
Yeah, was thinking about something about this too (conditional steps)… looks good but may still have some unnecessary overhead (compiled twice) but this cannot be avoided i thikn

**Comment by Wezea** [comment]
True, but I go with that overhead instead of having separate projects.
Thank you for your help and this great project!
