### ISSUE TITLE
API Explorer: Fix required/optional parameters

### ISSUE THREAD

**Issue by RSuter** [RSuter/NSwag#1599]
- Query parameters
- Header parameters
- Path parameters: 
    - Current: Always required
- Body parameters: 
    - Current: Always required, see https://github.com/RSuter/NSwag/issues/1600

Code to fix (currently API Explorer's IsRequired behavior is ignored): [OperationParameterProcessor.cs](https://github.com/RSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration.AspNetCore/Processors/OperationParameterProcessor.cs#L326)
Parameter unit tests: [NSwag.SwaggerGeneration.AspNetCore.Tests/Parameters](https://github.com/RSuter/NSwag/tree/master/src/NSwag.SwaggerGeneration.AspNetCore.Tests/Parameters)

PR: https://github.com/RSuter/NSwag/pull/1608

**Comment by rynowak** [comment]
Rico is there anything you need from us related to this? As I understand it, API Explorer reflects how MVC will behave. If you think there are bugs, lets us know and we can investigate for 2.2.0

**Comment by RSuter** [comment]
@rynowak I have to add more systematic unit tests for this. I wouldn't say there are bugs per se, just unexpected behavior... and maybe lots of breaking changes if I let API Explorer completely handle IsRequired. Will update you as soon as i know more...

**Comment by RSuter** [comment]
@rynowak From #1556: All parameters are by default optional in `public Task AffectCamera(string id, string cameraId)`, correct? Because I think typical parameters are required (otherwise the generator has lots of nullable parameters => ugly) I have to add [BindRequired] everywhere? Is that correct?

**Comment by rynowak** [comment]
When using `[ApiController]` query parameters are optional by default - path parameters are required unless they are optional in the route definition. This reflects how the framework behaves.

If you want a different convention (query parameters are required by default, you can implement that with a convention, and ApiExplorer will respect that).

**Comment by RSuter** [comment]
Ah thanks for this info, then ill switch to the correct implementation and provide an optional convention for backward campatibility...
