### ISSUE TITLE
FromBody action method paramter is being marked as required: true 

### ISSUE THREAD

**Issue by dwaijam** [RSuter/NSwag#1600]
FromBody action method paramter is being marked as required: true unlike FromQuery. Swashbuckle does not treat FromBody as required .

**Comment by RSuter** [comment]
Is this with the new *WithApiExplorer() generator (AspNetToSwaggerGenerator)?

Ref: https://github.com/RSuter/NSwag/issues/1599

**Comment by RSuter** [comment]
This is the problem: https://github.com/RSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration.AspNetCore/Processors/OperationParameterProcessor.cs#L287

**Comment by scottdewald** [comment]
> @pranavkm do you think we should change that?

Yes. Since the ApiControllerAttribute makes the FromBodyAttribute optional, it would be nice if NSwag did the same.

**Comment by RSuter** [comment]
Does this look good?

https://github.com/RSuter/NSwag/pull/1606
