### ISSUE TITLE
HTTP response missing in SwaggerException.Message

### ISSUE THREAD

**Issue by cbuchacher** [RSuter/NSwag#1605]
When a unit test throws an exception, [xUnit](https://xunit.github.io/) outputs Exception.Message. But SwaggerException.Message does not contain the HTTP status code or the HTTP response, which are crucial to describe the exception.

```
Xavo.DemandClient.SwaggerException : MyMessage
   at SwaggerTests.SwaggerTests.SwaggerTest() in C:\...\SwaggerTests.cs:line 12
```

The [docs](https://docs.microsoft.com/en-us/dotnet/api/system.exception.message?view=netcore-2.1) say this on `Exception.Message`:

> Gets a message that describes the current exception.

I think SwaggerException.Message should return both the HTTP response and the HTTP status code. Using `SwaggerException.ToString()` returns the HTTP response, but doubt that I could convince xUnit developers to switch to using `Exception.ToString` instead of `Exception.Message`.

For reference, here is the unit test which generates the output above:

```csharp
using System.Collections.Generic;
using Xavo.MyControllerClient;
using Xunit;

namespace SwaggerTests
{
    public class SwaggerTests
    {
        [Fact]
        public void SwaggerTest()
        {
            throw new SwaggerException("MyMessage", 401, "HTTP not found response", new Dictionary<string, IEnumerable<string>>(), null);
        }
    }
}
```

**Comment by RSuter** [comment]
So your proposal is to change the exception template?

https://github.com/RSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Templates/File.liquid#L112

To what?

You can do that already: https://github.com/RSuter/NSwag/wiki/Templates

**Comment by cbuchacher** [comment]
Unfortunately, the messages themselves are sometimes quite strange. For example, for a 400 bad request response the message is "\nor\n". But without daring to discard the message parameter entirely, something like this would be a start?

```diff
diff --git a/src/NSwag.CodeGeneration.CSharp/Templates/File.liquid b/src/NSwag.CodeGeneration.CSharp/Templates/File.liquid
index 28947a10..65327ec1 100644
--- a/src/NSwag.CodeGeneration.CSharp/Templates/File.liquid
+++ b/src/NSwag.CodeGeneration.CSharp/Templates/File.liquid
@@ -118,7 +118,7 @@ namespace {{ Namespace }}
         public System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

         public {{ exceptionClassName }}(string message, int statusCode, string response, System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
-            : base(message, innerException)
+            : base($"{message} {{status: \"{statusCode}\", response: \"{response}\"}}", innerException)
         {
             StatusCode = statusCode;
             Response = response;

```

I will also look into the template approach.

**Comment by RSuter** [comment]
TBH I'm not sure if the status code and response belongs into the message - they are part of the exception (properties).

**Comment by cbuchacher** [comment]
Well, in some cases the generated client already puts the status code into the message. But in some others it does not. The message `"\nor\n"` is a bug I suppose.

```csharp
                                throw new SwaggerException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            throw new SwaggerException("A server side error occurred.", (int)response_.StatusCode, responseData_, headers_, null);
                            throw new SwaggerException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", (int)response_.StatusCode, responseData_, headers_, null);
                            throw new SwaggerException<object>("\nor\n", (int)response_.StatusCode, responseData_, headers_, result_, null);
                            throw new SwaggerException<string>("A server side error occurred.", (int)response_.StatusCode, responseData_, headers_, result_, null);
```

Since we are building a web application, the HTTP status code and the HTTP response contain the relevant information. The message strings above are not interesting.

For what it's worth, I figured out how to use replace the liquid template file (using the `/TemplateDirectory:MyTemplateDirectory` option of nswag cli). After some testing, I have updated the proposed change as follows:

```csharp
+        public {{ exceptionClassName }}(string message, int statusCode, string response, System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
+            : base($"{message} " + "{" + $"status: {statusCode}, response: {response}" + "}", innerException)
+        {
```

In particular, I had to avoid using the double braces which have special meaning both for liquid and C# interpolation strings.

**Comment by cbuchacher** [comment]
Instead of overriding the File.liquid template I decided to override only the SwaggerException class using the ExceptionClass setting: https://github.com/RSuter/NSwag/blob/master/src/NSwag.Commands/Commands/CodeGeneration/SwaggerToCSharpClientCommand.cs#L90
