### ISSUE TITLE
How to use ReportProgress?

### ISSUE THREAD

**Issue by ranouf** [RSuter/NSwag#1623]
Hi,

I enabled _Call TransformOptions_ in nswagstudio
![image](https://user-images.githubusercontent.com/1764519/45892847-6232ae00-bd97-11e8-8ca7-1ae598bd454d.png)

Here is my method:

 ```
 protected transformOptions(options: any) {
    return Promise.resolve({
      reportProgress: true,
    });
  }
```

When I do a request, now I have:

> list.component.ts:111 filter failed Error: An unexpected server error occurred.
>     at new SwaggerException (api.services.ts:2148)
>     at throwException (api.services.ts:2168)
>     at MergeMapSubscriber.project (api.services.ts:870)
>     at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (mergeMap.js:61)
>     at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (mergeMap.js:51)
>     at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:55)
>     at Observable._subscribe (api.services.ts:2174)
>     at Observable.push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe (Observable.js:42)
>     at Observable.push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe (Observable.js:28)
>     at MergeMapOperator.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call (mergeMap.js:29)

I would like to be able to subscribe to the upload progression of my request like this:
https://stackoverflow.com/questions/42231123/how-to-use-angular2-http-api-for-tracking-upload-download-progress/45222419#45222419

Packages.json:
 "@angular/animations": "^6.1.7",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.7",
    "@angular/compiler": "^6.1.7",
    "@angular/core": "^6.1.7",
    "@angular/forms": "^6.1.7",
    "@angular/http": "^6.1.7",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.1.7",
    "@angular/platform-browser-dynamic": "^6.1.7",
    "@angular/router": "^6.1.7",
    "@aspnet/signalr": "1.0.3",
    "@auth0/angular-jwt": "^2.0.0",
    "@covalent/core": "2.0.0-beta.1",
    "angular2-notifications": "^1.0.4",
    "core-js": "^2.5.7",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.11",
    "rxjs": "^6.3.2",
    "rxjs-compat": "^6.3.2",
    "zone.js": "^0.8.26"

I use _HttpClientModule_

How can I configure it to make it work?

Thanks
Cedric

**Comment by RSuter** [comment]
You need to transform the options (not create a new one): 

Try

```
protected transformOptions(options: any) {
   options.reportProgress = true;
   return Promise.resolve(options);
 }
```

**Comment by ranouf** [comment]
Thanks for your really fast solution :)

**Comment by ranouf** [comment]
From what I understand, when I want to subscribe to the request, I need to enable _Call 'transformResult'_.

Here is my code:

  protected transformResult(url: string, response: any, processor: (response: any) => any): Observable<any> {
    if (response instanceof HttpErrorResponse) {
      return readFile(response.error).pipe(map(value => {
        throw <IErrorInfo>JSON.parse(value);
      }));
    }
    else {
      debugger;
      if (response.type === HttpEventType.UploadProgress) {
        const percentDone = Math.round(100 * response.loaded / response.total);
        console.log(`File is ${percentDone}% uploaded.`);
      } else if (event instanceof HttpResponse) {
        console.log('File is completely uploaded!');
      }
      return processor(response);
    }
  }

But nothing appears in my console.

Did I miss something?

Thanks for your help

**Comment by ranouf** [comment]
The response is:

  protected transformResult(url: string, response: any, processor: (response: any) => any): Observable<any> {
    console.log("transformResult", response)
    let type: HttpEventType = response.type;
    switch (type) {
      case HttpEventType.Sent:
        // The request was sent out over the wire.
        
        break;
      case HttpEventType.UploadProgress:
        // An upload progress event was received.
      case HttpEventType.DownloadProgress:
        // A download progress event was received.
        let percentDone = Math.round(100 * response.loaded / response.total);
        console.log(`File is ${percentDone}% uploaded.`);
        break;
      case HttpEventType.ResponseHeader:
        // The response status code and headers were received.
        break;
      case HttpEventType.Response:
        // The full response including the body was received.
        if (response instanceof HttpErrorResponse) {
          return readFile(response.error).pipe(map(value => {
            throw <IErrorInfo>JSON.parse(value);
          }));
        } else if (event instanceof HttpResponse) {
          console.log('File is completely uploaded!');
        }
        return processor(response);

        break;
      case HttpEventType.User:
        // A custom event from an interceptor or a backend.
      default:
    }
    return empty();

**Comment by TauanMatos** [comment]
> The response is:
> 
> ```
> protected transformResult(url: string, response: any, processor: (response: any) => any): Observable<any> {
>    console.log("transformResult", response)
>    let type: HttpEventType = response.type;
>    switch (type) {
>      case HttpEventType.Sent:
>        // The request was sent out over the wire.
>        
>        break;
>      case HttpEventType.UploadProgress:
>        // An upload progress event was received.
>      case HttpEventType.DownloadProgress:
>        // A download progress event was received.
>        let percentDone = Math.round(100 * response.loaded / response.total);
>        console.log(`File is ${percentDone}% uploaded.`);
>        break;
>      case HttpEventType.ResponseHeader:
>        // The response status code and headers were received.
>        break;
>      case HttpEventType.Response:
>        // The full response including the body was received.
>        if (response instanceof HttpErrorResponse) {
>          return readFile(response.error).pipe(map(value => {
>            throw <IErrorInfo>JSON.parse(value);
>          }));
>        } else if (event instanceof HttpResponse) {
>          console.log('File is completely uploaded!');
>        }
>        return processor(response);
> 
>        break;
>      case HttpEventType.User:
>        // A custom event from an interceptor or a backend.
>      default:
>    }
>    return empty();
> ```

Which file is this? I'm now trying to track progress of the uploading files but I don't know how.

**Comment by RSuter** [comment]
Related: https://github.com/RSuter/NSwag/issues/1862

**Comment by ranouf** [comment]
Hi,

@TauanMatos >
On nswagstudio:
![image](https://user-images.githubusercontent.com/1764519/50656114-2693ac80-0f60-11e9-884c-797117a61ea2.png)
![image](https://user-images.githubusercontent.com/1764519/50656141-3f9c5d80-0f60-11e9-93d6-b650a632d614.png)
![image](https://user-images.githubusercontent.com/1764519/50656204-678bc100-0f60-11e9-82b1-e5224c97f0ba.png)
![image](https://user-images.githubusercontent.com/1764519/50656258-94d86f00-0f60-11e9-86a0-1c135b5d26c2.png)

In _api.services.import.ts_:
```
import { ServiceBase, ServiceBaseConfiguration } from './api.servicesbase';
```

In _api.servicesbase.ts_:
```
import { DataTransferService, DataTransfer } from './data-transfer/data-transfer.service';
[...]
@Injectable()
export class ServiceBaseConfiguration {
  constructor(
    public dataTransferService: DataTransferService
  ) {
  }
}

@Injectable()
export class ServiceBase {

  constructor(
    private serviceBaseConfiguration: ServiceBaseConfiguration
  ) {
  }

  public transformOptions(options) {
    options.reportProgress = true;
    options.observe = 'events';
    return Promise.resolve(options);
  }

  public transformResult(url: string, response: any, processor: (response: any) => any): Observable<any> {
    let type: HttpEventType = response.type;
    switch (type) {
      case HttpEventType.Sent:
        // The request was sent out over the wire.

        break;
      case HttpEventType.UploadProgress:
      // An upload progress event was received.
      case HttpEventType.DownloadProgress:
        console.log("[Data transfering]", response);
        // A download progress event was received.
        this.serviceBaseConfiguration.dataTransferService.newValue(new DataTransfer(
          response.loaded,
          response.total
        ));
        break;
      case HttpEventType.ResponseHeader:
        // The response status code and headers were received.
        break;
      //case HttpEventType.Response:
      //  // The full response including the body was received.
      //  break;
      case HttpEventType.User:
      // A custom event from an interceptor or a backend.
      default:
        if (response instanceof HttpErrorResponse) {
          return readFile(response.error).pipe(map(value => {
            throw <IErrorInfo>JSON.parse(value);
          }));
        } else if (event instanceof HttpResponse) {
          console.log('File is completely uploaded!');
        }
        return processor(response);
    }
    return empty();
  }
}
```

in _data-transfer.service.ts_:
```
@Injectable()
export class DataTransferService implements OnInit {
  private _status: Subject<boolean> = new Subject<boolean>();
  private _dataTransfer: Subject<DataTransfer> = new Subject<DataTransfer>();

  constructor() {
  }

  public status(): Observable<boolean> {
    return this._status.asObservable();
  }

  public enable() {
    this._status.next(true);
  }

  public disable() {
    this._status.next(false);
  }

  public newValue(value: DataTransfer) {

    this._dataTransfer.next(value);
  }

  public data(): Observable<DataTransfer> {
    return this._dataTransfer.asObservable();
  }

  ngOnInit(): void {
    this._dataTransfer.subscribe(data => {
      let percentDone = data.getPercentDone();
      if (percentDone != null) {
        console.log(`File is ${percentDone}% uploaded.`);
      }
    })
  }
}

export class DataTransfer {
  public loaded: number;
  public total: number | undefined;

  constructor(
    loaded: number,
    total: number | undefined
  ) {
    this.loaded = loaded;
    this.total = total;
  }

  public getPercentDone(): number | null {
    if (this.loaded && this.total) {
      return Math.round(100 * this.loaded / this.total);
    }
    else {
      return null;
    }
  }
}
```

in _your.component.ts_:
```
  public percentDone: number;

  constructor(
    public dataTransferService: DataTransferService
  ) { }

  ngOnInit() {
    this.dataTransferService.data().subscribe((data: DataTransfer) => {
      this.percentDone = data.getPercentDone();
    });
  }
```
in _your.component.html_:
```
{{ percentDone != null ? ' (' + percentDone + '%)' : ''}}
```

**Comment by AEINSIT** [comment]
Does someone knows if it is possible to use a custom pipe instead of calling a service? In our case I have to track the progress of different upload requests, therefore I can't call the same service every time. Here is a similiar question https://github.com/RicoSuter/NSwag/issues/1862.

**Comment by AbuDawood** [comment]
How about using the 'transformOptions' for certain methods and classes only
Thanks in advance

**Comment by AbuDawood** [comment]
> How about using the 'transformOptions' for certain methods and classes only
> Thanks in advance

as you know  the reportProgress is costly
