### ISSUE TITLE
Add an `IDocumentProvider` interface and service implementing it

### ISSUE THREAD

**Issue by dougbu** [RSuter/NSwag#1626]
The overall aim of in-progress work in ASP.NET Core 2.2 is to give customers simple ways to annotate their project files for automated code generation during every build (as source API descriptions change). See ASP.NET Core Mvc's [feature/client.code.generation](https://github.com/aspnet/Mvc/tree/feature/client.code.generation) branch and the aspnet/Mvc#7947 high-level issue.

The ASP.NET Core work includes a "generic" document-fetching tool which can get the Open API / Swagger document from a web site project. This tool can download from a URI (with the site running in `TestHost`) but is easier to use when the document provider (e.g. NSwag.AspNetCore) adds a service implementing `Microsoft.Extensions.ApiDescription.IDocumentProvider`. In the NSwag case, the retrieved document would reflect the user's configuration -- unlike when using the `aspnetcore2swagger` CLI tool.

Specific work in this repo would include:
- define chosen `IDocumentProvider` interface in the NSwag.AspNetCore package
  - the generic tool in the Microsoft.Extensions.ApiDescription.Client package does not define this `interface`, allowing providers to choose their favourite signature
- implement `IDocumentProvider` in the same package
- update the `AddSwagger(...)` extension method to register the new `IDocumentProvider` service
  - will likely also require a few other new services in DI, making at least the necessary configuration information available

**Comment by RSuter** [comment]
- AddSwagger() should register this new interface
- UseSwagger*() methods should add the settings to IDocumentProvider service
    - Add a new "option" so that the registered document can have a name/identifier
- IDocumentProvider should serve all documents registered by the UseSwagger*() methods
    - Should provide an api to enumerate all registered documents and name
    - Should provide an api to generate multiple/all documents or just one document by name

**Comment by rynowak** [comment]
Hi Rico,

Some questions about this:

> AddSwagger() should register this new interface
> UseSwagger*() methods should add the settings to IDocumentProvider service

Currently you don't require `AddSwagger` to be called when using `UseSwagger()` - so is it your expectation that those cases would degrade gracefully when `AddSwagger` wasn't called?

> Add a new "option" so that the registered document can have a name/identifier

Does this go on `SwaggerSettings<>`? On `SwaggerGeneratorSettings`? Or external to both:
```
ISwaggerGeneratorSettingsRegistry
{
    SwaggerGeneratorSettings this[string documentName] { get; set; }
}
```

**Comment by rynowak** [comment]
Basically, from looking over the code - my idea is to create an internal service that serves as a registry of each named document and its settings. The `UseSwagger*()` methods will register their information with this service - then they can ask the document provider to generate a `SwaggerDocument` on their behalf. 

What makes it difficult is trying to fuse together the different kinds of settings objects, and supporting both of the generators that exist for asp.net core.

**Comment by rynowak** [comment]
One other question related to this - if we have a 'document generator' service - would you rather see a new middleware that just calls into the service? The two existing middleware both expose things in their public API that are now details of the service.

**Comment by dougbu** [comment]
Many thanks @RSuter for doing the last few laps on this enhancement!!
