### ISSUE TITLE
Generated c# code raises an exception on octet-stream binary data

### ISSUE THREAD

**Issue by gilzig** [RSuter/NSwag#1629]
Hi,

I am new to OpenApi so perhaps I am missing something small, butI could not find references to this issue elsewhere:
I am trying to write an interface to a server with OpenApi 3.0.1. Most of the generated c# interfaces work very well. However, when I try to receive a binary response data - the generated code crashes with the following exception:

`Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: . Path '', line 1, position 139.'`

On the following generated file lines:

`result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<string>(responseData_, _settings.Value);`

I would expect some other code to be generated, since the response is a binary buffer and not a standard string.

The Yaml specification I am using (the relevant sub-section) looks like this:

```
openapi: 3.0.1
info:
  title: defaultTitle
  description: defaultDescription
  version: '0.1'
servers:
  - url: 'http://localhost:8042'
paths:
  /instances/{id}/frames/{index}/raw:
    get:
      description: sample
      parameters:
        - in: path
          name: id
          description: The guid of the instance
          required: true
          schema:
            type: string
        - in: path
          name: index
          description: The index of the frame (usually 0 unless multi frame instance)
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: raw file in binary data
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
```
The strange thing is that when I change in the content  section:
`application/octet-stream:` 
to:
`application/json; charset=utf-8:`
I get the exact same code generated, which doesn't seem correct, since I am trying to retrieve a buffer of binary data.

Does anyone know if I am missing something? any solution to this issue?
Thank you very much!!
Gil

**Comment by RSuter** [comment]
Try

          content:
            application/octet-stream:
              schema:
                type: file

**Comment by RSuter** [comment]
Looks good to me with "file": 

![image](https://user-images.githubusercontent.com/2603405/46401460-5501b180-c6fd-11e8-91be-54c2e511ed6f.png)

We just need to change the generator so that it handles your case as if it is a "file"
