### ISSUE TITLE
CSharp Client does not support versioned API

### ISSUE THREAD

**Issue by domsew** [RSuter/NSwag#1649]
Generated CSharp Client adds Accept Header to the request (_HttpRequestMessage_).

```C#
request_.Headers.Accept
    .Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json;v=1.0"));
```

Object
```C#
new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json;v=1.0")
```
Throws exception:
> FormatException: The format of value 'application/json;v=1.0' is invalid.

**Possible solutions:**

- Use method:

```C#
MediaTypeWithQualityHeaderValue.Parse("application/json;v=1.0")
```

- Or

```C#
client_.DefaultRequestHeaders
    .TryAddWithoutValidation("Accept", new []{ "application/json", "v=1.0" });
```

EDIT:
I noticed this behavior with _Console App (.NET Core)_

**Comment by RSuter** [comment]
Let's use `MediaTypeWithQualityHeaderValue.Parse("application/json;v=1.0")` as it is easier to just render this instead of checking the actual string etc.
