### ISSUE TITLE
TypeScript client: DTO fields are not initialized

### ISSUE THREAD

**Issue by ili** [RSuter/NSwag#1653]
Hi!
After updating to current version toolchain (from  v11.12.9.0) we'v faced with breaking change - now DTO peoperties are not initialized by default:

Old ( v11.12.9.0):
```js
export class SelectRequestBaseOfInstallationFilter implements ISelectRequestBaseOfInstallationFilter {
   filter: InstallationFilter = new InstallationFilter(); // INITED
   page: Paginator = new Paginator(); //INITED

    // skipped constructor & etc..
}
```

Current (v11.20.1.0):
```js
export abstract class SelectRequestBaseOfInstallationFilter implements ISelectRequestBaseOfInstallationFilter {
    filter: InstallationFilter; // NOT INITED
    page: Paginator; // NOT INITED

    // skipped constructor & etc..
}
```

**Comment by RSuter** [comment]
Thats probably because the spec has changed. Can you post the old and new spec? Null handling has been improved for openapi 3 output...

**Comment by RSuter** [comment]
I get this typescript which looks fine for me (with TS 2.7 settings): 

- The properties are required (!)
- The properties are initialized in the ctor when no data is provided

![image](https://user-images.githubusercontent.com/2603405/46537604-fdf10d80-c8b1-11e8-9ad1-5c952801452d.png)

**Comment by ili** [comment]
Up )
Teammates are angry with me, the point is only one to migrate to the next Angular version :)

Please help :)

**Comment by RSuter** [comment]
> In some reason filter property is not initialized.

Can you post the declaration of the filter property and filter schema of your spec or the whole spec?

**Comment by ili** [comment]
Here it is [swagger.txt](https://github.com/RSuter/NSwag/files/2541184/swagger.txt)

**Comment by RSuter** [comment]
Looks good to me: 

![image](https://user-images.githubusercontent.com/2603405/47903022-66b4b100-de83-11e8-9647-78281be9de56.png)

You can run my config: 

[nswag.zip](https://github.com/RSuter/NSwag/files/2541667/nswag.zip)

**Comment by ili** [comment]
Shame on me!

I'v gave you wrong swagger definition! 

Here is one, where the problem is reproduced (this is to the same API but generated with newer NSwag version).
[swagger_new.txt](https://github.com/RSuter/NSwag/files/2551613/swagger_new.txt)

**Comment by ili** [comment]
Fixed in [NSwag Build 1047](https://github.com/RSuter/NSwag/releases/tag/NSwag-Build-1047)
