### ISSUE TITLE
Discussion: aspnetcore2swagger configuration

### ISSUE THREAD

**Issue by ilmax** [RSuter/NSwag#1654]
Hi @RSuter 

I was digging into how nswag launches a web application, because I was hitting nullref in some places. My discovery was that the [CreateTestServer](https://github.com/RSuter/NSwag/blob/master/src/NSwag.Commands/Commands/SwaggerGeneration/SwaggerGeneratorCommandBase.cs#L206-L209) method here just launches a test server using the Startup class of the target project, this mean the code into the Program.cs file is not run and AFIK the `new WebHostBuilder().UseStartup(startupType)` is not setting up all the defaults like `WebHost.CreateDefaultBuilder` is doing e.g. the only configuration provider (the root cause for my nullrefs) configured when `Startup` is invoked by the **aspnetcore2swagger** command is the [EnvironmentVariablesConfigurationProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.environmentvariables.environmentvariablesconfigurationprovider?view=aspnetcore-2.1).

What do you think about changing the `CreateTestServer` method from `new WebHostBuilder().UseStartup(startupType)` to `WebHost.CreateDefaultBuilder().UseStartup(startupType)` to have aspnetcore2swagger invoke and run our applications with an environment more close to the development one?

**Comment by RSuter** [comment]
What about instead of using startupType you can specify a "CreateWebHostBuilder" method which is then called with an empty string array to get a builder?

**Comment by ilmax** [comment]
Not sure I'm following, are you talking about writing a custom "CreateWebHostBuilder" called by the aspnet2swagger command in order to have the application properly configured?

**Comment by RSuter** [comment]
My idea was to call the "BuildWebHost" method to get the IWebHost: 

        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();

but this wont work because the TestServer expects an IWebHostBuilder and not a IWebHost...

So I think your idea to use

    WebHost.CreateDefaultBuilder().UseStartup(startupType)

instead of

    new WebHostBuilder().UseStartup(startupType)

seems good.

**Comment by ilmax** [comment]
@RSuter but hey, your idea matches the default Program.cs template, if you run dotnet new mvc, it generates something like this:

```csharp
public class Program
{
	public static void Main(string[] args)
	{
		CreateWebHostBuilder(args).Build().Run();
	}

	public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
		WebHost.CreateDefaultBuilder(args)
			.UseStartup<Startup>();
}
```

And a [TestServer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.testhost.testserver?view=aspnetcore-2.1) needs a `IWebHostBuilder` ctorp parameter, so in the end I think your idea should work perfectly.

If you like it, I can give this one a try

**Comment by RSuter** [comment]
You are right, with 2.1, we would have something like this: 

    namespace WebApplication4
    {
        public class Program
        {
            public static void Main(string[] args)
            {
                CreateWebHostBuilder(args).Build().Run();
            }

            public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
                WebHost.CreateDefaultBuilder(args)
                    .UseStartup<Startup>();
        }
    }

Then we would add a new setting like "WebHostBuilderMethod" which would be "WebApplication4.Program.CreateWebHostBuilder" here and if this is set uses this instead of a startup class?

**Comment by RSuter** [comment]
I've created a PR with both fixes: A new setting + use CreateDefaultBinder(), please have a look: https://github.com/RSuter/NSwag/pull/1655

I dont like adding more and more settings - mainly because it's really hard to understand how to use it...

**Comment by RSuter** [comment]
You can download a test installer here: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/3420/artifacts

Uninstall nswagstudio first. I didnt test yet...

**Comment by ilmax** [comment]
Just did a quick review, looks good! Just left few comments

**Comment by RSuter** [comment]
@ilmax is the PR working for you?

**Comment by ilmax** [comment]
@RSuter i actually switched to another approach where I'm essentially launching the application, download the swagger definition and run the generator, but when I've tried it it was working (I just had to set environment variable before launching the editor).

I can double-check it this evening and get back to you here

O.T. I was wondering if it's possible to use the swagger2csharp generator with an input URI instead of a document

**Comment by RSuter** [comment]
> O.T. I was wondering if it's possible to use the swagger2csharp generator with an input URI instead of a document

Not sure if this is (yet) supported but you can do that with a nswag.json
