### ISSUE TITLE
Make generated C# client .NET 4.0 compatible

### ISSUE THREAD

**Issue by Alexander8** [RSuter/NSwag#1656]
Good day!

I'm trying to use NSwag to generate C# client for desktop application written using .NET 4.0 framework.

I've managed to do it with only one problem left: 
**ConvertToString** function => _if (value is System.Enum)_ branch.

Originally generated code can't be compiled against .NET 4.0 because of using not available classes:
_System.Reflection.IntrospectionExtensions_ and _System.Reflection.CustomAttributeExtensions_.

I've overcome that problem by modifying _Client.Class.ConvertToString.liquid_ template and applying it via _TemplateDirectory_ setting of swagger2csclient generator.

Here is my _Client.Class.ConvertToString.liquid_ (I changed only _if (value is System.Enum)_ branch).
I hope it may be useful for others or you could even modify the original template.

```c#
private string ConvertToString(object value, System.Globalization.CultureInfo cultureInfo)
{
    if (value is System.Enum)
    {
        string name = System.Enum.GetName(value.GetType(), value);
        if (name != null)
        {
            System.Reflection.FieldInfo field = value.GetType().GetField(name);
            if (field != null)
            {
                var attr = System.Attribute.GetCustomAttribute(field, typeof(System.Runtime.Serialization.EnumMemberAttribute)) 
                    as System.Runtime.Serialization.EnumMemberAttribute;
                if (attr != null)
                {
                    return attr.Value;
                }
            }
        }
    }
    else if (value is byte[])
    {
        return System.Convert.ToBase64String((byte[]) value);
    }
    else if (value != null && value.GetType().IsArray)
    {
        var array = System.Linq.Enumerable.OfType<object>((System.Array) value);
        return string.Join(",", System.Linq.Enumerable.Select(array, o => ConvertToString(o, cultureInfo)));
    }

    return System.Convert.ToString(value, cultureInfo);
}
```

Thanks.

**Comment by RSuter** [comment]
I think .NET 4.0 support will not be implemented as it is quite old. 

But you can change templates: https://github.com/RSuter/NSwag/wiki/Templates

And maybe there are compatiblity packages which the missing types...

**Comment by aherrick** [comment]
Thanks! How did you handle IReadOnlyDictionary? @Alexander8

**Comment by Alexander8** [comment]
@aherrick , I don't remember any issues related to IReadOnlyDictionary. 
Probably it wasn't there when I was compiling it.
Could you show some code which can't be compiled?
