### ISSUE TITLE
TS Generator setting ExportTypes not used

### ISSUE THREAD

**Issue by FabianTe** [RSuter/NSwag#1660]
Hi!

When setting `"exportTypes":true` I would expect the generated TS client file to export all interfaces like this:

```
export interface ResourceDto {...}
```

But the setting is ignored.
Since the documentation is lacking I went into the source code but can' find where the config file is parsed to see if maybe parsing of ```exportTypes``` is missing.

**Comment by RSuter** [comment]
DTO generation is implemented in http://njsonschema.org

And it looks like interfaces are exported with this setting: 

![image](https://user-images.githubusercontent.com/2603405/47801399-6bb41c00-dd2e-11e8-9603-c48b40a683aa.png)

**Comment by FabianTe** [comment]
I guess this was a misconfiguration. It works now.
