### ISSUE TITLE
C# class which extends from List<T> gets parsed as a seperate object

### ISSUE THREAD

**Issue by robinabganpat** [RSuter/NSwag#1672]
I currently have an object which adds some logic to the List<T> class.
It looks like this:

```
public class RelationCollection<Dto> : List<Dto>
        where Dto : IRelation
    {
        private bool relationTableSet = false;

        public RelationCollection()
        {

        }

        /// <summary>
        /// Create a RelationCollection which adds the passed DTOs to the list. The DTOs passed are made unique.
        /// </summary>
        /// <param name="dtos">DTOs to add to list</param>
        public RelationCollection(IEnumerable<Dto> dtos)
        {
            // Group DTOs by unique identifier to avoid duplicates in the list
            IEnumerable<Dto> uniqueDtos = dtos.GroupBy(dto => dto.RelationIdentifier.GetUniqueIdentifier(), (key, g) => g.FirstOrDefault());

            // Add the DTOs to the inheriting structure
            base.AddRange(uniqueDtos);
        }
    }
```

as you can see this class implements List<>. I use this RelationCollection to handle some relation specific behavior. These RelationCollection<> types are used in response objects.

Based on the above, I want to generate a Angular typescript client. I would expect the RelationCollection to result in an array in Typescript. However, the resulting generated code generates the following:

```
export interface RelationCollectionOfPageDto {
    capacity: number;
    count: number;
    item?: PageDto;
}
```

when using the following property in a Response object:
`public RelationCollection<PageDto> Pages { get; set; }`

Does anyone have an idea how I could let the NSwagStudio generate the Pages property as an array, instead of creating an object?

**Comment by RSuter** [comment]
I think you can change the type with

    [JsonSchemaType(typeof(List<Dto>))]
    public class RelationCollection<Dto> : List<Dto>

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Annotations/JsonSchemaTypeAttribute.cs

**Comment by robinabganpat** [comment]
Great thank you. That was what I've been looking for. 
One note though: Because Dto is a generic type in my case it can not be used in an attribute unfortunately. I now use this attribute on each property using the RelationCollection class, like this:

```
[JsonSchemaType(typeof(List<PageDto>))]
public RelationCollection<PageDto> Pages { get; set; }
```

Thanks for the quick response!

**Comment by hmvs** [comment]
@RSuter Don't you think it should work by default, without marking it as `JsonSchemaType`? 
I am trying to migrate from `Swashbuckle`, and I am stuck with this right now as far as I don't want to include package which has `JsonSchemaType` to Models ClassLibrary. 

I can make a PR if you help me to find the place that I should correct (especially UnitTest to make a test for that)

**Comment by RSuter** [comment]
> Don't you think it should work by default, without marking it as JsonSchemaType?

In this case I'd say yes...

Otherwise you could achive the same with settings.TypeMappings

**Comment by hmvs** [comment]
Almost all our collection responses is inherited from the List. So it's not very convenient to add all the models there. 
Can you point a code in NSwag that is responsible for that?

**Comment by RSuter** [comment]
This is in NJsonSchema, but probably not that easy to do without breaking some other scenarios

**Comment by hmvs** [comment]
Pity to hear. Does these scenarios covered by tests? 
Because right now  `public class SomeModelCollectionResponse : List<SomeModel> { }`
is rendered just as an `object` response type which requires additional frictions  to make it work.

**Comment by RSuter** [comment]
I think most of this is covered, but I'll also check with my private projects... please create an issue here and we'll look into it: https://github.com/RSuter/NJsonSchema

**Comment by RSuter** [comment]
Please try with v12.0.12

**Comment by hmvs** [comment]
Works like a charm. Thank you very match. Going to do attempt of migration number 2 :)

**Comment by hmvs** [comment]
@RSuter Found one more issue. 
If methods returns `SomeModelCollectionResponse` NSwag will generate class `SomeModelCollectionResponse` but return type will be ` List<SomeModel>`

**Comment by RSuter** [comment]
@hmvs can you create a new issue for that?

**Comment by hmvs** [comment]
@RSuter here it is https://github.com/RSuter/NSwag/issues/1936
