### ISSUE TITLE
Question: How to define 'example value' json?

### ISSUE THREAD

**Issue by MrGroovy** [RSuter/NSwag#1682]
The API has a POST endpoint. We reuse DTO classes for POST and GET. When doing a POST some properties are not needed so i dont want the example to display them. Is it possible to override the example value that is displayed?

I tried to create a IOperationProcessor but i cant figure out what to change in the context. I get lost in 'ActualSchema', 'InheritedSchema', 'InheritedTypeSchema', 'ActualProperties'....

**Comment by RSuter** [comment]
According to your OP, POST and GET use the same DTO and thus you cannot change the DTO just for one of them. To do that you'd need to have two separate DTO classes so that only the required properties are generated per operation... I think at the moment you could use inheritance to do so (GetModel inherits from PostModel) but then the spec also would have this inheritance...

**Comment by RSuter** [comment]
To better support your scenario we would need the setting FlattenInheritanceHierarchy but only selective for a single type (i.e. merge GetModel and PostModel). ATM FlattenInheritanceHierarchy will flatten everything

**Comment by RSuter** [comment]
I think by default swagger ui infers the sample from the DTO models... but there might be a way to specify explicit samples eg in the “example” property... first you need to find out what swagger ui uses for custom samples. Then you can implement an operation processor to add the samples like this: https://blog.rsuter.com/nswag-tutorial-implement-a-custom-operation-processor-to-define-redoc-code-samples/

**Comment by MrGroovy** [comment]
It seems to be impossible with `SchemaType.Swagger2`, the `$ref` entry overwrites everything. If i put a `example` instance in the `Reference` property using a operation processor then the example is displayed. But this is then a global example i believe, not tied to a operation.

I didnt know but i can also use `SchemaType.OpenApi3` and then it does work as expected when using the following code in a operation processor. I use `JsonConvert` here because when setting the `SerializerSettings` property on `GeneratorSettings` from `UseSwaggerUi3WithApiExplorer` then i get a `NullReferenceException` from the middleware when opening the Swagger page.

Go ahead and close this issue, thanks.

```csharp
if (context.OperationDescription.Method == SwaggerOperationMethod.Post
    && context.OperationDescription.Path.Contains("Cats"))
{
    SwaggerOperation operation = context.OperationDescription.Operation;
    OpenApiMediaType mediaType = operation.RequestBody.Content.First().Value;

    var catDto = new CatDto
    {
        Name = "Mother",
        Kittens =
        {
            new Kitten { Name = "Boris" }
        }
    };
    mediaType.Example = JsonConvert.SerializeObject(
        catDto,
        new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore,
            Formatting = Formatting.Indented
        });
}
```
