### ISSUE TITLE
NSwag produces invalid typescript

### ISSUE THREAD

**Issue by Kordonme** [RSuter/NSwag#1683]
In my process methods NSwag produces an `else` statement, but the variable names doesn't seem to follow the correct naming:

```
} else {
    return response.text().then((_responseText) => {
    let resultdefault: any = null;
    let resultDatadefault = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
    result = resultData ? BadRequestObjectResult.fromJS(resultData) : new BadRequestObjectResult();
    return throwException("A server error occurred.", status, _responseText, _headers, resultdefault);
    });
}
```

`Cannot find name 'result'` and `Cannot find name 'resultData'`. The variables are obviously named `resultdefault` and `resultDatadefault`.

**Comment by RSuter** [comment]
Can you provide a sample swagger spec?

**Comment by Kordonme** [comment]
I will provide one in a few hours.

**Comment by Kordonme** [comment]
Here's a [sample swagger](https://gist.github.com/Kordonme/cf7fc2e83185ecaafb163af17f6bd976) specification and it produces [this typescript client](https://gist.github.com/Kordonme/66a6c020aa57cf055f02dde88b9f0460).

Using this command:

`nswag swagger2tsclient /input:Mock.json /output:Client.ts`
