### ISSUE TITLE
input is ignored - pet services client is being generated i/o my client

### ISSUE THREAD

**Issue by vmdrot** [RSuter/NSwag#1685]
Hi there, I only have swagger docs json (the webapi is not mine, hence I cannot and don't actually need to generate webApiToSwagger from an assemblyPath). All I need is swaggerToCSharpClient to generate client(s) out of json api docs exposed by this external API.
I specified input as follows (and the swagger.json contains that external API swagger doc), but I still see GetPetAsync, etc. in the output file:
`{
  "runtime": "WinX64",
  "codeGenerators": {
    "swaggerToCSharpClient": {
      "input": "./Cli/swagger.json",
...
}`
Is this supported at all, or you have to be API host to be able to generate clients?

**Comment by RSuter** [comment]
```
{
  "runtime": "Default",
  "defaultVariables": null,
  "swaggerGenerator": {
    "fromSwagger": {
      "url": "./Cli/swagger.json",
      "output": null
    }
  },
  "codeGenerators": {
    "swaggerToCSharpClient": `...
  }
}
``

**Comment by vmdrot** [comment]
Thanks, @RSuter, that worked!

**Comment by brynjolf** [comment]
Has this scenario stopped working? I can"t get fromDocument to read a local file specified in url
