### ISSUE TITLE
Make blobToText replaceable in Typescript template

### ISSUE THREAD

**Issue by ruskom** [RSuter/NSwag#1692]
I found difficult to replace the functionality implemented in blobToText function.
Because File API (FileReader) is not present in server side code (Angular SSR -> Universal), the calls are always failing with error message "ReferenceError: FileReader is not defined".
Not easy to avoid this issue, because the calls and the function itself hard coded.

It would be great if it can be more flexible somehow or avoid using DOM related functions like File API.

**Comment by RSuter** [comment]
You can replace this particular template (File.Utilities.liquid): https://github.com/RSuter/NSwag/wiki/Templates

What wouldbe a good always working replacement?

**Comment by ruskom** [comment]
Thank you. I'll give it a try.

**Comment by Chreekar** [comment]
We solved this by manually editing the generated code to replace `responseType: "blob"` with `responseType: "json"` in the options object. Then we could just cast the response body to our dto model and delete the blobToText function. 

It would have been great to have a select in the NSwag UI to use json instead of blob in HttpClient like this, would that be possible in the future?

**Comment by RicoSuter** [comment]
So ideally it would use "json" for JSON responses and "blob" for file/binary responses, correct?

**Comment by Chreekar** [comment]
Exactly :-)

**Comment by bluee** [comment]
@Chreekar thanks for suggesting the responseType change. 

For now I did Creekar's change with responseType: json but to prevent changing everywhere in the swagger file I kept blobToText with a minor change. It's not optimal but it works with Angular SSR.

Would be nice with a permanent fix though.


```
function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        observer.next(JSON.stringify(blob));
        observer.complete();
    });
}
```

**Comment by ashrafsa** [comment]
@Chreekar 
I think that its possible to work with providers for customization instead of manually change the auto generated output.
for instance:

- blobToTextProvider which is injectable and the developer can assign the ts class in the UI.

- httpRequestOptionsProvider

**Comment by Chreekar** [comment]
I haven't understood the concept of providers, is this something I just change in the UI or do I need to create them in code somehow?

**Comment by Chreekar** [comment]
Took another go at this. I downloaded AngularClient.liquid and File.Utilities.liquid from https://github.com/RicoSuter/NSwag/tree/master/src/NSwag.CodeGeneration.TypeScript/Templates into a folder I pointed out in the TemplateDirectory setting. Changed the response type and blobToText in them, and now when I generate code I won't have to change anything afterwards.

**Comment by mohammad-shadmehr** [comment]
> Took another go at this. I downloaded AngularClient.liquid and File.Utilities.liquid from https://github.com/RicoSuter/NSwag/tree/master/src/NSwag.CodeGeneration.TypeScript/Templates into a folder I pointed out in the TemplateDirectory setting. Changed the response type and blobToText in them, and now when I generate code I won't have to change anything afterwards.

I have got the same problem with the endpoints generated by nswag. can you please let me know where exactly I need to put those file into? The nswag folder that I have got has a service.config,nswag and refresh.bat.

**Comment by mohammad-shadmehr** [comment]
> Took another go at this. I downloaded AngularClient.liquid and File.Utilities.liquid from https://github.com/RicoSuter/NSwag/tree/master/src/NSwag.CodeGeneration.TypeScript/Templates into a folder I pointed out in the TemplateDirectory setting. Changed the response type and blobToText in them, and now when I generate code I won't have to change anything afterwards.

Any more info on what you did to fix the issue?

**Comment by Ben555555** [comment]
I changed it like this:

AngularClient.liquid
```
{%-    if operation.IsFile -%}
            responseType: "blob",
{%-    else -%}
            responseType: "json",
{%-    endif -%}
```

This is important, so you can still download files from the API.

File.Utilities.liquid
```
{% if Framework.IsAngular -%}
function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        observer.next(JSON.stringify(blob));
        observer.complete();
    });
}
```

**Comment by Brhav** [comment]
I replaced the following to ensure my error parsing worked:

AngularClient.liquid

Before:

```
const responseBlob =
          response instanceof HttpResponse ? response.body :
          (response as any).error instanceof Blob ? (response as any).error : undefined;
```

After:

```
const responseBlob =
          response instanceof HttpResponse ? response.body : (response as any).error;
```
