### ISSUE TITLE
TagSorter setting is not working

### ISSUE THREAD

**Issue by MrGroovy** [RSuter/NSwag#1694]
The `SwaggerUi3Settings` contains property `TagSorter`, and in `SwaggerUi3Settings.cs` is see the following line: `html = html.Replace("{TagSorter}", TagSorter);`. But in `SwaggerUi3/index.html` there is no `{TagSorter}` to replace, so it never gets in.

**Comment by RSuter** [comment]
This somehow got removed during a Swagger UI 3 upgrade...
