### ISSUE TITLE
Console / NSwag.MSBuild - Adding TypeMappers to AspNetCoreToSwaggerGeneratorSettings

### ISSUE THREAD

**Issue by FineWolf** [RSuter/NSwag#1698]
There seems to missing a way to configure `AspNetCoreToSwaggerGeneratorSettings` dynamically when generating code using the MSBuild pipeline.

We have custom `TypeMapper`s that we are adding during `Startup`. However those mappings are not applied when generating clients using MSBuild, causing discrepancies between our actual schema and the clients generated.

We are applying the following mappers (to support NodaTime's Instant and LocalDate):

```csharp
var typeMappers = settings.TypeMappers;

typeMappers.Add(new PrimitiveTypeMapper(
    typeof(LocalDate),
    jsonSchema =>
    {
        jsonSchema.Type = JsonObjectType.String;
        jsonSchema.Format = JsonFormatStrings.Date;
    }));

typeMappers.Add(new PrimitiveTypeMapper(
    typeof(Instant),
    jsonSchema =>
    {
        jsonSchema.Type = JsonObjectType.String;
        jsonSchema.Format = JsonFormatStrings.DateTime;
    }));
```

Is there an undocumented way of applying the same configuration during generation?

**Comment by RSuter** [comment]
In the next version you can control the whole config in code and call it from cli... main feature is merged, needs cli support + testing and refinements

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/pull/1655 (UseDocumentProvider)

**Comment by RSuter** [comment]
The referenced PR introduces a new UseDocumentProvider setting which gives you much more control over the controls, and you can also configure own processors, typemappers etc. and use them in CLI: 

![image](https://user-images.githubusercontent.com/2603405/47795868-8cc33f80-dd23-11e8-8ef4-cf598c24af45.png)

(not released yet)
