### ISSUE TITLE
Angular usage example

### ISSUE THREAD

**Issue by Sergey-Ryabov** [RSuter/NSwag#1709]
Hello.
Could you tell me how I can use NSwag with Angular2? Can I generate API layer from openapi.json?

**Comment by dylanvdmerwe** [comment]
See [this ](https://www.youtube.com/watch?v=UM7Qc_t6KBc)which can help. There are also plenty of tutorials. Also see the wikis.

**Comment by RSuter** [comment]
OpenAPI 3.0 is supported - but there might be some features which are not supported yet...

**Comment by Sergey-Ryabov** [comment]
Do you have list of features that not supported yet?
