### ISSUE TITLE
Typescript optional configuration parameter

### ISSUE THREAD

**Issue by Cyrus-d** [RSuter/NSwag#1710]
Is there a way that we can have an optional configuration parameter in the generated client constructor.

currently, it will generate constructor as follow, which required configuration supplied when instantiating the class:

```
    constructor(configuration: configurationClass, baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super(configuration);
        this.http = http ? http : <any>window;
        this.baseUrl = baseUrl ? baseUrl : this.getBaseUrl("");
    }
```

apparently, csharp generator allows this by generating overloaded constructors:

```
public partial class MyClient : MyBaseClass
{
    public MyClient() : this("", null) { }
  
    public MyClient(string baseUrl) : this(baseUrl, null) { }
    
    public MyClient(string baseUrl, MyConfig configuration) : base(configuration)
    {
        BaseUrl = baseUrl; 
    }
```
Thanks,

**Comment by RSuter** [comment]
You can already specify the ConfigurationClass setting which then is injected via DI...

**Comment by Cyrus-d** [comment]
Thank you for clarification.
