### ISSUE TITLE
Support Typescript 3 because blobtotext implementation is not valid

### ISSUE THREAD

**Issue by k290** [RSuter/NSwag#1715]
Currently the latest version of Typescript nswag supports is 2.7
Generating an angular.js  typescript client. In dataservices.ts the following is in the blobToText method

` reader.onload = function() { 
            resolve(this.result);
        }`

However for TypeScript 3 to compile this needs to be:
` reader.onload = function() { 
            resolve(this.result as string);
        }`

Currently we are manually editing this after each client generation.

Edit: Found a way. Overwrote it using the File.Utilities.liquid template

**Comment by RSuter** [comment]
Would this also be possible?

    reader.onload = function() { resolve(<any>this.result); }

**Comment by RSuter** [comment]
The function has already been updated: 

https://github.com/RSuter/NSwag/blob/master/src/NSwag.CodeGeneration.TypeScript/Templates/File.Utilities.liquid#L40

Would this solve your problem?

**Comment by k290** [comment]
Yes, 

But now that you've added the "RequiresFunctions" it breaks because we use "throwException" and it has been erased. How is RequiresFunctions set?

**Comment by RSuter** [comment]
It's from this PR: https://github.com/RSuter/NSwag/pull/1705

**Comment by RSuter** [comment]
Strange, why is it not rendered? `_settings.GenerateClientClasses` and `!string.IsNullOrEmpty(Clients);` should be true, even in your scenario, no?

**Comment by k290** [comment]
Yes it should be set. See below screenshot of our settings
![image](https://user-images.githubusercontent.com/5611876/47992215-fca34280-e0f4-11e8-8367-f7a0a65e05f1.png)

But if the changes here: https://github.com/RSuter/NSwag/pull/1705/commits/816bff0294fcd393410c19dc26c101e3545bc850
have not yet been released then it makes sense that it wouldn't work, correct? Currently on nswag 11.20.1.0, and I'm guessing we'll only see the addition of `bool RequiresClientFunctions =>` in the next release?

**Comment by FreeFrags** [comment]
This sounds like the same issue as why we added the RequiresClientFunctions. But I might be wrong....

11.20.1.0 doesnt contain the #1705 PR yet

**Comment by k290** [comment]
Yeah so it just means that before I use the latest .liquid template I need to wait for the next release. I had just copied the template directly from github

**Comment by RSuter** [comment]
> Yeah so it just means that before I use the latest .liquid template I need to wait for the next release. I had just copied the template directly from GitHub

You cannot just copy the latest template because the model property is missing in the latest release. So yes, you need to wait for the latest release... but do you think it the latest on master is fine now?

**Comment by k290** [comment]
Yes latest on master is fine

**Comment by RSuter** [comment]
Closed by PR #1705 (will be available in next release)
