### ISSUE TITLE
Class name not work with Swagger in ASP .NET Core 2.1 when generating TypeScriptClient

### ISSUE THREAD

**Issue by alvarosinmarca** [RSuter/NSwag#1723]
Hello.

If I generate a TypeScriptClient with Swagger in project .NET Framework this work.
If I generate with a project .NET Core 2.1 this NOT work **(Only generate a class Client instead of one for each controller)** "{controller}Client"

![image](https://user-images.githubusercontent.com/9324962/48214956-76e7f700-e381-11e8-8bbc-e529a60ef339.png)

![image](https://user-images.githubusercontent.com/9324962/48215021-9c750080-e381-11e8-9aa7-52c6d57c6c3b.png)

![image](https://user-images.githubusercontent.com/9324962/48215145-e52cb980-e381-11e8-97ce-1d62edc28050.png)

Thx!

**Comment by alvarosinmarca** [comment]
Should generate one for each controller with template {controller}Client and only generate a class Client. Thanks you.

**Comment by RSuter** [comment]
Can you post the spec? How is it generated?

**Comment by alvarosinmarca** [comment]
Solution:

Use package nuget **NSwag.AspNetCore** instead of Swashbuckle.AspNetCore.

This work!!!

![image](https://user-images.githubusercontent.com/9324962/48302093-0d3e2900-e4f8-11e8-91b7-04e6eafbe38a.png)

Thanks you RSuter, Nswag save my life!
