### ISSUE TITLE
How to configure NSwag to ignore property on model?

### ISSUE THREAD

**Issue by maikebing** [RSuter/NSwag#1726]
```
       public class ModelIgnoreTest
        {
            public string  NotIgnore { get; set; }
            [SwaggerIgnore]
            public string Ignore { get; set; }
        }
        public class MyController : ApiController
        {
          
            [Route("api/{id}/service")]
            public void FooModel([FromBody]  SwaggerIgnoreTests id)
            {

            }
        }

```

Example vlaue:
```

{
"NotIgnore":"string"
}
```

**Comment by RSuter** [comment]
Use jsonignoreattribute

**Comment by maikebing** [comment]
@RSuter  THS

**Comment by SRYER** [comment]
Public class MyDto{
   [JsonIgnore]
   public string MyField{ get; }
}

If you add this JsonIgnore field, it will not only be ignored in the documentation but also when the actual dto is serialized and sent to the client. Isnt there a way to ignore the property from the documentation only?

**Comment by Yaroslav-Smirnov** [comment]
@RicoSuter We have SDK generated automatically and sometimes we need to leave a property for backwards compatibility but we do not want it into a new version of the SDK. So it would really great if we could tell NSwag to ignore a property keeping it in json at the same time.
