### ISSUE TITLE
async controller methods with "Async" suffix should not generate "AsyncAsync"

### ISSUE THREAD

**Issue by timmkrause** [RSuter/NSwag#1730]
A controller with

`public async Task<ActionResult<Something>> GetSomethingAsync([Required] Guid foo)`

becomes

`System.Threading.Tasks.Task<Something> GetSomethingAsyncAsync(System.Guid foo);`

For the generated code I'd also simply prefer `GetSomethingAsync`.

**Comment by timmkrause** [comment]
That way you are forcing me to use `OperationId`s. Maybe there is no benefit for me in using them or I do want to reflect as much as I can to my clients without constantly adapting `OperationId`s.

**Comment by lukaskolafa** [comment]
operationId has the benefit, that internal implementation details (name of controller method) is not faced to clients. xxxAsync suffix is for me technical restriction/pattern and API (operationIds) is business/client point of view. Separating the technical part from the client part seems being plausible. Of course it is some overhead for improved quality - depends on your scenario how much you want to invest into that.

**Comment by RSuter** [comment]
NSwag generates operation ids in the form controllerName_operationName where operationName is stripped off the Async suffix. Async should not be part of a spec as it is an implementation detail. How did you generate the spec? Can you post process it?

**Comment by timmkrause** [comment]
Sorry guys, this was my bad. (If I remember correctly) I already had an `OperationId` in place which had the `Async` suffix in its name and the generation additionally added an `Async` suffix.

Please close if you're fine with this behavior (I am).

**Comment by RSuter** [comment]
I think Async should not be in the operation id as it is an implementation of the used language (leaky abstraction), ie all operations are async and this its not needed

**Comment by baskialdensys** [comment]
Is it possible to make Adding Async at the end  of a method as Settings option ?

**Comment by RicoSuter** [comment]
@baskialdensys please open a new issue for that
