### ISSUE TITLE
TS Client RequestUrl template does not check null

### ISSUE THREAD

**Issue by FabianTe** [RSuter/NSwag#1734]
Hi,

I noticed, that my generated clients ignore URL parameters that are `undefined` but not those that are `null`. An example:

```
if (width !== undefined)
  url_ += "width=" + encodeURIComponent("" + width) + "&";
if (height !== undefined)
  url_ += "height=" + encodeURIComponent("" + height) + "&";
```

I think that this should by default also check for null. [This would be the spot in the TS template.](https://github.com/RSuter/NSwag/blob/bb5902ec5dbf788d1be238dfc8be62a21a748bb6/src/NSwag.CodeGeneration.TypeScript/Templates/Client.RequestUrl.liquid#L35-L40)

If am not the only one who thinks this I'd create a PR.

**Comment by RSuter** [comment]
I think this is because the parameter is required but nullable. Can you post the spec?

**Comment by FabianTe** [comment]
I am generating the code from .NET Core controllers.
This is from the swagger JSON:

```json
{
  "/my/path": {
    "get": {
      "tags": [
        "Test"
      ],
      "operationId": "GetBlob",
      "consumes": [],
      "produces": [
        "application/json"
      ],
      "parameters": [
        {
          "name": "width",
          "in": "query",
          "required": false,
          "type": "integer",
          "format": "int32"
        },
        {
          "name": "height",
          "in": "query",
          "required": false,
          "type": "integer",
          "format": "int32"
        }
      ]
    }
  }
}
```

**Comment by FabianTe** [comment]
In that case changing it locally in my template will suffice. Thank you!

**Comment by RSuter** [comment]
OpenAPI 3.0 nullable sample here: https://github.com/RSuter/NSwag/issues/1732#issuecomment-438646426
