### ISSUE TITLE
Typescript MultipleClientsFromOperationId generates only one client

### ISSUE THREAD

**Issue by Cifyger** [RSuter/NSwag#1740]
Typescript MultipleClientsFromOperationId generates only one client but if i use the option MultipleClientsFromPathSegments the different clients are generatetd as i wish. Do i have to configure something in the operation id so nswagstudio can create the clients?

**Comment by RSuter** [comment]
The operation id must be in the form controllerName_operationName

**Comment by Cifyger** [comment]
Thanks everything works like it supposed to do.
