### ISSUE TITLE
Variables in JQueryCallbacks client are undeclared, causing TS compiler error

### ISSUE THREAD

**Issue by r3tina** [RSuter/NSwag#1745]
When generating a TS client with JQuery callbacks, the TS compiler gives an error on an undeclared variable. The following code is generated:

```typescript
let resultdefault: any = null;
let resultDatadefault = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
result = resultData ? ErrorModel.fromJS(resultData) : new ErrorModel();
return throwException("A server error occurred.", status, _responseText, _headers, resultdefault);
```

The resultdefault and resultDatadefault variables are never actually updated or used, and the result variable is undeclared. Is this an error in the template?

**Comment by RSuter** [comment]
i think this is already fixed (but not released yet): https://github.com/RSuter/NSwag/issues/1683

**Comment by r3tina** [comment]
Yep, that looks suspiciously similar, thank you. Any idea when #1683 will be included in a release?

**Comment by RSuter** [comment]
I'm just releasing v12... so if nothing goes wrong in an hour...
