### ISSUE TITLE
Linq JContainer class converstion in TS client fails

### ISSUE THREAD

**Issue by FabianTe** [RSuter/NSwag#1751]
Hi!

When I use [`JContainer`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Linq_JContainer.htm) in any DTO, NSwag generates this TypeSCript interface:

```typescript
interface JContainer extends any {
    // ... Some uninteresting fields
}
```

The `extends any` part is invalid and causes a syntax error.

Where does this come from? Is it because `JContainer` inherits from `JToken` which in turn inherits from `System.Object`?

**Comment by RSuter** [comment]
I think JContainer should just be treated as object, i.e. any and not show up in the TS, right?

**Comment by RSuter** [comment]
i.e. add JContainer here: 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L429

**Comment by RSuter** [comment]
Maybe we just change it to 

     if (type is JToken || type == typeof(object))

should match all these any types, right?

I think there are no tests for that yet, you can add one...

**Comment by FabianTe** [comment]
Yes, i think so too 👍

**Comment by FabianTe** [comment]
`type is JToken` won't work since we'd need not the type but the actual object itself. I'll introduce more conditions in the if statement for now.

Details on inheritance with typeof / is: https://stackoverflow.com/questions/1218178/c-net-how-can-i-get-typeof-to-work-with-inheritance

**Comment by RSuter** [comment]
You can use type.IsAssignableTo(“JToken), Name) (a NJS extension method)

**Comment by FabianTe** [comment]
I'll verify the fix as soon as possible and then close this issue :)

**Comment by RSuter** [comment]
NJS release: https://github.com/RSuter/NJsonSchema/pull/817
