### ISSUE TITLE
Hide one or more swagger documents

### ISSUE THREAD

**Issue by aaronhudon** [RSuter/NSwag#1757]
Using v12 and am generating multiple swagger documents.  I'd like to hide specific "specs" from the swagger UI.  E.g. hide "Internal".
e.g.
```
services.AddSwaggerDocument(config => config.DocumentName = "v1")
services.AddSwaggerDocument(config => config.DocumentName = "Internal")
services.AddSwaggerDocument(config => config.DocumentName = "External") // -- hide this one from UI
```

**Comment by RSuter** [comment]
You need to load each document in UseSwagger and specify what routes to use in UseSwaggerUi3, like here: https://github.com/RSuter/NSwag/blob/master/src/NSwag.Sample.NETCore20/Startup.cs#L68

**Comment by aaronhudon** [comment]
> You need to load each document in UseSwagger and specify what routes to use in UseSwaggerUi3, like here: https://github.com/RSuter/NSwag/blob/master/src/NSwag.Sample.NETCore20/Startup.cs#L68

Is there any sort of environment variable or state detection available
