### ISSUE TITLE
Default types for ArrayBaseType and ArrayType in CSharpGenerator

### ISSUE THREAD

**Issue by wasmachien75** [RSuter/NSwag#1761]
Hi,

Following code:
```
var settings = new SwaggerToCSharpClientGeneratorSettings
            {
                ClassName = "Client",
                CSharpGeneratorSettings =
                {
                    Namespace = "abc",
                },
                InjectHttpClient = true,
            };
var generator = new SwaggerToCSharpClientGenerator(document, settings);
var _class = generator.GenerateFile();
```
Creates following erroneous (?) client code:
`public System.Collections.Generic.ICollection<string> Ids{ get; set; } = new System.Collections.Generic.ICollection<string>();`

and

`public partial class DropDownList : System.Collections.Generic.Collection<DropDownListEntry>`

I can correct this by specifying both `ArrayType` and `ArrayBaseType`  as `System.Collections.Generic.ObservableCollection` in the `SwaggerToCSharpClientGeneratorSettings`. But according to the docs, those should be the default values. I'm using .NET Core 2.0, NSwag 12.

Is this a bug or am I missing something?

**Comment by RSuter** [comment]
Is this not allowed: 

    public partial class DropDownList : System.Collections.Generic.Collection<DropDownListEntry>

**Comment by RSuter** [comment]
This is a regression of the changed defaults... I think we need a new setting, e.g. ArrayImplementationType (but shorter :-)) to specify the type for using with `new ...` (default assignment of property).

**Comment by RSuter** [comment]
The new (correct) defaults in the next version (v12.0.2): 

![image](https://user-images.githubusercontent.com/2603405/49011474-d4988380-f176-11e8-8b96-56604241838e.png)
