### ISSUE TITLE
Default requried

### ISSUE THREAD

**Issue by stigc** [RSuter/NSwag#1772]
I am building OpenAPI definition for ny WebAPI controllers that deals with a lot of complex classes using lots of references (string and other complex types). All value types are marked as required by default, but all referece types must be marked with a [JsonRequired] attribute. Can I somehow change behaviour so required is default?

**Comment by RSuter** [comment]
DefaultReferenceTypeNullHandling = NotNull?

**Comment by stigc** [comment]
Thanks, what I was looking for.
