### ISSUE TITLE
PropertyNameHandling.Default does not respect casing

### ISSUE THREAD

**Issue by groogiam** [RSuter/NSwag#1778]
I am trying to preserve the exact casing of my .NET poco objects in my generated spec. It appears that PropertyNameHandling.Default does not do this. It seems to camel case everything. Is there a way to preserve the casing on the object as it is defined in .NET?

**Comment by RSuter** [comment]
Change the asp.net core serialier settings

**Comment by RSuter** [comment]
TODO: Update wiki

**Comment by RSuter** [comment]
These properties are now deprecated
