### ISSUE TITLE
x-amazon .... method type

### ISSUE THREAD

**Issue by aaronhudon** [RSuter/NSwag#1788]
I'm looking to augment the swagger json document to include an AWS specific proxy end point.
[https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-any-method.html](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-any-method.html)

The requirement is for the path to contain `{proxy+}` as the path (this works fine), however the method needs to be `x-amazon-apigateway-any-method`

NSwag seems to force method types to be of enum type `SwaggerOperationMethod`.  Is there anyway to override this an simply supply a string during document processing time?

**Comment by RSuter** [comment]
Isnt `x-amazon-apigateway-any-method` a header name?

**Comment by aaronhudon** [comment]
My understanding is that it's a method, like "GET", "PUT", etc.  Which is also how it appears in their generated swagger document.

**Comment by RSuter** [comment]
You are right: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-any-method.html

**Comment by aaronhudon** [comment]
> You are right: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-any-method.html

Any idea for a workaround?

**Comment by RSuter** [comment]
The only way is to change the key to string: 
https://github.com/RSuter/NSwag/blob/master/src/NSwag.Core/SwaggerPathItem.cs#L20

But this is breaking change in the most low-level abstraction... I need to check what the implications for this are.

**Comment by RSuter** [comment]
Create a PR to fix this: https://github.com/RSuter/NSwag/pull/1802
What do you think?
