### ISSUE TITLE
No service for type 'NSwag.SwaggerGeneration.ISwaggerDocumentProvider' has been registered.

### ISSUE THREAD

**Issue by ranouf** [RSuter/NSwag#1790]
Hi,

I discovered that the usual tab I use to configure "Web Api or Asp.Net Core  via Reflection" is now deprecated. So I tried to configure the new tab "Asp.Net Core via API explorer". 

I try to find the how to, I came here :
- https://github.com/RSuter/NSwag/wiki/NSwagStudio
- https://github.com/RSuter/NSwag/wiki/Assembly-loading#net-core

But they are not up-to-date, so I tried to make it work by myself:
![image](https://user-images.githubusercontent.com/1764519/49396195-90712a00-f706-11e8-808e-85804e05b6ef.png)

I created a new branch:
https://github.com/ranouf/TestNotification/tree/ISwaggerDocumentProviderError

First time I tried the generate Output button, I have an explicit error message recommending me to execute : `dotnet dev-certs https --trust`

But then when I wanted to generate the Output again, now, I have this error:

> Launcher directory: C:\Program Files (x86)\Rico Suter\NSwagStudio\NetCore21
> System.InvalidOperationException: Swagger generation failed with non-zero exit code '1'.
> 
> Runtime: NetCore21
>    at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 206
>    at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 268
>    at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
>    at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 77
>    at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 31
>    at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
>    at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
>    at NConsole.CommandLineProcessor.Process(String[] args, Object input)
>    at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54
> 
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: **No service for type 'NSwag.SwaggerGeneration.ISwaggerDocumentProvider' has been registered.**
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentAsync(AssemblyLoader assemblyLoader, IWebHost host, String currentWorkingDirectory) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 251
>    at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerGeneratorCommandEntryPoint.<>c__DisplayClass0_0.<<Process>b__0>d.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerGeneratorCommandEntryPoint.cs:line 30
> --- End of stack trace from previous location where exception was thrown ---
>    at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerGeneratorCommandEntryPoint.cs:line 29
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in C:\projects\nswag\src\NSwag.AspNetCore.Launcher\Program.cs:line 161
> 

What did I miss? Do you have a how-to somewhere I can use to configure the new tab?

Thanks @RSuter for your help :)

**Comment by RSuter** [comment]
In ConfigureServices you need a call to AddSwaggerDocument() or AddOpenApiDocument()... is this already the case?

**Comment by ranouf** [comment]
Not exactly, I have:

https://github.com/ranouf/TestNotification/blob/408fe90ed8fc9d73763ba9ba86c364dfc12fe444/TestNotification/Startup.cs#L26
` services.AddSwaggerGen(c =>`
and 
https://github.com/ranouf/TestNotification/blob/408fe90ed8fc9d73763ba9ba86c364dfc12fe444/TestNotification/Startup.cs#L67
`app.UseSwagger`
and 
`app.UseSwaggerUI`

**Comment by ranouf** [comment]
by searching "AddSwaggerDocument()" on google, I found this wiki:
https://github.com/RSuter/NSwag/wiki/AspNetCore-Middleware

I added the nugget package and I updated startup.cs like:

```
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
              // [...]
              services.AddSwaggerDocument();
              // [...]
        }
```

And not it works perfectly! And I can still continue to use _Swashbuckle.AspNetCore_ nuget package, I thought that conflict can happen.

I will close the issue, thanks for your help.

**Comment by RSuter** [comment]
Yes, the nice thing is that this way you can configure everything in your app. But you could also disable the UseDocumentProvider in NSwagStudio and configure everything there..

**Comment by shivanaru** [comment]
@RicoSuter - running into this with .Net core 3.1, even after adding the above suggestion.

---> Lamar.IoC.LamarMissingRegistrationException: No service registrations exist or can be derived for NSwag.Generation.IOpenApiDocumentGenerator
2>       at Lamar.IoC.Scope.GetInstance(Type serviceType)
2>       at Lamar.Container.Microsoft.Extensions.DependencyInjection.ISupportRequiredService.GetRequiredService(Type serviceType)
2>       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2>       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2>       at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentWithDocumentProviderAsync(IServiceProvider serviceProvider) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 286
2>       at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentAsync(AssemblyLoader assemblyLoader, IServiceProvider serviceProvider, String currentWorkingDirectory) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 276
2>       at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.<>c__DisplayClass0_0.<<Process>b__0>d.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 30
2>    --- End of stack trace from previous location where exception was thrown ---
2>       at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 29
2>       --- End of inner exception stack trace ---
2>       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2>       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2>       at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
2>       at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in C:\projects\nswag\src\NSwag.AspNetCore.Launcher\Program.cs:line 170

**Comment by dmitry-pavlov** [comment]
The seat of the trouble was wrong value for `aspNetCoreEnvironment` setting, which somehow was causing issues with resolving services from `DI`. See #3737
