### ISSUE TITLE
Effect of disabling warnings may be unspecified

### ISSUE THREAD

**Issue by kjkrum** [RSuter/NSwag#1793]
Generated clients disable warnings (#205). Normally this only applies until the end of the file. But I recently saw it claimed that [the compiler behavior is unspecified](https://stackoverflow.com/a/556784/8773089) when warnings are disabled in a partial class, which the generated clients are. The pragma may or may not be in effect in other parts of the partial class. To be safe, please re-enable warnings at the end of each generated class.

**Comment by RSuter** [comment]
So just add this at the end of the file?

**Comment by kjkrum** [comment]
@RSuter `#pragma warning restore` at the end of the generated file, yes.

**Comment by RSuter** [comment]
See commit, ok?
