### ISSUE TITLE
error TS2304: Cannot find name 'FileResponse'

### ISSUE THREAD

**Issue by Sayeeganesh** [RSuter/NSwag#1815]
I used NSwagStudio v12 to generate the TypeScript client class, i expect the API to return file (ExportToExcel), and i see that the generated TypeScript code has references to FileResponse, and i am getting compiler error that "TS2304: Cannot find name 'FileResponse'". What am i missing here? Please help.

![image](https://user-images.githubusercontent.com/45796564/49815874-a749f900-fd64-11e8-8dd5-1669973dbbcf.png)

**Comment by Sayeeganesh** [comment]
this is the swagger snippet. Hope this helps.

`"/api/DictionaryVersion/ExportToExcel": {
      "get": {
        "tags": [
          "DictionaryVersion"
        ],
        "summary": "Action for the dictionary version widget - returns all the versions of all dictionaries as excel spreadsheet",
        "operationId": "ExportToExcel",
        "consumes": [],
        "produces": [
          "application/octet-stream"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },`

**Comment by Sayeeganesh** [comment]
this is our controller web-api method definition, used to generate the Swagger snippet. Please let me know what i am doing wrong.

![image](https://user-images.githubusercontent.com/45796564/49861215-474e6380-fdf3-11e8-923b-821736675bab.png)

**Comment by RSuter** [comment]
I think the workaround is

    [SwaggerResponse(200, typeof(IFormFile))]

**Comment by Sayeeganesh** [comment]
This workaround didnt work. but we added fileresponse class manually and manually edited auto generated code to link the fileresponse as a workaround. 
However i tried the latest nswagstudio now v12.0.7.0, and it is working as expected now. you can close this.

**Comment by simeyla** [comment]
I got some odd unexpected `FileResponse` objects when I accidentally put `[Route("api/[controller]")]` on two partial class definitions.

I'm not doing anything that should require a `FileResponse`. 

So for anyone else having similar issues check if you've got any duplicate attributes such as this

**Comment by RicoSuter** [comment]
This is strange, but the rule is that file response is always generated when the return type cannot be inferred (and is not void)

**Comment by simeyla** [comment]
@RicoSuter I agree - just wanted to add that in there in case it helped anyone else. I did get an error in the console about duplicate attributes (I'm building as part of the build process) - but once I fixed the duplicate attribute the FileResponse went away.  The operation that ended up with FileResponse was a brand new API call and once I fixed the attribute it seemed to work - could always be something else - who knows!

**Comment by jsilvazuniga** [comment]
hello i have the same problem, i'm working with nswagstudio v13.7.1.0

web api
   
        [HttpGet]
        [Route(ApiRoutes.Version.Get)]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public ActionResult<VersionApplication> GetVersionApp(){ ... Ok(Result); }


and file swagger :
"/api/v1/version": {
"get": {
"tags": [
"Version"
],
"operationId": "Version_GetVersionApp",
"produces": [
"text/plain",
"application/json",
"text/json"
],
"responses": {
"200": {
"x-nullable": false,
"description": "",
"schema": {
"$ref": "#/definitions/VersionApplication"
}
},
"404": {
"x-nullable": false,
"description": "",
"schema": {
"$ref": "#/definitions/ProblemDetails"
}
}
}
}
}

**Comment by RicoSuter** [comment]
Should be fixed with v13.7.3
