### ISSUE TITLE
Pragma warning disable with comment incompatible with Resharper code analysis

### ISSUE THREAD

**Issue by ackginger** [RSuter/NSwag#1816]
Hi

In the C# generated client, the pragma disable warning line (#205), with trailing comment is ignored by Resharper code analysis leading to warnings being identified. Obviously this is not an issue with NSwag, however would it be at all possible to move the comment to the line above (or just remove it) since they seem unlikely to fix any time soon?

Thanks very much!

**Comment by RSuter** [comment]
Can you create a pr with this? File.liquid
Thanks

**Comment by ackginger** [comment]
See #1832 
Thanks!

**Comment by RSuter** [comment]
PR merged + released v12.0.9
