### ISSUE TITLE
Swagger UI does not send the API key bearer token for authentication

### ISSUE THREAD

**Issue by Octoate** [RSuter/NSwag#1819]
Hi,
thanks for your hard work on NSwag. It is great to use it and works fine in my environment. However, after the last update, I have switched to the new way to integrate the Swagger UI, but the JWT token authentication of the Swagger UI does not work anymore. In the previous version it worked without a problem.

In the new version, after I retrieved the bearer token and used the authorize button to set it in the Swagger UI, the token is still not send by the UI (see screenshot below):

![swaggerui-authorizebearertoken](https://user-images.githubusercontent.com/1457566/49872253-d0c45c80-fe18-11e8-951e-ec3db9d5f84b.png)

NSwag is configured in the following way:

In "ConfigureServices" in the StartUp class:

            services.AddOpenApiDocument(document => 
            {
                document.DocumentName = "OpenAPI";

                document.Title = Properties.Resources.SympholightWebAPITitle;
                document.Description = Properties.Resources.SympholightWebApiDescription;
                document.DocumentProcessors.Add(
                    new SecurityDefinitionAppender("Bearer", new SwaggerSecurityScheme
                    {
                        Type = SwaggerSecuritySchemeType.ApiKey,
                        Name = Properties.Resources.SwaggerWebUIAuthorizationName,
                        Description = Properties.Resources.SwaggerWebUIAuthorizationDescription,
                        In = SwaggerSecurityApiKeyLocation.Header
                    })
                );
            });

            services.AddSwaggerDocument(document =>
            {
                document.DocumentName = "Swagger v2.0";

                document.Title = Properties.Resources.SympholightWebAPITitle;
                document.Description = Properties.Resources.SympholightWebApiDescription;
                document.DocumentProcessors.Add(
                    new SecurityDefinitionAppender("Bearer", new SwaggerSecurityScheme
                    {
                        Type = SwaggerSecuritySchemeType.ApiKey,
                        Name = Properties.Resources.SwaggerWebUIAuthorizationName,
                        Description = Properties.Resources.SwaggerWebUIAuthorizationDescription,
                        In = SwaggerSecurityApiKeyLocation.Header
                    })
                );
            });

In "Configure" in the StartUp class:

            app.UseSwaggerUi3();
            app.UseSwagger();

If I have a look at the Swagger definition, it seems to be correctly configured, too:

            "securityDefinitions": {
                        "Bearer": {
                                    "type": "apiKey",
                                    "description": "Copy 'Bearer ' + valid JWT token (retrieved by using \"/api/Auth/login\" entrypoint) into the field",
                                    "name": "Authorization",
                                    "in": "header"
                        }
            }

I use ASP.NET Core v2.2 and NSwag v12.0.5 in the project.

Any ideas what I am doing wrong?

**Comment by RSuter** [comment]
You also need to configure the oauth client: 

```
app.UseSwaggerUi3(options =>
{
    options.OAuth2Client = new OAuth2ClientSettings
    {
        ClientId = "..."
        ...
    };

    ...
});
```

**Comment by Octoate** [comment]
Thanks for your fast answer. 
Hmm... do I really have to configure the OAuth2ClientSettings for "bearer token" authentication? I retrieve the token by a GET request with username and password on a login URL and then put "Bearer <token>" into the field in the "Authorize" window. 
So I am not sure why I have to set the OAuth2ClientSettings there!?

**Comment by Octoate** [comment]
Got it... I missed the line

    document.OperationProcessors.Add(new OperationSecurityScopeProcessor("Bearer"));

in the configuration. Now it works as before.
