### ISSUE TITLE
How do you generate a separate swagger.json for a list of controllers?

### ISSUE THREAD

**Issue by youngcm2** [RSuter/NSwag#1821]
We used to use SwaggerExtensions.UseSwaggerUi3(
      this IApplicationBuilder app,
      IEnumerable<Type> controllerTypes,
      Action<SwaggerUi3Settings<WebApiToSwaggerGeneratorSettings>> configure = null,
      SwaggerJsonSchemaGenerator schemaGenerator = null)

to create a separate swagger.json file for different parts of our application. Now that it is obsolete, how do you specify that only certain controllers are part of the document.

**Comment by RSuter** [comment]
Add multiple documents with AddOpenApiDocument and filter with a custom operation processor in each

**Comment by RSuter** [comment]
Or filter based on api group names (api versioning)

**Comment by RSuter** [comment]
Btw: Insert the processor at index 0 so that no unneeded stuff is generated

**Comment by RSuter** [comment]
I’ve added a AddOperationFilter method so that its more obvious/easy to add a filter.
