### ISSUE TITLE
Generation of class does not generate a constructor with mappings

### ISSUE THREAD

**Issue by jabisolutions** [RSuter/NSwag#1826]
Hi,
Got the latest Studio (`v12.0.6`) and generated my service files and encountered a massive issue. We rely on the constructor of many of our classes to build the classes. But since `v12.0.6`, the constructor does not have the mappings. Is that an issue or have you changed the way it works?

Previous
```
constructor(data?: className) {
        super(data);
}
// Super
constructor(data?: ICommand) {
    if (data) {
        for (var property in data) {
            if (data.hasOwnProperty(property))
                (<any>this)[property] = (<any>data)[property];
        }
    }
}
```
Now
```
constructor(data?: className) {
        super(data);
}
// Super
constructor(data?: ICommand) {}
```

Thanks

**Comment by RSuter** [comment]
Probably a regression of this PR: https://github.com/RSuter/NJsonSchema/pull/831

Is it correct that this code is missing in the root dto?

**Comment by RSuter** [comment]
Ah i need to remove the properties.size check

**Comment by RSuter** [comment]
NSwag v12.0.7

**Comment by jabisolutions** [comment]
Thank you!
