### ISSUE TITLE
IApplicationBuilder' does not contain a definition for 'UseSwaggerWithApiExplorer' and no extension

### ISSUE THREAD

**Issue by kudlatiger** [RSuter/NSwag#1844]
I am using .NET Core2.1 to developer Web API

I have added Nuget - NSwag.AspNetCore

> 'IApplicationBuilder' does not contain a definition for 'UseSwaggerWithApiExplorer' and no extension method 'UseSwaggerWithApiExplorer' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)

**Comment by RSuter** [comment]
UseSwaggerWithApiExplorer is deprectated, you should use AddOpenApiDocument(), UseSwagger() and UseSwaggerUi3()

**Comment by RSuter** [comment]
I think in your case the DocumentName in UseSwagger is wrong: 

            options.DocumentName = "swagger";

it must match the document name registered in AddSwaggerDocument (default: "v1")

**Comment by dlucazeau** [comment]
Please, update [this article](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.2&tabs=netcore-cli%2Cvisual-studio-xml).
Few days later a method is now obsolete. It is very difficult to first use this toolchain with this gap between package and examples.

**Comment by RSuter** [comment]
Article is updated, thanks @daveabrock :-)
