### ISSUE TITLE
12.0.9 no longer generates nullable enums for non-required fields

### ISSUE THREAD

**Issue by altso** [RSuter/NSwag#1851]
Given the schema below, I would expect a Pet class to have a `public Sex? Sex { get; set; }` property to be generated. This is how it worked in NSwag.MSBuild 12.0.7. However, starting from 12.0.8, Sex property is no longer nullable `public Sex Sex { get; set; }`.

Please see a detailed diff here: https://github.com/altso/PetStore/compare/12.0.7...master

```yaml
swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
host: petstore.swagger.io
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
definitions:
  Sex:
    type: string
    enum:
      - male
      - female
  Pet:
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      sex:
        $ref: '#/definitions/Sex'
```
I was not able to find a corresponding change log for this change. Please advise if it's a bug or an expected behavior.

**Comment by RSuter** [comment]
Maybe a regression of this: https://github.com/RSuter/NJsonSchema/pull/853

**Comment by altso** [comment]
@RSuter thanks for verifying. Any chance it could be fixed in the next versions?

**Comment by RSuter** [comment]
I couldnt see the problem yet, need to reproduce this in a test. Did you also try with v12.0.9?

**Comment by altso** [comment]
@RSuter I added a test in #1853. Please check it out.

I also tried to reproduce the issue in NJsonSchema repository, but it seems to work just fine there. Most likely I've missed something though.

**Comment by RSuter** [comment]
> I also tried to reproduce the issue in NJsonSchema repository, but it seems to work just fine there. Most likely I've missed something though.

Did you change the SchemaType to Swagger2? Otherwise it's using JsonSchema which has other nullability semantics than Swagger2 or OpenApi3...

**Comment by altso** [comment]
@RSuter I just tried to specify SchemaType, but not sure how to do that. It seems to me that I need to use the method below which require some non-trivial arguments:
```csharp
JsonSchemaSerialization.FromJsonAsync<T>(
    string json, SchemaType schemaType, string documentPath,
    Func<T, JsonReferenceResolver> referenceResolverFactory, IContractResolver contractResolver);
```

Also, I found out that a nullable property is generated if enum type is defined _inline_ instead of using `$ref`:
```json
"definitions": {
  "Pet": {
    "required": [
      "id",
      "name"
    ],
    "properties": {
      "id": {
        "type": "integer",
        "format": "int64"
      },
      "name": {
        "type": "string"
      },
      "sex": {
        "type": "string",
        "enum": [
          "male",
          "female"
        ]
      }
    }
  }
}
```
Produces:
```csharp
public partial class Pet 
{
    // ...
    public PetSex? Sex { get; set; }
}

public enum PetSex
{
    Male = 0,
    Female = 1,
}
```
If not mistaken, `$ref`s are resolved by `JsonReferenceResolver` which in this case is specific to NSwag.

**Comment by RSuter** [comment]
I could repro the problem in njsonschema... it’s an issue there.

**Comment by RSuter** [comment]
I've created a PR: https://github.com/RSuter/NJsonSchema/pull/859
But things like that are dangerous so I need to run integration tests with other, internal projects before merging
