### ISSUE TITLE
What is the purpose of NSwag.Commands?

### ISSUE THREAD

**Issue by plk** [RSuter/NSwag#1854]
I am trying to automate generation of an API controller from openapi spec. I can do this with nswag.exe and have configured an external command to do this in Visual Studio. However, is there a better way to integrate this? I saw the NSwag.Commands package but I can't tell what it does ... (project is not .Net Core so NSwag.ConsoleCore is not an option).

**Comment by RSuter** [comment]
The package `NSwag.Commands` contains all the `IConsoleCommand` implementations (Nconsole) which are the exposed in the runtime specific CLI binaries (nswag.exe, etc.)
