### ISSUE TITLE
OpenAPI 3.0 

### ISSUE THREAD

**Issue by lgadola** [RSuter/NSwag#1857]
I tried to parse an OpenApi 3 spec in NSwag Studio with no success. Entered the json in "JSON schema" - is this the correct way? "Generate outputs" generates an empty Swagger spec.
![nswagopenapi](https://user-images.githubusercontent.com/8344473/50540840-642bba80-0b99-11e9-83f9-b31372b50282.PNG)

**Comment by RSuter** [comment]
Can you post the spec? Json schema is wrong for openapi specs

**Comment by lgadola** [comment]
[sumup.swagger.zip](https://github.com/RSuter/NSwag/files/2716744/sumup.swagger.zip)

**Comment by RSuter** [comment]
You need to select Swagger: 

![image](https://user-images.githubusercontent.com/2603405/50790365-0137d300-12bf-11e9-91d7-669dcebef2d5.png)

But it seems that this spec is invalid, it uses required as boolean on property instead of a string list on an object schema...

**Comment by lgadola** [comment]
Thanks, Rico
I amended the spec. It now parses. However, the generated TS File has errors. It generates function names like:
   meRefundId}(body: any | undefined, txn_id: string): Observable<void> {
[sumup.zip](https://github.com/RSuter/NSwag/files/2758854/sumup.zip)

**Comment by RSuter** [comment]
Can you provide the used operationId? It probably contains } ...

**Comment by lgadola** [comment]
Yes, it does:
    "/customers/{customer_id}": {
      "parameters": [
        {
          "$ref": "#/components/parameters/CustomerID"
        }
      ], ...

**Comment by lgadola** [comment]
tried "create client from operationId" instead of path. That works!
