### ISSUE TITLE
Azure OpenAPI specs - definitions: null

### ISSUE THREAD

**Issue by GuiGimenez** [RSuter/NSwag#1861]
In Azure APIM it generates a specs with a property set as null:

![azure-apim-null-spec](https://user-images.githubusercontent.com/9427625/50578112-f8cf3a80-0e6f-11e9-84cb-aeb3d7e5a3c0.JPG)

which then causes NSwagStudio to throw an error

![azure-apim-null-spec-error](https://user-images.githubusercontent.com/9427625/50578125-3f249980-0e70-11e9-8ff5-a8197f78125d.JPG)

is this require a fix in NSwagStudio to parse null or would be a spec generation issue from Azure ?

**Comment by RSuter** [comment]
> is this require a fix in NSwagStudio to parse null or would be a spec generation issue from Azure ?

I'd say that this is a spec generation issue in Azure - but I'll try to fix it in NSwag/NJS
