### ISSUE TITLE
C# generated client return null as FIleRespone.

### ISSUE THREAD

**Issue by Temppus** [RSuter/NSwag#1890]
In generated C# client, there is fallback to default(FileResponse) return value (in case of 204 HTTP code).
Because FileResponse is IDisposable, I tend to always dispose FileResponse, which triggered:

> System.NullReferenceException: Object reference not set to an instance of an object.

**Possible suggestions:** 

1. Generated method should return plain Task.
2. Generated method should return FileResponse object intsance with fields that came back from reponse. However, this will cause further validation of FileResponse fields by clients.

**Comment by RSuter** [comment]
Can you provide a swagger spec? I think file response is only generated if the response is not "void" but "any" and thus it cannot determine the actual response and just returns a file stream...

**Comment by Temppus** [comment]
Hi I cannot disclose whole spec, but this is definition of that method.

```
  "paths": {
    "/rpc/Examples/Register": {
      "post": {
        "tags": [
          "Rpc/Examples"
        ],
        "operationId": "ExamplesRpc_Register",
        "consumes": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml",
          "application/x-www-form-urlencoded",
          "multipart/form-data",
          "application/octet-stream"
        ],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml",
          "application/x-www-form-urlencoded",
          "multipart/form-data",
          "application/octet-stream"
        ],
        "parameters": [
          {
            "name": "Payload",
            "in": "body",
            "description": "desc",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ExampleData"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "NoContent"
          }
        }
      }
    },
```

**Comment by RSuter** [comment]
I think NSwag currently does not handle 204 as a special case where there is never a response...
