### ISSUE TITLE
Unable to generate return type for ActionResult<T> in ASP.NET Core 2.1 with ProducesResponseType attribute

### ISSUE THREAD

**Issue by LiangZugeng** [RSuter/NSwag#1904]
Our WebAPI is running on ASP.NET Core 2.1, we previously used [ProducesResponseType(200, Type=typeof(SomeType)] for NSwag to generate the result types and everything worked well, now we are switching to use ActionResult<T> so the action signature became like this:

```
[HttpGet("{id}")]
[ProducesResponseType(200)]
[ProducesResponseType(400)]
public ActionResult<string> Get(int id)
```

After the change, NSwag is unable to generate the return type automatically, it produces the swagger json like this:

```
    "/api/Values/{id}": {
      "get": {
        "tags": [
          "Values"
        ],
        "operationId": "Values_Get",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true,
            "format": "int32",
            "x-nullable": false
          }
        ],
        "responses": {
          "200": {
            "description": ""
          },
          "400": {
            "description": ""
          }
        }
      },
```

Note that the 200 response doesn't include the return type, that is not what we expected.

If we completely remove all [ProducesResponseType] attributes on an action, NSwag will generate a 200 response with proper return type, see the following:

```
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
```

```
    "/api/Values": {
      "get": {
        "tags": [
          "Values"
        ],
        "operationId": "Values_GetAll",
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "responses": {
          "200": {
            "x-nullable": true,
            "description": "",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
```

Seems that NSwag doesn't like the combined usage of ProducesResponseType and ActionResult<T> under ASP.NET Core 2.1, we tried to upgrade the app framework to netcoreapp2.2 and the problem is gone, in our case we cannot make the upgrade in the production as one of the app dependencies isn't compatible with ASP.NET Core 2.2, so please kindly help investigate the issue.

We also prepared a repro code at https://github.com/LiangZugeng/ASPNetCoreWebAPISwagger.git, before you run it just make sure you have .NET Core SDK 2.1 installed on your machine (if you only have .NET Core SDK 2.2 installed the app will use 2.2 runtime regardless what app framework is specified in the .csproj file).

**Comment by RSuter** [comment]
I’d say this is as expected of the asp.net api explorer. You need to specify the type explicitly in the second argument of the ProducesResponseTypeAttribute...

**Comment by LiangZugeng** [comment]
@RSuter thanks for the quick response.

The issue doesn't exist on ASP.NET Core 2.2 though, if it's expected of the ASP.NET API explorer then it shouldn't work on 2.2. Please try change the `<TargetFramework>netcoreapp2.1</TargetFramework>` to `<TargetFramework>netcoreapp2.2</TargetFramework>` in `ASPNetCoreWebAPISwagger.csproj` to see the produced swagger.json content.

**Comment by RSuter** [comment]
Maybe this is a feature which has been added in the 2.2 release? We caould add a setting to manually add this behavior.. it is already implemented in the old generator...

**Comment by LiangZugeng** [comment]
Could you please point me to some source files (preferably methods) in NSwag swagger generator for the ProducesResponseType and ActionResult<T> matching and processing, I can spend some time doing some debugging to find out whether it's a new feature in 2.2 release as I'm curious why this issue is there. 😄

**Comment by LiangZugeng** [comment]
Done the debugging and searching. Figured that out, the issue was caused by [a bug in API Explorer](https://github.com/aspnet/Mvc/issues/7871), it was fixed in .net core runtime 2.1.3. I was running 2.1.2 so the issue was there, installed the latest version of .NET Core SDK 2.1.503 (contains .NET Core runtime 2.1.7) and the issue was gone.

Thanks for the help @RSuter, this issue is closed.

**Comment by IronSean** [comment]
This seems to be happening again in .Net 5
