### ISSUE TITLE
Exclude enum generation

### ISSUE THREAD

**Issue by Inzanit** [RSuter/NSwag#1908]
This may seem like an odd question/request - however, I am currently modifying NSwag to do some specific stuff for work. NSwag works beautifully and generates everything properly client side; we have repeated issues with enum generation, as it excludes any additional annotations we decorate enums with.

TL;DR We have a common library where we have all enums and we'd like to use this instead of letting NSwag duplicate the enum definitions.

I know there is a way of disabling all DTO generation, but this is undesirable, we only want enums to **not** be generated. Is this possible?

I've been looking through the code and it seems I'd need to actually go deeper and modify (or hack) the NJsonSchema code?

**Comment by RSuter** [comment]
You can exlude specific types with ExcludedTypes (no regex etc) or you can generate via c# and remoce some types from the artifact collection or we add a new setting

**Comment by RSuter** [comment]
... everything dto specific is in njsonschema

**Comment by Inzanit** [comment]
Thanks a lot for the very quick response, I assume you'd be referring to somewhere near here, https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/CSharpTypeResolver.cs#L82

**Comment by RSuter** [comment]
Id gowith this: https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration/CodeGeneratorSettingsBase.cs#L30

**Comment by RSuter** [comment]
This exposes a list of individually generated types/files but this is not yet fully exposed in nswag yet i think: https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration/GeneratorBase.cs#L55

**Comment by Inzanit** [comment]
Thanks very much 👍
