### ISSUE TITLE
Web Api 2 file upload example in wiki is not a valide example

### ISSUE THREAD

**Issue by squadwuschel** [RSuter/NSwag#1917]
The example posted in the wiki: 

https://github.com/RSuter/NSwag/wiki/WebApiToSwaggerGenerator#file-uploads 

seems not to be a valide web api example. Because in web api you can't use HttpPostedFile oder HttpPostedFileBase 

https://stackoverflow.com/questions/10320232/how-to-accept-a-file-post

I can't find any examples for web api 2 which uses parameters they allways only this.Request ...

perhaps someone has a good example how to implement file upload with web api 2

**Comment by RSuter** [comment]
Then you probably need to implement a custom operation processor to add this “dynamic” parameter

**Comment by squadwuschel** [comment]
I've created my own Operation Processor

    public class SwaggerFilChunkUploadOperationProcessor : IOperationProcessor
    {
        public Task<bool> ProcessAsync(OperationProcessorContext context)
        {
            var data = context.OperationDescription.Operation.Parameters;
            
            //File upload
            data.Add(new SwaggerParameter()
            {
                IsRequired = true,
                Name =  "file",
                Description = "filechunk",
                Type = JsonObjectType.File,
                Kind = SwaggerParameterKind.FormData
            });
            
            //custom formdata
            data.Add(new SwaggerParameter()
            {
                IsRequired = true,
                Name = "file-name",
                Description = "the original file name",
                Type = JsonObjectType.String,
                Kind = SwaggerParameterKind.FormData
            });

            return Task.FromResult(true);
    }

    //defined as Attribute Usage, so you can use the attribute in your Controller
    public class SwaggerFileChunkUploadAttribute : SwaggerOperationProcessorAttribute
    {
        public SwaggerFileChunkUploadAttribute() : base(typeof(SwaggerFilChunkUploadOperationProcessor))
        {
        }
    }


In your controller you can now use
       
       [ValidateMimeMultipartContentFilter]
       [SwaggerFileChunkUpload]
        public async Task<IHttpActionResult> Upload(long ordernumber)
        {
             //process your file here!
        }

**Comment by AbuDawood** [comment]
Hi
I have same problem and tried to use @squadwuschel 's custom method
the operation succeeds when I have used OpenApi (NSwag.Generation.Processors) package.
However, using NSwag.SwaggerGeneration caused a cast exception during the generation process (using the desktop app)
Unable to cast object of type''  to type 'NSwag.Generation.Processors.IOperationProcessor'.

Can someone explain why?
