### ISSUE TITLE
Bump Newtonsoft.Json version

### ISSUE THREAD

**Issue by LeonidEfremov** [RSuter/NSwag#1923]
C#-client generated code
```c#
[System.CodeDom.Compiler.GeneratedCode("NSwag", "12.0.12.0 (NJsonSchema v9.13.15.0 (Newtonsoft.Json v11.0.0.0))")]
public partial interface IClient
{
}
```
@RSuter can you bump `Newtonsoft.Json` to `12.0.1`?

**Comment by RSuter** [comment]
It is actually compiled against v9 but asp.net core is coming with v11 - if you need v12, just manually install it it in your app to override this.
