### ISSUE TITLE
OAuth2ClientSettings.AdditionalQueryStringParams is readonly

### ISSUE THREAD

**Issue by rjmiller-revint** [RSuter/NSwag#1932]
According to the sample below it says to set the AdditionalQueryStringParams, but it seems to be readonly.  Is there a workaround for this in OAuth2ClientSettings?

https://github.com/aribakker/AspNetCore.AzureAd.Swagger/blob/4b899c72e69de6656029390a160820a7714a923f/Startup.cs#L87

**Comment by RSuter** [comment]
This is a swashbuckle issue and not nswag
