### ISSUE TITLE
C# generated illegal field name

### ISSUE THREAD

**Issue by IvanJosipovic** [RSuter/NSwag#1950]
When converting the Kubernetes swagger.json to c# client, a field is generated with an illegal name.

Swagger.json
https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

NSwag toolchain v12.0.13.0 (NJsonSchema v9.13.17.0 (Newtonsoft.Json v11.0.0.0))
Default settings

```
    /// <summary>JSONSchemaProps is a JSON-Schema following Specification Draft 4 (http://json-schema.org/).</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.17.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class JSONSchemaProps 
    {   
        [Newtonsoft.Json.JsonProperty("$schema", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string $schema { get; set; }
    
```

**Comment by RSuter** [comment]
Needs to be fixed here: 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/CSharpPropertyNameGenerator.cs

**Comment by IvanJosipovic** [comment]
Sent a PR 👍
