### ISSUE TITLE
Generate TypeScript Client by writing C# code

### ISSUE THREAD

**Issue by sankp** [RSuter/NSwag#1964]
Hello,

Is there any document available to write typescript client using C# code. So that during my MVC project build only I can generate apiclient.ts 
Any sample code will be helpful which doesn't use nswag tool but just configuration file and nuget package.

**Comment by RSuter** [comment]
Check out the TypeScript unit tests, e.g. 

https://github.com/RSuter/NSwag/blob/master/src/NSwag.CodeGeneration.TypeScript.Tests/AxiosTests.cs#L34
