### ISSUE TITLE
怎么添加header ，请求的时候

### ISSUE THREAD

**Issue by beibeijerry** [RSuter/NSwag#1966]

**Comment by RSuter** [comment]
Please write issues in english and add a description

**Comment by kkman021** [comment]
老乡，参考这个[官网连结](IOperationProcessor)

去改变 Operation 的项目，OperationProcessorContext context。
`
context.OperationDescription.Operation.Parameters.Add(new SwaggerParameter()
{
}
`

提示就到这里啦！老乡加油！！

PS： RSuter 的回应是请你发 issues 的时候写英文同时增加描述！

**Comment by kkman021** [comment]
> 
> 
> Please write issues in english and add a description

I just write the tip to beibeijerry with chinese.
He's issue just need know How to add http header when call the api.
