### ISSUE TITLE
Swagger UI  Error :  model has recursive relationship 

### ISSUE THREAD

**Issue by good821018** [RSuter/NSwag#1967]
the `Menu`  model has a reference type self, looks like :
```
public class Menu {
     //....
     public Menu Parent { get;set; } 
}
```
it will cause swagger ui parse error !
![image](https://user-images.githubusercontent.com/5648078/53073751-e1cdd000-3523-11e9-9fb5-0709cfc93439.png)

**How to fix**
try update swagger ui 3 javascript ?

because I test [swagger ui 3 demo](https://petstore.swagger.io/)  not broken.

**version**
Nswag 12. 0.14

**Comment by RSuter** [comment]
So we just need to use latest Swagger UI?
