### ISSUE TITLE
XmlDoc Example

### ISSUE THREAD

**Issue by dr-consit** [RSuter/NSwag#1972]
I had a lot of trouble getting NSwag to include basic XmlDoc <example> tag text into the swagger documentation. 
In case someone else might want to do the same, or something similar, I would like to leave my "solution" somewhere useful (maybe in the wiki?).
I'm just not sure where is the best place to put this information.

Here's a pastebin with the relevant information: https://pastebin.com/LYrsSLnt

**Comment by RSuter** [comment]
What exactly are you trying to solve?

Maybe you can add this here: https://github.com/RSuter/NJsonSchema/wiki/XML-Documentation

**Comment by dr-consit** [comment]
Well the idea is to get NSwag to take this:

```
        /// <summary>
        /// Really cool UUID property.
        /// </summary>
        /// <example>
        /// 12345678-9012-3456-7890-123456789012
        /// </example>
        [Required]
        public Guid UUID { get; set; }
```
and output this:

 ```
       "UUID": {
          "type": "string",
          "description": "Really cool UUID property.",
          "format": "guid",
          "minLength": 1,
          "example": "12345678-9012-3456-7890-123456789012"
        }
```

That is: take the example string from the XmlDoc example tag and output it in the Json as is.

I will try to add this code example to the Wiki under XML-Documentation if you think that is the best place and approach.

**Comment by RSuter** [comment]
I think you could implement a custom schema processor which reads this xml docs after a DTO schema has been created: 

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/ISchemaProcessor.cs

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/JsonSchemaGeneratorSettings.cs#L97

**Comment by dr-consit** [comment]
I tried. I couldn't find a reasonable way to get the `MemberInfo` from the `SchemaProcessorContext`.
Are you implying that there is something wrong with my implementation using a custom contract resolver?
It does work as intended.

**Comment by RSuter** [comment]
You probably can get the property info from SchemaProcessorContext.Type and the Settings.ContractResolver.GetProperties(type) 

The custom contract resolver works but the idea is to use the same contract resolver for actually serializing/deserializing data (e.g. with NSwag/Web API) and then you'll end up with unwanted properties... But if it works for you as expected you keep it as is...

**Comment by dr-consit** [comment]
> You probably can get the property info from SchemaProcessorContext.Type and the Settings.ContractResolver.GetProperties(type)

But the Type is just something like `Int64` or `String`.

**Comment by RSuter** [comment]
The schema processor should be called for the DTO class and then the int/string should be a property of it, or not?

**Comment by dr-consit** [comment]
OK. But then what you propose is to recurse the properties of the DTO classes in the schema processor and patch them up there?
This does seem rather more involved. And I'm not sure I understand the advantages.
The desired end result is still the same. Which, as far as I understand your reservations with using the custom contract resolver, will result in the same issues (if any) with de-serializing the data?

I mean at the time of de-serialization, two identical inputs should result in the same output, right?

**Comment by RSuter** [comment]
Just checked your code again, it looks fine as it really just adds an JsonSchemaExtensionDataAttribute which is only picked up by the NJsonSchema generator - so i think your solution is fine...

**Comment by dr-consit** [comment]
OK. I have updated the Wiki with my example code.
