### ISSUE TITLE
How to update GeneratorSettings from UseSwaggerUi3() in Asp.NetCore to something that is not marked as deprecated?

### ISSUE THREAD

**Issue by SeppPenner** [RSuter/NSwag#1974]
How can I update the GeneratorSettings from `UseSwaggerUi3()` in Asp.NetCore to something that is not marked as deprecated? I am using the following code (Which is deprecated and therefore ignored...)

```csharp
app.UseSwaggerUi3(
	settings =>
	{
		settings.GeneratorSettings.DefaultPropertyNameHandling = PropertyNameHandling.CamelCase;
		settings.GeneratorSettings.OperationProcessors.TryGet<ApiVersionProcessor>().IncludedVersions = new[] { "1.0" };
		settings.GeneratorSettings.Title = "My Api";
		settings.GeneratorSettings.Description = "REST interface for my Api.";
	});
```

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/wiki/AspNetCore-Middleware

**Comment by SeppPenner** [comment]
Ok, so far I have the following piece of code:
```csharp
services.AddSwaggerDocument(document =>
{
	document.DocumentName = "My Api";
	document.PostProcess = d =>
	{
		d.Info.Title = "My Api";
		d.Info.Description = "REST interface for my Api.";
	};
	document.OperationProcessors.Add(new ApiVersionProcessor { IncludedVersions = new[] { "1.0" } });
});
```
in the `public void ConfigureServices(IServiceCollection services)` method. I did not find the `DefaultPropertyNameHandling`. Is there a way to set this, too?

**Comment by SeppPenner** [comment]
Thank you for your reply. I now used this code:
```csharp
services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1).AddJsonOptions(
options =>
{
	options.SerializerSettings.ContractResolver = new DefaultContractResolver
	{
		NamingStrategy = new CamelCaseNamingStrategy()
	};
});
```

where `DefaultContractResolver` and `CamelCaseNamingStrategy` come from the `Newtonsoft.Json.Serialization` namespace.

> ApiVersionProcessor has been deprecated, see #1701 
Good to know, I am now using `d.Info.Version = "1.0.0";` for that one.
