### ISSUE TITLE
Asp.NetCore: How can I tell Nswag to only show the properties from base classes but not the base class itself in the models section?

### ISSUE THREAD

**Issue by SeppPenner** [RSuter/NSwag#1980]
One example on that:

Let's say there is a base class like that:

```csharp
public class BaseClass
{
    public long Id {get; set;}
	
    public string Name {get; set;}
	
    public string Email {get; set;}
}
```

and a class that inherits:

```csharp
public class RegularClass : BaseClass
{
    public string Address {get; set;}
}
```

In the models class, I would like to see only:

```
RegularClass --> 
{
    id integer($int64)
    name string
    email string
    address string
}
```

but not the `BaseClass` type. Is this possible somehow?

**Comment by RSuter** [comment]
Add JsonSchemaFlattenAttribute on the RegularClass class

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Annotations/JsonSchemaFlattenAttribute.cs

**Comment by SeppPenner** [comment]
Thank you for the fast reply again. This is what I was searching for.
