### ISSUE TITLE
TS invalid

### ISSUE THREAD

**Issue by andmattia** [RSuter/NSwag#1997]
I try to use NSwag to generate my proxy class but TS is invalid.

```ts
export class customAttributeData {
        attributeType: type;
        constructor : constructorInfo;
        constructorArguments: iListOfCustomAttributeTypedArgument;
        namedArguments: iListOfCustomAttributeNamedArgument;
    }
```

My source is an .NET 4.6.1 Application. I need any time to rename constructor -> constructors

**Comment by RSuter** [comment]
We need to rename (this) reserved words here: 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.TypeScript/TypeScriptPropertyNameGenerator.cs

**Comment by andmattia** [comment]
I can extend in some option on Nswag configuration file?

**Comment by RSuter** [comment]
You need to write an own cmd line app to provide an own implementation at the moment... or we fix this in the default one..
