### ISSUE TITLE
NSwag generates wrong code for the Cherwell API  

### ISSUE THREAD

**Issue by Linus62** [RSuter/NSwag#1998]
I am trying the same as ABotond in issue 797 and I get not compilable C# code as well.
I was just trying to generate a C# Client for the Cherwell API:
https://cherwellsupport.com/CherwellAPI/swagger/docs/all

In generated code at line 16572 I get the following code:
```
[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.13.22.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class KeyValuePair`2OfOfStringAndMscorlibAnd_0AndCulture=neutralAndPublicKeyToken=b77a5c561934e089AndOfStringAndMscorlibAnd_0AndCulture=neutralAndPublicKeyToken=b77a5c561934e089 
    {
        [Newtonsoft.Json.JsonProperty("key", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Key { get; set; }
    
        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Value { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
    
        public static KeyValuePair`2OfOfStringAndMscorlibAnd_0AndCulture=neutralAndPublicKeyToken=b77a5c561934e089AndOfStringAndMscorlibAnd_0AndCulture=neutralAndPublicKeyToken=b77a5c561934e089 FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<KeyValuePair`2OfOfStringAndMscorlibAnd_0AndCulture=neutralAndPublicKeyToken=b77a5c561934e089AndOfStringAndMscorlibAnd_0AndCulture=neutralAndPublicKeyToken=b77a5c561934e089>(data);
        }
    
    }
```

Seems that NSwag is not able to deal with ref-constructs found on line 6360 in the source json:
```
        "parameters": {
          "type": "array",
          "items": { "$ref": "#/definitions/System.Collections.Generic.KeyValuePair`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]" }
        },

```

_Originally posted by @Linus62 in https://github.com/RSuter/NSwag/issues/797#issuecomment-469234422_

**Comment by RSuter** [comment]
You should not use type names like

    System.Collections.Generic.KeyValuePair`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]

in Swagger specs - this is .NET specific and this is a [leaky abstraction](https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/)

**Comment by RSuter** [comment]
But otherwise we need to fix this in the DefaultTypeNameGenerator: 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/DefaultTypeNameGenerator.cs

Or you can provide an own type name generator: 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration/CodeGeneratorSettingsBase.cs#L38

**Comment by Linus62** [comment]
Hi Reto

Thanks for the fast reply!

I tried it with my own TypeNameGenerator returning `KeyValuePair<string,string>`:
```
        public override string Generate(JsonSchema4 schema, string typeNameHint, IEnumerable<string> reservedTypeNames)
        {
            if (!string.IsNullOrEmpty(typeNameHint) && typeNameHint.Contains("KeyValuePair`2"))
            {
                var match = Regex.Match(typeNameHint,@"^.*KeyValuePair`2\[\[([a-zA-Z+\.]+),.*\],\[([a-zA-Z+\.]+),.*\]\]");
                var customType = $"KeyValuePair<{match.Groups[1]},{match.Groups[2]}>";
                return base.Generate(schema, customType);
            }
            // else
            return base.Generate(schema, typeNameHint, reservedTypeNames);
        }
```
This compiles well. But now multiple root classes with their own `ConvertToString` method are generated (12 times!), logically causing the following bugs:
Error	CS0111	Type 'IdwCherwellRestAPI' already defines a member called 'ConvertToString' with the same parameter types

**Comment by Linus62** [comment]
Probably that the generator produces a root class (as defined in the `ClassName` property of the settings for every SwaggerTag in the source. 
The Cherwell API defines 13 tags and 2 versions ("V1" and "V2").

I am a newbie on Swagger and just trying to generate a working C# client for the Cherwell API...

**Comment by RSuter** [comment]
So these parameters property is your only problem?

**Comment by RSuter** [comment]
The problem is that the swagger spec is just bad in this case - it describes a string/string dictionary as a list of key-value-pairs with .net types (leaky abstraction). My proposal is to download the spec and fix it manually: 

Change the "parameters" property to just

            "parameters": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            }

so that just a dictionary<string, string> is generated

**Comment by Linus62** [comment]
Hi Rico

Thanks for this easy solution for the `KeyValuePair` problem. I ended up with the following:
```using KeyValuePairString = KeyValuePair<string,string>;```
But your solution is probably easier in usage.

No, my only problem right now is that it generates multiple service root classes with the same name.
This causes a lot of "already defines ..." compilation errors in the generated code.
```
Error CS0111 Type 'IdwCherwellRestAPI' already defines a member called 'ConvertToString' with the same parameter types
.....
Error CS0111 Type 'IdwCherwellRestAPI' already defines a member called '.ctor' with the same parameter types
....
Error CS0102 The type 'IdwCherwellRestAPI' already contains a definition for '_settings'
```
etc.

**Comment by RSuter** [comment]
It generates multiple classes with the same name?

**Comment by Linus62** [comment]
Yes, 12 times.
You should try it by yourself. The https://cherwellsupport.com/CherwellAPI/swagger/docs/all is available for everyone.

**Comment by RSuter** [comment]
I tried it myself and if I replace

    KeyValuePair`2OfOfStringAndMscorlibAnd_0AndCulture=neutralAndPublicKeyToken=b77a5c561934e089AndOfStringAndMscorlibAnd_0AndCulture=neutralAndPublicKeyToken=b77a5c561934e089

with just

    KeyValuePair

it compiles and looks fine... check out this project:

[ClassLibrary1.zip](https://github.com/RSuter/NSwag/files/2949909/ClassLibrary1.zip)

Will fix the compile problem in NJS - but the output will be ugly class name - but at least it will directly compile...

**Comment by Linus62** [comment]
By the way: I figured out why it generated multiple definitions of the service root class:

I configured my generator like this:
```
            var settingsCs = new SwaggerToCSharpClientGeneratorSettings
            {
                ClassName = "IdwCherwellRestAPI",
                CSharpGeneratorSettings =
                {
                    Namespace = "Idw.Cherwell.RestAPI",
                    SchemaType = SchemaType.Swagger2,
                },
            };

```
 **ClassName = "IdwCherwellRestAPI"** seems to invalidate the SwaggerTags which produce usually the class name, resulting in multiple definitions of this class.

**Comment by RSuter** [comment]
You need to use the {controller} placeholder in the class name
