### ISSUE TITLE
Swagger page loads HTTP in 'try it out' instead of HTTPS

### ISSUE THREAD

**Issue by pietervdvn** [RSuter/NSwag#2002]
Our swagger scheme supports only requests via HTTPS (or at least, this is what the swagger.json is telling me).

Despite this, `https//mydomain.com/swagger/index.html` only shows that HTTP is supported. The _try it out_ feature hence also only uses http, which firefox blocks as being "mixed content".

**Comment by RSuter** [comment]
You can manually change the protocol scheme in PostProcess

https://github.com/RSuter/NSwag/wiki/AspNetCore-Middleware#post-process-the-served-swagger-specification
