### ISSUE TITLE
facing problem generating nullable DateTime property

### ISSUE THREAD

**Issue by Sudhir89** [RSuter/NSwag#2021]
I am facing issue, while generating Nullable DateTime property written in API.
API Definition for Date looks like:
-------------------------------------
       [Required]
        [DataMember(Name = "completionDate")]
        public DateTime? CompletionDate { get; set; }
---------------------------------------
Below is my NSwag file for Code Generation:
----------------------------------------------
{
  "runtime": "WinX64",
  "defaultVariables": null,
  "swaggerGenerator": {
    "fromSwagger": {
      "url": "https://someservice.net/swagger/1.0.0/swagger.json",
      "output": null
    }
  },
  "codeGenerators": {
    "swaggerToCSharpClient": {
      "clientBaseClass": null,
      "configurationClass": null,
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateDtoTypes": true,
      "injectHttpClient": false,
      "disposeHttpClient": true,
      "protectedMethods": [],
      "generateExceptionClasses": true,
      "exceptionClass": "SwaggerException",
      "wrapDtoExceptions": true,
      "useHttpClientCreationMethod": false,
      "httpClientType": "System.Net.Http.HttpClient",
      "useHttpRequestMessageCreationMethod": false,
      "useBaseUrl": true,
      "generateBaseUrlProperty": true,
      "generateSyncMethods": false,
      "exposeJsonSerializerSettings": false,
      "clientClassAccessModifier": "public",
      "typeAccessModifier": "public",
      "generateContractsOutput": false,
      "contractsNamespace": null,
      "contractsOutputFilePath": null,
      "parameterDateTimeFormat": "s",
      "generateUpdateJsonSerializerSettingsMethod": true,
      "serializeTypeInformation": false,
      "queryNullValue": "",
      "className": "{controller}Client",
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "additionalNamespaceUsages": [],
      "additionalContractNamespaceUsages": [],
      "generateOptionalParameters": false,
      "generateJsonMethods": true,
      "enforceFlagEnums": false,
      "parameterArrayType": "System.Collections.Generic.IEnumerable",
      "parameterDictionaryType": "System.Collections.Generic.IDictionary",
      "responseArrayType": "System.Collections.ObjectModel.Collection",
      "responseDictionaryType": "System.Collections.Generic.Dictionary",
      "wrapResponses": false,
      "wrapResponseMethods": [],
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "namespace": "SomeController.Client",
      "requiredPropertiesMustBeDefined": true,
      "dateType": "System.DateTime",
      "jsonConverters": null,
      "dateTimeType": "System.DateTime",
      "timeType": "System.TimeSpan",
      "timeSpanType": "System.TimeSpan",
      "arrayType": "System.Collections.ObjectModel.Collection",
      "arrayInstanceType": null,
      "dictionaryType": "System.Collections.Generic.Dictionary",
      "dictionaryInstanceType": null,
      "arrayBaseType": "System.Collections.ObjectModel.Collection",
      "dictionaryBaseType": "System.Collections.Generic.Dictionary",
      "classStyle": "Poco",
      "generateDefaultValues": true,
      "generateDataAnnotations": true,
      "excludedTypeNames": [],
      "handleReferences": false,
      "generateImmutableArrayProperties": false,
      "generateImmutableDictionaryProperties": false,
      "jsonSerializerSettingsTransformationMethod": null,
      "templateDirectory": null,
      "typeNameGeneratorType": null,
      "propertyNameGeneratorType": null,
      "enumNameGeneratorType": null,
      "serviceHost": null,
      "serviceSchemes": null,
      "output": "SomeControllerServiceAPIClient.Core.cs"
    }
  }
------------------------------------------------------------
Below is the output, that i am getting, without Nullable declaration of Date field:
----------------------------------------------------------
        [Newtonsoft.Json.JsonProperty("completionDate", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTime CompletionDate { get; set; }
------------------------------------------------------------

Could you please help me out resolving the issue?

Thanks in advance,
Sudhir

**Comment by RSuter** [comment]
And what do you expect?

**Comment by Sudhir89** [comment]
Hi,
I want like this:
----------------------------------------------
        [Newtonsoft.Json.JsonProperty("completionDate", Required = Newtonsoft.Json.Required.Default, 
        NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTime? CompletionDate { get; set; }
----------------------------------------------

**Comment by Sudhir89** [comment]
Hello,
This issue is solved. I just removed "Required" attribute from API definition and now definition is like:
=================================
   ~~[Required]~~
    [DataMember(Name = "completionDate")]
    public DateTime? CompletionDate { get; set; }
=================================
