### ISSUE TITLE
Spec generated for OpenAPI 3 wrongly contains „consumes“ and „produces“ props

### ISSUE THREAD

**Issue by meiedomi** [RSuter/NSwag#2023]
In OpenAPI 3 specification files, top-level MIME properties „consumes“ and „produces“ are no longer allowed, but NSwag still generates them.

Related code:
https://github.com/RSuter/NSwag/blob/master/src/NSwag.Core/SwaggerDocument.Serialization.cs#L85

**Comment by RSuter** [comment]
Will be in v12.0.16 soon
