### ISSUE TITLE
Generated Typescript expecting wrong Content Type

### ISSUE THREAD

**Issue by ElGusanito** [RSuter/NSwag#2032]
I've got a web API method returning content type of application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:

       [Route("Bookings")]
        [HttpGet]
        [Produces(contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")]
        public async Task<ActionResult<Stream>> GetBookings()...

In swagger.json, I can see that the produces content type for this operation is correct.

But in the autogenerated client , this routine blows up because it's expecting json but it's getting something else and I get an error indicating an invalid token in JSON:

        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? Stream.fromJS(resultData200) : new Stream();
            return _observableOf(result200);
            }));

Shouldn't the generated client have something in place of JSON.Parse?

**Comment by RSuter** [comment]
This is the problem:
https://github.com/RSuter/NSwag/blob/master/src/NSwag.Core/SwaggerResponse.cs#L120

For now you need to use "application/octet-stream" but maybe it would be better to treat everything as binary which is not JSON...

**Comment by ElGusanito** [comment]
Thanks.  That does get over that problem but it raises another issue....

**Comment by RSuter** [comment]
> but it raises another issue....

Which one?

**Comment by GeorgDangl** [comment]
Please see #2061, it now fails to recognize values like `application/vnd.model+json` as object responses.
