### ISSUE TITLE
YamlDotNet.Signed - Method not found: 'YamlDotNet.Serialization.DeserializerBuilder.Build()'

### ISSUE THREAD

**Issue by AlaricDelany** [RSuter/NSwag#2037]
Hey there,
I Have the Same Problem described here:
https://github.com/kubernetes-client/csharp/issues/224

When i try to Generate a CSharp Client based on a Yaml file it fails with the Following Error Message:
Method not found: 'YamlDotNet.Serialization.Deserializer YamlDotNet.Serialization.DeserializerBuilder.Build()'.

Cause the Return Type has been Updated from Deserializer to IDeserializer.

I am using the Package: `YamlDotNet.Signed` for parsing the yaml.
I am just doing:
`var document = await SwaggerYamlDocument.FromFileAsync(yamlPath);`

A Update of the YamlDotNet.Signed Package to Version >= 5.1.0 instead of: >= 5.0.1 should do the trick.

Regards,
Alaric

**Comment by AlaricDelany** [comment]
Thank you, it works

**Comment by RSuter** [comment]
How is that possible? Its not yet released in nswag...
