### ISSUE TITLE
3.0 OAS generated using NSwag has non-compliant schema that contains 'consumes'

### ISSUE THREAD

**Issue by safalkishore** [RSuter/NSwag#2040]
We notice the below on the OAS 3 generated using NSwag on a .NET Core Api project

 "consumes": [
    "application/json-patch+json",
    "application/json",
    "text/json",
    "application/*+json"
  ],

As per the guidance on OAS 3.0  as shown below, this element should not be present on the 3.0 schema

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#fixed-fields

This is causing parse errors while using tools like 'Swagger Editor' as shown below :

Structural error should NOT have additional properties
additionalProperty: consumes
Jump to line 0

**Comment by safalkishore** [comment]
Version of NSwag used - 

"x-generator": "NSwag v12.0.13.0 (NJsonSchema v9.13.17.0 (Newtonsoft.Json v12.0.0.0))"

**Comment by RSuter** [comment]
Already fixed: https://github.com/RSuter/NSwag/issues/2023
