### ISSUE TITLE
Epic: Replace template engine

### ISSUE THREAD

**Issue by RSuter** [RSuter/NSwag#263]
**Missing feature: Compile template at runtime... so that templates can be customized on a per template basis**

In the future, we will use **DotLiquid** as template engine in NSwag and NJsonSchema to support template customizations, etc.

**Documentation: https://github.com/RSuter/NSwag/wiki/Templates**
Also see https://github.com/NSwag/NSwag/wiki/Roadmap

Implications: 

- The template model classes are part of the public API and must be stable after this changes (because people start to customize parts of the templates which are coupled to the model classes).

**Comment by rsuter** [comment]
In the future, we will use DotLiquid as template engine to support template customizations, etc.

See https://github.com/NSwag/NSwag/wiki/Roadmap

**Comment by RSuter** [comment]
Ref: https://github.com/RSuter/NJsonSchema/issues/404

**Comment by RSuter** [comment]
https://github.com/RSuter/NJsonSchema/pull/515

**Comment by RSuter** [comment]
T4 to Liquid regexes: 

```
<#=Model.(.*?)#>
{{ $1 }}

<#=(.*?)#>
{{ $1 }}

<#(.*?)#>
{%- $1 -%}
```

**Comment by RSuter** [comment]
https://github.com/RSuter/NJsonSchema/wiki/Templates

**Comment by RSuter** [comment]
Notepad++ language for liquid: 


[liquid-notepadpp.zip](https://github.com/RSuter/NSwag/files/1402189/liquid-notepadpp.zip)

**Comment by RSuter** [comment]
Documentation https://github.com/RSuter/NJsonSchema/wiki/Templates
