### ISSUE TITLE
Feature Request: Use ASP.NET Core services

### ISSUE THREAD

**Issue by SebastianStehle** [RSuter/NSwag#280]
In ASP.NET Core there are services for almost everything, e.g. detecting controllers and so on. I think it is better to use these services to find controllers and actions. This means that the documentation also shows all the special adjustments that the user made (e.g. controllers in another assembly, other prefixes, special actions, ...).

You can also get rid of this ugly config: typeof(Startup).GetTypeInfo().Assembly

**Comment by rsuter** [comment]
This would be a complete rewrite of the Swagger generator

**Comment by SebastianStehle** [comment]
I know, but it would be compliant to asp.net core and there already options to show or hide a controller for example.

http://stackoverflow.com/questions/38368750/dotnetcore-is-apiexplorer-supported-and-how-to-use-it

**Comment by RSuter** [comment]
Closed due to duplicate, see referenced epic.
