### ISSUE TITLE
Feature request: generating all types in a namespace

### ISSUE THREAD

**Issue by mvarblow** [RSuter/NSwag#366]
I have a Rest.Models namespace that includes all the models for our Web API.  I'd like to generate typescript versions of those model classes.  The commandline tool (types2swagger) requires that I list every class that I want to generate.  That's a lot of classes and the list is constantly growing.  I'd really like to be able to just pass in a namespace name and have it generate a swagger file with all the types in that namespace.

**Comment by rsuter** [comment]
I recommend to implement your own command line tool with the NSwag.CodeGeneration NuGet and your type loading logic. See: https://github.com/NSwag/NSwag/wiki/AssemblyTypeToSwaggerGenerator

**Comment by rsuter** [comment]
The task: Add support for wildcards in the controller names...

**Comment by glatzert** [comment]
I was interested in this Feature and just wanted to take a look, if I could implement it - and hey - it _is_ already implemented. I think, this Feature request is done 👍

**Comment by RSuter** [comment]
I think wildcards are implemented for controllers but probably not for types?

**Comment by glatzert** [comment]
Ahh - that might be true. I was so confused by the Task mentioned above, which talks about Controller names Parameter. Nevertheless:

https://github.com/RSuter/NSwag/blob/69eb9128daf6a555ec45bf79437183d264517da7/src/NSwag.Commands/Commands/SwaggerGeneration/TypesToSwaggerCommand.cs#L111-L113

seems to fullfill this Feature Request.

**Comment by RSuter** [comment]
Yes, seems to be implemented.

**Comment by RSuter** [comment]
The project is a little to big to keep track of all issues :)

**Comment by glatzert** [comment]
Anyway - thanks for you work - if I find something else, I'd like to see and it has a "help wanted", I'll be here again :)

**Comment by jayryemure** [comment]
I'm not able to get wildcards to work in my application:

![image](https://user-images.githubusercontent.com/7969256/42062729-26f147ec-7af4-11e8-88c6-c9a2ed43d0b3.png)

Result:

> ClassNames: Code has been successfully generated but not written to file (no change detected).

With an empty swagger.json, presumably from no classes getting selected.   Also tried various combinations of wildcards with the same results.

I _do_ get results when I use the normal explicit way of specifying classes as a control measure, but I have hundreds so not a workable solution in my case.

Please advise, thank you.

**Comment by glatzert** [comment]
Via WebAPI to swagger that'll work ` webapi2swagger /assembly:&quot;$(TargetPath)&quot; /output:swagger.json /Controller:&quot;**.WebService.V1.**&quot;` - but I did not try to use types2swagger.

**Comment by RSuter** [comment]
The parameter is called ClassNames and supports wildcards: 

https://github.com/RSuter/NSwag/blob/master/src/NSwag.Commands/Commands/SwaggerGeneration/TypesToSwaggerCommand.cs#L36

**Comment by jayryemure** [comment]
Yes, sorry I was using the correct parameter but messed it up when providing the snippet.  Here's the corrected snippet, again getting no results in swagger.json.  My comment about getting correct results when explicitly providing the full name still stands.

![image](https://user-images.githubusercontent.com/7969256/42096021-e8cde232-7b79-11e8-992d-85cc76dede5f.png)

I tried webapi2swagger per @glatzert but getting the same empty results.  

Also it seems that using ** anywhere causes a build error `exited with code -1.` Example:
![image](https://user-images.githubusercontent.com/7969256/42097374-9bb1da54-7b7d-11e8-9f60-aadd752f893d.png)

Note sure if that's due to the syntax or caused when parsing the code.

**Comment by glatzert** [comment]
I had some issues with NSwagExe as well - until I realized I need NSwagExe_Core21 - just by chance: are you building a netstandard-project?

**Comment by jayryemure** [comment]
@glatzert .NET 4.6.1+

So looking at the stack trace for the exception I posted above, there was a good possibility that it's actually breaking reading my code, hard to tell even with full build log verbosity as it doesn't as it doesn't emit the necessary information.  Therefore, I tried it in simpler project and was able to get it to work with the wildcards.  Sorry for the confusion.
