### ISSUE TITLE
Middlewares: Add support for ReDoc web UI

### ISSUE THREAD

**Issue by RSuter** [RSuter/NSwag#462]
https://github.com/Rebilly/ReDoc

    appBuilder.UseSwaggerReDoc(....)

**Comment by sandord** [comment]
That would be really nice!

**Comment by RSuter** [comment]
https://github.com/RSuter/NSwag/tree/redoc-and-new-swagger-ui

**Comment by RSuter** [comment]
UseSwaggerReDoc() or UseReDoc()?

**Comment by RomanGotsiy** [comment]
Hey, @RSuter. Great work with NSwag!

ReDoc author here 👋 
Let me know if you have any troubles with ReDoc integration. I would be happy to help out!

and just FYI: I'm migrating ReDoc to React.js: https://github.com/Rebilly/ReDoc/issues/327

**Comment by RSuter** [comment]
@RomanGotsiy integration was no problem - UI looks good so far. If I see any issues with how the spec is processed I'll come back to you :-). ReDoc looks like a nice alternative to Swagger UI.

**Comment by RSuter** [comment]
Will be available soon in v11.8.0

**Comment by Chiliukas** [comment]
Sorry, false alert. 

URL: https://github.com/RSuter/NSwag/blob/master/src/NSwag.Sample.NETCore20/Startup.cs

But i found out the problem with URL. In browser i must to use URL "http://www.example.com/swagger/" but not "http://www.example.com/swagger". This is confusing.

**Comment by RSuter** [comment]
This is strange, can you open a new issue with that?

**Comment by Chiliukas** [comment]
New issue https://github.com/RSuter/NSwag/issues/1557
