### ISSUE TITLE
xmlObject support

### ISSUE THREAD

**Issue by emilw** [RSuter/NSwag#508]
Hi,
I cannot find any information anywhere how to get the XML object(http://swagger.io/specification/#xmlObject) working in NSwag, is it a missing feature or am i doing something wrong?
I am after this section:
` "xml": {
                "name": "Pet"
            }`

From:
The pet store example JSON:
http://petstore.swagger.io/v2/swagger.json

 

Thanks for feedback,
Emil

**Comment by rsuter** [comment]
The "xml" attribute is currently not supported. 

What exactly would you expect? Generated .NET `Xml*` attributes?

**Comment by emilw** [comment]
Hi,
Ok, thanks for feedback!
I guess that what i was after was the same behaviour as the XMLSerializer in WebAPI e.g. property/type name from Xml* attribute and if that is not available go with the type/property name.

I guess this would complicate things even more if you would use different serializers.... :-(

Can you point me in a direction where in the source i can start looking, to make this change, or is there anyone that have looked into it earlier?

**Comment by rsuter** [comment]
This is part of the JSON Schema and class generator which is implemented in http://njsonschema.org

We have to add a setting which specifies whether the "xml" properties should be generated and generate the required attributes in the code generator. The changes to the C# generator seem to be simple but the TypeScript part is trickier...

**Comment by emilw** [comment]
Hi,
What do you think is best, only support pure type names and properties in Njsonschema and let the WebAPI part in NSwag take care of the Xml* attributes? My take is that it would be sad to bind it to close to the serializer in the Njsonschema and instead limit it to only operate on the type and property names instead...

The other option as i see it is to only add the xmlObject to JsonSchema4 and not do anything in NJsonschema just to be able to use it from the outside. What is your take on it?

**Comment by rsuter** [comment]
The problem is, that the schema and code for DTO classes are completely generated in NJS. If we add only the xml object data structures to NJS we need lots of extension points to hook into this generation process... I agree that it is not correct to add the whole functionality to NJS because it is not a JSON Schema feature but it is the simplest way to implement and later understand it...

**Comment by emilw** [comment]
I buy it completely, i have done the implementation on the NJsonSchema side for the non XML*Attribute scenarios, but they do not make sense due to that you need to use them to make well formated XML. So maybe it's best to implement a nice approach in there instead of relying partly on NSwag side as you say.

My implementation only covers Assembly => Swaggerfile, is that ok as a first step?
Should i make a pull request?

**Comment by rsuter** [comment]
Yes, please create a PR and ill have a look...

**Comment by rsuter** [comment]
Thank you for the PR. The next step would be to generate Xml* attributes in the NJS code generators... I think for C# it should be simple, but for TypeScript I don't know an easy solution yet... So I think we should start with the C# generator.

**Comment by emilw** [comment]
Hi,
I have tested it all the way now with the latest NSwag => SwaggerUI and it looks good!
You are fast in integrating it all the way, i thought you would wait until i gave you a thumb up :-) 👍 .

Do you want me to start working on the generation also or do you want to do it yourself?

**Comment by rsuter** [comment]
Because this is a new feature it is fine for me to release it that fast. I tested it and it looked good.

For the generation part: Again we need a setting GenerateXmlAttributes and if it is on, generate the appropriate attributes (full qualified). 

I have a lot of other issues to work on in NSwag and NJS and if you have time i would really appreciate it if you can look into this.

**Comment by emilw** [comment]
Ok, I will look at it. I have not worked so much with Typescript so i will start with generating the attributes for the classes.

**Comment by rsuter** [comment]
Typescript xml is a much bigger effort to implement. I think we should start with c# generation..

**Comment by RSuter** [comment]
Any update on this?

**Comment by RSuter** [comment]
Created new issue: https://github.com/RSuter/NSwag/issues/1735
