### ISSUE TITLE
Feature Request: Allow NSwag Run to specify an alternative output location.

### ISSUE THREAD

**Issue by empedia** [RSuter/NSwag#566]
We are using NSwag to build a Swagger specification as part of our build process using Atlassian Bamboo and would like to have a bit more control over the location of the output file as part of the build. Bamboo will substitute a variable for the build folder in shell scripts and command lines but replacing this in the nswag file is tricky. 

It would therefore be useful to be able to specify the output path on the command line of the run command to override the value in the nswag file. To avoid having to specify a different output file for each type of output perhaps it would be useful if there was an OutputPath command line switch  which could be prepended to the Output parameter in the nswag file.

**Comment by RSuter** [comment]
Implemented in: https://github.com/RSuter/NSwag/commit/13292181bd41c4433ab3c0ed566b94fd1650b88a
