### ISSUE TITLE
Optional parameter not being respected from specification

### ISSUE THREAD

**Issue by DanubeRS** [RSuter/NSwag#608]
Howdy!

I have a config generated by Swashbuckle, and read by NSwag Studio to create a client.

Generated Json;
```
"parameters": [
          {
            "name": "begin",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "date-time"
          },
          {
            "name": "end",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "date-time"
          }
        ]
```

However, the right pane with Swagger spec shows parameters with 'required' omitted;

```        
"parameters": [
          {
            "type": "string",
            "name": "begin",
            "in": "query",
            "format": "date-time"
          },
          {
            "type": "string",
            "name": "end",
            "in": "query",
            "format": "date-time"
          }
        ]
```

Both toolsets are configured for the 2.0 spec

**Comment by rsuter** [comment]
"required" is removed because it is not needed (default value is "false"). See http://swagger.io/specification/#parameterObject

> required: Otherwise, the property MAY be included and its default value is false.

**Comment by DanubeRS** [comment]
Ah, cool beans. So what would be the step to get Studio to reflect this as an optional parameter in a Typescript client generator? I have enabled the "Mark optional properties with ?" option and at the moment have to explicitly provide `undefined` for each property I don't wish to supply.

**Comment by rsuter** [comment]
The option "Mark optional properties with ?" is only for DTO classes/interfaces... I think for TypeScript there isn't currently the option to generate default parameters.

**Comment by rsuter** [comment]
Maybe we should add the option "GenerateOptionalParameters" (like in CSharp) which reorders parameters and adds "?" to the optional ones...

**Comment by DanubeRS** [comment]
As the language stands, I would say there were two approaches; using `?` syntax on an optional parameter, or defining [default parameters](https://www.typescriptlang.org/docs/handbook/functions.html). Inherently optional nature of query parameters, the `?` syntax would be my vote.

**Comment by rsuter** [comment]
I think we should go with ? because it does not need additional procedural code. Just FYI: As per the spec, query parameters can be required.

**Comment by lmdg** [comment]
Hi @RSuter, I just ran into this issue with an optional boolean. I just wanted to bump this and see if there were any updates since it's been over a year. Thanks.

**Comment by lmdg** [comment]
@RSuter oh, thank you good sir, that's exactly what I was missing. I really appreciate the quick reply, thanks again.

**Comment by RSuter** [comment]
Can we close this issue?

**Comment by lmdg** [comment]
I would say so, this functionality is covered.
