### ISSUE TITLE
"title" property is missing in schema object when SwaggerDocument is serialized to JSON

### ISSUE THREAD

**Issue by harouny** [RSuter/NSwag#687]
Related to #477 and commit ba17c08ec114eeb99f78dec71508a87669ddd0ac

Ignoring "title" on parameter level has the side effect of also ignoring "title" in schema object. See http://swagger.io/specification/#schema-object-80 where "title" is a valid property, yet ignored when serializing SwaggerDocument to Json.

**Comment by RSuter** [comment]
So should we remove title from parameters but not from schemas? Correct?

**Comment by harouny** [comment]
Yes, thats correct as far as I remember.

**Comment by RSuter** [comment]
Please test with latest CI artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts
