### ISSUE TITLE
NSwag.CodeGeneration.CSharp it is impossible to get response.Content with out json deserialization

### ISSUE THREAD

**Issue by BlackGad** [RSuter/NSwag#701]
Can you support auto/manual/custom response content processing?

It is impossible (ClientTemplate.tt, line: 310) to get raw response content. Generated client code trying to deserialize content as json formatted string and fails.

I have an issue when trying to get response with content type text/html, text/plain.

**Comment by rsuter** [comment]
Have you tried to set the response.schema.type to 'file'?

**Comment by BlackGad** [comment]
No, bcs it is deffinetly not file :) we use swagger for client generation, and api documentation (swagger api is dev UI, https://github.com/Rebilly/ReDoc in future for clients) so i just cant say that method for page rendering or license ID (plain guid) is a file in swagger doc.

**Comment by rsuter** [comment]
Can you post a sample swagger spec/controller code and the wrong and expected output?

**Comment by BlackGad** [comment]
ok, tomorrow will post example here

**Comment by BlackGad** [comment]
Controller:
``` 
        [HttpGet]
        [Route("test", Name = nameof(CustomController) + nameof(Get2))]
        [SwaggerResponse(HttpStatusCode.OK, Type = typeof(string))]
        [SwaggerResponse(HttpStatusCode.InternalServerError, Type = typeof(ErrorData))]
        [SwaggerResponseContentType("plain/text")]
        public IHttpActionResult Get2()
        {
            return Content(HttpStatusCode.OK, Guid.NewGuid().ToString("D"), new TextPlainFormatter());
        }
```

Plain text formatter:
```
public class TextPlainFormatter : MediaTypeFormatter
    {
        #region Constructors

        public TextPlainFormatter()
        {
            SupportedMediaTypes.Add(new MediaTypeHeaderValue("text/plain"));
        }

        #endregion

        #region Override members

        public override bool CanWriteType(Type type)
        {
            return type == typeof(string);
        }

        public override bool CanReadType(Type type)
        {
            return false;
        }

        public override Task WriteToStreamAsync(Type type, object value, Stream writeStream, HttpContent content, TransportContext transportContext)
        {
            return Task.Factory.StartNew(() =>
            {
                var writer = new StreamWriter(writeStream);
                writer.Write(value);
                writer.Flush();
            });
        }

        #endregion
    }
```
Swagger:
```
{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Alpha",
    "description": ""
  },
  "host": "localhost",
  "schemes": [
    "http"
  ],
  "paths": {
    "test": {
      "get": {
        "tags": [],
        "summary": "summary",
        "description": "description",
        "operationId": "CustomControllerGet2",
        "consumes": [],
        "produces": [
          "text/plain"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          }
        },
      }
    }
  },
  "definitions": {}
}
```
Client:
```
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v9.12.6284.27589 (NJsonSchema v8.11.6284.26855) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace MyNamespace
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "9.12.6284.27589")]
    public partial class Client 
    {
        private string _baseUrl = "http://localhost";
        
        public string BaseUrl 
        {
            get { return _baseUrl; }
            set { _baseUrl = value; }
        }
    
        partial void PrepareRequest(System.Net.Http.HttpClient request, string url);
        partial void PrepareRequest(System.Net.Http.HttpClient request, System.Text.StringBuilder urlBuilder);
        partial void ProcessResponse(System.Net.Http.HttpClient request, System.Net.Http.HttpResponseMessage response);
    
        /// <summary>summary</summary>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <returns>OK</returns>
        /// <exception cref="SwaggerException">A server side error occurred.</exception>
        public async System.Threading.Tasks.Task<string> CustomControllerGet2Async(System.Threading.CancellationToken cancellationToken)
        {
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl).Append("/test");
    
            var client_ = new System.Net.Http.HttpClient();
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    PrepareRequest(client_, urlBuilder_);
                    var url_ = urlBuilder_.ToString();
                    PrepareRequest(client_, url_);
    
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                    request_.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("text/plain"));
                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    try
                    {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        foreach (var item_ in response_.Content.Headers)
                            headers_[item_.Key] = item_.Value;
    
                        ProcessResponse(client_, response_);
    
                        var status_ = ((int)response_.StatusCode).ToString();
                        if (status_ == "200") 
                        {
                            var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
                            var result_ = default(string); 
                            try
                            {
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<string>(responseData_);
                                return result_; 
                            } 
                            catch (System.Exception exception) 
                            {
                                throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
                            }
                        }
                        else
                        if (status_ != "200" && status_ != "204")
                        {
                            var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
                            throw new SwaggerException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", status_, responseData_, headers_, null);
                        }
            
                        return default(string);
                    }
                    finally
                    {
                        if (response_ != null)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (client_ != null)
                    client_.Dispose();
            }
        }
    
    }
}
```

**Comment by rsuter** [comment]
Related: https://github.com/NSwag/NSwag/issues/420

**Comment by rsuter** [comment]
This scenario is currently not supported. Currently, the client supports either JSON deserialization or file stream responses (response.schema.type == file). But we should support this, or at least treat this as stream response...

**Comment by rsuter** [comment]
For now, you can add the method to the ProtectedMethods setting (makes it protected and adds "Core" postfix) and implement it yourself in a partial class.

**Comment by BlackGad** [comment]
yeah. Thank you :)

**Comment by Teeem** [comment]
Hi, I have the same\similar issue; however the GET response is in "application\xml" and needs to be deserialized into the appropriate object.  I am unsure if this falls under the same enhancement or as a new one.

Thank You

**Comment by rsuter** [comment]
Related to https://github.com/NSwag/NSwag/issues/420

**Comment by rsuter** [comment]
Added ContentTypes to SwaggerResponseAttribute: https://github.com/NSwag/NSwag/commit/8ef23ef4a65bfb19dfd1fa6d6733f85f8ba9e5b8

What do you think (check out the tests)?

**Comment by rsuter** [comment]
As always, test with the CI artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/2195/artifacts

**Comment by rsuter** [comment]
@BlackGad 

Your api operation would look like: 

    [HttpGet]
    [Route("test", Name = nameof(CustomController) + nameof(Get2))]
    [SwaggerResponse(HttpStatusCode.OK, ContentTypes = string[] { "plain/text" })]
    [SwaggerResponse(HttpStatusCode.InternalServerError, Type = typeof(ErrorData))]
    public IHttpActionResult Get2()
    {
        return Content(HttpStatusCode.OK, Guid.NewGuid().ToString("D"), new TextPlainFormatter());
    }

**Comment by BlackGad** [comment]
I think it is not good idea to allow different content types on different responses.
In reality when u call some method u will expect exactly specified content type (does not matter it is OK or bad request). 

Also i do not use NSwag server part(use Swashbuckle bcs of swagger UI) so i have my specific attributes and document generator.

To rule different content types there is standard HttpConfiguration MediaTypeFormatters exist.
For u,i think, it is better to add annotation attribute(allow multiple) SwaggerResponseContentType(mime) and somehow use it (replace default mimes or just expand them)

**Comment by BlackGad** [comment]
I need somehow rule client code through standard swagger document specification (or documented vendor extensions).

It would be great if u will introduce virtual(partial) method process response to customize and deserialize(prepare) response content(basic response with stream as input argument). By default leave Json deserialization.

**Comment by BlackGad** [comment]
and yeah, i am agree with person from different issue post - for u it is better to add extension points, do not try to handle all use cases it is just impossible :)

**Comment by rsuter** [comment]
Btw: NSwag server side also has swagger ui integrated... The problem is that an error may be json and the 200 is text...

**Comment by rsuter** [comment]
Maybe we can split the Get() method into Get() and virtual ProcessGet() or (like ProtectedMethods and ProcessGetCore() and you implement ProcessGet()) so that you can override the processing or the whole Get()

**Comment by BlackGad** [comment]
Btw: NSwag server side also has swagger ui integrated... The problem is that an error may be json and the 200 is text...

no it is uncommon situation. Basically it is content negotiation mechanism. 
Look https://en.wikipedia.org/wiki/List_of_HTTP_header_fields Accept request header, and response Content-Type header.

External systems pass this header to make sure that response will be understandable.

**Comment by BlackGad** [comment]
If u are asking my opinion than

Your current implementation: 
```
...
 var status_ = ((int)response_.StatusCode).ToString();
                        if (status_ == "200")
                        {
                            var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(Cinegy.Web.Http.Contracts.SuccessData);
                            try
                            {
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<Cinegy.Web.Http.Contracts.SuccessData>(responseData_);
                                return new Response<Cinegy.Web.Http.Contracts.SuccessData>(status_, headers_, result_);
                            }
                            catch (System.Exception exception)
                            {
                                throw new ResponseException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
                            }
                        }
...
```
My implementation would be look like this:
```
 protected async virtual Task<T> ExtractResponseContent<T>(HttpResponseMessage response)
        {
            if (response.Headers.Contains("content-type"))
            {
                var contentTypeHeader = response.Headers.GetValues("content-type").FirstOrDefault();
                var mediaType = MediaTypeHeaderValue.Parse(contentTypeHeader);
                if (string.Equals(mediaType.MediaType, "application/json", StringComparison.InvariantCultureIgnoreCase) ||
                    string.Equals(mediaType.MediaType, "text/json", StringComparison.InvariantCultureIgnoreCase))
                {
                    var responseData_ = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                    return Newtonsoft.Json.JsonConvert.DeserializeObject<T>(responseData_);
                }
            }

            throw new NotSupportedException();
        }
...
  if (status_ == "200")
                        {
                            try
                            {
                                var result_ = await ExtractResponseContent<Cinegy.Web.Http.Contracts.SuccessData>(response_).ConfigureAwait(false);
                                return new Response<Cinegy.Web.Http.Contracts.SuccessData>(status_, headers_, result_);
                            }
                            catch (System.Exception exception)
                            {
                                throw new ResponseException("Could not deserialize the response body.", status_, string.Empty, headers_, exception);
                            }
                        }
...
```
Same code for all errors

code above was not tested! 

than i could override ExtractResponseContent in my generated client and support additional/new content types.

Also u force to accept 
request_.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

It is also not right in general situation. U can use this if only application/json(text/json) was specified in swagger document (produces section). Otherwise it must be one of well known types.

**Comment by BlackGad** [comment]
It is easy to support any text specific types (content will be wrapped to simple text) also all xml types can be wrapped into XElement.

Example: 
1) MIME: text/ANYTYPE, Swagger response type: string - just read content as string with appropriate encoding.
2) MIME: application/json, Swagger response type OBJECT - read content and deserialize
3) MIME: application/xml, Swagger response type OBJECT- read content and return deserialized xml (it is complex task, there is a lot of different deserializers so leave to user customization)

It was my personal opinion

**Comment by BlackGad** [comment]
> NSwag server side also has swagger ui integrated

I saw, but it was lack of functionality when i've started to implement swagger generation. Maybe in future i will review my decision and implementation.

**Comment by rsuter** [comment]
What functionality is missing?

**Comment by BlackGad** [comment]
:) i am not ready to answer u right now. 

As long as I remember:
- Multiple versions support (1 hosted UI with several APIs with several versions)
- Flagged enumeration handling
- Something that i forget :)

But I am afraid that my customization is way to complex. I can describe u cases in details if u interested in.

**Comment by BlackGad** [comment]
> 1 hosted UI with several APIs with several versions
By default Swashbuckle also dont support this but i handle this with some reflection hacks.

**Comment by rsuter** [comment]
Duplicate: https://github.com/NSwag/NSwag/issues/731

**Comment by stijnherreman** [comment]
@RSuter Are there any showstoppers to merge the `ContentTypes` code? It looks good to me.

I disagree with @BlackGad that all responses should be of the same type. As you indicate yourself, an error response could contain JSON while an OK response could contain something else. Very relevant here is https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#response-object, I need to be able to specify the MIME types when `type` is `"file"`.

**Comment by RSuter** [comment]
The branch is very old, I have to check how to merge it...
Also this has change has to be implemented here: https://github.com/RSuter/NSwag/pull/994

**Comment by RSuter** [comment]
Such extensions can also be implemented with a custom operation processor, like: 

https://github.com/RSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration.WebApi.Tests/OperationProcessors/SwaggerOperationProcessorAttributeTests.cs

**Comment by ctaggart** [comment]
Please support response type of `string`:
``` yaml
      responses:
        200:
          schema:
            type: string
```

This should just return the response string instead of trying to decode json.

**Comment by antonGritsenko** [comment]
This was broken with 13.#
