### ISSUE TITLE
Pass request body with DELETE method

### ISSUE THREAD

**Issue by molszews** [RSuter/NSwag#744]
It is not a good practice and it is not supported by all servers, however this sometimes happens. In generated c# client there is a request body serialized to JSON however it is not passed then to the request object.

**Comment by lethargicgeek** [comment]
Just came across this issue as well.  The variable "content_" is created for Deletes but "request_.Content = content_;" is never called.

**Comment by RSuter** [comment]
I think the body is created and assigned if the body schrema is defined in the spec (the http method is not considered for this). Isnt this how it is implemented?

**Comment by RSuter** [comment]
https://github.com/RSuter/NSwag/commit/aa23096e5946a24828951a8d117d07b5e4b01892
