### ISSUE TITLE
NSwag Studio Asp.Net Core 2.0 preview

### ISSUE THREAD

**Issue by ranouf** [RSuter/NSwag#782]
Hi,

It seems that NswagStudio is not compatible with Asp.Net Core 2.0 preview?
I have this error when I try to load the assemblies:
Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=1.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

Is there a way to fix this problem?

**Comment by RSuter** [comment]
I haven't tested it with .NET Core 2.0, but there may be problems loading .NET Core assemblies because NSwagStudio runs with full .NET (v4.6) and loads the core dlls in a full .NET AppDomain. I'm currently migrating everything to .NET Standard but I have lots of problems when loading .NET Core dlls (more than with the released version v9.12). 

But you can try the CI versions, maybe they work better with .NET Core 2.0?

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by RSuter** [comment]
For now, you should use the ASP.NET Core middlewares (NuGet: NSwag.AspNetCore) and generate the swagger spec in the web app process... this way you can avoid all these dll loading problems... (just start the web app [with app.UseSwaggerUi(....)] and import the swagger url in NSwagStudio

**Comment by ranouf** [comment]
I will test that on Monday, but it seems to be a good solution, thanks :)

**Comment by RSuter** [comment]
Yes, with this option you have many more extension points and ways to customize the outcome 

see https://github.com/NSwag/NSwag/wiki/Middlewares

**Comment by RSuter** [comment]
Can you try with the latest CI build?
I worked on the assembly loader and maybe it now works also for .NET Core 2.0 projects

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts
https://www.myget.org/gallery/nswag-ci

**Comment by RSuter** [comment]
Btw: It seems that not all dlls are available, try publishing first:

    dotnet publish

**Comment by ranouf** [comment]
Still the same error
![errornswagcore2](https://cloud.githubusercontent.com/assets/1764519/26786039/2799f296-49d3-11e7-91ae-c4593d53a38b.PNG)

So with swagger-ui, it works well, but the name of the service Change, instead of UserService.GetUsers(), I know have apiUserGetUsersGet() or ShopLocationService.DeleteShopLocation is now apiShopLocationDeleteShopLocationDelete.

Is there a way to configure it as It was?

Moreover, I have an error for all my delete functions:
Error	TS2322	(TS) Type 'Observable<{}>' is not assignable to type 'Observable<void>'.
  Type '{}' is not assignable to type 'void'.

On this part:


    ```
    return Observable.fromPromise(this.transformOptions(options_)).flatMap(transformedOptions_ => {
            return this.http.request(url_, transformedOptions_);
        }).flatMap((response_) => {
            return this.transformResult(url_, response_, (r) => this.processApiShopChainDeleteShopChainDelete(r));
        }).catch((response_: any) => {
            if (response_ instanceof Response) {
                try {
                    return this.transformResult(url_, response_, (r) => this.processApiShopChainDeleteShopChainDelete(r));
                } catch (e) {
                    return <Observable<void>><any>Observable.throw(e);
                }
            } else
                return <Observable<void>><any>Observable.throw(response_);
        });
```

**Comment by RSuter** [comment]
You need to use MultipleClientsFromOperationId as OperationGenerationMode setting to preserve the names:

https://github.com/NSwag/NSwag/blob/master/src/NSwag.Commands/Commands/OperationGenerationMode.cs

Can you provide the signature of a delete operation method?

**Comment by ranouf** [comment]
The C# code:
       ```
 [HttpDelete]
        public async Task<IActionResult> DeleteShop([FromQuery]Guid id)
        {
            var currentUser = await GetCurrentUserAsync();

            var shop = await _shopManager.FindShopByIdAsync(id, currentUser);

            if (shop == null)
            {
                return NotFound();
            }

            await _shopManager.DeleteShopAsync(shop);

            return Ok();
        }
```
From SwaggerUi
![deleteshop](https://cloud.githubusercontent.com/assets/1764519/26787160/fe26dd30-49d6-11e7-8ad9-78e80b5a1459.PNG)

**Comment by ranouf** [comment]
![shopserviceconfiguration](https://cloud.githubusercontent.com/assets/1764519/26787336/a0bd385a-49d7-11e7-8acc-6ca9904e1cb6.PNG)

I already used MultipleClientsFromOperationId , but I probably misconfigured something?

**Comment by RSuter** [comment]
Use the ProducesResponseType attribute with typeof(void) and status code 204 (or 200?) on the operation to specify that it does not have a response...

**Comment by RSuter** [comment]
https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator

**Comment by ranouf** [comment]
For the delete problem:
Stil the same error:
`Type '{}' is not assignable to type 'void'`

With error 200 or error 204:
```
        [HttpDelete]
        [ProducesResponseType(typeof(void), 200)]
        public async Task<IActionResult> DeleteOffer([FromQuery]Guid id)
```

I will try to follow the configuration from:
https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator

Thanks for your quick help 👍

**Comment by ranouf** [comment]
So from I read:

> The WebApiToSwaggerGenerator class is used to generate a Swagger specification from ASP.NET Web API controllers:
> 
> var settings = new WebApiToSwaggerGeneratorSettings 
> { 
>     DefaultUrlTemplate = "api/{controller}/{action}/{id}" 
> };
> var generator = new WebApiToSwaggerGenerator(settings);
> var document = await generator.GenerateForControllerAsync<PersonsController>();
> var swaggerSpecification = document.ToJson();

Currently my controller is :
   ```
 [Authorize]
    [Route("api/[controller]/[action]")]
    public class ShopController
```

So It seems well configured. The only difference I see is the id. 

From Swagger.json, I can see that:
   ```
 "/api/Shop/GetShop": {
      "get": {
        "tags": [
          "Shop"
        ],
        "operationId": "ApiShopGetShopGet",
        "consumes": [],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "uuid"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ShopDto"
            }
          }
        }
      }
    },
```

From what I understand, the generated code use the OperationId, how to configure it to become ShopService.GetShop?

**Comment by ranouf** [comment]
i need to do advance other things currently, i will look at it this week i hope, thank you for your help,  i will let you know

**Comment by RSuter** [comment]
.NET core 2.0 support has been added. Can you test with latest ci builds?
