### ISSUE TITLE
DataAnnotations dependency issue running NSwag in Linux

### ISSUE THREAD

**Issue by wdtracy** [RSuter/NSwag#787]
I confess that I am pretty new to this, so forgive me if I have missed something, but I haven't been able to uncover a whole lot about running in Linux, but from what I did find I was able to get .net core installed in a docker container running Debian 8 and did the npm install of NSwag.  Now when I try to use webapi2swagger I get a dependency error trying to find System.ComponentModel.Annotations:

> NSwag NPM CLI
NSwag command line tool for .NET Core, toolchain v10.6.6324.28497 (NJsonSchema v8.33.6323.36213) (x64)
Visit http://NSwag.org for more information.
NSwag bin directory: usr/local/lib/node_modules/nswag/bin/binaries/netcoreapp1.1
System.AggregateException: One or more errors occurred. (Could not load file or assembly 'System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

The command I am running is:
`nswag webapi2swagger --core /ReferencePaths:/root/swagger/packages /Output:/root/swagger/api.json /Assembly:/root/swagger/packages/api.306.0.0/lib/net452/api.dll`

I tried adding the file to the path in `ReferencePaths` but no luck.

Any ideas?

**Comment by RSuter** [comment]
First you need to

    dotnet publish

Have you done that?

**Comment by RSuter** [comment]
And --core must be at a end..

**Comment by wdtracy** [comment]
Just tried --core at the end and no luck, as far as publish is concerned, I'm not sure if it will apply here since I don't have a solution or project.  What I'm doing is retrieving a list of DLLs from our internal nuget server using the nuget CLI and then using NSwag to generate swagger files from the DLLs.  I actually have it working just fine from my Windows 10 box but now there is a requirement to dockerize it.  I may be trying to cram a square peg into a round hole, but wanted to give it a shot.

**Comment by RSuter** [comment]
you need to retrieve all dependencies so that all required dlls are available.. you could also try to reference the nuget cache directory...

**Comment by RSuter** [comment]
To be honest, I didnt do many linux tests... i have enough problems with the assembly loader on windows :-)

**Comment by wdtracy** [comment]
heh, I hear you.  I'll keep playing with it and see if I can get something working.

Thanks

**Comment by RSuter** [comment]
You should also try v11 (ci build)

**Comment by RSuter** [comment]
Maybe just use the nswag middleware and generate the spec in the http pipline/asp.net process

**Comment by RSuter** [comment]
According to
    /Assembly:/root/swagger/packages/api.306.0.0/lib/net452/api.dll

You are trying to load a full .net lib in a core process. Id be surprised if this is possible...

**Comment by Johlandabee** [comment]
I have the same issue with NSwagStudio (NSwag version: 11.1.2.0). There is no option to specify if code gen should use Core namespaces. 

**System.ComponentModel.DataAnnotations** will be used instead of **System.ComponentModel.Annotations**

**Comment by RSuter** [comment]
System.ComponentModel.DataAnnotations 

is located in the package

    System.ComponentModel.Annotations

makes sense? :-)

**Comment by Johlandabee** [comment]
Yeah, i realized that myself, had a nobrainer there. I had other dependancy fuckery going on, thats why i quickly removed my comment :sweat_smile:

**Comment by RSuter** [comment]
... yes, i was very confused because i got a notification and couldn't find any activity on this issue ;-)

**Comment by RSuter** [comment]
.NET 4.5.2 assemblies can only be loaded on Windows and with the .NET 4.6 command line nswag.exe. Can we close this as this is not supported?
