### ISSUE TITLE
How To Change Date Fomat method

### ISSUE THREAD

**Issue by baiyunchen** [RSuter/NSwag#805]
When I send data to the API, I find that the parameters of the moment.Moment type are converted to ISO time when calling the ToJS method, resulting in inconsistent with my current time zone. Can I modify the ToJS method to modify the date formatting rules?

`
 data["startDate"] = this.startDate ? this.startDate.toISOString() : null;
`

**Comment by RSuter** [comment]
At the moment this is not doable without exchanging the whole template...
How would you modify it?

**Comment by baiyunchen** [comment]
I think need provide an option to allow users to customize how to format the date. Because the date is a special type. I decided to temporarily rewrite the moment.js toISOString method to implement this functionality.

**Comment by RSuter** [comment]
How would you change the output? How should the code look like?

**Comment by danzel** [comment]
@baiyunchen I've added date support to the typescript generator in NJsonSchema:
https://github.com/RSuter/NJsonSchema/pull/493
(Not included in an NSwag release yet)

So for `date` format properties it will generate `yyyy-MM-dd` format data.
Is that what you were after?

**Comment by RSuter** [comment]
The feature is now released

**Comment by RSuter** [comment]
Can we close this?

**Comment by baiyunchen** [comment]
@RSuter  Sorry for my reply late, please close it.thanks
