### ISSUE TITLE
Extend FileParameter to support specification of content type

### ISSUE THREAD

**Issue by sandord** [RSuter/NSwag#816]
Currently, the generated clients leave the `Content-Type` header empty when uploading a file.

This is a problem for me because my WebAPI endpoint that receives the upload, has a model with a custom media type formatter. Custom media type formatters cannot handle requests with an empty `Content-Type` header. Consequently, WebAPI returns a `The HTTP status code of the response was not expected (415)` response.

It would be great if I could provide a content type like in the following example:

    await myClient.UploadAsync(new FileParameter(stream, "Image.png", "image/png"));

**Comment by RSuter** [comment]
Can you try to replace

    var content_ = new System.Net.Http.MultipartFormDataContent(boundary_);

with

	var boundary_ = System.Guid.NewGuid().ToString();
    var content_ = new System.Net.Http.MultipartFormDataContent(boundary_);
    content_.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("multipart/form-data; boundary=" + boundary_);

is this working?

**Comment by sandord** [comment]
I made the suggested replace. I'm getting this error though:

    System.FormatException : The format of value 'multipart/form-data; boundary=80b40ca7-3214-4a11-bc1a-0077dc28e286' is invalid.
    at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
    at System.Net.Http.Headers.MediaTypeHeaderValue..ctor(String mediaType)

To migitate that error, I had to change the last line of your code to:

    content_.Headers.TryAddWithoutValidation("Content-Type", "multipart/form-data; boundary=" + boundary_);

The `ContentType` stays `null` in the API method however.

**Comment by sandord** [comment]
In the meantime, I have updated the media type formatter to match by the `multipart/form-data` type but that (of course) still doesn't provide me with the content type of the uploaded file.

**Comment by RSuter** [comment]
Maybe this is working?

https://stackoverflow.com/a/23072922

**Comment by RSuter** [comment]
Can you add a unit test for this?

**Comment by RSuter** [comment]
In v11.2.0 we now remove and then add the header... is this now working without workarounds for you?

**Comment by sandord** [comment]
I'm note sure we're being entirely on the same page here.

Let's just say the issue boils down to this: (tested with v11.2.0)

When I upload a file through Swagger UI, I get this content:

![image](https://user-images.githubusercontent.com/260737/27724148-c599bdd6-5d70-11e7-96d6-98f805cd4a0c.png)

But when I do the same through the generated C# client, I get:

![image](https://user-images.githubusercontent.com/260737/27724196-16e696aa-5d71-11e7-94c1-9dd77e5eaaa5.png)

You see? No content type. I currently use `MimeMapping.GetMimeMapping()` to infer it from the filename but it would be really nice if we could provide the content type along with the upload.
