### ISSUE TITLE
NSwagStudio generating wrong endpoint address

### ISSUE THREAD

**Issue by andrecarlucci** [RSuter/NSwag#843]
Hi @RSuter 

I started a new project to try to reproduce the parameter problem (#842)  and got another one:

```cs
namespace nswagtest.Controllers {
    [Produces("application/json")]
    [Route("/api/{subscriptionId}/[controller]")]
    public class SitesController : Controller {

        [HttpGet]
        [ProducesResponseType(typeof(Array), StatusCodes.Status200OK)]
        public IActionResult List(string searchString) {
            return Ok(new[] {"with", "parameter"});
        }

        [HttpGet("/api/sites")]
        [ProducesResponseType(typeof(Array), StatusCodes.Status200OK)]
        public IActionResult ListAll(string searchString) {
            return Ok(new[] {"list", "all"});
        }
    }
}
```

SwaggerUI generates the `/api/sites` endpoint correctly, but **NSwagStudio** creates it like: `/api/{subscriptionId}/Sites/api/sites`

**Comment by RSuter** [comment]
The routes are appended but i think they only need to be appended if the httpget route does not start with /. Id say this is a bug...

**Comment by RSuter** [comment]
We need to add this check here

https://github.com/RSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration.WebApi/WebApiToSwaggerGenerator.cs#L275

Can you confirm that the class route is ignored when the operation route starts with /? What asp.net version are you working with?

**Comment by andrecarlucci** [comment]
I'm using asp.net core.
Yes, from the docs (https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing):

> Route templates applied to an action that begin with a / do not get combined with route templates applied to the controller. This example matches a set of URL paths similar to the default route.

```cs
[Route("Home")]
public class HomeController : Controller
{
    [Route("")]      // Combines to define the route template "Home"
    [Route("Index")] // Combines to define the route template "Home/Index"
    [Route("/")]     // Does not combine, defines the route template ""
    public IActionResult Index()
    {
        ViewData["Message"] = "Home index";
        var url = Url.Action("Index", "Home");
        ViewData["Message"] = "Home index" + "var url = Url.Action; =  " + url;
        return View();
    }

    [Route("About")] // Combines to define the route template "Home/About"
    public IActionResult About()
    {
        return View();
    }   
}
```

**Comment by RSuter** [comment]
Test with https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by andrecarlucci** [comment]
Wow! That was fast!
Thank you so much!!!
It worked :)
