### ISSUE TITLE
swagger2tsclient doesn't recognize File[] as known input and renders any[] instead

### ISSUE THREAD

**Issue by roysudi** [RSuter/NSwag#845]
Hello @RSuter ,

I'm using nSwag v 11.3.0 with Angular 4.x app. I would like to report a bug with swagger2tsclient not being able to recognize an array of type: file. It works great for a single type: file input. We have a REST API that has the below param configuration:
`"parameters": [{
    "in": "body", 
    "name": "uploadfiles",
    "description": "uploadfiles",
    "required": true,
    "schema": {
    "type": "array",
    "items": {
	"type": "file"
     }} }]`

The TSClient renders the method as below:
`upload(uploadfile: any[]): Observable<... | null> {
        let url_ = this.baseUrl + "/.../.../upload";
        url_ = url_.replace(/[?&]$/, "");
        const content_ = JSON.stringify(uploadfile);
        let options_ = {
            body: content_,
            method: "post",
            headers: new Headers({
                "Content-Type": "multipart/form-data", 
                "Accept": "*/*"
            })
        };
        return ...
    }`
The above request fails due to incorrect handling. Please help!

**Comment by RSuter** [comment]
Have you tried formData param with milti?

**Comment by roysudi** [comment]
Spec is valid. If you check above, the json o/p says it's an array of file. We have another API that takes a single file as i/p and is converted correctly. For now I created a method that uses formData and loops through the file[], adding them.

**Comment by RSuter** [comment]
Im not sure that is supported: 

- https://github.com/swagger-api/swagger-ui/issues/823
- https://github.com/OAI/OpenAPI-Specification/issues/254
- https://github.com/swagger-api/swagger-editor/issues/467

**Comment by roysudi** [comment]
Yeah, I kind of sensed it wouldn't be supported....let me close this for now. Thanks!

**Comment by RSuter** [comment]
We could still support it. How will this be supported in swagger 3.0?

**Comment by roysudi** [comment]
I guess it's worth a while for 3.0 and not 2.0. As per the specs, the file handling is changing semantically...
https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md

**Comment by RSuter** [comment]
The questions are: 

- How does the public operation method for multi file upload look like in Web API (so that we can scan this with reflection and generate a spec)?
- What would be the the best way (with as less as possible "propriatary"/custom extensions to the swagger spec) to describe multiple file upload?
- How to call this API (i.e. how to generate correct code for CSharp and TypeScript)?

**Comment by roysudi** [comment]
Yep, valid questions!

**Comment by roysudi** [comment]
btw, any plans to switch to the new HttpClientModule in ng 4.3 for TSClient? Trying to get our apps set up. Would be an awesome update :-)
