### ISSUE TITLE
WebApiToSwaggerGenerator: Mapping types

### ISSUE THREAD

**Issue by Johlandabee** [RSuter/NSwag#849]
I am using Swashbuckle and remap two types like this:

````csharp
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc(Swagger.Version, new Info
    {
        Title = Swagger.Title,
        Version = Swagger.Version,
        Description = Swagger.Description,
        Contact = new Contact
        {
            Name = Swagger.Name,
            Email = Swagger.Email
        }
    });

    c.MapType<Base64DataUrl>(() => new Schema { Type = "string" });
    c.MapType<ColorRgb>(() => new Schema { Type = "string" });
});
````
Is there a possibility to archive the same using the NSwag CLI?

**Comment by RSuter** [comment]
There are TypeMappers but they only work when used with the middleware... The cli uses appdomains and it is (currently) not possible to do this... You need to write your own simple cmd line tool.

**Comment by Johlandabee** [comment]
Alright, I will write a little tool for that. Thanks.
