### ISSUE TITLE
Is there any way how I can disable DisallowNull generation

### ISSUE THREAD

**Issue by hmvs** [RSuter/NSwag#850]
Hi.
For specific reason I have an API that has method with parameter and returned value with the same type. 
```
class HelloObject{
[Required]
  string SomeProp {get;set;}
}
----
HelloObject Index(HelloObject) {
}
```
In this DTO one property is marked with DataAnnotation [Required] for validation of incoming parameter. But output model can have null value there. 

But. If I generate definition with NSwag i will get 
```
        [Newtonsoft.Json.JsonProperty("SomeProp", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SomeProp { get; set; }
```

And will get an exception while invoking this method in generated Client.

Required property 'SomeProp' expects a non-null value. Path '[0].HelloObject', line 1, position 354.

I've tried: 
```
                    RequiredPropertiesMustBeDefined = false,
                    GenerateDataAnnotations = false,
```
same as both states of `NullHandling`
So is there any way how to disable DisallowNull generation?

**Comment by RSuter** [comment]
There is only one schema generated per class. The problem is, that your request and response DTO are different, so you cannot use the same class... The mentioned settings change the behavior for all classes, not just the request or response DTO clases

**Comment by hmvs** [comment]
For me it's ok to have for both of them `Required = Newtonsoft.Json.Required.Default`.

**Comment by RSuter** [comment]
Here is the code: 

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/Models/PropertyModel.cs#L57

do you see a way to support your needs? 

i think using required is wrong here because the response can contain null values even if the required attribute is set. this is a violation of the api contract defined in c#. maybe you should just remove the attribute and do manual validation in the operation method?

**Comment by hmvs** [comment]
Seems to be there is no option how can i do it. 

I fully agree with you that it should't be like that. But unfortunately I can't change it now, i am not an owner of this code :( But I generated clients for this API. And manually replacing all the `Newtonsoft.Json.Required.DisallowNull` with `Newtonsoft.Json.Required.Default` every time when new methods are added. 

So would be good to have some way to ignore `Required` at all. I would do a PR if i saw where we can put this option.

**Comment by RSuter** [comment]
The best option is to transform the generated swagger spec before generating client code (ie with an own cmd line tool which uses the nswag.core lib).

**Comment by soroshsabz** [comment]
ITNOA

In general I think flexibility in library and tool is important, so I suggest to add this option into NSwag
