### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by devingoble** [RSuter/NSwag#856]
I just created a new ASP.NET Core 2.0 web application, and installed NSwag.AspNetCore. 

I added `services.AddCors()` as well as
```
app.UseSwaggerUi(typeof(Startup).GetTypeInfo().Assembly, new SwaggerUiSettings()
{
	DefaultPropertyNameHandling = NJsonSchema.PropertyNameHandling.CamelCase
});
```

However, Swagger UI is returning the following error:
```
Can't read from server. It may not have the appropriate access-control-origin settings.
```
I enabled CORS, but I'm still getting the same error.

**Comment by RSuter** [comment]
Try calling the json url directly, then you will see the actual error. Its most probably not a cors problem...

**Comment by devingoble** [comment]
Ok, that was it. However, there's something weird about the current ASP.NET Core template. Swagger doesn't really like any of the OOTB controllers. I'll keep after it, but this takes care of my immediate issue. Thank you!
