### ISSUE TITLE
Unable to set namespace for C# client

### ISSUE THREAD

**Issue by frank71336** [RSuter/NSwag#859]
Hi,

in the documentation

https://github.com/RSuter/NSwag
https://github.com/RSuter/NSwag/wiki/SwaggerToCSharpClientGenerator

there is an example how to set the namespace for the generated client:

```
var clientSettings = new SwaggerToCSharpClientGeneratorSettings 
{
    ClassName = "MyClass",
    Namespace = "MyNamespace"
};
```

But there doen't seem to be a "Namespace" attribute in the SwaggerToCSharpClientGeneratorSettings  class: **Error CS0117 'SwaggerToCSharpClientGeneratorSettings' does not contain a definition for 'Namespace'**

So how do I set the namespace? (At the moment, the namespace is always "MyNamespace"...)

**Comment by RSuter** [comment]
The Namespace property is on the CSharpGeneratorSettings property...

**Comment by frank71336** [comment]
According to 

https://github.com/RSuter/NSwag

it is

```
var clientSettings = new SwaggerToCSharpClientGeneratorSettings
{
	ClassName = "MyClass",
	Namespace = "MyNamespace"
};
```

where "Namespace" is unknown. **So the example on this page is not correct?**

According to 

https://github.com/RSuter/NSwag/wiki/SwaggerToCSharpClientGenerator

it is

```
var settings = new SwaggerToCSharpGeneratorSettings
{
    ClassName = "MyClass", 
    Namespace = "MyNamespace"
};
```

which is also not possible as **SwaggerToCSharpGeneratorSettings** is an abstract class. **So the example on this page is not correct?**

If I use **CSharpGeneratorSettings** then I have to use **CSharpGenerator**, too? How to I decide if I want server or client code here? In addition, **CSharpGenerator** doesn't accept a **SwaggerDocument** as suggested in the samples on the pages above. So what is a valid example here?

May I kindfully suggest to have a verifying look at the documentation?

**Comment by RSuter** [comment]
Ok, ive updated the docs. CSharpGeneratorSettings  is part of SwaggerToCSharpGeneratorSettings  as you can see now..

**Comment by frank71336** [comment]
Just back from holiday. Documentation looks correct now. I've just tested the code. Works great! Thank you.
