### ISSUE TITLE
401 (Unauthorized) error with SwaggerDocument.FromUrlAsync

### ISSUE THREAD

**Issue by frank71336** [RSuter/NSwag#860]
Hi,

Both

`document = await SwaggerDocument.FromJsonAsync(json);`

and

`document = await SwaggerDocument.FromFileAsync(@"c:\temp\swagger.json");`

work fine for me, but using

`document = await SwaggerDocument.FromUrlAsync("http://localhost/PasswordService/swagger/docs/v1");`

I always get an exception "**Response status code does not indicate success: 401 (Unauthorized).**" although the URL is correct when entering it in Browser or using it in a manual C# GET request. (Chrome says "Resource interpreted as Document but transferred with MIME type application/json").

Any ideas?

(Web Server requires Windows Authentication. So I have to use Windows Authentication when doing the manual C# GET request, of cause. So maybe the question is: How can I use Windows Authentication when using "SwaggerDocument.FromUrlAsync" ?)

**Comment by RSuter** [comment]
You should clone the project and debug this in a unit test.

**Comment by RSuter** [comment]
The HTTP get method is implemented here: 

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Infrastructure/DynamicApis.cs#L60

**Comment by frank71336** [comment]
I will close this issue as I do not really need a solution. The other two options for getting the document work fine for me and I do not have the time right now to debug is myself. Thank you for your assistance.
