### ISSUE TITLE
Wrong code for parameter of type enum list

### ISSUE THREAD

**Issue by ranouf** [RSuter/NSwag#865]
Hi,

This is my C# class:
```
    public class GetUsersRequestDto : PermissionRequestDto<Guid>
    {
        public IEnumerable<RoleDto> ExcludedRoles { get; set; }
        public IEnumerable<RoleDto> IncludedRoles { get; set; }
    }
```
Where RoleDTo is:
```
    public enum RoleDto
    {
        SuperAdmin = 1,
        Admin = 2,
        Manager = 3,
        User = 4,
        Invite = 5
    };
```

So when NSwag generate the script i have an error:

> ERROR in [at-loader] ./ClientApp/app/services/app.services.ts:2575:34 
>     TS2407: The right-hand side of a 'for...in' statement must be of type 'any', an object type or a type parameter.
> ERROR in [at-loader] ./ClientApp/app/services/app.services.ts:2580:34 
>     TS2407: The right-hand side of a 'for...in' statement must be of type 'any', an object type or a type parameter.

this is generated code in error:
```
        if (excludedRoles !== undefined)
            excludedRoles.forEach((item, index) => { 
                for (let attr in item)
                    url_ += "excludedRoles[" + index + "]." + attr + "=" + encodeURIComponent("" + item[attr]) + "&";
            });
        if (includedRoles !== undefined)
            includedRoles.forEach((item, index) => { 
                for (let attr in item)
                    url_ += "includedRoles[" + index + "]." + attr + "=" + encodeURIComponent("" + item[attr]) + "&";
            });
```

I will transform my C# class to  
```
        public IEnumerable<int> ExcludedRoles { get; set; }
        public IEnumerable<int> IncludedRoles { get; set; }
```

But could it be possible to fix the problem in the generating algorithm?

Thanks
Cedric

**Comment by RSuter** [comment]
https://github.com/RSuter/NSwag/commit/a9c675f7f6ea0b9f0d41e1fd146141bd82c19d4d

**Comment by ranouf** [comment]
Wahoooo! So Efficient!!!
Thanks!
