### ISSUE TITLE
BaseClass with generic Type

### ISSUE THREAD

**Issue by ldvalido** [RSuter/NSwag#867]
I'm using the latest version of the nswagStudio.
I'm trying to generate the files with an specific Base Class Name using the placeHolder {controller} but it doesn't work. 
For example, i tried to create a hierarchy of the the type "SynchroClient<{controller}>"
Is there any work around for that? 
I saw the source code, but i didn't found it.

**Comment by RSuter** [comment]
I think the base class currently does not support the {controller} placeholder.
