### ISSUE TITLE
Needlessly complex method is suggested for handling the static files

### ISSUE THREAD

**Issue by stijnherreman** [RSuter/NSwag#871]
https://github.com/RSuter/NSwag/wiki/OwinGlobalAsax suggests adding three handlers to deal with the static files, but this method is needlessly complex. I assume you got your info from https://stackoverflow.com/a/41155395 ?

I've posted a new answer to that question, repeating it here for convenience:

By default, the StaticFile handler is the last handler to be executed. This means that simply intercepting all NSwag requests is enough:

```xml
<add name="NSwag" path="swagger" verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
```

This also [used to be](https://github.com/domaindrivendev/Swashbuckle/issues/57) the recommended method by Swashbuckle, until it switched to extensionless URLs. You may notice that ASP.NET is able to handle extensionless URLs with the same type of handler in `<add name="ExtensionlessUrlHandler-Integrated-4.0"`.

In addition, this should also be documented on https://github.com/RSuter/NSwag/wiki/Middlewares because this problem is not limited to the Global.asax method.

**Comment by RSuter** [comment]
Can you update the docs/wiki and create a pr for a fix in the sample project?

**Comment by stijnherreman** [comment]
Sure. Should I change both NSwag.Sample.NetGlobalAsax in this repo and the projects in the Samples repo?

**Comment by RSuter** [comment]
I'm not sure whether it makes sense to update the Samples repo as it is outdated and we have samples in the NSwag repo itself...
