### ISSUE TITLE
Plans for supporting the new Angular2 HttpClient

### ISSUE THREAD

**Issue by adzhiljano** [RSuter/NSwag#872]
Are there any plans on supporting the new Angular2 HttpClient, introduced in [Angular2 4.3.0 (2017-07-14)](https://github.com/angular/angular/blob/master/CHANGELOG.md#430-2017-07-14), by the ng2 typescript client? 

Preview of the [new HttpClient API](https://github.com/angular/angular/commit/37797e2) :

> HttpClient is an evolution of the existing Angular HTTP API, which exists
> alongside of it in a separate package, @angular/common/http. This structure
> ensures that existing codebases can slowly migrate to the new API.
> 
> The new API improves significantly on the ergonomics and features of the legacy
> API. A partial list of new features includes:
> 
> * Typed, synchronous response body access, including support for JSON body types
> * JSON is an assumed default and no longer needs to be explicitly parsed
> * Interceptors allow middleware logic to be inserted into the pipeline
> * Immutable request/response objects
> * Progress events for both request upload and response download
> * Post-request verification & flush based testing framework

**Comment by RSuter** [comment]
Its not planned right now by myself. Maybe one of my customers is interested in this - otherwise it will not be implemented soon (its not that the old API is gone). 

Are there many changes (new template) or can we just enhance the existing template?

**Comment by roysudi** [comment]
++1 for this change. As far as I know the changes predominantly involve moving to @ng/common/http from @ng/http. Since the newer module assumes all responses as JSON, it means the template needs to get rid of / change the .map method a bit.

[Http Official Docs](https://angular.io/guide/http)

**Comment by RSuter** [comment]
It should be an option for the existing Angular template then.

**Comment by RSuter** [comment]
The docs have been updated: https://github.com/RSuter/NSwag/wiki/SwaggerToTypeScriptClientGenerator#angular

Test with CI builds: https://ci.appveyor.com/project/rsuter/nswag-25x6o

Please report any problems, suggestions, etc. thank you.

**Comment by roysudi** [comment]
@RSuter Great! Will do & lyk if there’s anything off. Cheers!

**Comment by RSuter** [comment]
![image](https://user-images.githubusercontent.com/2603405/31437163-a80ba3e6-ae84-11e7-8297-11c32846b3c8.png)

**Comment by sandord** [comment]
Thanks -a- lot!

**Comment by roysudi** [comment]
@RSuter Excellent work on this! So far all looks great! I noticed we are using 'BLOB' response type to make the XHR calls. Can we switch to using ArrayBuffer instead (for non-file calls)? I have done some comparative analysis & they seem faster than blobs. Converting them back to actual form is simple as well.. 

Few links:
[ArrayBuffer to String / STring to ArrayBuffer](https://developers.google.com/web/updates/2012/06/How-to-convert-ArrayBuffer-to-and-from-String)
[Array Buffer & Transferable Objects](https://developers.google.com/web/updates/2011/12/Transferable-Objects-Lightning-Fast)

Thoughts please?

**Comment by roysudi** [comment]
Side note: I make all my rest calls in web workers hence the array buffer/transferable objects concept is a huge perf boost..
