### ISSUE TITLE
DateTimeOffset in endpoint return type is generated as DateTime

### ISSUE THREAD

**Issue by Blackbaud-StewartStephens** [RSuter/NSwag#875]
I have an endpoint which returns a class:
`class StatusHistory { public IEnumerable<StatusItem> Items { get; set; } }`
`class StatusItem { public DateTimeOffset Date { get; set; } }`

When using NSwag to generate a client, the `Date` property of `StatusItem` is generated as `DateTime`, rather than `DateTimeOffset`.  I do not want to lose the precision provided by `DateTimeOffset`.

Is there any way I can get this property to be generated as `DateTimeOffset`?

**Comment by RSuter** [comment]
Is this "the same" as a TimeSpan?

**Comment by Blackbaud-StewartStephens** [comment]
I'm not sure I follow your question.  If you're asking if `DateTimeOffset` is the same as `TimeSpan` then it is not.  `DateTimeOffset` is basically a `DateTime` that also includes time zone information.  It reduces the ambiguity normally associated with working with `DateTime`s across time zones.

**Comment by RSuter** [comment]
Ok, then we should treat DateTimeOffset like a DateTime in JSON Schema and you can set the DateTimeType to "DateTimeOffset" to generate the client code... JSON Schema cannot differentiate between datetime and datetimeoffset. Would this be ok?

**Comment by Blackbaud-StewartStephens** [comment]
Yes that sounds good to me.

**Comment by RSuter** [comment]
Ok, no changes needed. Just set the DateTimeType setting of the C# generator to "System.DateTimeOffset"
