### ISSUE TITLE
Exception thrown when using generics

### ISSUE THREAD

**Issue by grovesNL** [RSuter/NSwag#877]
An exception is thrown when using newer versions of NJsonSchema and NSwag with any simple generics such as `class A<T> { }`.

I'm still working on isolating this further, but my current test case is located at https://github.com/grovesNL/nswag-test

Running ConsoleApp2 (referencing older NJsonSchema and NSwag versions) will succeed.

Running ConsoleApp3 (referencing newer NJsonSchema and NSwag versions) will fail with `System.ArgumentException: 'Invalid type owner for DynamicMethod.'`.

I know generics are not fully supported yet (https://github.com/RSuter/NJsonSchema/issues/23 and https://github.com/RSuter/NSwag/issues/704), but for now I was using `TypeScriptResolver` to replace ```A`1``` with `A<T>` and it worked well with older versions.

I'll continue to look into it and use the older versions for now.

**Comment by RSuter** [comment]
The newer versions use the JSON.net contract resolver to better reflect types. I think the problem comes from this change...

**Comment by RSuter** [comment]
I didn't even know that this was working... Usually NSwag/NJS only supports specific generic types (ie the generic parameters are known). 

The bug comes from JSON.NET ContractResolver which cannot handle open generic types: 

![image](https://user-images.githubusercontent.com/2603405/29282840-9770c878-8124-11e7-9106-e75fe2726311.png)

I'm not sure whether it makes sense to fix this, because the schema will most probably be wrong. I changed to 

    private JsonContract ResolveContract(Type type)
    {
        try
        {
            return Settings.ActualContractResolver.ResolveContract(type);
        }
        catch
        {
            return null;
        }
    }

The output is: 

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "A`1",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "B": {
      "oneOf": [
        {
          "$ref": "#/definitions/T"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "definitions": {
    "T": {
      "type": "object",
      "additionalProperties": false
    }
  }
}
```

Is this as expected?

**Comment by grovesNL** [comment]
@RSuter Thank you for your quick response as always. I cloned NJsonSchema and made the change, the interfaces look as I expect:

```
"/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.3.3.0 (NJsonSchema v9.4.5.0) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import * as moment from 'moment';


export interface A`1 {
    b?: T;
}

export interface T {
}"

"/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.6.6324.28497 (NJsonSchema v8.33.6323.36213) (http://NSwag.org)
// </auto-generated>
//----------------------

import * as moment from 'moment';


export interface A`1 {
    b?: T;
}

export interface T {
}"
```

So it matches the behavior prior to the change. Currently I fix the ```A`1``` in the `TypeScriptResolver` as I mentioned above, so this is fine for me until generics are supported. I don't know if it's useful for anyone else though.

**Comment by grovesNL** [comment]
@RSuter Sounds great, thanks!
