### ISSUE TITLE
strings in moment fields

### ISSUE THREAD

**Issue by jtheisen** [RSuter/NSwag#878]
I was trying to get `moment.Moment` objects for dates.

Setting `TypeScriptGeneratorSettings.DateTimeType` to `TypeScriptDateTimeType.MomentJS` does indeed change the TypeScript type of the respective fields, but I get only strings in them at runtime.

Looking at the generated TypeScript, I can't see any conversion code. It seems that the result from the server is simply parsed with `JSON.parse` and passed unmodified to the application code.

I just updated to the most recent NuGet package.

**Comment by RSuter** [comment]
this only works if you use DTO classes - this cannot work with DTO interfaces

**Comment by jtheisen** [comment]
I don't see why.

And if it's not supported, it should probably better throw.

**Comment by RSuter** [comment]
This is because the received JSON is just parsed and returned - we cannot convert it to the correct structure. But you could inject a custom reviver and parse the datetime objects yourself...

**Comment by jtheisen** [comment]
I don't see why it has to be that way - the client knows the type structure, so it can deserialize the json with the correct types.

Thinking about it, I'm no longer sure whether it's such a good idea in my own case specifically though. I'm using MobX, and that thinks all types with ctors (like moment.Moment) are user-defined, which would be bad in this case.

**Comment by jtheisen** [comment]
Ok, since my motivation to have this work is gone you can have this closed if you feel the current behavior is as intended.

**Comment by RSuter** [comment]
Have you checked the generated code for the DTO interfaces? It's just JSON.parse and returning the result... If you want to have correct date objects or rename properties, we have to post process this result and this means generating a lot of code...

**Comment by jtheisen** [comment]
Yes, it would generate more code.

By the way, I've got this related suggestion that one could generate only the client interface and the type information in a form that's available at runtime so that you could use this one definition with all of the different ways of calling the server (jquery, fetch, angular, etc.).

That way, the generated code would stay really lean (much more so even than it is now) and it could also be used in a more flexible manner.

Just a thought, after all it's very different from how it's being done now. I just always wanted to drop this thought.

I'm closing this then.
