### ISSUE TITLE
Float being sent with comma rather than decimal point

### ISSUE THREAD

**Issue by dbruning** [RSuter/NSwag#880]
Hi,

I've had a bug request from a german customer, which turns out to be due to my CSharpClient sending floats like this in URL's: 
&reach=619%2C563522438208
... where the %2C is a url-encoded comma. The server is expected a decimal point and so won't parse the URL.

In my generated client, the code looks like this:
`urlBuilder_.Append("reach=").Append(System.Uri.EscapeDataString(reach.ToString())).Append("&");`

... so that problem here is that ToString() will be formatting the number with a comma due to the German culture settings of the client.
I'm pretty sure that Json.NET would have serialised with a decimal point. I can't find anywhere stating 100% that decimals should always use decimal point characters in URLs, but there is a bit of a discussion [here](https://stackoverflow.com/questions/39017012/how-to-format-a-decimal-floating-point-number-parameter-in-url)

Would be great if there was a central place where I could provide my generated client with a culture to be used an all ToString() calls?

**Comment by RSuter** [comment]
Hmm good idea, maybe we should generate only ToLocaleString(this.locale) and this.locale is a member on the client class with default "en-us"?

**Comment by dbruning** [comment]
Yep sounds like a plan.

**Comment by RSuter** [comment]
Just checked the templates, we use culture invariant for all tostring() calls. Your code is not generated with the latest version of nswag. What version are you using?

**Comment by dbruning** [comment]
Yep I was using 10.6. I will update to the latest, thanks.
