### ISSUE TITLE
Generating ASP.NET Core Controllers

### ISSUE THREAD

**Issue by ma499** [RSuter/NSwag#887]
SwaggerToCSharpWebApiControllerGenerator currently generates Web API 2 controllers. Would you be willing to accept a PR to generate ASP.NET Core controllers? 

I'm thinking this could be handled by passing a parameter, similar to #884.

What I'm open-minded about is whether to have separate T4 templates for ASP.NET core or to just add conditional formatting based on the model.

**Comment by RSuter** [comment]
I think this is a good idea. We should use the same template as it will be much more time consuming to always update both templates with new features... What do we have to change? Just change the namespaces of the base class and attributes?

**Comment by ma499** [comment]
That's pretty much it. It's minor enough.

**Comment by PerArneng** [comment]
This would be a great feature. I use it for client generation right now but it would be excellent to also use it as a generator for the controllers.  Then the producers and consumers could agree on one OpenAPI spec file and generate code on both sides. The perfect setup.

**Comment by PerArneng** [comment]
I created a powershell script and generated the controller. In the end of the script i just ran:
`
$replacements = @{
	"System.Web.Http.ApiController" = "Microsoft.AspNetCore.Mvc.Controller"; 
	"System\.Web\.Http\." = "Microsoft.AspNetCore.Mvc."; 
}

$content = [System.IO.File]::ReadAllText($sourceFile)

foreach ($replacement in $replacements.GetEnumerator()) {
    Write-Host "replacing $($replacement.Name) with $($replacement.Value)"
	$content = [System.Text.RegularExpressions.Regex]::Replace($content, $replacement.Name, $replacement.Value)
}

[System.IO.File]::WriteAllText($sourceFile, $content)
`
And then it worked fine for ASP.NET Core 2.0 at least

**Comment by RSuter** [comment]
Looks like we need two new settings: 

- [ ] **AspNetNamespace** (default: "System.Web.Http"), use for all attributes, etc. **OR**
   - Or just **IsAspNetCore** and hardcode the used namespace in the template
- [ ] ControllerBaseClass (default: "System.Web.Http.ApiController"). Does this already exist?

**Comment by tedepstein** [comment]
Hi @RSuter , wondering if you have an ETA for resolution of this issue? I can see there has been a lot of recent activity on NSwag, so I'm sure you're quite busy with other issues.  This one happens to be high-priority for one of our clients. Any updates appreciated.  Thanks!

**Comment by RSuter** [comment]
@tedepstein I'm currently concentrating on other issues which are relevant for a bigger audience and my paying clients

**Comment by tedepstein** [comment]
OK @RSuter . We may take a look at this and consider submitting a pull request if it's something we can address.

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/wiki/SwaggerToCSharpControllerGenerator

**Comment by rh78** [comment]
It seems something changed, see https://github.com/RSuter/NSwag/issues/1564
