### ISSUE TITLE
Nullability control for reference return values and parameters

### ISSUE THREAD

**Issue by jtheisen** [RSuter/NSwag#895]
For properties, nullability can be influenced with the `RequiredAttribute`.

How can I control whether the return value or certain parameters that are reference types are in fact meant to be non-nullable?

**Comment by RSuter** [comment]
At the moment the nullability of the response or parameter cannot be controlled directly... And yes, I agree we need an attribute to do that. Any suggestion what to use? An own one (eg SwaggerRequiredAttribute) or an existing one from the .net fw?

**Comment by jtheisen** [comment]
ASP.NET Core used to have `NotNullAttribute` for a while, but no longer. I like that it's short when it needs to come before parameters and it seems less weird in the context of return values. Not a strong opinion though.

In case you don't know (I didn't until a few seconds ago), you can actually apply attributes to return values:

```
[return: SwaggerRequired]
SomeReferenceType Foo()
```

**Comment by RSuter** [comment]
Maybe we should: 

- Add an own NotNullAttribute to NSwag.Annotations (also NotNullAttribute from R#/old ASP.NET will be supported), with support on parameters and return (as shown in your sample)
- Add Nullable (default: true) property to SwaggerResponseAttribute from NSwag.Annotations

> In case you don't know (I didn't until a few seconds ago), you can actually apply attributes to return values

Yes, I knew that but I don't like the syntax :)

**Comment by jtheisen** [comment]
Sounds all reasonable to me. And the return annotation syntax is a bit off, yes. I do like that it makes the same attribute type work for both parameters and return values.

Thinking of that, it may make sense to honor the attribute on properties also for consistency.

**Comment by RSuter** [comment]
https://github.com/RSuter/NJsonSchema/commit/d408df54457290018761035303f9f897df60816d

**Comment by jtheisen** [comment]
Works great, thanks for the quick fix.
