### ISSUE TITLE
XML Documentation missing with ASP.NET core 2.0

### ISSUE THREAD

**Issue by odinnou** [RSuter/NSwag#899]
Hi, I just create an API with the new ASP.net Core 2.0 framework.
I added NSwag, the swagger works but, the XML Documentation associate with functions (with /// comments) are not visible :(

I use Nswag in another API with ASP.net Core 1.1 (Full Framework 4.6.2) and no problem to display these comments

Thank you !

**Comment by RSuter** [comment]
Have you verified that the .xml documentation files for each dll are generated?

**Comment by odinnou** [comment]
Yes they are

![image](https://user-images.githubusercontent.com/3084655/29622636-38617a88-8824-11e7-87c9-6ab19e36e588.png)


but nothing :(

![image](https://user-images.githubusercontent.com/3084655/29622229-24f824ac-8823-11e7-883f-997285be06c3.png)

To configure NSwag, I just put these lines of code in Startup.cs / public void Configure(IApplicationBuilder app, IHostingEnvironment env)



app.UseSwaggerUi(typeof(Startup).GetTypeInfo().Assembly, new SwaggerUiSettings
            {
                DocumentProcessors =
    {
        new SecurityDefinitionAppender(....)
    }
            });

**Comment by RSuter** [comment]
Are the required nugets installed:

https://github.com/RSuter/NJsonSchema/wiki/XML-Documentation

?

**Comment by odinnou** [comment]
I upgrade from 11.3.5 to 11.4.1

then I add 

```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="NJsonSchema" Version="9.4.7" />
    <PackageReference Include="NSwag.AspNetCore" Version="11.4.1" />
    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
    <PackageReference Include="System.Xml.XPath.XDocument" Version="4.3.0" />
  </ItemGroup>

```
But don't work :( :( :(

I don't know if I need to configure NJsonSchema to display the documentation


Thank you, NSwag Team is awesome ^^

**Comment by RSuter** [comment]
Ok, I have the same problem in my sample project... investigating...

**Comment by RSuter** [comment]
It seems that the dynamic handling has been slightly changed: 

https://github.com/RSuter/NJsonSchema/commit/cb790767150038877d3878111efef9b7b18ffa8e

**Comment by RSuter** [comment]
v11.4.2

**Comment by RSuter** [comment]
Can you verify?

**Comment by odinnou** [comment]
Thank you !! It's OK !!!
