### ISSUE TITLE
Bad code generated for API call returning DateTime

### ISSUE THREAD

**Issue by CRidge** [RSuter/NSwag#901]
We have been generating a TypeScript 2.0 client (Angular 2) from our Web API using NSwagStudio (version 1.14.1.0) for a while now, but hit a snag when we recently added a method on one of our controllers which returned a DateTime. We use MomentJS for DatetTime Type.

The generated client included this method:

`   protected processGetStart(response: Response): Observable<moment.Moment | null> {
        const status = response.status;

        let _headers: any = response.headers ? response.headers.toJSON() : {};
        if (status === 200) {
            const _responseText = response.text();
            let result200: moment.Moment | null = null;
            result200 = new Date(_responseText);
            return Observable.of(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.text();
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Observable.of<moment.Moment | null>(<any>null);
    }`

The line

'result200 = new Date(_responseText);'

of course fails as result200 is a moment. It seems the date parsing doesn't honor the selected Date Time Type. Manually changing it to

'result200 = moment(_responseText);'

fixes the issue - but that's a pain to do every time the client is regenerated.

**Comment by RSuter** [comment]
Fixed in v11.4.3

**Comment by CRidge** [comment]
Excellent @RSuter - fantastic response time :)
