### ISSUE TITLE
NSwag.MSBuild 11.4.3.0 throwing error about assembly Microsoft.AspNetCore.Mvc.ViewFeatures

### ISSUE THREAD

**Issue by jim-strang** [RSuter/NSwag#905]
Recently upgraded my .NET Core 1.1 app to 2.0, and also updated the NSwag packages I was using. Calling NSwag.MSBuild inside of a pre-build event:

`$(NSwagExe) webapi2swagger /assembly:"$(SolutionDir)API\bin\$(Configuration)\netcoreapp2.0\API.dll" /output:API.swagger.json`

Produces the following error:

```
4>  NSwag command line tool for .NET 4.6+, toolchain v11.4.3.0 (NJsonSchema v9.4.8.0) (x64)
4>  Visit http://NSwag.org for more information.
4>  NSwag bin directory: C:\Users\jstrang\.nuget\packages\nswag.msbuild\11.4.3\build
4>  System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
4>  File name: 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

Anyone else having this issue with .NET Core 2.0?

**Comment by RSuter** [comment]
Is the file "'Microsoft.AspNetCore.Mvc.ViewFeatures" located in "$(SolutionDir)API\bin\$(Configuration)"?

**Comment by jim-strang** [comment]
Nope, but that doesn't seem to matter (unless I am completely missing something here). Its the NSwag.exe inside of "\.nuget\packages\nswag.msbuild\11.4.3\build" that is missing "Microsoft.AspNetCore.Mvc.ViewFeatures" as well as the Mvc.Core.dll

**Comment by jim-strang** [comment]
And yes, definitely doing a dotnet publish on the API project before trying to call NSwag on the API assembly. The spot where it is failing is on `$(NSwagExe) webapi2swagger` , and the same result if I call NSwag.exe (the one in  ".nuget\packages\nswag.msbuild\11.4.3\build") directly through command line. It was working as-is with .NET Core 1.1 and the most-recently-compatible version of NSwag.

Here's the gist of the build event:

` dotnet publish "$(SolutionDir)API\API.csproj" --configuration "$(Configuration)"`
`$(NSwagExe) webapi2swagger /assembly:"$(SolutionDir)API\bin\$(Configuration)\netcoreapp2.0\API.dll" /output:API.swagger.json`
`$(NSwagExe) swagger2csclient /input:API.swagger.json /classname:{controller}Client  /namespace:API.Client /output:Clients.Generated.cs`
`$(NSwagExe) swagger2tsclient /input:API.swagger.json /generateClientClasses:false /generateClientInterfaces:false /typeStyle:Interface /output:ServerModels.ts"`

**Comment by RSuter** [comment]
The msbuild package still runs in full .net 4.6.2 and maybe this fw is not able to load .net core 2.0 assemblies? Maybe we need a .net 4.7 or a .net core 2.0 version? Only the npm package is currently published with a .net core 2.0 version ("--core 2.0" switch)

**Comment by RSuter** [comment]
Can you create a repro of the problem?

Btw: You should use a nswag.json file and just run "nswag.exe run nswag.json" - much simpler to manage the config.

**Comment by jim-strang** [comment]
Sure, I'll create a sample project tonight or tomorrow and reply back here. Thank you for the tip about the json config, I'll definitely incorporate that. I'll keep you posted on the repro.

**Comment by jim-strang** [comment]
https://github.com/jim-strang/nswag-issue905-sample

Here's an example solution. Try building the API.Client project in Release mode and you will see the build errors. I tried to make it as simple as possible.

Please let me know if there is anything else I can do to help out with this issue.

**Comment by RSuter** [comment]
Strange, why are the ASP.NET Core assemblies not in the publish folder? Where are they loaded from? 

Btw: NSwag also provides a middleware like Swashbuckle and Swagger UI, you don't need both :-) - and if the Swagger is generated in-process, you avoid all these problems - but you cant generate code during compilation... (ie the server must be running and serve the spec for the code generator)

**Comment by jim-strang** [comment]
Right yeah - that makes sense, removing the Swashbuckle swagger gen is on my todo list. I want to have it done during the build so we can do c# and TS code gen based on the spec.

I assume that the .NET Core assemblies are pulled from the dotnet SDK location? Maybe dotnet publish changed between 1.1 and 2.0 and there's some other flag needed to copy ALL assemblies to publish. I'll look into that.

**Comment by RSuter** [comment]
Ok, I've got one step further. If I add

    <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>

to the .csproj, all required dlls are published. Now the assembly "netstandard" cannot be loaded...

**Comment by RSuter** [comment]
If I upgrade NSwagStudio to .NET 4.6.1 and install NETStandard.Library.NETFramework it works

https://www.nuget.org/packages/NETStandard.Library.NETFramework/2.0.0-preview2-25405-01

![image](https://user-images.githubusercontent.com/2603405/29689699-692564c6-8924-11e7-922c-0682a793e1ad.png)

But NETStandard.Library.NETFramework is deprecated :)

**Comment by jim-strang** [comment]
Nice! Good find. How about the regular NETStandard.Library? 

https://www.nuget.org/packages/NETStandard.Library/

**Comment by RSuter** [comment]
Nope, doesn't work... only working with the prerelease version of NETStandard.Library.NETFramework...

There must be something missing...

**Comment by RSuter** [comment]
Ref: https://github.com/dotnet/sdk/issues/1220

Maybe NSwagStudio.csproj is using the old MSBuild tooling and this is why it is not working?

**Comment by RSuter** [comment]
If i run the .net core 2.0 nswag cmd line tool it also works (if the dlls are in the publish folder).

**Comment by RSuter** [comment]
Ill do some more tests tomorrow, already too late..

**Comment by jim-strang** [comment]
No worries, let me know if I can help out in any way

**Comment by RSuter** [comment]
Ok, I think I've found a solution. If you add 

    <DependsOnNETStandard>true</DependsOnNETStandard>

to your project (NSwagStudio, NSwag.Console), the loading works if the web app is published with 

    <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>

I've updated the wiki, but we should improve it...

https://github.com/RSuter/NSwag/wiki/WebApiAssemblyToSwaggerGenerator#net-core

**Comment by jim-strang** [comment]
I'm looking into ways to have something "pick up" the .net core assemblies without having to publish with `<PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>`. Maybe something to do with `dotnet store`?

**Comment by RSuter** [comment]
Including with nswag is not an option because we would have to pick a specific version of asp.net - but nswag supports all versions of asp.net. This would force the users to always use the same asp.net version as nswag.

**Comment by RSuter** [comment]
Maybe this option can be set as dotnet publish cmd line param? 

Or you have to find the cache location and add this path to the ReferencePaths setting.

**Comment by RSuter** [comment]
Ref: https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store

**Comment by jim-strang** [comment]
`dotnet publish` with` --self-contained` seems to do exactly that (after you also specify a `--runtime` value)

**Comment by josemotta** [comment]
Hi,
I arrived here due original error at top, then I cloned Jim´s repo and added paths below to NSwag Studio in order to search for missing assemblies:

C:\_git\nswag-issue905-sample\API\bin\Release\PublishOutput
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0

Now error changed to a 4.6.1 version of another assembly:

Could not load type 'System.Object' from assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' because the parent does not exist.

I hope we can fix issue in order to run netcore 2 with swagger automation

**Comment by RSuter** [comment]
For me the latest code in master works ehen publishing all dlls... only problem is that the appveyor ci builds are no longer working.

**Comment by RSuter** [comment]
OK, now the CI build looks good... should we release so that you can really test this?

**Comment by jim-strang** [comment]
Works with me, if you push out a new release I can test it on my end later today and report back

**Comment by jim-strang** [comment]
NSwag.MSBuild 11.5.0 is looking good for me!

**Comment by josemotta** [comment]
It seems .msi is broken, I will wait for Rico fix.

**Comment by RSuter** [comment]
Fixed.

**Comment by RSuter** [comment]
Please report any problems. And we should update the wiki with tips how to load core assemblies: 

https://github.com/RSuter/NSwag/wiki/WebApiAssemblyToSwaggerGenerator#net-core

Maybe we should create a new page for the dll loader alone.

**Comment by josemotta** [comment]
Hi, good news! I noticed that  .msi is missing from the newest NSwag Build 868. I was testing at Windows and already uninstalled the previous version. Should I use now the command line?  In this case, I need to double check documentation in order to start using .zip file.

**Comment by RSuter** [comment]
The latest MSI should be fine...

**Comment by josemotta** [comment]
Sorry, I am missing something. The .msi from NSwag v11.5.0 (Build 866) is broken. Should I replace the .exe/.dll files in the Program Files folder with newest from NSwag Build 868 .zip?

**Comment by RSuter** [comment]
Its fixed in v11.5.1, use this: 

https://github.com/RSuter/NSwag/releases/tag/NSwag-Build-868

**Comment by josemotta** [comment]
Sorry again, there is no .msi installer there, only .zip and source code.

**Comment by RSuter** [comment]
Sorry, use this:

http://rsuter.com/Projects/NSwagStudio/installer.php

Will add tomorrow

**Comment by josemotta** [comment]
Great! Got it, error free now, 11.5.1 passed over the last error. I will keep testing.

**Comment by josemotta** [comment]
Working fine! Thank you.

**Comment by RSuter** [comment]
Created a new wiki page: 

https://github.com/RSuter/NSwag/wiki/Assembly-loading

please update with your tips, findings, etc...

**Comment by jim-strang** [comment]
updated with a link to the runtime catalog
