### ISSUE TITLE
Generating client from contracts

### ISSUE THREAD

**Issue by cruikshj** [RSuter/NSwag#909]
Is it possible to generate a client from previously generated contracts?  I would like to be able to publish contracts to a nuget feed and then consume them in a client factory at runtime.  So far, I have come up with using `AssemblyTypeToSwaggerGenerator` to create a `SwaggerDocument` from contracts, then passing that document into a `SwaggerToCSharpGenerator`.  However, there are certain settings involved in generating a client that are not provided by the swagger document, such as `ArrayType` or `DateTimeType`.  These theoretically would not be necessary as I have the interfaces and objects with the important type information as part of the generated contracts.

**Comment by cruikshj** [comment]
After prototyping some more, I have determined that `AssemblyTypeToSwaggerGenerator` is not suitable for generating a swagger document from contracts.  I have started creating a new generator as a port of the `WebApiToSwaggerGenerator` called `ContractsToSwaggerGenerator` which will use the interfaces as a source for operations rather than controllers. 

However, I still anticipate issues determining some of the other NSwag client generator settings purely from contracts.

**Comment by cruikshj** [comment]
Never-mind me... the dream is dead.  Not enough info in pure contracts to reverse engineer a client.  I plan on including the swagger.json and nswag config along with the contracts.

**Comment by RSuter** [comment]
If the contracts describe only the DTOs then its not possible. You also need the operation contracts...

**Comment by cruikshj** [comment]
The contracts actually do describe the operations via interfaces.  However, the interfaces generated by nswag do not have the Http/Route attributes that would be necessary to derive operations.

**Comment by RSuter** [comment]
I dont understand why you would want that? Why dont generate a swagger spec in the first place and reuse that?

**Comment by cruikshj** [comment]
I am attempting to dynamically generate a client at runtime with contracts generated at build time of the service.  I can then develop against actual types (the contracts), and let a factory figure out the implementation at runtime.  The factory is generic and built to support this concept for many (potentially hundreds) of micro services.  

The benefit is to avoid generating clients at build time as that code is much more complicated and prone to change than the contracts themselves.  If I want to change how the client works (to make it more efficient) I do not have to update hundreds of microservices, just the client factory library.

**Comment by RSuter** [comment]
Maybe you can dynamically create a list of all pre compiled dto types and pass this as type exclusions to the dynamic client generator?

**Comment by cruikshj** [comment]
It looks like I can generate specifically the implementation of the client using:
```
var generator = new SwaggerToCSharpClientGenerator(swaggerDocument, settings);
var code = generator.GenerateFile(ClientGeneratorOutputType.Implementation);
```
I have not tried it yet.  But this leads me to believe I would not have to exclude any types.  It comes down to getting a swagger document and settings.  I was hoping to get those things purely from the "Contracts" (interfaces and dtos), but there is not enough information directly on the interfaces.  In the end, I think this ok.  Otherwise the contracts would have dependencies on the server technology (like ASP.NET Web API).  

I plan on embedding the `swagger.json` and `nswag.json` files in my contracts assembly.  My factory can pull these files after getting a reference to the contracts assembly when provided an interface type off of the contracts.
