### ISSUE TITLE
NSwagDir removed from NSwag.MSBuild.props

### ISSUE THREAD

**Issue by paulomorgado** [RSuter/NSwag#911]
`NSwagDir` was added in https://github.com/RSuter/NSwag/commit/8745ffddea7355464f561cb081442feb6e5887fd to allow its use from T4 templates.

It has been remove on version 11.5.1 of `NSwag.MSBuild`.

**Comment by RSuter** [comment]
Fixed in msbuild v11.5.1.1

**Comment by RSuter** [comment]
Current version on nuget: 

https://github.com/RSuter/NSwag/blob/master/src/NSwag.MSBuild/NSwag.MSBuild.props

Do you think it's ok?
