### ISSUE TITLE
JsonProperty ignored in NSwag.Msbuild

### ISSUE THREAD

**Issue by purple-lemon** [RSuter/NSwag#912]
if we have class like that

public class Product{
[JsonProperty("my_name")]
public string MyName {get;set}
}

in generated code it looks like it:

public class Product{
[Newtonsoft.Json.JsonProperty("MyName ", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
public string MyName {get;set}
}

**Comment by RSuter** [comment]
What version of NSwag.MSBuild and what binary are you using?

**Comment by RSuter** [comment]
Can you provide a sample project?

**Comment by purple-lemon** [comment]
Sure, will do it on this week, if you are ok to wait.

**Comment by RSuter** [comment]
Just tried this in my project and had no issues: 

1. Open project with NSwag.MSBuild
2. Added JsonPropertyAttribute with new property name
3. Regenerated swagger.json / client.cs
4. New property name has been detected

**Comment by RSuter** [comment]
I think I have the same problem with one of my project when using the .NET Core 2.0 binaries...

**Comment by RSuter** [comment]
Are also seeing this problem with the .net core binaries?

**Comment by RSuter** [comment]
Just FYI: I had the same problem with a .NET Core project and generating with the .NET Core NSwag binaries. This has been solved in the latest release - please retest

**Comment by RSuter** [comment]
After many attempts to solve this i think its finally fixed with nswag v11.15
