### ISSUE TITLE
Support yaml

### ISSUE THREAD

**Issue by gozdebozkurt** [RSuter/NSwag#913]
Hi,
We would like to use yaml file instead of json file for web api controller generation. Will NSwag support yaml in the future? If not would you consider the option to support it?
Thanks,

**Comment by RSuter** [comment]
Do you know a JSON <-> YAML conversion library for .NET?

**Comment by gozdebozkurt** [comment]
I did some research about that. [It](https://github.com/aaubry/YamlDotNet) looks very popular. I never used it. But maybe you can have a look if you want.

**Comment by RSuter** [comment]
**If yaml and json are fully compatible (ie can be converted back and forth)**, then this should be pretty simple: 

- [ ] Create new project "NSwag.Core.Yaml"
- [ ] Reference YamlDotNet via NuGet
- [ ] Implement static class SwaggerDocumentYaml with
    - static FromYaml (converts yaml to JSON and calls SwaggerDocument.FromJson())
    - ToYaml extension method (calls SwaggerDocument.ToJson() and converts it to yaml)

**Comment by RSuter** [comment]
Added the project, currently completely untested...

**Comment by gozdebozkurt** [comment]
Hi,

Thanks for supporting yaml. 
I'm trying to use it but it returns parsing error. Maybe some commands don't support yaml yet. Could you have a look, please? 

**Package  NSwag.MSBuild.11.12.3** 
**Command**
swagger2cscontroller 
input: ..\src\Web\openapi.yaml 

**Error**
 Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: s. Path '', line 0, position 0. (TaskId:6)
1>     at Newtonsoft.Json.JsonTextReader.ParseValue() (TaskId:6)
1>     at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter) (TaskId:6)
1>     at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) (TaskId:6)

Thanks,

**Comment by RSuter** [comment]
Try v11.12.4, available in the next minutes...
