### ISSUE TITLE
SwaggerResponseAttribute - Make Type optional

### ISSUE THREAD

**Issue by redbaran** [RSuter/NSwag#917]
Suggested feature: For some response codes, there is no data to be returned. The SwaggerResponse should be able to be created with just an HttpStatusCode and a description. So instead of:
`[SwaggerResponse(HttpStatusCode.NotFound, typeof(object), Description = "Not Found")]`

This (or similar):
`[SwaggerResponse(HttpStatusCode.NotFound, Description = "Not Found")]`

It wasn't clear to me in the beginning that typeof(object) should be used when there is no explicit type.

**Comment by RSuter** [comment]
Use typeof(void) in the case of no response

**Comment by RSuter** [comment]
- [ ] Add new ctors without `type` parameter and set type to `typeof(void)`

**Comment by redbaran** [comment]
Being on the other side of this now and knowing how to do it, I think it's a minor inconvenience. typeof(void) isn't something that I've had to use frequently, so I suspect for a lot of people, it's not going to come to mind to use it.

I'm trying to think of what the downsides are to automatically setting the type but with as green as I am to all of this, I'd just be guessing. It definitely feels like a sane default though.

**Comment by RSuter** [comment]
Its documented here:
https://github.com/RSuter/NSwag/wiki/WebApiToSwaggerGenerator#specify-the-response-type-of-an-action

And i dont like it to be implicit because it may confuse users as it would replace the actual response type and some people might think that the attribute with just a status code only changes the status code but not the method response type..

**Comment by redbaran** [comment]
I do remember scanning over that now, but I took that more in the context of forcing a 204, but now that I read it again, I see it clearer.

I made a minor edit to the page to show that usage. Feel free to backout if need be.

Thanks for the great project!
