### ISSUE TITLE
wrong xml declaration NSwag.MSBuild.props 11.6.0

### ISSUE THREAD

**Issue by LeonidEfremov** [RSuter/NSwag#920]
\NSwag.MSBuild.11.6.0\build\NSwag.MSBuild.props missing second char:

`<xml version="1.0" encoding="utf-8"?>`

it have to be

`<?xml version="1.0" encoding="utf-8"?>`

**Comment by RSuter** [comment]
Is this breaking the package?

**Comment by LeonidEfremov** [comment]
This typo break my build, because of (.csproj) this usage
`<Import Project="..\packages\NSwag.MSBuild.11.6.0\build\NSwag.MSBuild.props" Condition="Exists('..\packages\NSwag.MSBuild.11.6.0\build\NSwag.MSBuild.props')" />`

**Comment by RSuter** [comment]
v11.6.1
