### ISSUE TITLE
TypeLoadException: Could not load type TaskAwaiter from System.Runtime

### ISSUE THREAD

**Issue by zuckerthoben** [RSuter/NSwag#922]
I am trying to generate a CSharp client for my asp.net core Web Api project. I added the "PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>" to the csproj, which didnt work and then I compiled self contained via CLI. When generating output I get the following exception however: 

Could not load type 'System.Runtime.CompilerServices.TaskAwaiter`1' from assembly 'System.Runtime, Version=4.0.0.0, Culture...

Server stack trace: 
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.<>c.<GetActionMethods>b__14_1(MethodInfo m)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.<GenerateForControllerAsync>d__11.MoveNext()

Whats up here?

**Comment by RSuter** [comment]
Can you provide a reproduction sample project?

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/wiki/Assembly-loading#troubleshooting

**Comment by zuckerthoben** [comment]
When I try to add the assembly that fails to load into the ".NET Assembly Paths" as described in the troubleshooting, I get the following error: 

Could not load file or assembly or one of its dependencies. Strong name signature could not be verified. The assembly may have been tampered with ... 

Tried with: C:\Users\<user>\source\repos\BlobApiTest\BlobApiTest\bin\Debug\netcoreapp2.0\win10-x64\publish\System.Runtime.dll

Here is the sample project: https://www.file-upload.net/download-12696327/BlobApiTest.zip.html

**Comment by RSuter** [comment]
With NSwag.NPM it works when using the .NET Core binaries: 

     nswag run nswag.json /runtime:core2.0

With this config in the project directory: 

[nswag.zip](https://github.com/RSuter/NSwag/files/1283654/nswag.zip)

But this is not a solution - I'd like this to work also with a full .NET process...

**Comment by zuckerthoben** [comment]
Ok, I will try that. Can I generate the client with code instead of the GUI? Will it also crash?
Do you know what the issue is? 
I know that it worked with a blank solution. After I added some packages and logic, I started getting errors.

**Comment by RSuter** [comment]
The problem is that NSwagStudio always generates in the same process in a seperate AppDomain (full .NET) with the command line (NSwag.NPM) you also have binaries for .NET Core and you can generate in a .NET Core process, which works... 

The question is whether it makes sense to search for solutions to generate .NET Core assemblies in a full .NET process/AppDomain or if we should just refactor NSwagStudio so that it internally uses the one of the runtime specific command line exes (full .net, core...)

**Comment by RSuter** [comment]
With these settings: 

![image](https://user-images.githubusercontent.com/2603405/30151310-2e859cf6-93af-11e7-840c-6aced5db6aa4.png)

You can use the UI to configure, save the "nswag.json" file and run the command line .NET core binary against it: 

     nswag run nswag.json /runtime:core2.0

this works. 

But id like a solution which works out of the box :)

**Comment by RSuter** [comment]
Btw: With these settings I can now load the controller names (see screenshots) but generation gives mit this error: 

'Could not load type 'System.Object' from assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' because the parent does not exist.'

same as https://github.com/RSuter/NSwag/issues/918

**Comment by RSuter** [comment]
In v11.7 the annotations redirect is removed, you can use studio to create the nswag.json file and run it via cmd line and the core binaries. 

I hope to find a solution for this so that it also works in a full .net process.

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/issues/952

**Comment by RSuter** [comment]
Implementation: https://github.com/RSuter/NSwag/issues/953

**Comment by RSuter** [comment]
Please test the new feature with the CI build: 

https://github.com/RSuter/NSwag/issues/953#issuecomment-330751737

**Comment by RSuter** [comment]
Please discuss this in the new issue: https://github.com/RSuter/NSwag/issues/953

**Comment by RSuter** [comment]
v11.8 has been released, please test your projects with it: 

![image](https://user-images.githubusercontent.com/2603405/30813908-001d7afa-a20f-11e7-890a-63956094a788.png)
