### ISSUE TITLE
WebApiAssemblyToSwaggerGenerator settings serialization loose TypeMappers

### ISSUE THREAD

**Issue by MaxDeg** [RSuter/NSwag#923]
https://github.com/RSuter/NSwag/blob/af109c212bdee3bf5ac59ee53f68e8e6fa392315/src/NSwag.AssemblyLoaderCore/SwaggerGenerators/WebApi/WebApiAssemblyToSwaggerGenerator.cs#L86

https://github.com/RSuter/NSwag/blob/af109c212bdee3bf5ac59ee53f68e8e6fa392315/src/NSwag.AssemblyLoaderCore/SwaggerGenerators/WebApi/WebApiAssemblyToSwaggerGenerator.cs#L102

In the WebApiAssemblyToSwaggerGenerator when you call GenerateForControllersAsync with settings containing TypeMappers, the serialization of settings in json loose those typemappers.

A simple fix is to not serialize the settings to json (I don't know the reason it's done like that).

Here is my usage of WebApiAssemblyToSwaggerGenerator to use Nodatime instead of BCL DateTime.
```csharp
            var settings = new WebApiAssemblyToSwaggerGeneratorSettings
            {
                AssemblyPaths = options.InputFilePaths.ToArray(),
                IsAspNetCore = options.IsAspNetCore,
                DefaultEnumHandling = options.DefaultEnumHandling,
                DefaultPropertyNameHandling = options.DefaultPropertyNameHandling,
                FlattenInheritanceHierarchy = options.FlattenInheritanceHierarchy,
                Title = options.Title,
                Version = options.Version,
                TypeMappers =
                {
                    new PrimitiveTypeMapper(typeof(LocalDate), s =>
                    {
                        s.Type = JsonObjectType.String;
                        s.Format = "date";
                    }),
                    new PrimitiveTypeMapper(typeof(OffsetDateTime), s =>
                    {
                        s.Type = JsonObjectType.String;
                        s.Format = "date-time";
                    }),
                }
            };
            
            var generator = new WebApiAssemblyToSwaggerGenerator(settings);
            var controllerClasses = generator.GetControllerClasses();
            var document = await generator.GenerateForControllersAsync(controllerClasses).ConfigureAwait(false);

            var swaggerJson = document.ToJson();
            await File.WriteAllTextAsync(options.OutputFilePath, swaggerJson).ConfigureAwait(false);
```

**Comment by RSuter** [comment]
WebApiAssemblyToSwaggerGenerator  runs the WebApiToSwaggerGenerator in a second, isolated AppDomain (like a process), you cannot just pass the settings over to this AppDomain. This is why the settings serialized with JSON. 

To fix this, we need to pass the type mappers, and other extension classes (e.g. custom PropertyNameGenerator, etc.) as string (just class name) and create an instance in the second appdomain.
I began with this in the "extension-points" branch, but didn't have the time for this yet: 

https://github.com/RSuter/NSwag/commit/6d91f61053761333a27ded8e044a288bd8eb1139

At the moment, if you need typemappers, etc then you have to generate the swagger spec via ASP.NET middleware or via C#.

**Comment by MaxDeg** [comment]
Ok for fullnet but we got the issue with netcore. In that case the serialization is not really needed.

By the way what the reason of running it in an isolated AppDomain?

**Comment by RSuter** [comment]
If you don't need to run it in a separate AppDomain (full .NET) or AssemblyLoadContext (.NET Core) just use WebApiToSwaggerGenerator and everything should work as expected. 

AppDomains are required if you need to load and unload DLLs - in the main AppDomain you cannot unload DLLs - and to avoid conflicts with assembly version. Usually if a dll is already loaded, you cannot load the same dll with another version - but NSwag requires this to do, because it loads external assemblies which may have other versions - and this is only possible with appdomains. Also they are required if you want do cleanup all loaded assemblies after genererating a swagger spec..

**Comment by RSuter** [comment]
And BTW: I think we should support nodatime out of the box without typemappers?

**Comment by MaxDeg** [comment]
Indeed it works perfectly :)
My bad.

Thanks for the very quick answer ;)

Well indeed supporting NodaTime out of the box would be a great idea :)

**Comment by MaxDeg** [comment]
Yes it's not working without them

**Comment by RSuter** [comment]
We just need to add them here 

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/JsonObjectTypeDescription.cs#L79

**Comment by MaxDeg** [comment]
Well there a lot of types for NodaTime, not only those 2. 
http://nodatime.org/2.2.x/userguide/core-types
