### ISSUE TITLE
Return type defined anonymously in swagger.json on certain conditions

### ISSUE THREAD

**Issue by jtheisen** [RSuter/NSwag#928]
I'm generating a TypeScript client from a WebAPI. I have a function that returns an enum:

        public SetPasswordResult SetPassword(Guid accountId, Guid userId, [NotNull] String oldPassword, [NotNull] String password, String passwordRepetition) { ...

The enum gets defined in the emitted swagger.json, but it's not used as the return type of the function:

    "/api/Users/SetPassword": {
      "post": {
        "tags": [
          "Users"
        ],
        "operationId": "Users_SetPassword",
        "parameters": [ ... ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "integer",
              "description": "",
              "x-enumNames": [
                "Ok",
                "OldPasswordIncorrect",
                "PasswordsDontMatch",
                "PasswordTooShort"
              ],
              "enum": [
                0,
                1,
                2,
                3
              ]
            },
            "x-nullable": false
          }
        }
      }
    }

The resulting TypeScript is thus not created correctly either.

Strangely this happens only when I create the client through MSBuild by calling nswag.exe with a configuration file. When I create it by calling the nswag api programmatically, it doesn't happen. I reckon I must have the configuration slightly different, but I don't see how. (My config.nswag is here:
 [config.nswag.txt](https://github.com/RSuter/NSwag/files/1281903/config.nswag.txt))

Any idea why this happens?

**Comment by RSuter** [comment]
So is the problem the Swagger generator or the code generator?

**Comment by jtheisen** [comment]
The Swagger generator.

**Comment by RSuter** [comment]
This looks as if its the correct output (except that the enum is not referenced)? How does the incorrect swagger spec look like?

**Comment by jtheisen** [comment]
Yes, it's correct except that the enum isn't referenced.

Here's the complete wagger spec: [client.nswag.json.txt](https://github.com/RSuter/NSwag/files/1283731/client.nswag.json.txt)

**Comment by jtheisen** [comment]
Man, that's one hell of a fast support I'm getting here...

**Comment by RSuter** [comment]
Just try with the ci build first :)
