### ISSUE TITLE
Cant set CSharpGeneratorSettings in SwaggerToCSharpClientGeneratorSettings

### ISSUE THREAD

**Issue by zuckerthoben** [RSuter/NSwag#929]
According to: https://github.com/RSuter/NSwag/wiki/SwaggerToCSharpClientGenerator

You can initialize SwaggerToCSharpGeneratorSettings and set CSharpGeneratorSettings in the initializer. SwaggerToCSharpGeneratorSettings is abstract though, so you need to use SwaggerToCSharpClientGeneratorSettings. The problem now is that CSharpGeneratorSettings is readonly (although the summary says "Gets or sets") and I cant set it in SwaggerToCSharpClientGeneratorSettings initializer, because it is inheriting the readonly field from the base class. Am I wrong or is the documentation wrong and/or  the implementation? I would suggest making CSharpGeneratorSettings not readonly in the base class. Cant find a reason why it should be readonly and changing it also shouldn't break something, since its adding rather than removing. 

https://github.com/RSuter/NSwag/blob/523028bd56a7d5ab76b445869f6d27e68abd8ea0/src/NSwag.CodeGeneration.CSharp/SwaggerToCSharpGeneratorSettings.cs

https://github.com/RSuter/NSwag/blob/4ef97476691c13a89eaab650c48a35d68bdd2450/src/NSwag.CodeGeneration.CSharp/SwaggerToCSharpClientGeneratorSettings.cs

**Comment by RSuter** [comment]
The reason is that some properties (eg NullHandlung) must be correctly set for swagger generation and this is why these settings can only be changed via properties but not replaced...

Why do you need to replace it? Cant you just change the props on it?

**Comment by zuckerthoben** [comment]
Now I got it. So it should be: 

    var settings = new SwaggerToCSharpClientGeneratorSettings
    {
        ClassName = "{controller}Client",
        GenerateClientInterfaces = true,
        InjectHttpClient = true,
    };

    settings.CSharpGeneratorSettings.Namespace = "<Namespace>";

I guess the documentation should be updated?

**Comment by RSuter** [comment]
You can also: 

```
var settings = new SwaggerToCSharpClientGeneratorSettings
{
    ClassName = "{controller}Client",
    GenerateClientInterfaces = true,
    InjectHttpClient = true,
    CSharpGeneratorSettings
    {
         Namespace = "<Namespace>"
    }
};
```

**Comment by blumu** [comment]
@RSuter Why not make the specific properties readonly rather than making `CSharpGeneratorSettings` entirely readonly? In a language like F# that would allow one to define the setting object entirely in the constructor without any mutation (like it was possible before). I also agree with @zuckerthoben that the XML documentation is confusing: `Get or set the Csharp generator settings` suggests that you can set the `CSharpGeneratorSettings` property itself. It might be helpful to rephrase.

**Comment by RSuter** [comment]
Because we need special settings in CSharpGeneratorSettings for Swagger which are set in the ctor of SwaggerToCSharpClientGeneratorSettings. If we would allow to set the CSharpGeneratorSettings, we could not ensure that they are correctly set.

**Comment by blumu** [comment]
What about making it a parameter to the constructor then? @rsuter

**Comment by RSuter** [comment]
An additional ctor with this as parameter would be possible, yes. Where is the problem anyway? You can change properties on the precreated CSharpGeneratorSettings instance...
