### ISSUE TITLE
Suggestion: Following nullable reference types

### ISSUE THREAD

**Issue by jtheisen** [RSuter/NSwag#931]
I've come to realize that I'm now basically putting `[NotNull]` *everywhere*.

Maybe you've heard about the proposal for [nullable reference types](https://gist.github.com/olmobrutall/31d2abafe0b21b017d56) that will make unqualified reference types be non-nullable by default. ([champion](https://github.com/dotnet/csharplang/blob/master/proposals/nullable-reference-types.md))

Not sure how likely that is to make it, but it's one of the more popular proposals.

I think for NSwag, it makes sense to have a mode where the `[NotNull]` is implicit on everything: Properties, return values and parameters - and then have another attribute `[Null]` or `[CanBeNull]`.

**Comment by RSuter** [comment]
Makes sense, this must be a setting for NJsonSchema (handled in JsonObjectTypeDescription). 

Yes, I've heard. I just have two open questions: 

- Is this just a compiler feature, or how can you read these ! via reflection? Do they generate [NotNull] attributes or how is this working internally?
- Are these ! also applied to .NET framework (BCL) classes so that the feature is even usable?

**Comment by jtheisen** [comment]
I think they're adding attributes and yes, they need to go over all the framework stuff at least. Bold move.

**Comment by RSuter** [comment]
This feature would be extremely cool (see typescript). Considering all the work to do (add flow analysis to roslyn, tag whole bcl, ensure backward compability, have a solution for all edge cases) it may take a while...

**Comment by jtheisen** [comment]
Added the wrong proposal earlier, [this is the right one](https://github.com/dotnet/csharplang/blob/master/proposals/nullable-reference-types.md).

The new proposal has no !, just ? like with value types.

**Comment by RSuter** [comment]
Ah no ! and a project flag to treat reference types as not null? This is the best solution i think...

BTW: I added the settings DefaultReferenceTypeNullHandling (default null) so that you can change the default behavior... not released yet.

**Comment by RSuter** [comment]
Added in v11.7.0 - please test with the latest release. And if you have the time, add some unit tests to NJS to cover this feature :-)

**Comment by jtheisen** [comment]
Is there also an attribute for allowing nulls now?

**Comment by RSuter** [comment]
CanBeNullAttribute, but its not yet in NJsonSchema.Annotations (you have to implement it yourself). Ill add it just now...

**Comment by RSuter** [comment]
The attributes are also defined in https://www.nuget.org/packages/ReSharper.Annotations/
