### ISSUE TITLE
Question: ProducesResponseType for BadRequest when using Model validation (ASP.Net Core Web Api)

### ISSUE THREAD

**Issue by zuckerthoben** [RSuter/NSwag#932]
I have an ASP.NET Core 2.0 Web Api that uses Model Validation. I want to throw BadRequest results with the ModelState to inform the API user why the model he posted is not valid. I tried not specifying the response type at all, IActionResult, BadRequestResult, BadRequestResult and ModelStateDictionary. The actual string response from the api is e.g.:   

"{\"Data\":[\"You cant upload data bigger than 15MB\"]}"

Everything I tried out does not deliver the result I wish for. The ModelState ErrorMessage is hidden all the time. 

The model property:

    /// <summary>
    /// Gets or sets the content
    /// </summary>
    [Required]
    [MaxLength(15728640, ErrorMessage = "You cant upload data bigger than 15MB")]
    public byte[] Data { get; set; }

The Validation Attribute: 

    /// <summary>
    /// A Filter for all actions for cross
    /// </summary>
    public sealed class ValidateModelAttribute : ActionFilterAttribute
    {
        /// <inheritdoc/>
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (!context.ModelState.IsValid)
            {
                context.Result = new BadRequestObjectResult(context.ModelState);
            }
        }
    }

The controller action: 

       
    [ValidateModel]
    [HttpPost]
    [ProducesResponseType(typeof(BlobItem), 200)]
    [ProducesResponseType(typeof(ModelStateDictionary), 400)]
    public async Task<IActionResult> Create([FromBody] BlobItem item)
    {
         var blobItem = await BlobHelpers.PostBlobItemAync(this.container, item);
         return this.CreatedAtRoute("GetBlobInfo", new { blobName = blobItem.Name }, blobItem);
    }

The issue with ModelStateDictionary is, that almost all required properties are empty, so the Serializer throws an exception. 

What is the best way to throw BadRequests with the NSwag workflow?

**Comment by RSuter** [comment]
As always there are many ways to solve this: 

- The simplest way is to create an own ModelStateDictionary DTO class, catch the 400 error and respond with the DTO class (and specify  ModelStateDictionaryDto as ProducesResponseType)
- You could also write an own ASP.NET serializer for ModelStateDictionary and an NSwag OperationProcessor which adds the correct schema for the 400 error

**Comment by zuckerthoben** [comment]
My simple solution so far is to just return string inside the attribute and fill the message for the http result. This is simple for consumers and hides implementation, compared to returning the full modelstatedictionary.

**Comment by RSuter** [comment]
Sorry, I don't understand :-)

**Comment by springy76** [comment]
I would try `Dictionary<string,string[]>`
