### ISSUE TITLE
Generated CSharp Code contains leading digit `1` instead of operation name

### ISSUE THREAD

**Issue by marcwittke** [RSuter/NSwag#934]
Reproduction:
- Open NSwagStudio
- Point to [this Swagger documentation](https://ps-reg-demo.chemaxon.com/RegistryCxn/rest/api/doc)
- Tick "CSharp Client"
- Generate Outputs

Behavior:
The resulting code is syntactically wrong. Line 2171 (2181 similar) and following read:

```
public System.Threading.Tasks.Task<SearchResult> 1Async(SearchRequest searchRequest)
{
    return 1Async(searchRequest, System.Threading.CancellationToken.None);
}
```

Note the syntactically wrong ```1``` at the beginning of the identifier.

Expected Behavior:

```
public System.Threading.Tasks.Task<SearchResult> SearchAsync(SearchRequest searchRequest)
{
    return SearchAsync(searchRequest, System.Threading.CancellationToken.None);
}
```

Same behavior can be reproduced using the API through .net itself:

```
SwaggerDocument document = await SwaggerDocument.FromUrlAsync("https://ps-reg-demo.chemaxon.com/RegistryCxn/rest/api/doc");
SwaggerToCSharpClientGeneratorSettings settings = new SwaggerToCSharpClientGeneratorSettings();
SwaggerToCSharpClientGenerator generator = new SwaggerToCSharpClientGenerator(document, settings);
string code = generator.GenerateFile();
```

**Comment by RSuter** [comment]
Try using 

![image](https://user-images.githubusercontent.com/2603405/30286242-34c5f492-9721-11e7-9200-9d0b72a0d641.png)

**Comment by marcwittke** [comment]
This worked. However, I leave it up to you to decide if this is bug to fix or "as designed". Thanks for your response!

**Comment by RSuter** [comment]
This is as designed - the default mode assumes that the operation ID is "controllerName_operationName" as generated by NSwag (Web API => Swagger). 

In CSharp you can also implement an own OperationGenerationMode...

**Comment by Jehoel** [comment]
Which parts of a Swagger JSON file determine the method naming? I have an NSwag project where I can't change the Operation Generation Mode but I can change the input Swagger JSON file to produce valid output. Can I specify a manual name somewhere?
