### ISSUE TITLE
CSharp Client: Serialization of ContentParameter Prevents Certain TypeNameHandling

### ISSUE THREAD

**Issue by mataylor87** [RSuter/NSwag#942]
The current Serialization of a Content Parameter looks something like this:

`var content_ = new System.Net.Http.StringContent(Newtonsoft.Json.JsonConvert.SerializeObject(myParam, _settings.Value));`

Where `myParam` is passed to the CSharp client as type `BaseType` but is of a higher type `MyType : BaseType`

When `JsonSerializerSettings.TypeNameHandling = Auto` the resulting JSON will not generate $type data for `MyType`.

This can be fixed by passing `typeof` to the serializer method so that it can compare the types and decide if it should generate $type data.

`var content_ = new System.Net.Http.StringContent(Newtonsoft.Json.JsonConvert.SerializeObject(myParam, typeof(BaseType), _settings.Value));`

From my understanding this change would only affect people using `TypeNameHandling = Auto`. And therefore, would like to open it first up to discussion.

**Comment by RSuter** [comment]
See for correct support in swagger: https://github.com/RSuter/NJsonSchema/wiki/Inheritance

**Comment by mataylor87** [comment]
Unfortunately, the contracts and API are upstream and out of my control. The API is designed to look for the $type data on the passed in JSON. 

It impacts only two calls so my workaround is to hide these methods. Copy paste and manually pass the `typeof()`. Another workaround is to set `TypeNameHandling = All` but the overhead is too much. Neither of these workarounds are much preferred.

**Comment by RSuter** [comment]
At the moment this is not supported directly, first because you cannot describe this properly with a Swagger spec and second, it is a potentially security risk... but we could add a setting for that so that the $type is always set...

**Comment by mataylor87** [comment]
I admittedly am not an expert on this subject so please correct me where I am wrong.

I believe you are referring to the security issues this blog raises here: https://www.alphabot.com/security/blog/2017/net/How-to-configure-Json.NET-to-create-a-vulnerable-web-API.html

This setting can indeed be dangerous if contracts contain dynamic/object properties which can be deserialized to anything using $type. However, this is not the fault of Swagger/NSwag. Therefore, I don't think you should add a setting to make it easy to enable $type.

But, I don't see an inherit security danger in adding the typeof(ExpectedType) to SerializeObject. It's only purpose is to append $type if TypeNameHandling is turned on. Meaning the user has already assumed the risk of having such a flag turned on. And it is a much lesser evil than setting TypeNameHandling to All.

That's my two cents.

**Comment by RSuter** [comment]
Adding $type is not a security problem but processing $type is - of course this is your choice. My bigger problem is that this construct does not conform to the Swagger spec (i.e. your service is not interoperable with other programming langs because this contruct only works with .NET and Newtonsoft.Json). 

This is why Swagger uses "discriminator" and "allOf" to describe inheritance (as described here: https://github.com/RSuter/NJsonSchema/wiki/Inheritance)

However I'm ok to add a setting **SerializeTypeInformation** (default: false) (other name?) which adds the `typeof(BaseType)` to the `SerializeObject()` call. Is this the only change needed?

**Comment by mataylor87** [comment]
Yup, adding typeof to serialize is the only change needed when the setting is turned on. The setting name sounds good to me.

**Comment by RSuter** [comment]
Can't you enable GenerateUpdateJsonSerializerSettingsMethod and update the serializer in an own UpdateJsonSerializerSettings() so that the $type is added?

**Comment by mataylor87** [comment]
Yeah, that's what I am doing. I set `TypeNameHandling = Auto` in UpdateJsonSerializerSettings(). Setting it to All adds $type to everything, not just inherited types. That amount of overhead is too high.

The typeof() in SerializeObject is there exclusively for Auto: https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonConvert_SerializeObject_7.htm

_The type of the value being serialized. This parameter is used when TypeNameHandling is Auto to write out the type name if the type of the value does not match. Specifying the type is optional._

**Comment by RSuter** [comment]
Ok, so when the setting **SerializeTypeInformation** is true, then we should probably automatically use `TypeNameHandling = Auto` otherwise it makes no sense?

**Comment by mataylor87** [comment]
Agreed

**Comment by RSuter** [comment]
Please test with the CI artifacts

**Comment by mataylor87** [comment]
There is an issue with this code: `Newtonsoft.Json.Auto`
Should be: `Newtonsoft.Json.TypeNameHandling.Auto`

Also it could be combined in the previous line like this:

`var settings = new Newtonsoft.Json.JsonSerializerSettings { PreserveReferencesHandling = Newtonsoft.Json.PreserveReferencesHandling.All,  TypeNameHandling = Newtonsoft.Json.TypeNameHandling.Auto};

**Comment by RSuter** [comment]
I think its simpler like that in the template => the compiled IL is the same.

**Comment by mataylor87** [comment]
Yeah, to the compiler it should be the same.

Tested the CI and it looks good to me. Thanks for helping me out with this!
