### ISSUE TITLE
Value types are affected by defaultReferenceTypeNullHandling

### ISSUE THREAD

**Issue by jtheisen** [RSuter/NSwag#943]
When I set `defaultReferenceTypeNullHandling` to `notNull`, even nullable value types such as `Guid?` are defined as non-null unless they have a `[CanBeNull]` attribute (when used as parameters at least).

**Comment by RSuter** [comment]
Oh this is bad...

**Comment by RSuter** [comment]
I think we need some unit tests for this ;)

**Comment by RSuter** [comment]
I'm just releasing NJS v9.6.1, you can install/update this version in your root project (ie the application which is started) so that you can use this fix... NSwag will be released later.
