### ISSUE TITLE
Error trying to generate CSharp Client: Could not load type 'System.Runtime.CompilerServices.TaskAwaiter'

### ISSUE THREAD

**Issue by andrecarlucci** [RSuter/NSwag#952]
It was working before this version (sorry, I don't know exactly what version exactly I upgraded from)
I'm using `11.7.2.0` now.

The project is `asp.net core 2.0` and all references are `netstandard 2.0`.
I get this error even if I don't select any controller.

Any clues?

Thanks!

![image](https://user-images.githubusercontent.com/66689/30501187-d9339764-9a37-11e7-9e88-3df7de129009.png)

**Comment by andrecarlucci** [comment]
Wait, I'm trying the solutions from here: https://github.com/RSuter/NSwag/issues/922

**Comment by andrecarlucci** [comment]
I published as self-contained as oriented.

I got an error with `System.Runtime` when generating outputs (loading assemblies was fine)

![image](https://user-images.githubusercontent.com/66689/30503913-839fe662-9a42-11e7-9228-3eec8aaf67c4.png)

Then I added System.Runtime to the assembly paths, the error when generating outputs changed to:

![image](https://user-images.githubusercontent.com/66689/30504004-e89b0934-9a42-11e7-8eb2-95dea6d13dca.png)

Then I added System.Private.CoreLib.dll to assembly paths and the same error persistent, but now when I click on "Load assemblies"

Any clues?

**Comment by andrecarlucci** [comment]
Here is a small project (file -> new asp.net core 2.0, nothing fancy) that reproduces the problem.

[nswagtest.zip](https://github.com/RSuter/NSwag/files/1307790/nswagtest.zip)

**Comment by RSuter** [comment]
Can you try with this release?

https://github.com/RSuter/NSwag/releases/tag/NSwag-Build-877

**Comment by RSuter** [comment]
This is bad, i already tried to find a solution for this but couldnt find one... at least you can select all controllers: For now you could create the config in studio and run it with the core binaries (in the nswag.npm package or nswag.msbuild)

**Comment by RSuter** [comment]
I just tried your sample with various older versions, but it didnt work with any of them...

I tried many different things, but it isnt working. Maybe it is not possible to load .NET Core DLLs in a full .NET process - maybe you can try to move the controllers to a .NET Standard 2.0 project and load this in NSwagStudio?

My other solution is to ship all binaries (full .NET and .NET Core cmd line tools) with NSwagStudio and call these from NSwagStudio to generate (chosen via settings).

**Comment by RSuter** [comment]
I'm currently implementing the second solution: Call command line tools in NSwagStudio. 

https://github.com/RSuter/NSwag/tree/studio-uses-command-line

In the current version in the branch, you can select a runtime and the selected binary is used (this currently works only for "Generate Files"): 

![image](https://user-images.githubusercontent.com/2603405/30532763-4926bafe-9c56-11e7-8bb8-ca0c0e65b30d.png)

The build can be tested here: 

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/2657

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/issues/953

**Comment by andrecarlucci** [comment]
@RSuter Nice, thank you so much for this.
I believe this solution will fix that and any future problem with runtimes.

**Comment by RSuter** [comment]
Yes and i think you also dont need to dotnet publish selfcontained - dotnet build should be enough

**Comment by RSuter** [comment]
Please test the new feature with the CI build: 

https://github.com/RSuter/NSwag/issues/953#issuecomment-330751737

**Comment by RSuter** [comment]
Please discuss this in the new issue: https://github.com/RSuter/NSwag/issues/953

**Comment by RSuter** [comment]
Please try with v11.8 (just released): 

![image](https://user-images.githubusercontent.com/2603405/30813908-001d7afa-a20f-11e7-890a-63956094a788.png)
