### ISSUE TITLE
Use full/core command line binaries in NSwagStudio and fallback

### ISSUE THREAD

**Issue by RSuter** [RSuter/NSwag#953]
- [x] Package NSwagStudio with all binaries (full and core1.0/1.1/2.0)
- [x] Add "runtime" setting and generate files via command line binary (chosen via "runtime" settting)
- [x] Generate output via command line binary (inline)
- [x] Implement "runtime" check in command line binaries (full/core) so that other binaries are called when not in correct runtime
- [x] Load available controllers via command line
    - Commands: list-controllers and list-types
- [x] Cleanup
    - [x] Remove NSwagStudio.x86 => Not needed anymore (x86 cmd line tool is bundled)
    - [x] Refactor settings
- [ ] Add "Undefined" (auto) to Runtime

Branch: 

https://github.com/RSuter/NSwag/tree/studio-uses-command-line

**Comment by RSuter** [comment]
In the current version in the branch, you can select a runtime and the selected binary is used (this currently works only for "Generate Files"): 

![image](https://user-images.githubusercontent.com/2603405/30532763-4926bafe-9c56-11e7-8bb8-ca0c0e65b30d.png)

The build can be tested here: 

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/2657

**Comment by RSuter** [comment]
With the latest commit, the outputs are redirected to temp files so that "Generate" and display output in UI only also works.

**Comment by RSuter** [comment]
I think all changes in NSwagStudio are now done (maybe more refactorings will come), can you please test with the latest CI artifacts: 

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/2661

**Comment by andrecarlucci** [comment]
Yeap, it worked, thank you so much!

The only problem was that as my assemblies are .net core 2.0 and the default runtime is winx64, I got an error when loading my old powerhub.nswag file. Changing the runtime makes the error disappear, so maybe a friendly message saying that would be nice to the final user :)

Once again, thank you and congrats for such a great tool NSwagStudio is.

![error-snagit](https://user-images.githubusercontent.com/66689/30644851-29925b7c-9dea-11e7-98e5-ec93f0b42fd6.jpg)

**Comment by RSuter** [comment]
I changed the Runtime names from Core20 to NetCore20 => I think you got the error from this. Correct? Because you created the file with a prerelease build, this should not be a problem for the normal user...

**Comment by andrecarlucci** [comment]
Hmm.. it makes sense. Perfect :)

**Comment by RSuter** [comment]
Sorry, the error message cannot be easily avoided - we have to detect what type of assembly is selected and check the runtime with this... this will be a feature for the future :)

**Comment by RSuter** [comment]
Added runtime detection for command line: 

![image](https://user-images.githubusercontent.com/2603405/30655127-582f87c0-9e30-11e7-9e3c-0c4e2f7754a8.png)

**Comment by RSuter** [comment]
I think we I'm done here :-), now we have to test this with as many projects as possible

**Comment by zuckerthoben** [comment]
We will test this with our solution after our first release.
