### ISSUE TITLE
High CPU usage for NSwagStudio

### ISSUE THREAD

**Issue by codymullins** [RSuter/NSwag#954]
Noticed a couple times after leaving the app open for a while the CPU usage continually climbed. I can't find any logs but can try to keep an eye on it over time. Let me know what more information you need.

![image](https://user-images.githubusercontent.com/1738479/30546319-55c06798-9c5a-11e7-97d5-a99d9df467ce.png)

**Comment by RSuter** [comment]
Thank you for reporting this. In the latest release (v11.8+) we no longer generate in the same process, but execute the NSwag command line binary in a separate process - maybe this fixes this problem... we have to keep checking this. (My problem: I normally dont leave NSwagStudio open for a longer time - I start it, generate and close it)

**Comment by RSuter** [comment]
Is still still a problem with the latest release?

**Comment by codymullins** [comment]
@RSuter I believe this is now resolved. Thanks!
