### ISSUE TITLE
TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

### ISSUE THREAD

**Issue by ranouf** [RSuter/NSwag#966]
Hi,

Is there someone who already have this error:
`TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.`

This is my Call to the nswagstudio generated function:
```
		this.authenticationService.test()
			.subscribe(result => {
				debugger;
			}, error => {
				console.log('Error - AuthenticationService.test: ' + error);
			});
```

I probably forget to import something, I guess, but I dont know what.

Thank you,
Cedric

**Comment by ranouf** [comment]
For the next one who will have this issue, the NswagStudio auto generated script is currently calling http://localhost:XXX/authentication/login instead of http://localhost:XXX/api/v1/authentication/login
I m trying to find how to fix it.

**Comment by RSuter** [comment]
You canchange the bade url in the settings or in the ctor of the generated clien
