### ISSUE TITLE
500 with css/js files on ASP.NET Core with .NET framework 4.7

### ISSUE THREAD

**Issue by odinnou** [RSuter/NSwag#967]
Hello !

I have an issue with my setup of NSwag on a new API built with ASP.NET Core 2.0 targetted .NET Framework 4.7

![image](https://user-images.githubusercontent.com/3084655/30960188-920e1e6c-a442-11e7-9e27-d6c56f8456a0.png)

All GET request to /swagger/css .. /swagger/lib etc. returns 500 error code :((  is-it a issue with .NET Framework 4.7 ?

Thanks in advance !!

Kind regards

**Comment by RSuter** [comment]
What UI are you using? UseSwaggerUi()? UseSwaggerUi3()? UseSwaggerReDoc()?

Can you debug this and check what the actual exception is which results in this 500er?

**Comment by odinnou** [comment]
Oups i forget this : 

attached: my Configure method in the startup.cs

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseSwaggerUi(typeof(Startup).GetTypeInfo().Assembly, new SwaggerUiSettings
            {
            });

            app.UseDeveloperExceptionPage();
            app.UseCors(builder => builder.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod());

            app.UseMvc();
        }

**Comment by odinnou** [comment]
> Microsoft.AspNetCore.Server.Kestrel: Error: Connection id "0HL86D6R2BBHE", Request id "0HL86D6R2BBHE:00000001": An unhandled exception was thrown by the application.
> 
> System.MissingMethodException: Méthode introuvable : 'Void Microsoft.Net.Http.Headers.EntityTagHeaderValue..ctor(System.String)'.
>    à Microsoft.AspNetCore.StaticFiles.StaticFileContext.LookupFileInfo()
>    à Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    à Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddleware.Invoke(HttpContext context)
>    à NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.<Invoke>d__5.MoveNext()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à NSwag.AspNetCore.Middlewares.RedirectMiddleware.<Invoke>d__4.MoveNext()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à NSwag.AspNetCore.Middlewares.SwaggerMiddleware.<Invoke>d__7.MoveNext()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    à Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()

**Comment by odinnou** [comment]
Ok

**Comment by RSuter** [comment]
Ok? What was the problem/solution?

**Comment by odinnou** [comment]
the package Microsoft.AspNetCore.StaticFiles is not added by default with a project ASP.NET core 2.0 with .NET Framework 4.7 instead of a project built with .NET Core framework

**Comment by RSuter** [comment]
Strange, static files is one of the declared dependencies, why do you have to install it manually?

![image](https://user-images.githubusercontent.com/2603405/30967336-499814b6-a45c-11e7-9970-a82080ebf35b.png)

**Comment by RSuter** [comment]
Another question: The NSwag.AspNetCore package is compiled against .NET Core 1.1 packages, is everything working as expected with ASP.NET Core 2.0?

**Comment by odinnou** [comment]
With ASP.NET Core 2.0 Framework Core it seems to be perfect. I have all the documentation etc. 

With .NET Framework 4.7, I have this issue (solved by adding manually the nuget package StaticFiles v2.0.0 because the version added automatically is the version 1.0.2 and cause the issue) 

And I have the feeling that the documentation don't care about "base" class when the API return a class inherited by this "base" class.

Ex : 

> public class A
> {
> public int ID{get;set;}
> }
> 
> public class B : A
> {
> public string Name{get;set;}
> }

If I flag the result as :  

> [ProducesResponseType(typeof(IEnumerable< B >), 200)]

![image](https://user-images.githubusercontent.com/3084655/30968273-1198715c-a45f-11e7-8007-48793d012a7b.png)


I have only the properties from B in the documentation



Thank you

**Comment by RSuter** [comment]
I think the problem is Swagger UI: 

UseSwaggerUi() uses Swagger UI 2.x and this version does not support inheritance/disriminators, try UseSwaggerUi3() or UseSwaggerReDoc() - if its also not showing up, check the generated Swagger spec (url can be copied in Swagger UI) and check if an oneOf with a reference to A is generated...

**Comment by odinnou** [comment]
Concerning the StaticFiles package
I think the 1.0.2 version installed by defaut cause an issue with ASP.Net Core 2 targeting .NET 4.7

I don't know if you can force to download the 2.0.0 version when we target the .NET 4.7

**Comment by odinnou** [comment]
With UseSwaggerUi3() I have the doc for A but not for B ( XD o.O ) 

![image](https://user-images.githubusercontent.com/3084655/30969966-38fd7170-a464-11e7-8195-84c0c8c262fa.png)


With UseSwaggerReDoc() it's perfect

**Comment by RSuter** [comment]
Ok, then this has to be fixed in Swagger UI, you should create an issue there - I know that inheritance was not handled well in Swagger UI 2.x but I thought that it's now supported in 3.x...

**Comment by RSuter** [comment]
I dont want to force 2.0.0 for .net 4.7 because there may also be users which use asp.net core 1.0 with .net 4.7

**Comment by RSuter** [comment]
Important for inheritance in swagger: https://github.com/RSuter/NJsonSchema/wiki/Inheritance

**Comment by RSuter** [comment]
I think if you dont follow this guide, and no "discriminator" is generated, then Swagger UI **cannot** work because the inheritance information is missing...

**Comment by odinnou** [comment]
Thank you :) I will check that !
