### ISSUE TITLE
How move BaseUrl to base class in swaggerToCSharpClient generator

### ISSUE THREAD

**Issue by Rgl88** [RSuter/NSwag#971]
Hello
How move BaseUrl to base class in swaggerToCSharpClient generator?
I see i can use two method CreateHttpClientAsync and CreateHttpRequestMessageAsync, but after i set url
it reassign in generated code.
`                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);`
I can not use this method PrepareRequest because i must redefine this method for all classes

**Comment by RSuter** [comment]
You can set the base url on the http client

**Comment by Rgl88** [comment]
I test it but problem is another place, 

` result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<AuthenticateResultModel>(responseData_, _settings.Value);`

I put it into base class (also without this method not work):

` 
protected void UpdateJsonSerializerSettings(JsonSerializerSettings setting)
        {
            setting.ContractResolver = new CamelCasePropertyNamesContractResolver();
            setting.Formatting = Formatting.Indented;
        }
`

but deserializer not work!
json string:
`
{"result":{"accessToken":"ff5","encryptedAccessToken":"gg","expireInSeconds":86400,"userId":2},"targetUrl":null,"success":true,"error":null,"unAuthorizedRequest":false,"__abp":true}
`
Model class:
```
 [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.6.5.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class AuthenticateResultModel 
    {
        [Newtonsoft.Json.JsonProperty("accessToken", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string AccessToken { get; set; }
    
        [Newtonsoft.Json.JsonProperty("encryptedAccessToken", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string EncryptedAccessToken { get; set; }
    
        [Newtonsoft.Json.JsonProperty("expireInSeconds", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? ExpireInSeconds { get; set; }
    
        [Newtonsoft.Json.JsonProperty("userId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public long? UserId { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static AuthenticateResultModel FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<AuthenticateResultModel>(data);
        }
    }
```

**Comment by Rgl88** [comment]
More about problem.
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2552

**Comment by RSuter** [comment]
Maybe you can implement a dummy DTO class which represents the **actual response** and use the `SwaggerResponse(200, typeof(DtoDummy))` to use the dummy class for the schema so that it matches

**Comment by Rgl88** [comment]
I think it is not posible.
```
result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<AuthenticateResultModel>(responseData_, _settings.Value);
return new SwaggerResponse<AuthenticateResultModel>(status_, headers_, result_); 
```
The generated code must modified.

`result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<Response<AuthenticateResultModel>>(responseData_, _settings.Value);`

    public class Response<T>
    {
        public T Result { get; set; }
        public string TargetUrl { get; set; }
        public bool Success { get; set; }
        public string Error { get; set; }
        public bool UnAuthorizedRequest { get; set; }
        public bool __abp { get; set; }
    }

    public class AuthenticateResultModel
    {
        public string AccessToken { get; set; }
        public string EncryptedAccessToken { get; set; }
        public int? ExpireInSeconds { get; set; }
        public long? UserId { get; set; }
    }

```
Can i customize generated code?

**Comment by RSuter** [comment]
As I said you can define the correct classes: 

	public class MyResponse
    {
        public MyAuthenticateResultModel Result { get; set; }
        public string TargetUrl { get; set; }
        public bool Success { get; set; }
        public string Error { get; set; }
        public bool UnAuthorizedRequest { get; set; }
        public bool __abp { get; set; }
    }

    public class MyAuthenticateResultModel
    {
        public string AccessToken { get; set; }
        public string EncryptedAccessToken { get; set; }
        public int? ExpireInSeconds { get; set; }
        public long? UserId { get; set; }
    }
	
and then add

    [SwaggerResponse(200, typeof(MyResponse)]
	
to the controller operation so that the correct schema is generated. 

You can also implement a custom OperationProcessor and modify the schema there so that the generated client is correct. 

Or you can completely exclude the operation and implement yourself in a partial class...

**Comment by Rgl88** [comment]
Very simple solution:
```
var str = File.ReadAllText(filePath);

var methodReturnPattern = @"System.Threading.Tasks.Task<(?'TypeName'\w+){1}\>+";

var deserializerPattern = @"result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<(?'TypeName'\w+){1}\>{1}";

var resultDefinitionPattern = @"default\((?'TypeName'\w+){1}\);{1}";

var baseUrlPattern = @"(?'VarName'urlBuilder_)\.Append";

var result = Regex.Replace(str, methodReturnPattern, m => m.Value.Replace(m.Groups["TypeName"].Value, "Response<"+m.Groups["TypeName"].Value + ">"));
result = Regex.Replace(result, deserializerPattern, m => m.Value.Replace(m.Groups["TypeName"].Value, "Response<" + m.Groups["TypeName"].Value + ">"));
result = Regex.Replace(result, resultDefinitionPattern, m => m.Value.Replace(m.Groups["TypeName"].Value, "Response<" + m.Groups["TypeName"].Value + ">"));
result = Regex.Replace(result, baseUrlPattern, m => m.Value.Replace(m.Groups["VarName"].Value, m.Groups["VarName"].Value + ".Append(BaseUrl)"));
File.WriteAllText(filePath, result);
```
