### ISSUE TITLE
Question: Customizing Code Gen using the Command Line Tool

### ISSUE THREAD

**Issue by tonysneed** [RSuter/NSwag#979]
Is it possible to customize generated C# or TypeScript code using the command line tool?

**Comment by RSuter** [comment]
There is no option to postprocess the generated code. What is your problem?

**Comment by tonysneed** [comment]
Let's say I'd like to generate C# classes that have property setters which call a method in a base class that fires a PropertyChanged event for client-side data binding. This is something I could accomplish with a T4 template, but I have to use Visual Studio to run it, and I would prefer to do this customization from a command line tool rather than visual studio. Have you thought about allowing use of a templating utility such as handlebars?

**Comment by RSuter** [comment]
The this is the long-term plan, see https://github.com/RSuter/NSwag/issues/263
But this is a huge refactoring (no breaking changes, should output the exact same code, clean up models as they will be public API, etc). 

Because I run this project in my free time and without being paid, I didnt have the time to implement it...

Back to your question: There is the option to generate classes with INPC support...

**Comment by RSuter** [comment]
And consider: This feature not only affects NSwag but must also be implemented in NJsonSchema (where the POCOs are generated).

**Comment by RSuter** [comment]
However you can currently provide an own ITemplateFactory and use the models and your own engine. For this you need to write an own command line tool with the nswag libs...

**Comment by RSuter** [comment]
... but i dont recommend it because you have to rewrite the whole class template and the models may be refactored in the coming months

**Comment by tonysneed** [comment]
Thanks for answering my question.  Looks like T4 is currently the best option currently for custom code generation.  I should be able to use it in VS for Mac by manually saving the file.

**Comment by RSuter** [comment]
https://github.com/RSuter/NSwag/wiki/Templates
