### ISSUE TITLE
Extend constructor to inject other service in Anguar TypeScript client

### ISSUE THREAD

**Issue by andrewinkler1** [RSuter/NSwag#981]
I want to extend the constructor of the client services to inject other service in Anguar TypeScript client. Is that possible? Example?

**Comment by RSuter** [comment]
Use the ConfigurationClass setting for that

**Comment by andrewinkler1** [comment]
How can I use this setting, I found no documentation in the wiki...

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/blob/master/src/NSwag.CodeGeneration.TypeScript/SwaggerToTypeScriptClientGeneratorSettings.cs#L54

Not all settings are described in the wiki... but if you use NSwagStudio to create the configuration (nswag.json) you'll see all available configs in the UI...

**Comment by RSuter** [comment]
You also need extension code and either import the configuration class or implement it: 

https://github.com/RSuter/NSwag/wiki/SwaggerToTypeScriptClientGenerator#extended-classes-and-extension-code

**Comment by andrewinkler1** [comment]
Cool, thank you
