### ISSUE TITLE
Is there a way to override the behavior of the status code logic?

### ISSUE THREAD

**Issue by sheltonc** [RSuter/NSwag#983]
When generating a typescript client, the following code is produced:

```
if (status === 200) {
   ...
   ...
        } else if (status !== 200 && status !== 204) {
            ...
            return throwException("An unexpected server error occurred.", status, _responseText);
        }
```

This is not desirable. 

What if we want to return a 201 from a POST? this will be thrown as an unexpected server error.

What if we want to return a 400 as a result of validation? Again. server error.

Is there any way to override this logic?

**Comment by grovesNL** [comment]
Please post your swagger.json, or if you're generating it from Web API, could you clarify whether you are annotating all possible response types for your controller methods?

If you list 201 or 400 as possible (expected) response type then NSwag will generate the appropriate client to handle it. Besides that, there are ways to customize error handling if a response is actually unexpected.

**Comment by RSuter** [comment]
See https://github.com/RSuter/NSwag/wiki/WebApiToSwaggerGenerator#specify-the-response-type-of-an-action
