### ISSUE TITLE
FileNotFoundException with /referencepaths

### ISSUE THREAD

**Issue by lurumad** [RSuter/NSwag#986]
Hi, 

I'm using NSwag.AspNetCore 11.9.0 y NSwag.MSBuild 11.9.0. I have a weird problem when I remove  /referencepaths from my csproj I received this erros:

 dotnet publish
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  xxxxxxxxx.Common -> C:\Dev\xxxxxxxxx\src\Common\xxxxxxxxx.Common\bin\Debug\netstandard2.0\xxxxxxxxx.Common.dll
  xxxxxxxxx.Administration.Model -> C:\Dev\xxxxxxxxx\src\Administration\xxxxxxxxx.Administration.Model\bin\Debug\netstandard2.0\xxxxxxxxx.Administration.Model.dll
  xxxxxxxxx.Administration.Security -> C:\Dev\xxxxxxxxx\src\Administration\xxxxxxxxx.Administration.Security\bin\Debug\netstandard2.0\xxxxxxxxx.Administration.Security.dll
  xxxxxxxxx.Administration.Application -> C:\Dev\xxxxxxxxx\src\Administration\xxxxxxxxx.Administration.Application\bin\Debug\netstandard2.0\xxxxxxxxx.Administration.Application.dll
  xxxxxxxxx.Administration.Infrastructure -> C:\Dev\xxxxxxxxx\src\Administration\xxxxxxxxx.Administration.Infrastructure\bin\Debug\netstandard2.0\xxxxxxxxx.Administration.Infrastructure.dll
  xxxxxxxxx.Administration.Api -> C:\Dev\xxxxxxxxx\src\Administration\xxxxxxxxx.Administration.Api\bin\Debug\netcoreapp2.0\xxxxxxxxx.Administration.Api.dll
  NSwag command line tool for .NET Core, toolchain v11.7.2.0 (NJsonSchema v9.6.3.0) (x64)
  Visit http://NSwag.org for more information.
  NSwag bin directory: C:\Users\lruiz\.nuget\packages\nswag.consolecore\11.7.2\lib\netcoreapp2.0
  Code has been successfully written to file.

  Duration: 00:00:02.2925820
  NSwag command line tool for .NET Core, toolchain v11.7.2.0 (NJsonSchema v9.6.3.0) (x64)
  Visit http://NSwag.org for more information.
  NSwag bin directory: C:\Users\lruiz\.nuget\packages\nswag.consolecore\11.7.2\lib\netcoreapp2.0
  Code has been successfully written to file.

  Duration: 00:00:01.5594978
  xxxxxxxxx.Administration.Api -> C:\Dev\xxxxxxxxx\src\Administration\xxxxxxxxx.Administration.Api\bin\Debug\netcoreapp2.0\publish\
  NSwag command line tool for .NET Core, toolchain v11.7.2.0 (NJsonSchema v9.6.3.0) (x64)
  Visit http://NSwag.org for more information.
  NSwag bin directory: C:\Users\lruiz\.nuget\packages\nswag.consolecore\11.7.2\lib\netcoreapp2.0
  _**System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
  File name: 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.IO.FileNotFoundException: Could not load the specified file.**_
  File name: 'Microsoft.EntityFrameworkCore'
     at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
     at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
     at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
     at System.Reflection.RuntimeAssembly.GetExportedTypes()
     at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.GetControllerClasses(Assembly assembly)
     at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
     at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.OrderedEnumerable`1.ToArray()
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at NSwag.SwaggerGeneration.WebApi.WebApiAssemblyToSwaggerGenerator.WebApiAssemblyLoader.GetControllerClasses(String[] assemblyPaths, IEnumerable`1 referencePaths)
     at NSwag.Commands.WebApiToSwaggerCommandBase.<<RunAsync>b__80_0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NSwag.Commands.WebApiToSwaggerCommandBase.<RunAsync>d__80.MoveNext()

This is my task without /referencepaths

```xml
<Target Name="ExecuteProductionNswagAndFrontendBuild" AfterTargets="AfterPublish">
    <Exec Command="dotnet nswag webapi2swagger /assembly:$(PublishDir)\$(ProjectName).dll /DefaultPropertyNameHandling:CamelCase /output:swagger.json" />
    <Exec Command="dotnet nswag swagger2tsclient /input:swagger.json /output:../xxxxx.Administration.ClientSide/modules/xxxxx/services/services.ts /template:Angular" />
    <Exec Command="npm run build:prod" WorkingDirectory="..\xxxxx.Administration.ClientSide" />
    <Copy SourceFiles="@(ClientSideFiles)" DestinationFiles="@(ClientSideFiles->'$(PublishDir)\wwwroot\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
```

If I add **/referncepaths**, works:

```xml
<Target Name="ExecuteProductionNswagAndFrontendBuild" AfterTargets="AfterPublish">
    <Exec Command="dotnet nswag webapi2swagger /assembly:$(PublishDir)\$(ProjectName).dll /DefaultPropertyNameHandling:CamelCase /output:swagger.json /referencepaths:%USERPROFILE%\\.nuget\\packages"  />
    <Exec Command="dotnet nswag swagger2tsclient /input:swagger.json /output:../xxxxx.Administration.ClientSide/modules/xxxxx/services/services.ts /template:Angular" />
    <Exec Command="npm run build:prod" WorkingDirectory="..\xxxxx.Administration.ClientSide" />
    <Copy SourceFiles="@(ClientSideFiles)" DestinationFiles="@(ClientSideFiles->'$(PublishDir)\wwwroot\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
```
Why NSwag needs a reference path? EF Core 2.0 depends in AspNetCoreAll and is not storage in .nuget dir, is storage in Runtime package store

https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store

Any ideas I could fix this???

Regards!

**Comment by RSuter** [comment]
Try using the correct binary (I think you're using .NET Core) of NSwag.MSBuild: 

e.g. NSwagExe_Core20 instead of NSwagExe

https://github.com/RSuter/NSwag/wiki/MSBuild

**Comment by lurumad** [comment]
Hi @RSuter 

The same error in VSTS:

d:\a\_tool\dncs\2.0.0\x64\dotnet.exe publish d:\a\1\s\src\Administration\xxxxxxxxx.Administration.Api\xxxxxxxxx.Administration.Api.csproj --configuration release --output d:\a\1\a\xxxxxxxxx.Administration.Api
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  xxxxxxxxx.Common -> d:\a\1\s\src\Common\xxxxxxxxx.Common\bin\release\netstandard2.0\xxxxxxxxx.Common.dll
  xxxxxxxxx.Administration.Model -> d:\a\1\s\src\Administration\xxxxxxxxx.Administration.Model\bin\release\netstandard2.0\xxxxxxxxx.Administration.Model.dll
  xxxxxxxxx.Administration.Security -> d:\a\1\s\src\Administration\xxxxxxxxx.Administration.Security\bin\release\netstandard2.0\xxxxxxxxx.Administration.Security.dll
  xxxxxxxxx.Administration.Application -> d:\a\1\s\src\Administration\xxxxxxxxx.Administration.Application\bin\release\netstandard2.0\xxxxxxxxx.Administration.Application.dll
  xxxxxxxxx.Administration.Infrastructure -> d:\a\1\s\src\Administration\xxxxxxxxx.Administration.Infrastructure\bin\release\netstandard2.0\xxxxxxxxx.Administration.Infrastructure.dll
  xxxxxxxxx.Administration.Api -> d:\a\1\s\src\Administration\xxxxxxxxx.Administration.Api\bin\release\netcoreapp2.0\xxxxxxxxx.Administration.Api.dll
  xxxxxxxxx.Administration.Api -> d:\a\1\a\xxxxxxxxx.Administration.Api\
  NSwag command line tool for .NET Core NetCore20, toolchain v11.9.0.0 (NJsonSchema v9.7.1.0 (Newtonsoft.Json v9.0.0.0))
  Visit http://NSwag.org for more information.
  NSwag bin directory: C:\Users\buildguest\.nuget\packages\nswag.msbuild\11.9.0\build\NetCore20
  System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
  File name: 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

My msbuild task:

```xml
<Target Name="ExecuteProductionNswagAndFrontendBuild" AfterTargets="AfterPublish">
    <Exec Command="$(NSwagExe_Core20) webapi2swagger /assembly:$(PublishDir)\$(ProjectName).dll /DefaultPropertyNameHandling:CamelCase /output:swagger.json /referencepaths:%USERPROFILE%\\.nuget\\packages" />
    <Exec Command="$(NSwagExe_Core20) swagger2tsclient /input:swagger.json /output:../xxxxxxxxx.Administration.ClientSide/modules/xxxxxxxxx/services/services.ts /template:Angular" />
    <Exec Command="npm run build:prod" WorkingDirectory="..\xxxxxxxxx.Administration.ClientSide" />
    <Copy SourceFiles="@(ClientSideFiles)" DestinationFiles="@(ClientSideFiles->'$(PublishDir)\wwwroot\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
```
Fails also adding referencepath.

Regards!

**Comment by lurumad** [comment]
Hi @RSuter 

I've found the problem:

https://github.com/RSuter/NSwag/wiki/Assembly-loading#net-core

Once I added <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest> everything is works.

Thanks for your help and for this awesome project!!!
