### ISSUE TITLE
Support for class access modifier on DTO classes?

### ISSUE THREAD

**Issue by yberstad** [RSuter/NSwag#990]
Hi!

NSwagStudio currently support setting "Client class access modifier", but how can I change the class access modifier for DTO classes? 

Kind regards, Øyvind.

**Comment by RSuter** [comment]
Currently not possible, please create an issue in http://njsonschema.org

**Comment by yberstad** [comment]
@RSuter, thanks for your quick response! I have added a question here https://github.com/RSuter/NJsonSchema/issues/509.

**Comment by RSuter** [comment]
Released: v11.9.3

**Comment by yberstad** [comment]
SWEET, tested it now, works like charm! Thank you so much for your help. Impressed that you fixed it so fast! :-)
