### ISSUE TITLE
Update swagger-ui to 2.2.10

### ISSUE THREAD

**Issue by alexvaluyskiy** [RSuter/NSwag#995]
Swagger UI 2.2.10 has a lot of improvements related to OAuth2 Password and ClientCredentials flows

**Comment by RSuter** [comment]
I didnt know that there is a new version of the (old) Swagger UI 2.x

https://github.com/swagger-api/swagger-ui/releases/tag/v2.2.10

**Comment by alexvaluyskiy** [comment]
Thanks. Waiting for the new version

**Comment by RSuter** [comment]
v11.11.3
