### ISSUE TITLE
Exposing response headers through a generated C# client

### ISSUE THREAD

**Issue by stijnherreman** [RSuter/NSwag#997]
Preface: I want to implement the ETag header for some of my resources. My initial plan is to use `[SwaggerResponse(HttpStatusCode.NotModified, typeof(void))]` and handle ETag logic inside the action.

For the above to work, I need to be able to read the response headers with my generated clients, to extract the current ETag. I'm not quite sure how this can be achieved without breaking existing code. Perhaps a new generator setting can be added, to have methods return value tuples containing the response headers. So instead of

```c#
Task<Foo> Foos_GetFooAsync(int id)
```

it generates

```c#
Task<(Foo value, HttpResponseHeaders responseHeaders)> Foos_GetFooAsync(int id)
```

Then you can either use the headers

```c#
(var foo, var headers) = await Foos_GetFooAsync(id)
```

or discard them

```c#
(var foo, _) = await Foos_GetFooAsync(id)
```

Do you think this is a path worth exploring? Or do you have something else in mind? I can help out with implementing this if you like.

**Comment by stijnherreman** [comment]
On a related note, the code generator currently handles HEAD requests, but it doesn't seem to do anything other than throwing on an unexpected status code.

**Comment by RSuter** [comment]
There is the WrapResponses option...

Another option would be to split the generated method in two e.g. GetFooAsync and ProcessGetFooAsync(...). You could then make GetFooAsync protected (ProtectedMethods) and reimplement it with calls to GetFooAsync and ProcessGetFooAsync and own code...

**Comment by stijnherreman** [comment]
Thank you, I'll take a look at both options soon-ish.

**Comment by RSuter** [comment]
The second option is not yet implemented

**Comment by stijnherreman** [comment]
WrapResponses seems to do what I need. I also see there is a WrapResponseMethods option, but I couldn't figure out the correct syntax. I tried the following but none of them work:

* /wrapresponses:true /wrapresponsemethods:Workspaces.Head
* /wrapresponses:true /wrapresponsemethods:WorkspacesController.Head
* /wrapresponses:true /wrapresponsemethods:Workspaces.Workspaces_Head
* /wrapresponses:true /wrapresponsemethods:WorkspacesController.Workspaces_Head

**Comment by RSuter** [comment]
I think it’s clientName.methodName

**Comment by RSuter** [comment]
https://github.com/RSuter/NSwag/blob/8a6a331e9ceed740255f54bef6f7bd6f976cffd4/src/NSwag.CodeGeneration/Models/OperationModelBase.cs#L250

**Comment by stijnherreman** [comment]
Ah, thank you. The client name is `Client` in this case, so `Client.Workspaces_Head` made it work.

**Comment by bpred754** [comment]
@RicoSuter maybe I am just not as familiar with the product.. but I feel like the code (the link you referenced above) and the description [here](https://github.com/RicoSuter/NSwag/blob/85ae862fd6d68173a201a79e0ad06e0be2ec5de1/src/NSwag.Commands/Commands/CodeGeneration/OpenApiToTypeScriptClientCommand.cs#L176) and [here](https://github.com/RicoSuter/NSwag/blob/cdd5e819dc9f65d2a6a80d00f2f750956bb55c85/src/NSwag.Commands/Commands/CodeGeneration/OpenApiToCSharpCommandBase.cs#L112) are a bit confusing. I was having trouble too with the format for wrapResponseMethods. I think it should be labeled as `ClientName.MethodName` instead of `ControllerName.MethodName`
