### ISSUE TITLE
Client generated C# code for Path parameter with type array of string does not compile 

### ISSUE THREAD

**Issue by backlune** [RSuter/NSwag#998]
When a swagger contains a path like below the generated C# code won't compile. 
```
"/tasks/{ids}": {
    "get": {
    "description": "Returns complete information about single or multiple tasks.",
    "operationId": "getTasksById",
    "parameters": [
        {
            "name": "ids",
            "in": "path",
            "description": "ids",
            "required": true,
            "type": "array",
            "items": {
                "type": "string"
            },
            "collectionFormat": "csv"
        }
    ],
    "responses": {
        "200": {
            ....
        },
    }
    }
}
```

Generated code contains:
```
urlBuilder_.Replace("{ids}", System.Uri.EscapeDataString(string.Join(",", ids.Select(s_ => System.Convert.ToString(s_, System.Globalization.CultureInfo.InvariantCulture)))));
```

Expected:
```
urlBuilder_.Replace("{ids}", System.Uri.EscapeDataString(string.Join(",", System.Linq.Enumerable.Select(ids, s_ => System.Convert.ToString(s_, System.Globalization.CultureInfo.InvariantCulture)))));
```

Using `SwaggerToCSharpClientGeneratorSettings.AdditionalNamespaceUsages` to workaround the issue but preferred if the generated client can compile.

**Comment by RSuter** [comment]
Can you check the commit? Does it look correct?
You can test with the latest CI build: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by backlune** [comment]
Commit looks good! 

Used NSwagStudio from the CI build and the generated CSharp client compiles. 👍

**Comment by RSuter** [comment]
Ok thx, sorry i just released before the commit. Im pretty sure ill release again soon... :-)

**Comment by backlune** [comment]
No worries, we got a workaround in the meantime :)
